// Russian business-copy dictionary for the 1Cati dashboard, AI assistant and
// platform marketing content. Populated by the July 2026 localization audit.
// Keys are the canonical Turkish source strings (or {token} templates); do not
// hand-edit keys without updating every sibling locale file identically.

export const ruCopy: Record<string, string> = {
  "212.298+": "212 298+",
  "10.000+": "10 000+",
  "6.000+": "6 000+",
  "Aidat, tahsilat, depozito veya finans raporu sorun...": "Спросите про взносы, платежи, депозиты или финансовые отчёты...",
  "Atanan servis, saha notu veya rezervasyon işi sorun...": "Спросите про назначенные заявки, полевые заметки или бронирования...",
  "Servis, rezervasyon, belge veya mesaj hakkında sorun...": "Спросите про сервис, бронирования, документы или сообщения...",
  "Operasyon Kullanıcısı": "Оператор системы",
  "Operasyon Asistanı": "Операционный ассистент",
  "Toplam Daire": "Всего квартир",
  "{rate}% doluluk": "{rate}% заполняемость",
  "{vacant} boş, {maintenance} bakımda": "{vacant} свободно, {maintenance} на обслуживании",
  "Toplam Borç": "Общая задолженность",
  "{count} erişim kısıtı": "{count} ограничений доступа",
  "Açık Servis": "Открытые заявки",
  "{count} SLA dışı": "{count} вне SLA",
  "Teknik, finans ve depozito işleri": "Технические, финансовые вопросы и депозиты",
  "Bugünkü İşler": "Задачи на сегодня",
  "{count} çıkış": "{count} выездов",
  "Giriş, çıkış, temizlik, depozito": "Заезд, выезд, уборка, депозит",
  "{count} operasyon riski AI kuyruğunda: borç, SLA ve check-out birlikte takip ediliyor.": "{count} операционных рисков в очереди AI: задолженность, SLA и выезд отслеживаются вместе.",
  "{count} dairede erişim kısıtı var. Finans onayı olmadan servis yönlendirilmemeli.": "В {count} квартирах действует ограничение доступа. Заявки нельзя направлять без согласования с финансовым отделом.",
  "{count} servis talebi SLA dışına çıktı. Teknik ekip için öncelik listesi hazır.": "{count} заявок вышли за пределы SLA. Список приоритетов для технической службы готов.",
  "ERP Operasyon Merkezi": "Операционный центр ERP",
  "Satış, proje takibi, WhatsApp/Telegram lead akışı, evrak, servis, finans ve AI önceliklendirme tek çalışma alanında toplanır. Operasyon görünümü 769 birim ölçeğinde yönetim, kontrol ve takip için çalışır.": "Продажи, отслеживание проектов, поток лидов WhatsApp/Telegram, документы, заявки, финансы и AI-приоритизация собраны в одном рабочем пространстве. Операционная панель обеспечивает управление, контроль и мониторинг в масштабе 769 юнитов.",
  "Aktif rol:": "Активная роль:",
  "Veri yenilenemedi. Lütfen tekrar deneyin.": "Не удалось обновить данные. Повторите попытку.",
  "Portföy kaynağı": "Источник портфеля",
  "daire": "квартир",
  "açık servis": "открытая заявка",
  "aktif rol": "активная роль",
  "modülüne git": "перейти в модуль",
  "ERP modül durumu": "Статус модулей ERP",
  "CRM, daire matrisi, kullanıcı rolleri, finans, servis, saha, rezervasyon, iletişim, mobil PWA, entegrasyon, AI ve güvenlik kontrolleri aynı işletim planında izlenir.": "CRM, матрица квартир, роли пользователей, финансы, заявки, полевые работы, бронирования, коммуникации, мобильное PWA-приложение, интеграции, AI и контроль безопасности отслеживаются в рамках единого операционного плана.",
  "{complete} aktif · {readyForUat} kontrol hazır · {inProgress} yapımda": "{complete} активно · {readyForUat} готово к проверке · {inProgress} в разработке",
  "Modül": "Модуль",
  "ekranını aç": "открыть экран",
  "Aktif": "Активен",
  "Kontrol hazır": "Готово к проверке",
  "Yapımda": "В разработке",
  "Planlandı": "Запланировано",
  "Bloke": "Блокировано",
  "Nasıl kullanılır:": "Как использовать:",
  "modülünü aç": "открыть модуль",
  "Doluluk ve tahsilat sağlığı detayını aç": "Открыть детали по заполняемости и сборам",
  "Doluluk ve tahsilat sağlığı": "Заполняемость и состояние сборов",
  "Doluluk oranı, gecikmiş borç ve servis baskısı birlikte okunur.": "Уровень заполняемости, просроченная задолженность и нагрузка по заявкам анализируются в комплексе.",
  "Haziran hedefi korunuyor": "Цель на июнь удерживается",
  "Daire durum dağılımı detayını aç": "Открыть детали распределения статусов квартир",
  "Daire durum dağılımı": "Распределение статусов квартир",
  "Operasyon ekibi için canlı portföy kırılımı.": "Актуальная разбивка портфеля для операционной команды.",
  "Blok bazlı operasyon": "Операции по блокам",
  "{count} blok": "{count} блоков",
  "Blok": "Блок",
  "daire matrisi detayını aç": "открыть детали матрицы квартир",
  "{count} daire": "{count} квартир",
  "Dolu:": "Занято:",
  "Boş:": "Свободно:",
  "Bakım:": "На обслуживании:",
  "Borç:": "Задолженность:",
  "AI operasyon asistanı raporlarını aç": "Открыть отчёты AI-операционного ассистента",
  "AI operasyon asistanı": "AI-операционный ассистент",
  "Borç, SLA, depozito ve rezervasyon verilerini birleştirerek günlük yapılacakları sıralar.": "Объединяет данные по задолженности, SLA, депозитам и бронированиям и формирует список задач на день.",
  "detayını aç": "открыть детали",
  "Son operasyon akışı": "Последний операционный поток",
  "Bugünkü kritik işler": "Критические задачи на сегодня",
  "{hours} saat": "{hours} ч",
  "servis talebini aç": "открыть заявку",
  "rezervasyon detayını aç": "открыть детали бронирования",
  "Depozito:": "Депозит:",
  "Finans özetini aç": "Открыть финансовую сводку",
  "Aylık beklenen aidat": "Ожидаемые взносы за месяц",
  "Haziran tahsilat": "Сбор за июнь",
  "Depozito riski": "Риск по депозитам",
  "rol izni yok": "нет прав по роли",
  "Bu modül mevcut rol için kapalı": "Этот модуль закрыт для текущей роли",
  "Rol kapalı": "Роль без доступа",
  "İncele": "Просмотреть",
  "Canlı daire": "Квартиры онлайн",
  "Açık servis": "Открытые заявки",
  "finans kontrolü": "финансовый контроль",
  "Erişim riski": "Риск доступа",
  "Operasyon merkezi": "Операционный центр",
  "Daire, servis, finans ve rezervasyon aynı kontrol düzleminde": "Квартиры, заявки, финансы и бронирования в единой плоскости контроля",
  "Bu görünüm yönetim ve sorumlu rolü için portföy ölçeğinde risk, iş yükü ve tahsilat sinyallerini birleştirir.": "Эта панель объединяет сигналы риска, нагрузки и сборов в масштабе портфеля для управляющей и ответственной роли.",
  "AI risk": "AI-риск",
  "öncelikli aksiyon": "приоритетное действие",
  "İş yoğunluğu": "Загрузка работой",
  "Saatlik sinyal": "Почасовой сигнал",
  "Gün {day}: {value}%": "День {day}: {value}%",
  "Saat {hour}: {value}%": "Час {hour}: {value}%",
  "Rol bağlantıları aktif": "Ролевые связи активны",
  "Dashboard kartları, API ve AI yanıtları aynı RBAC matrisinden geçer.": "Карточки дашборда, API и ответы AI проходят через одну и ту же матрицу RBAC.",
  "Çalışma alanı ritmi": "Ритм рабочего пространства",
  "Hover ve kart geçişleri gerçek modül akışlarını gösterir.": "Наведение и переходы по карточкам отражают реальные потоки модулей.",
  "Yetki sınırları": "Границы полномочий",
  "Bu ekranda şirket geneli daire matrisi, finans defteri, kullanıcı yönetimi ve platform ayarları gösterilmez. Kapalı bir sayfa URL ile açılırsa sistem sizi tekrar kendi çalışma alanınıza döndürür.": "На этом экране не отображаются общая матрица квартир по компании, финансовый журнал, управление пользователями и настройки платформы. Если закрытая страница открыта по URL, система вернёт вас в ваше рабочее пространство.",
  "açık modül": "открытый модуль",
  "yetkili iş": "доступная задача",
  "Finans, Satış & Aidat": "Финансы, продажи и взносы",
  "{clientName} için satış ödemeleri, aidat, borç yaşlandırma, depozito, ödeme doğrulama, kira geliri ve erişim kısıtı kararları aynı finans akışında yönetilir.": "Платежи по продажам, взносы, старение задолженности, депозиты, верификация платежей, доход от аренды и решения об ограничении доступа для {clientName} управляются в единой финансовой цепочке.",
  "Toplam borç": "Общая задолженность",
  "Aylık aidat": "Ежемесячный взнос",
  "Kısıtlı erişim": "Ограниченный доступ",
  "Aylık nakit akışı": "Ежемесячный денежный поток",
  "Tahsilat, açık borç ve servis gideri birlikte takip edilir.": "Сборы, непогашенная задолженность и расходы на обслуживание отслеживаются в комплексе.",
  "Tahsilat {amount}": "Собрано {amount}",
  "Borç yaşlandırma": "Старение задолженности",
  "Önceliklendirme 90+ gün ve erişim kısıtından başlar.": "Приоритизация начинается с задолженности 90+ дней и ограничения доступа.",
  "{days} gün": "{days} дн.",
  "Yasal takip": "Юридическое взыскание",
  "Gecikmiş": "Просрочено",
  "Ödeme doğrulama": "Верификация платежей",
  "Banka dekontu, online ödeme, manuel tahsilat ve kasa hareketi aynı hesap kaydına bağlanır.": "Банковская квитанция, онлайн-платёж, ручной сбор и кассовая операция привязываются к одной и той же записи счёта.",
  "Borç kısıtlama kuralı": "Правило ограничения при задолженности",
  "90+ gün borçta erişim kısıtı, servis bekletme ve yasal takip önerisi otomatik görünür.": "При задолженности от 90 дней автоматически отображаются ограничение доступа, приостановка обслуживания и рекомендация юридического взыскания.",
  "Depozito kontrolü": "Контроль депозита",
  "Hasar, temizlik ve iade onayı rezervasyon çıkışıyla finans panelinde kapanır.": "Ущерб, уборка и подтверждение возврата закрываются в финансовой панели одновременно с выездом по бронированию.",
  "Satış ödeme planı": "График платежей по продаже",
  "0% taksit akışı; liste fiyatı, peşinat, kalan vade, kur riski ve sözleşme blokajını satıştan önce görünür yapar.": "Схема рассрочки 0%; до сделки отображает цену по прайсу, первоначальный взнос, остаток по срокам, валютный риск и блокировку по договору.",
  "Açık vade {amount}": "Открытый платёж {amount}",
  "Plan sayısı": "Количество планов",
  "Planında": "В графике",
  "Vade uyarısı": "Предупреждение по сроку платежа",
  "Blokeli": "Заблокировано",
  "Plan": "План",
  "Alıcı": "Покупатель",
  "Liste": "ЦЕНА",
  "Ödenen": "Оплачено",
  "Sonraki vade": "Следующий платёж",
  "Durum": "Статус",
  "Vade yaklaştı": "Срок платежа приближается",
  "Gecikti": "Просрочено",
  "Blokaj": "Блокировка",
  "Daire": "Квартира",
  "Malik": "Собственник",
  "Borç": "Задолженность",
  "Yaş": "Возраст долга",
  "Erişim": "Доступ",
  "Önerilen aksiyon": "Рекомендуемое действие",
  "Ucretsiz": "Бесплатно",
  "Odeme once": "Оплата предварительно",
  "Cari hesaba yaz": "Занести на текущий счёт",
  "Onayli": "Подтверждено",
  "Beklet": "Отложить",
  "Taslak": "Черновик",
  "Borc kontrolu": "Проверка задолженности",
  "Odeme bekliyor": "Ожидает оплаты",
  "Gorev acildi": "Задача создана",
  "Atandi": "Назначено",
  "Tamamlandi": "Завершено",
  "Iptal": "Отменено",
  "Supabase live": "Supabase live",
  "Yetkili dairenize bağlı servis taleplerini, randevu durumunu, medya kanıtını ve yönetim yanıtlarını tek ekrandan takip edin.": "Отслеживайте заявки по вашей закреплённой квартире, статус визита, фото/видео подтверждения и ответы управляющей компании на одном экране.",
  "Saha ekibi için atanan servis işleri, SLA önceliği, medya kanıtı ve kapanış adımları aynı iş kuyruğunda yönetilir.": "Назначенные полевой бригаде заявки, приоритет по SLA, медиа-подтверждения и этапы закрытия ведутся в одной рабочей очереди.",
  "ve diğer Ataberk portföyleri için teknik servis, ödeme doğrulama, fotoğraf/video kanıtı ve SLA takibi aynı iş kuyruğunda yönetilir.": "и других объектов портфеля Ataberk техническое обслуживание, проверка оплаты, фото/видео подтверждения и контроль SLA ведутся в единой рабочей очереди.",
  "Servis Talepleri": "Заявки на обслуживание",
  "Kuyrugu yenile": "Обновить очередь",
  "SLA inceleme istegi alindi": "Запрос на проверку SLA принят",
  "Servis SLA ve kanit kuyrugu incelemesi": "Проверка очереди SLA и подтверждений по заявкам",
  "Servis talebi verisi su anda alinamadi. Yerel veriyle devam ediliyor.": "Данные по заявкам сейчас недоступны. Продолжаем работу с локальными данными.",
  "Açık talep": "Открытая заявка",
  "SLA dışı": "Вне SLA",
  "Onay bekleyen": "Ожидает согласования",
  "Borç blokeli": "Блокировка по задолженности",
  "Medya kanıtı": "Медиа-подтверждение",
  "Katalog": "Каталог",
  "Siparis": "Заказ",
  "Saha gorevi": "Полевая задача",
  "Borc kapali": "Заблокировано по задолженности",
  "SLA {hours} saat": "SLA {hours} ч.",
  "Siparis hazirligi kayda alindi": "Подготовка заказа зафиксирована",
  "{name} servis siparisi": "Заказ на обслуживание {name}",
  "{count} blokeli": "{count} заблокировано",
  "{count} onay": "{count} на согласовании",
  "{count} SLA riski": "{count} в зоне риска по SLA",
  "Yonetici": "Управляющий",
  "{count} medya - SLA {sla} saat": "{count} медиа - SLA {sla} ч.",
  "Gorev aksiyonu kayda alindi": "Действие по задаче зафиксировано",
  "{id} saha gorevi": "Полевая задача {id}",
  "Aksiyon": "Действие",
  "Takipteki talepleriniz": "Ваши заявки на контроле",
  "Öncelikli iş kuyruğu": "Приоритетная рабочая очередь",
  "{count} gecikmiş": "{count} просрочено",
  "Finans blokeli": "Блокировка по финансам",
  "Servis kapsamı": "Область обслуживания",
  "Servis güvenlik kuralı": "Правило безопасности обслуживания",
  "Sadece sizin dairenize veya yetkili kaydınıza bağlı talepler gösterilir.": "Отображаются только заявки, привязанные к вашей квартире или вашей учётной записи.",
  "Borç blokeli dairelerde teknisyen sahaya çıkmadan önce muhasebe onayı ve ödeme doğrulaması gerekir.": "По квартирам с блокировкой из-за задолженности перед выездом техника требуется согласование бухгалтерии и подтверждение оплаты.",
  "Kanıt ve yanıt": "Подтверждения и ответы",
  "Saha iş akışı": "Рабочий процесс на объекте",
  "Fotoğraf, açıklama, randevu ve kapanış kararı yönetim ekibiyle aynı kayıt üzerinden paylaşılır.": "Фото, описание, время визита и решение о закрытии заявки передаются управляющей команде в той же карточке заявки.",
  "Talep, fotoğraf, maliyet, onay, atama ve kapanış kanıtı tek kayıtta tutulur.": "Заявка, фото, стоимость, согласование, назначение и подтверждение закрытия хранятся в одной карточке.",
  "Günlük rota": "Дневной маршрут",
  "AI önerisi": "Рекомендация ИИ",
  "SLA ve kanıt ihtiyacına göre teknik rota sadeleştirilir; finans tutarları saha görünümünde maskelenir.": "Маршрут техников формируется с учётом SLA и требований к подтверждениям; финансовые суммы скрыты в полевом интерфейсе.",
  "SLA, tahmini maliyet ve borç durumu birlikte skorlanarak günlük teknik rota oluşturulur.": "Дневной технический маршрут формируется на основе совокупной оценки SLA, ожидаемой стоимости и статуса задолженности.",
  "Ticketing mimarisi": "Архитектура тикет-системы",
  "Talep": "Заявка",
  "Konu": "Тема",
  "Öncelik": "Приоритет",
  "Sorumlu": "Ответственный",
  "Servis izni": "Допуск на обслуживание",
  "Ödeme": "Оплата",
  "Onaylı": "Согласовано",
  "Kontrol": "Контроль",
  "Maliyet": "Стоимость",
  "Rezervasyon & Giriş-Çıkış": "Бронирование и заезд-выезд",
  "Yetkili rezervasyon, giriş-çıkış, erişim kodu ve depozito durumunu sadece kendi kaydınız kapsamında takip edin.": "Отслеживайте бронирование, заезд-выезд, код доступа и статус депозита только в рамках вашей учётной записи.",
  "Saha ekibi için giriş-çıkış, temizlik, erişim ve operasyon görevleri sadeleştirilmiş çizelgede gösterilir.": "Задачи по заезду-выезду, уборке, доступу и операционной деятельности отображаются для полевой бригады в упрощённом графике.",
  "Web uygulama içinde rezervasyon, check-in, check-out, temizlik, erişim kodu ve depozito süreçlerini yönetin.": "Управляйте бронированием, заездом, выездом, уборкой, кодом доступа и депозитом непосредственно в веб-приложении.",
  "Aktif kayıt": "Активная запись",
  "Bugün giriş": "Заезд сегодня",
  "Bugün çıkış": "Выезд сегодня",
  "Depozito kontrol": "Проверка депозита",
  "Rezervasyon durumunuz": "Статус вашего бронирования",
  "Bugünkü operasyon çizelgesi": "Операционный график на сегодня",
  "aktif iş": "активные задачи",
  "Giriş": "Заезд",
  "Çıkış": "Выезд",
  "Depozito": "Депозит",
  "Erişim kodu": "Код доступа",
  "Erişim durumu yalnızca yetkili kaydınız için gösterilir.": "Статус доступа отображается только для вашей учётной записи.",
  "Borç, depozito ve kimlik kontrolü tamamlanınca erişim kodu onaya hazır hale gelir; aktivasyon insan onayıyla yapılır.": "После проверки задолженности, депозита и удостоверения личности код доступа готовится к утверждению; активация выполняется вручную.",
  "bekleyen veya kısıtlı kayıt": "запись в ожидании или с ограничением",
  "Kapanış kontrolü": "Контроль закрытия",
  "Hasar ve depozito": "Повреждения и депозит",
  "Check-out sonrası hasar, fotoğraf kanıtı ve iade kararı portal kaydına bağlanır.": "Повреждения после выезда, фотоподтверждения и решение о возврате депозита фиксируются в карточке портала.",
  "Check-out sonrası fotoğraf, servis maliyeti ve depozito kesintisi aynı finans kaydına bağlanır.": "Фото после выезда, стоимость работ и удержание из депозита фиксируются в одной финансовой записи.",
  "Saha önceliği": "Приоритет на объекте",
  "AI doluluk önerisi": "Рекомендация ИИ по загрузке",
  "Temizlik, erişim ve çıkış işleri günlük ekip kapasitesine göre sıralanır.": "Задачи по уборке, доступу и выезду выстраиваются в очередь с учётом дневной загрузки бригады.",
  "Boş daire, bakım durumu ve önceki kanal performansına göre fiyat ve kanal önerisi üretilebilir.": "На основе свободных квартир, статуса технического обслуживания и показателей каналов продаж формируется рекомендация по цене и каналу.",
  "Gezinti ve online tur akışı": "Процесс показов и онлайн-туров",
  "New Level Premium satış görüşmeleri dil, alıcı hedefi, kanal, sorumlu danışman ve takip tarihiyle yönetilir.": "Переговоры по продажам New Level Premium ведутся с учётом языка, цели покупателя, канала, ответственного консультанта и даты следующего контакта.",
  "aktif görüşme": "активных переговоров",
  "Onaylı tur": "Подтверждённый тур",
  "Takip gerekli": "Требуется контакт",
  "Online tur": "Онлайн-тур",
  "No-show kurtarma": "Работа с неявкой",
  "Tur": "Тур",
  "Hedef": "Цель",
  "İstenen tip": "Желаемый тип",
  "Kanal": "Канал",
  "Takip": "Контакт",
  "Sonraki aksiyon": "Следующее действие",
  "Kayıt": "Запись",
  "Misafir/Sakin": "Гость/Резидент",
  "Temizlik": "Уборка",
  "Onaylandı": "Подтверждено",
  "Tamamlandı": "Завершено",
  "Gelmedi": "Не явился",
  "Cevap gerekli": "Требуется ответ",
  "İşlemde": "В работе",
  "Hazır": "Готово",
  "Portal mesajları, bildirimler ve yönetim yanıtları yalnızca yetkili kaydınız kapsamında gösterilir.": "Сообщения портала, уведомления и ответы управляющей команды отображаются только в рамках вашей учётной записи.",
  "Saha ekibi için görev mesajları, SLA bildirimleri ve operasyon yanıtları sadeleştirilmiş görünümde tutulur.": "Сообщения по задачам, уведомления по SLA и операционные ответы отображаются для полевой бригады в упрощённом виде.",
  "Yönetim sohbeti, ekip içi koordinasyon, bildirim kuralları ve müşteri cevap takibi tek sayfada yönetilir.": "Переписка с управляющей командой, внутренняя координация, правила уведомлений и контроль ответов клиентам ведутся на одной странице.",
  "İletişim Merkezi": "Центр коммуникаций",
  "Açık konuşma": "Открытая переписка",
  "Acil takip": "Срочный контроль",
  "Hazır mesaj": "Готовый шаблон сообщения",
  "Rol kuralı": "Правило по ролям",
  "Portal konuşmaları": "Переписка в портале",
  "Müşteri ve ekip konuşmaları": "Переписка с клиентами и командой",
  "Kanal, konu, son mesaj ve durum bilgisi yetki kapsamınıza göre filtrelenir.": "Канал, тема, последнее сообщение и статус отображаются с учётом ваших прав доступа.",
  "Her konuşmada kanal, sorumlu ekip, öncelik ve son aksiyon görünür.": "В каждой переписке видны канал, ответственная команда, приоритет и последнее действие.",
  "Toplu bildirim hazırla": "Подготовить массовую рассылку",
  "Toplu bildirim taslağı hazırlandı": "Черновик массовой рассылки подготовлен",
  "Taslak hazır": "Черновик готов",
  "Toplu bildirim": "Массовая рассылка",
  "Kitle": "Аудитория",
  "Bildirim mantığı": "Логика уведомлений",
  "Bildirimler yanlış kişiye gitmeyecek şekilde daire ve rol kapsamıyla sınırlandırılır.": "Уведомления ограничены по квартире и роли, чтобы исключить отправку не тому получателю.",
  "Push, SMS, WhatsApp ve e-posta aynı olaydan tetiklenebilir; hassas finans ve erişim kararları insan onayı olmadan uygulanmaz.": "Push, SMS, WhatsApp и e-mail могут запускаться одним и тем же событием; критичные финансовые решения и решения по доступу без одобрения человека не применяются.",
  "Yanıt takibi": "Контроль ответов",
  "Negatif durumlar": "Негативные случаи",
  "Yönetim yanıtı, servis randevusu ve belge talebi aynı konuşma geçmişinde kalır.": "Ответ управляющей компании, заявка на сервисный визит и запрос документа сохраняются в одной истории переписки.",
  "Yanlış alıcı, kapalı kanal, borç ihtilafı, dil uyumsuzluğu ve tekrar eden mesajlar audit kuyruğuna düşer.": "Неверный получатель, закрытый канал, спор по задолженности, языковое несоответствие и повторяющиеся сообщения попадают в очередь аудита.",
  "Kural": "Правило",
  "Tetikleyici": "Триггер",
  "Sahip": "Ответственный",
  "Kritik": "Критично",
  "Yüksek": "Высокий",
  "Orta": "Средний",
  "Düşük": "Низкий",
  "Uygun": "Соответствует",
  "Kontrol gerekli": "Требуется проверка",
  "Partner incelemesi": "Проверка партнёра",
  "Kimlik": "Идентификация",
  "QR, kart, plaka": "QR, карта, номер авто",
  "Finans": "Финансы",
  "Borç ve depozito": "Задолженность и депозит",
  "Karar": "Решение",
  "Geçiş veya kısıt": "Доступ или ограничение",
  "Kapı": "Дверь",
  "Otopark": "Паркинг",
  "Havuz": "Бассейн",
  "Asansör": "Лифт",
  "Erişim karar motoru": "Движок решений по доступу",
  "Kapı, borç, depozito ve kimlik tek karar motorunda": "Дверь, задолженность, депозит и идентификация - в едином движке решений",
  "Sistem erişim kararını sadece geçiş kartı olarak değil; ödeme, rezervasyon, belge ve güvenlik sinyaliyle birlikte değerlendirir.": "Система принимает решение по доступу не только на основании карты доступа, а с учётом оплаты, бронирования, документов и сигналов безопасности.",
  "aktif kısıt": "активное ограничение",
  "Canlı risk filtresi": "Фильтр риска в реальном времени",
  "{pending} bekleyen, {critical} kritik karar": "{pending} в ожидании, {critical} критичных решений",
  "Denetim ritmi": "Периодичность контроля",
  "Her geçiş kararı kullanıcı, sebep, saat ve belge referansıyla kayıt altında tutulur.": "Каждое решение о доступе фиксируется с указанием пользователя, причины, времени и ссылки на документ.",
  "Erişim & Uyum": "Доступ и соответствие",
  "Mobil kod, kart, plaka, QR, borç kısıtı, depozito kontrolü ve güvenlik olaylarını tek karar motorunda izleyin.": "Отслеживайте мобильный код, карту, номер авто, QR, ограничение по задолженности, контроль депозита и события безопасности в едином движке решений.",
  "Takipteki kayıt": "Запись на контроле",
  "Kısıtlı": "Ограничено",
  "Bekleyen": "В ожидании",
  "Kritik risk": "Критичный риск",
  "Erişim bölgesi yoğunluğu": "Загруженность зоны доступа",
  "{count} bölge": "{count} зон",
  "Kapı karar motoru": "Движок решений по дверям",
  "Borç, rezervasyon, depozito ve kimlik kontrolü tamamlanmadan geçici erişim açılmaz.": "Временный доступ не открывается до завершения проверки задолженности, бронирования, депозита и идентификации.",
  "Plaka ve otopark": "Номер авто и паркинг",
  "Otopark, misafir ve sakin erişimleri aynı uyum kayıtlarına bağlanır.": "Доступ на паркинг, для гостей и жильцов привязан к единым записям соответствия.",
  "Her erişim kararı kullanıcı, sebep, saat ve belge referansıyla denetlenebilir tutulur.": "Каждое решение по доступу подлежит проверке с указанием пользователя, причины, времени и ссылки на документ.",
  "Oturum, vatandaşlık ve alıcı uygunluk ön kontrolü": "Предварительная проверка резидентства, гражданства и соответствия покупателя",
  "Satış ekibi uygunluk ön kontrolünü görür; sistem hukuki garanti vermez ve riskli durumları partner incelemesine gönderir.": "Отдел продаж видит результат предварительной проверки соответствия; система не даёт юридических гарантий и направляет рисковые случаи на проверку партнёра.",
  "{count} inceleme kuyruğu": "{count} в очереди на проверку",
  "Alıcı dosyası": "Дело покупателя",
  "Ön uygun": "Предварительно одобрено",
  "Ekspertiz gerekli": "Требуется экспертиза",
  "Bütçe": "Бюджет",
  "Bölge": "Регион",
  "Ekspertiz": "Экспертиза",
  "Gerekli": "Требуется",
  "Gerekmez": "Не требуется",
  "Sakin": "Жилец",
  "Risk": "Риск",
  "Sebep": "Причина",
  "İnceleme": "Проверка",
  "Planlı": "Запланировано",
  "Var": "Есть",
  "Yok": "Нет",
  "Bildirim kuralları": "Правила уведомлений",
  "Borç, SLA, check-in, check-out ve belge eksikliği için rol bazlı uyarılar.": "Уведомления по ролям для задолженности, SLA, заезда, выезда и недостающих документов.",
  "Güvenlik politikası": "Политика безопасности",
  "Rol bazlı erişim, hassas finans işlemleri ve insan onaylı AI kararları.": "Доступ на основе ролей, чувствительные финансовые операции и решения AI с одобрением человека.",
  "Dil ve yerelleştirme": "Язык и локализация",
  "Türkçe ana kullanım, çok dilli sakin desteği ve resmi ton standardı.": "Турецкий как основной язык, поддержка жильцов на нескольких языках и стандарт официального тона.",
  "Platform Yönetim Merkezi": "Центр управления платформой",
  "Rol yetki kapsamı, denetim izi, güvenlik kontrolleri ve kullanıcı görünürlüğü tek yönetim alanında takip edilir.": "Объём прав ролей, журнал аудита, проверки безопасности и видимость пользователей отслеживаются в едином разделе управления.",
  "Yüksek risk denetim": "Аудит высокого риска",
  "Güvenlik ve platform kontrolleri": "Безопасность и контроли платформы",
  "Her kontrolün sahibi, amacı ve canlı durumu yönetim için görünür.": "Ответственный, цель и текущий статус каждой проверки видны руководству.",
  "Operasyon ayarları": "Настройки операций",
  "Yönetici, finans, güvenlik ve saha ekipleri aynı kontrol merkezinden standart kuralları görür.": "Управляющий, финансы, безопасность и полевые команды видят стандартные правила из единого центра контроля.",
  "Görünüm": "Внешний вид",
  "Açık/koyu tema desteği.": "Поддержка светлой/тёмной темы.",
  "Rol": "Роль",
  "Kullanıcı": "Пользователь",
  "Finans onayı": "Финансовое одобрение",
  "Erişim kısıtı": "Ограничение доступа",
  "Dışa aktarım": "Экспорт",
  "Denetim": "Аудит",
  "Aktör": "Инициатор",
  "Platform sürümü:": "Версия платформы:",
  "Doğrulandı": "Подтверждено",
  "Bekliyor": "Ожидает",
  "Eksik": "Отсутствует",
  "Süresi doldu": "Истёк срок",
  "Reddedildi": "Отклонено",
  "Yetkili dairenize bağlı sözleşme, kimlik, depozito, servis ve uyum belgelerini güvenli portal görünümünde takip edin.": "Отслеживайте договоры, документы удостоверения личности, депозиты, сервисные и документы соответствия по вашему объекту в защищённом портале.",
  "Saha operasyonu için yalnızca görev dosyaları, servis kanıtları ve gerekli onay kayıtları gösterilir.": "Для полевой операции отображаются только файлы по задачам, подтверждения выполненных работ и необходимые записи об одобрении.",
  "satış ve after-sales süreci için TAPU, kimlik, sözleşme, ödeme, depozito, servis, uyum ve proje belgelerini güvenli, denetlenebilir ve işlem bağlantılı yönetin.": "управляйте документами TAPU, удостоверениями личности, договорами, платежами, депозитами, сервисными и нормативными документами, а также проектной документацией для процессов продаж и постпродажного обслуживания — безопасно, с возможностью аудита и привязкой к операционной деятельности.",
  "TAPU & Belge Kasası": "TAPU и хранилище документов",
  "Belge yükle": "Загрузить документ",
  "Toplam belge": "Всего документов",
  "Eksik/Süre doldu": "Отсутствует/Истёк срок",
  "Satış dosyası, TAPU, KYC ve EIDS kontrolü": "Дело продажи, проверка TAPU, KYC и EIDS",
  "Satış dosyası; alıcı kimliği, TAPU, EIDS, rezervasyon, satış sözleşmesi ve ödeme planı olmadan sonraki adıma geçmez.": "Дело продажи не переходит на следующий этап без удостоверения личности покупателя, TAPU, EIDS, бронирования, договора купли-продажи и плана платежей.",
  "{count} yüksek risk": "{count} с высоким риском",
  "Satış belgesi": "Документ по продаже",
  "Belge tipi": "Тип документа",
  "Belge": "Документ",
  "Kapsam": "Охват",
  "Dosya": "Дело",
  "Kategori": "Категория",
  "İşlem": "Операция",
  "Belgeyi görüntüle": "Просмотреть документ",
  "Belgeyi indir": "Скачать документ",
  "Kiracı": "Арендатор",
  "Misafir": "Гость",
  "Müşteri & Malik CRM": "CRM клиентов и собственников",
  "için alıcı, malik, kiracı ve misafirleri; dil, WhatsApp/telefon tercihi, borç, servis, erişim ve yatırım ilgisiyle tek kayıt altında yönetin.": "управляет покупателями, собственниками, арендаторами и гостями в единой записи, включая язык, предпочтения по WhatsApp/телефону, задолженность, обращения в сервис, доступ и инвестиционный интерес.",
  "Aktif sakin": "Активный жилец",
  "Riskli kayıt": "Рисковая запись",
  "WhatsApp tercih": "Предпочтение WhatsApp",
  "Çok dilli destek": "Многоязычная поддержка",
  "AI iletişim önceliği": "Приоритет коммуникации AI",
  "aksiyon": "действия",
  "servis": "заявок",
  "İletişim merkezi": "Центр коммуникаций",
  "WhatsApp, telefon, e-posta ve portal bildirimleri tek sakin profiline bağlanır.": "WhatsApp, телефон, e-mail и уведомления портала привязаны к единому профилю жильца.",
  "Borç + servis bağlamı": "Контекст задолженности и сервиса",
  "Sakin temsilcisi aramadan önce açık borç, erişim kısıtı ve servis geçmişini görür.": "Оператор по работе с жильцами перед звонком видит открытую задолженность, ограничение доступа и историю обращений по сервису.",
  "Ad": "Имя",
  "Tip": "Тип",
  "Dil": "Язык",
  "Telefon": "Телефон",
  "Kapalı": "Закрыто",
  "AI Rapor Merkezi": "Центр отчётов AI",
  "Yönetim kurulu, muhasebe, operasyon, güvenlik ve misafir ekipleri için hazır rapor görünümleri ve karar özetleri.": "Готовые представления отчётов и сводки решений для совета директоров, бухгалтерии, операционного отдела, службы безопасности и команд по работе с гостями.",
  "Rapor seti": "Набор отчётов",
  "AI kontrol": "Контроль AI",
  "Tahsilat trendi": "Динамика сбора платежей",
  "Daire dağılımı": "Распределение квартир",
  "Yönetim kuruluna uygun tek bakışlık portföy özeti.": "Сводка портфеля одним взглядом, подходящая для совета директоров.",
  "{bucket} gün borç": "Задолженность {bucket} дн.",
  "AI aksiyon listesinde önceliklendirilir.": "AI расставляет приоритеты в списке действий.",
  "Rapor": "Отчёт",
  "Başlık": "Заголовок",
  "Periyot": "Период",
  "Metrik": "Показатель",
  "AI içgörü": "AI-инсайт",
  "Dışa aktar": "Экспорт",
  "Raporu dışa aktar": "Экспортировать отчёт",
  "Kullanıcılar & Roller": "Пользователи и роли",
  "Malik, kiracı, misafir ve personel kayıtları; dil, görev yükü ve yetki kapsamı tek yönetim alanında izlenir.": "Учёт собственников, арендаторов, гостей и персонала; язык, загрузка по задачам и объём полномочий отслеживаются в единой панели управления.",
  "Personel": "Персонал",
  "Sakin kaydı": "Учётная запись жильца",
  "Aktif görev": "Активная задача",
  "Finans onaycı": "Согласующий по финансам",
  "Personel operasyon kapsamı": "Операционный охват персонала",
  "Her ekip üyesinin rolü, saha yükü, onay limiti ve erişim kapsamı yönetim için görünürdür.": "Роль, нагрузка на объекте, лимит согласования и объём доступа каждого сотрудника видны руководству.",
  "Görev": "Задача",
  "Limit": "Лимит",
  "Yetki prensibi": "Принцип полномочий",
  "Kullanıcı sadece kendi görevi için gerekli modülleri görür. Finans, erişim ve kullanıcı yönetimi ayrı onay kapsamındadır.": "Пользователь видит только модули, необходимые для его задачи. Финансы, доступ и управление пользователями находятся в отдельном контуре согласования.",
  "Riskli": "Риск",
  "Ekip": "Команда",
  "Export": "Экспорт",
  "Yönetim": "Управление",
  "Muhasebe": "Бухгалтерия",
  "Eğitim": "Обучение",
  "Tüm site": "Весь комплекс",
  "Operasyon": "Операции",
  "Sadece finans": "Только финансы",
  "Saha": "Объект",
  "Bu sayfa rolünüz için kapalı": "Эта страница закрыта для вашей роли",
  "Yetki modeli güvenlik nedeniyle varsayılan olarak erişimi reddeder. Sizin rolünüz için açık olan panele yönlendiriliyorsunuz.": "Модель полномочий по умолчанию запрещает доступ в целях безопасности. Вы будете перенаправлены на панель, доступную для вашей роли.",
  "Finans defteri": "Финансовый журнал",
  "Aidat, ödeme, depozito, ceza ve düzeltme kayıtları değiştirilemez defter mantığıyla takip edilir. Hassas finans aksiyonları onay ve denetim akışına alınır.": "Начисления, платежи, депозиты, штрафы и корректировки ведутся по логике неизменяемого журнала. Чувствительные финансовые операции проходят через согласование и аудит.",
  "Son güncelleme:": "Последнее обновление:",
  "Defteri yenile": "Обновить журнал",
  "Finans defteri dışa aktarım isteği oluştur": "Создать запрос на экспорт финансового журнала",
  "Dışa aktarım isteği alındı": "Запрос на экспорт принят",
  "Finans defteri dışa aktarım isteği": "Запрос на экспорт финансового журнала",
  "Finans defteri şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Не удалось загрузить финансовый журнал. Повторите попытку через кнопку обновления или проверьте статус API.",
  "Finans defteri kalite kontrolü dikkat istiyor:": "Контроль качества финансового журнала требует внимания:",
  "Açık bakiye": "Открытый остаток",
  "Bu ay tahsilat": "Сборы за этот месяц",
  "Açık kayıt": "Открытая запись",
  "Son finans kayıtları": "Последние финансовые записи",
  "vade": "срок платежа",
  "Finans kaydı bulunamadı.": "Финансовые записи не найдены.",
  "Finans kontrol modeli": "Модель финансового контроля",
  "Onaylanmış finans kaydı doğrudan değiştirilmez; düzeltme için karşı kayıt açılır. Dışa aktarım, mutabakat ve ödeme aksiyonları role göre denetim akışına alınır.": "Согласованная финансовая запись не изменяется напрямую; для корректировки открывается встречная запись. Экспорт, сверка и платёжные операции проходят аудит в зависимости от роли.",
  "Onaylı kayıt": "Согласованная запись",
  "Yasal risk": "Юридический риск",
  "Ödendi": "Оплачено",
  "Açık": "Открыто",
  "Kısmi": "Частично",
  "İptal": "Отменено",
  "Bilinmiyor": "Неизвестно",
  "Daire yok": "Нет квартиры",
  "Kişi yok": "Нет контакта",
  "Blokaj yok": "Нет блокировки",
  "Rezervasyon sözleşmesi eksik": "Отсутствует договор резервирования",
  "İkinci taksit doğrulanmadı": "Второй платёж не подтверждён",
  "Ödeme planı imzası bekliyor": "Ожидается подпись плана платежей",
  "Blokede": "Заблокировано",
  "Rezerve": "Зарезервировано",
  "İade hazır": "Готово к возврату",
  "İade edildi": "Возвращено",
  "Kesinti bekliyor": "Ожидается удержание",
  "Kesildi": "Удержано",
  "Tahsil edildi": "Собрано",
  "Hatalı": "Ошибка",
  "İade": "Возврат",
  "Banka transferi": "Банковский перевод",
  "Manuel banka": "Ручной банковский перевод",
  "tamamlandı": "завершено",
  "Checkout": "Выезд",
  "gün": "дн.",
  "Riskli plan": "Рисковый план",
  "Depozito kuyruğu": "Очередь по депозитам",
  "Kısıt kararı": "Решение об ограничении",
  "Mutabakat": "Сверка",
  "Onay kuyruğu": "Очередь согласования",
  "Ödeme, depozito ve kısıt kontrol merkezi": "Центр контроля платежей, депозитов и ограничений",
  "Satış ödeme planı, depozito iadesi, banka mutabakatı ve borca bağlı erişim kısıtı aynı onay kuyruğunda izlenir. Sistem karar önerir; finans ve erişim aksiyonları insan onayıyla kapanır.": "План платежей по продаже, возврат депозита, банковская сверка и ограничение доступа за долг отслеживаются в единой очереди согласования. Система предлагает решение; финансовые операции и операции доступа закрываются только после согласования человеком.",
  "Kontrolleri yenile": "Обновить проверки",
  "Mutabakat inceleme isteği oluştur": "Создать запрос на проверку сверки",
  "İnceleme isteği alındı": "Запрос на проверку принят",
  "Phase 7 mutabakat inceleme isteği": "Запрос на проверку сверки Phase 7",
  "İnceleme aç": "Открыть проверку",
  "Ödeme kontrol verisi şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Не удалось загрузить данные контроля платежей. Повторите попытку через кнопку обновления или проверьте статус API.",
  "Kalite kontrolü dikkat istiyor:": "Контроль качества требует внимания:",
  "Ödeme planı ve depozito işi": "Задача по плану платежей и депозиту",
  "Açık vade": "Открытый срок платежа",
  "Açık ödeme veya depozito işi bulunamadı.": "Открытые задачи по платежам или депозитам не найдены.",
  "Kısıt ve mutabakat kuyruğu": "Очередь ограничений и сверки",
  "depozito": "депозит",
  "Kısıt veya mutabakat kuyruğu boş.": "Очередь ограничений или сверки пуста.",
  "Iade emrini finans onay kuyruguna al": "Поставить распоряжение на возврат в очередь согласования финансов",
  "Erisim kodunu depozito ve borc kontrolu kapanana kadar acma": "Не открывать код доступа до закрытия проверки депозита и задолженности",
  "Temizlik blokajini operasyonla eslestir": "Сопоставить блокировку по уборке с операционным отделом",
  "Yasal takip ve erişim kısıtı": "Юридическое взыскание и ограничение доступа",
  "Telefon + WhatsApp tahsilat": "Сбор задолженности по телефону и WhatsApp",
  "Otomatik hatırlatma": "Автоматическое напоминание",
  "Aile": "Семья",
  "Yetkili": "Ответственное лицо",
  "telefon yok": "нет телефона",
  "Daire bağlantısı yok": "Нет привязки к квартире",
  "Kişi ve rol dizini": "Справочник контактов и ролей",
  "Personel, malik, kiracı, misafir ve rol kapsamı tek dizinden yönetilir. Ekip yükü, erişim kapsamı ve riskli kayıtlar aynı ekranda takip edilir.": "Персонал, собственники, арендаторы, гости и объём ролей управляются из единого справочника. Загрузка команды, объём доступа и рисковые записи отслеживаются на одном экране.",
  "Son güncelleme: {lastUpdated}": "Последнее обновление: {lastUpdated}",
  "Kişi verisini yenile": "Обновить данные контактов",
  "Kişi dizini dışa aktarım isteği oluştur": "Создать запрос на экспорт справочника контактов",
  "Kişi dizini dışa aktarım isteği": "Запрос на экспорт справочника контактов",
  "Kişi dizini şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Не удалось загрузить справочник контактов. Повторите попытку через кнопку обновления или проверьте статус API.",
  "Kişi dizini kalite kontrolü dikkat istiyor: {checks}": "Контроль качества справочника контактов требует внимания: {checks}",
  "Malik / Kiracı": "Собственник / Арендатор",
  "Personel iş yükü": "Загрузка персонала",
  "Sakin bağlantıları": "Связи жильца",
  "Risk {riskScore}": "Риск {riskScore}",
  "Rol kapsamı": "Объём ролей",
  "Rol matrisi kullanıcı görünürlüğü, finans onayı, erişim kısıtı ve dışa aktarım yetkisini ayrı ayrı tutar.": "Матрица ролей раздельно определяет видимость для пользователя, согласование финансов, ограничение доступа и право на экспорт.",
  "Onaycı": "Согласующий",
  "Site operations risk map": "Карта операционных рисков комплекса",
  "Operasyon risk haritası": "Карта операционных рисков",
  "Blok, borç, servis ve erişim risk haritası": "Карта рисков по блокам, задолженности, заявкам и доступу",
  "8 blok ve 769 daire; borç, servis, erişim ve SLA riskleri tek operasyon görünümünde okunur.": "8 блоков и 769 квартир; риски по задолженности, заявкам, доступу и SLA отображаются в едином операционном обзоре.",
  "kısıt": "ограничение",
  "borç": "задолженность",
  "3D blok risk haritasını daire matrisinde aç": "Открыть 3D-карту рисков блока в матрице квартир",
  "Tahsilat rotası": "Маршрут сбора задолженности",
  "90+ gün, aktif rezervasyon ve erişim kısıtı birlikte skorlanır.": "Задолженность 90+ дн., активные резервирования и ограничения доступа оцениваются совместно.",
  "SLA alarmı": "Тревога по SLA",
  "{count} iş": "{count} задач",
  "Teknik rota ödeme onayı ve öncelik riskine göre sıralanır.": "Технический маршрут сортируется по согласованию платежа и риску приоритета.",
  "Erişim motoru": "Модуль контроля доступа",
  "{count} kısıt": "{count} ограничений",
  "Mobil kod, kart ve plaka kararları tek güvenlik modelinden geçer.": "Решения по мобильному коду, карте и номеру автомобиля проходят через единую модель безопасности.",
  "AI nabız": "Пульс AI",
  "{count} risk": "{count} риск(ов)",
  "Her risk aksiyona çevrilir: ara, kısıtla, servis ata, belge iste.": "Каждый риск преобразуется в действие: позвонить, ограничить, назначить заявку, запросить документ.",
  "{label} detayını aç": "Открыть детали {label}",
  "operasyon kaydı": "операционных записей",
  "portföy akışı": "операций по портфелю",
  "tamamlanan işlem": "завершённых операций",
  "rol bazlı ekip": "сотрудников по ролям",
  "Emlak satışını, site yönetimini ve servis operasyonunu tek çalışma alanında yönetin.": "Управляйте продажей недвижимости, эксплуатацией комплекса и сервисными операциями в едином рабочем пространстве.",
  "1Çatı; CRM, portföy, finans, servis, belge, uyumluluk ve malik raporlamasını Türkiye emlak pazarı için tasarlanmış rol bazlı bir ERP deneyiminde birleştirir.": "1Çatı объединяет CRM, портфель объектов, финансы, сервис, документооборот, комплаенс и отчётность для собственников в едином ERP-решении с ролевым доступом, разработанном для рынка недвижимости Турции.",
  "Çalışma alanına gir": "Войти в рабочее пространство",
  "Ürün akışını incele": "Изучить процесс работы с продуктом",
  "Operasyon modeli": "Операционная модель",
  "Tek kayıt, net yetki, hızlı aksiyon.": "Единая запись, чёткие полномочия, быстрое действие.",
  "Ekipler arası kopukluk yerine, her işlem daire, kişi, belge, ödeme ve görev ilişkisiyle görünür hale gelir.": "Вместо разрыва между отделами каждая операция становится видимой через связь с квартирой, контактом, документом, платежом и задачей.",
  "Portföy ve daire kontrolü": "Контроль портфеля объектов и квартир",
  "Blok, kat, daire, malik, sakin, borç, servis ve erişim durumu tek kayıt üzerinden filtrelenir.": "Блок, этаж, квартира, собственник, жилец, задолженность, сервис и статус доступа фильтруются через единую запись.",
  "CRM ve rol bazlı çalışma": "CRM и работа по ролям",
  "Satış, muhasebe, saha, güvenlik, malik ve kiracı ekranları aynı veriye kendi yetki kapsamıyla erişir.": "Экраны продаж, бухгалтерии, полевых служб, охраны, собственников и арендаторов обращаются к одним данным в рамках своих полномочий.",
  "Uyumluluk ve denetim": "Комплаенс и аудит",
  "EİDS, TAPU, belge, ödeme, erişim ve hassas aksiyonlar izlenebilir karar kayıtlarıyla yönetilir.": "EİDS, TAPU, документы, платежи, доступ и чувствительные действия управляются с прослеживаемыми журналами решений.",
  "Temel ERP modülleri": "Основные модули ERP",
  "CRM, lead ve iletişim merkezi": "CRM, лиды и центр коммуникаций",
  "Daire matrisi ve portföy yönetimi": "Матрица квартир и управление портфелем",
  "Servis, saha görevleri ve SLA takibi": "Сервис, полевые задачи и контроль SLA",
  "Finans defteri, aidat ve tahsilat": "Финансовый журнал, взносы и сбор задолженности",
  "Belge kasası, TAPU, KYC ve EİDS kontrolleri": "Хранилище документов, TAPU, проверки KYC и EİDS",
  "Malik, kiracı, personel ve rol matrisi": "Матрица собственников, арендаторов, персонала и ролей",
  "Entegrasyon ve otomasyon katmanı": "Уровень интеграций и автоматизации",
  "Sağlayıcı kararı bekleyen yol haritası; üretimde henüz aktif değildir.": "Дорожная карта в ожидании выбора провайдеров; ещё не активна в продакшене.",
  "E-posta, SMS, WhatsApp/Telegram ve bildirim sağlayıcıları": "Провайдеры e-mail, SMS, WhatsApp/Telegram и уведомлений",
  "Ödeme, banka mutabakatı ve dijital bakiye yükleme akışları": "Платежи, банковская сверка и процессы пополнения цифрового баланса",
  "Erişim kontrolü, plaka/kart/bariyer ve sayaç entegrasyonları": "Контроль доступа, интеграции с номерными знаками/картами/шлагбаумами и счётчиками",
  "AI brifing, risk sıralama, kaynaklı yanıtlar ve insan onaylı aksiyonlar": "AI-брифинг, ранжирование рисков, ответы со ссылкой на источник и действия с подтверждением человеком",
  "Kalite standardı": "Стандарт качества",
  "Üretim sistemi gibi tasarlanır, kontrol sistemi gibi işletilir.": "Проектируется как производственная система, эксплуатируется как система контроля.",
  "Güvenilir": "Надёжность",
  "TypeScript, üretim build'i, tarayıcı kontrolleri ve rol bazlı testler release öncesi çalıştırılır.": "Перед релизом выполняются проверки TypeScript, продакшн-сборка, браузерные тесты и тесты по ролям.",
  "İzlenebilir": "Подотчётность",
  "Finans, erişim, belge ve veri değişiklikleri aktör, zaman, modül ve gerekçe ile kaydedilir.": "Изменения в финансах, доступе, документах и данных фиксируются с указанием пользователя, времени, модуля и причины.",
  "Ölçeklenebilir": "Масштабируемость",
  "769 birimlik operasyon verisi, çok dilli ekipler ve büyüyen portföy için modüler yapı kullanılır.": "Используется модульная структура для операционных данных по 769 объектам, многоязычных команд и растущего портфеля.",
  "Asansör kapısı arızası": "Неисправность двери лифта",
  "Daire içi su kaçağı": "Утечка воды в квартире",
  "Klima drenaj kontrolü": "Проверка дренажа кондиционера",
  "Aidat borcu nedeniyle hizmet bekliyor": "Услуга приостановлена из-за задолженности по взносам",
  "Ortak alan kamera kontrolü": "Проверка камер в общих зонах",
  "Check-out sonrası hasar raporu": "Акт повреждений после выезда",
  "Elektrik pano bakımı": "Обслуживание электрощита",
  "Temizlik ekibi yönlendirme": "Направление клининговой бригады",
  "Havuz teknik ölçüm": "Технические замеры бассейна",
  "Kapı giriş kartı yenileme": "Перевыпуск карты доступа",
  "Yangın sensörü testi": "Тест пожарного датчика",
  "Balkon camı hasar tespiti": "Осмотр повреждений балконного стекла",
  "Otopark bariyer erişimi": "Доступ к шлагбауму паркинга",
  "Legal takip öncesi son bildirim": "Последнее уведомление перед передачей в юридическое взыскание",
  "Tesisat": "Сантехника",
  "İklimlendirme": "Климатическое оборудование",
  "Güvenlik": "Безопасность",
  "Elektrik": "Электрика",
  "Ortak alan": "Общая зона",
  "Hasar": "Повреждение",
  "Tahsilat": "Взыскание задолженности",
  "Antalya havalimani transferi": "Трансфер из/в аэропорт Антальи",
  "Spa, fitness ve ortak alan rezervasyonu": "Бронирование спа, фитнеса и общих зон",
  "Kart, QR ve plaka erisim islemi": "Операция доступа по карте, QR и номерному знаку",
  "Hasar tespiti ve depozito raporu": "Осмотр повреждений и отчёт по депозиту",
  "Yeni kart/QR, plaka tanimi, kayip kart iptali ve erisim log kontrolu.": "Выпуск новой карты/QR, привязка номерного знака, аннулирование утерянной карты и проверка журнала доступа.",
  "Checkout, bakim veya sikayet sonrasi fotograf/video kanitli hasar raporu.": "Акт повреждений с фото/видео подтверждением после выезда, обслуживания или жалобы.",
  "Kat hizmetleri": "Хаускипинг",
  "Rezervasyon": "Бронирование",
  "Sakin destek": "Поддержка жильцов",
  "Asansor": "Лифт",
  "Iklimlendirme": "Климатическое оборудование",
  "Finans onayi": "Финансовое согласование",
  "Erisim": "Доступ",
  "Odeme linki veya cari hesaba borclandirma secimini onayla": "Подтвердить выбор: ссылка на оплату или списание с текущего счёта",
  "Malik/kiraci memnuniyet ve kapanis onayini al": "Получить подтверждение закрытия и удовлетворённости собственника/арендатора",
  "Arsiv ve rapor kontrolu": "Проверка архива и отчёта",
  "Parca/islem notunu gir": "Внести заметку по запчастям/работам",
  "Kapanis kaniti yukle": "Загрузить подтверждение закрытия",
  "Kimlik/yetki kontrolu": "Проверка личности/полномочий",
  "Kart/QR/plaka islem kaydi": "Журнал операций по карте/QR/номерному знаку",
  "Access log kontrolu": "Проверка журнала доступа",
  "Kapanis onayi": "Подтверждение закрытия",
  "Temizlik checklist": "Чек-лист уборки",
  "Teslim notu": "Акт передачи",
  "Depozito etkisini not et": "Зафиксировать влияние на депозит",
  "Kapanis raporu": "Отчёт по закрытию",
  "Tamamlandi onayi": "Подтверждение выполнения",
  "Yetki kapsamını dogrula": "Подтвердить объём полномочий",
  "Randevu uygunlugunu kontrol et": "Проверить доступность времени визита",
  "Bildirim gonder": "Отправить уведомление",
  "Geri bildirim al": "Получить обратную связь",
  "Hemen": "Срочно",
  "Sabah": "Утро",
  "Ogle": "День",
  "Aksam": "Вечер",
  "Finans onayi bekleniyor; saha aksiyonu kilitli.": "Ожидается финансовое согласование; полевые действия заблокированы.",
  "SLA asimi var; ekip lideri eskalasyonu gerekli.": "Нарушение SLA; требуется эскалация руководителю бригады.",
  "Atama ve kanit akisi hazir.": "Назначение и процесс подтверждения готовы.",
  "Ana Kapı": "Главный вход",
  "Depo": "Склад",
  "Mobil Kod": "Мобильный код",
  "Kart": "Карта",
  "Plaka": "Номерной знак",
  "QR": "QR",
  "Aidat borcu veya depozito kontrolü": "Задолженность по взносам или проверка депозита",
  "Giriş ön kontrolü bekliyor": "Ожидает предварительной проверки на входе",
  "Bakım veya güvenlik kapaması": "Блокировка на обслуживание или по безопасности",
  "Normal kullanım": "Обычное использование",
  "Sözleşme": "Договор",
  "Aidat": "Взнос",
  "Uyum": "Соответствие",
  "Kaynak: {path}": "Источник: {path}",
  "OCR / insan onayı gerekli: {path}": "Требуется OCR / проверка вручную: {path}",
  "Yönetim Kurulu Operasyon Özeti": "Операционная сводка для правления",
  "Aidat Tahsilat ve Yaşlandırma": "Взыскание взносов и просрочка",
  "Servis SLA ve Maliyet Kontrolü": "SLA сервисных заявок и контроль затрат",
  "Rezervasyon, Depozito ve Hasar": "Бронирование, депозиты и ущерб",
  "Erişim Güvenliği ve Uyum": "Безопасность доступа и соответствие",
  "Haftalık": "Еженедельно",
  "Günlük": "Ежедневно",
  "Anlık": "В реальном времени",
  "Müdür": "Управляющий",
  "Misafir Operasyonu": "Операции с гостями",
  "769 daire / %70 doluluk": "769 квартир / заполняемость 70%",
  "1.4M ₺ açık borç": "Непогашенный долг 1,4 млн ₺",
  "4 SLA dışı servis": "4 заявки вне SLA",
  "2 kritik check-out": "2 критичных выезда",
  "33 kısıtlı erişim": "33 ограничения доступа",
  "Borç ve servis SLA riski aynı raporda izlenmeli.": "Риски по долгам и SLA сервисных заявок нужно отслеживать в одном отчёте.",
  "90+ gün borçlu 19 hesap erişim kısıtıyla takip edilmeli.": "19 счетов с задолженностью более 90 дней должны отслеживаться с ограничением доступа.",
  "Borç blokeli servisler finans onayı olmadan sahaya düşmemeli.": "Заявки, заблокированные по долгу, не должны попадать на объект без согласования с финансовым отделом.",
  "Depozito kesintisi fotoğraf kanıtı ile kapatılmalı.": "Удержание депозита необходимо закрывать с фотодоказательствами.",
  "Mobil kod, kart ve plaka erişimi aynı karar motorundan yönetilmeli.": "Мобильный код, карта и доступ по номеру авто должны управляться единым механизмом принятия решений.",
  "23 daire için otomatik borç hatırlatma kuyruğu hazırlandı.": "Для 23 квартир сформирована очередь автоматических напоминаний о долге.",
  "Bugünkü 2 check-out için depozito hasar kontrolü açıldı.": "Для 2 сегодняшних выездов открыта проверка депозита на предмет ущерба.",
  "Acil asansör talebi teknisyene atandı ve SLA sayacı başladı.": "Срочная заявка по лифту назначена технику, таймер SLA запущен.",
  "Haziran tahsilat riski yüksek 37 hesap için öncelik skoru üretildi.": "Для 37 счетов с высоким риском невзыскания за июнь рассчитан приоритетный балл.",
  "Tahsilat önceliği": "Приоритет взыскания",
  "Servis darboğazı": "Затор по сервисным заявкам",
  "Check-out kontrolü": "Контроль выезда",
  "37 hesapta gecikme riski yüksek. AI, önce 90+ gün ve aktif rezervasyonu olan daireleri öneriyor.": "По 37 счетам высокий риск просрочки. ИИ рекомендует начать с квартир с задержкой 90+ дней и активным бронированием.",
  "3 talep SLA dışına çıktı. Borç blokeli talepler finans onayı olmadan sahaya gönderilmemeli.": "3 заявки вышли за пределы SLA. Заявки, заблокированные по долгу, нельзя направлять на объект без согласования с финансовым отделом.",
  "2 check-out bugün kapanıyor. Depozito kesintisi ve temizlik kanıtı aynı akışta tamamlanmalı.": "Сегодня закрываются 2 выезда. Удержание депозита и подтверждение уборки нужно завершить в рамках одного процесса.",
  "Kas": "Ноя",
  "Oca": "Янв",
  "Şub": "Фев",
  "Mar": "Мар",
  "Nis": "Апр",
  "May": "Май",
  "Haz": "Июн",
  "Ağu": "Авг",
  "Eyl": "Сен",
  "Eki": "Окт",
  "Ara": "Дек",
  "Yetkili kiracı kaydı": "Учётная запись авторизованного арендатора",
  "Yetkili malik kaydı": "Учётная запись авторизованного собственника",
  "Operasyon görev dosyası": "Файл операционной задачи",
  "Portalda görüntülenebilir": "Доступно для просмотра в портале",
  "Yönetim onayı bekliyor": "Ожидает согласования руководства",
  "Checkout tamamlanana kadar depozitoyu bloke tut": "Блокировать депозит до завершения выезда",
  "Depozito ve erisim kararini finans onayina bagla": "Привязать решение по депозиту и доступу к согласованию финансового отдела",
  "Erisim kisitini hukuk ve finans onayiyla surdur": "Сохранять ограничение доступа до согласования юридического и финансового отделов",
  "Tahsilat hatirlatmasi ve onayli kisit kontrolu ac": "Включить напоминание о взыскании и согласованный контроль ограничений",
  "Taksit doğrulanmadı": "Платёж по частям не подтверждён",
  "Keşif, kapsam kilidi ve pazar kıyası": "Исследование, фиксация объёма и анализ рынка",
  "UX/UI tasarım sistemi ve ürün navigasyonu": "Система UX/UI-дизайна и навигация продукта",
  "Platform temeli, auth, RBAC ve audit": "Базовая платформа, авторизация, RBAC и аудит",
  "Site, blok, kat, daire ve veri importu": "Комплекс, блок, этаж, квартира и импорт данных",
  "Kullanıcı, malik, kiracı ve personel yönetimi": "Управление пользователями, собственниками, арендаторами и персоналом",
  "Finans ledger motoru": "Финансовый учётный движок (леджер)",
  "Ödeme, depozito, mutabakat ve borç kısıtı": "Оплата, депозиты, сверка и ограничение по долгу",
  "Servis kataloğu ve servis siparişi akışı": "Каталог услуг и процесс оформления заявок",
  "Görev, saha ekibi, SLA ve medya raporu": "Задачи, полевая бригада, SLA и медиаотчёты",
  "Rezervasyon, kiralama, move-in ve checkout": "Бронирование, аренда, заселение и выезд",
  "İletişim, bildirim ve doküman merkezi": "Центр коммуникаций, уведомлений и документов",
  "Mobil PWA ve kurulabilir kullanıcı deneyimi": "Мобильное PWA-приложение с возможностью установки",
  "Dış sistem entegrasyonları": "Интеграции с внешними системами",
  "AI premium katmanı ve gelişmiş analitik": "Премиум-слой ИИ и расширенная аналитика",
  "QA, güvenlik, performans, kabul testi ve canlıya geçiş": "QA, безопасность, производительность, приёмочное тестирование и запуск в эксплуатацию",
  "769 dairelik site, roller, finans, servis, rezervasyon, erişim ve raporlama kapsamı tek ERP hedefinde netleşir.": "Комплекс на 769 квартир, роли, финансы, сервисные заявки, бронирование, доступ и отчётность объединяются в рамках единой цели ERP-системы.",
  "Yönetici, muhasebe, saha ekibi, sakin ve destek rolleri kendi işlerine uygun, sade ve erişilebilir arayüzden ilerler.": "Управляющий, бухгалтерия, полевая бригада, жильцы и служба поддержки работают через простой и доступный интерфейс, соответствующий их задачам.",
  "Oturum, rol, izin, RLS ve denetim izi bütün hassas işlemler için gerçek kontrol zemini sağlar.": "Сессии, роли, права доступа, RLS и журнал аудита формируют реальную основу контроля для всех чувствительных операций.",
  "769 daire blok, kat, durum, borç ve erişim ilişkisiyle filtrelenebilir; import kalite kapısı yönetilir.": "769 квартир можно фильтровать по блоку, этажу, статусу, долгу и доступу; контролируется шлюз качества импорта.",
  "Her kişi doğru daire, hesap, belge, iletişim dili ve yetki kapsamıyla tek kayıtta yönetilir.": "Каждый человек ведётся в единой карточке с правильной квартирой, счётом, документами, языком общения и объёмом прав.",
  "Bakiyeler ekran hesabından değil, hesap, borç/alacak, tahakkuk, düzeltme ve ekstre kayıtlarından hesaplanır.": "Остатки рассчитываются не по экранным расчётам, а на основе записей счёта, дебета/кредита, начислений, корректировок и выписок.",
  "Ödeme, depozito, iade, borç eşiği ve servis/erişim kısıtları muhasebe ve hukuk onayıyla yürür.": "Оплаты, депозиты, возвраты, пороги задолженности и ограничения по сервису/доступу применяются только после согласования с бухгалтерией и юридическим отделом.",
  "Temizlik, transfer, bakım ve özel hizmetler fiyat, SLA, borç kontrolü ve görev üretimiyle siparişe dönüşür.": "Уборка, трансфер, обслуживание и дополнительные услуги превращаются в заявки с ценой, SLA, проверкой долга и созданием задач.",
  "Müsaitlik, rezervasyon, depozito, giriş hazırlığı, checkout, kesinti ve erişim kapatma tek süreç olur.": "Наличие, бронирование, депозит, подготовка к заселению, выезд, удержания и закрытие доступа объединяются в единый процесс.",
  "Sakin, malik, yönetici ve personel iletişimi daire, borç, görev, rezervasyon ve belgeyle ilişkilendirilir.": "Общение с жильцами, собственниками, управляющими и персоналом привязывается к квартире, долгу, задаче, бронированию и документу.",
  "Sakin, personel ve yönetici ana işleri telefondan hızlı, erişilebilir ve kurulabilir PWA olarak yapılır.": "Основные операции жильцов, персонала и управляющего выполняются с телефона через быстрое, доступное и устанавливаемое PWA-приложение.",
  "Banka/ödeme, SMS/e-posta, erişim kartı/bariyer, sayaç ve kimlik sistemleri test modu ve retry kuyruğuyla bağlanır.": "Банковские/платёжные системы, SMS/e-mail, карты доступа/шлагбаумы, счётчики и системы идентификации подключаются с тестовым режимом и очередью повторных попыток.",
  "AI günlük brifing, borç riski, servis triage, anomali, doğal dil arama ve rapor taslağı üretir; hassas işlem yapmaz.": "ИИ формирует ежедневный брифинг, оценку риска по долгам, приоритизацию заявок, выявление аномалий, поиск на естественном языке и черновики отчётов; чувствительных операций не выполняет.",
  "Üretim canlıya geçmeden önce güvenlik, performans, yedekleme, eğitim, kabul testi ve destek kanıtı tamamlanır.": "Перед запуском в продуктив завершаются проверки безопасности, производительности, резервного копирования, обучения, приёмочного тестирования и подготовки поддержки.",
  "Yönetim özeti ve dokümantasyon merkezinden kapsam, risk ve karar kayıtlarını kontrol edin.": "Проверяйте объём работ, риски и записи решений в центре управленческой сводки и документации.",
  "Sol menüden rolünüze açık modülü seçin; üst kartlarda kritik sayılar, altta detay tabloları, arama ve aksiyonlar kullanılır.": "Выберите доступный вашей роли модуль в левом меню; в верхних карточках отображаются критические показатели, ниже — детальные таблицы, поиск и действия.",
  "Ayarlar ekranında güvenlik kontrollerini, rol yetkilerini ve son audit olaylarını inceleyin.": "На экране настроек проверяйте параметры безопасности, права ролей и последние события аудита.",
  "Daire Matrisi ekranında blok özetini, canlı matrisi, import doğrulamasını ve detay tablosunu kullanın.": "На экране матрицы квартир используйте сводку по блокам, живую матрицу, проверку импорта и детальную таблицу.",
  "Kullanıcılar ekranında sakin, malik, kiracı, personel ve rol ilişkilerini kontrol edin.": "На экране пользователей проверяйте связи между жильцами, собственниками, арендаторами, персоналом и ролями.",
  "Finans ekranında aidat, borç, tahsilat, gecikme ve ekstre hareketlerini ledger mantığıyla inceleyin.": "На финансовом экране анализируйте взносы, долги, взыскание, просрочки и движения по выписке по логике учётного леджера.",
  "Finans ve Uyum ekranlarında gecikme, depozito, kısıt ve onay kuyruğunu takip edin.": "На экранах финансов и соответствия отслеживайте просрочки, депозиты, ограничения и очередь согласований.",
  "Servis Talepleri ekranında katalog, borç kontrolü, görev üretimi ve durum takibini yönetin.": "На экране сервисных заявок управляйте каталогом, проверкой долга, созданием задач и отслеживанием статуса.",
  "Servis Talepleri ekranında görev panosu, SLA riski ve saha raporlarını yönetin.": "На экране сервисных заявок управляйте доской задач, риском по SLA и полевыми отчётами.",
  "Rezervasyon ekranında takvim, giriş/çıkış işleri, depozito ve final kontrol adımlarını takip edin.": "На экране бронирования отслеживайте календарь, операции заселения/выезда, депозиты и финальные проверки.",
  "İletişim ve Belgeler ekranlarında konuşma, duyuru, bildirim ve dosya izinlerini yönetin.": "На экранах коммуникаций и документов управляйте переписками, объявлениями, уведомлениями и правами доступа к файлам.",
  "Mobil görünümde bakiye, servis, görev, belge, sohbet ve bildirim akışlarını test edin.": "В мобильном режиме проверяйте потоки баланса, сервисных заявок, задач, документов, чата и уведомлений.",
  "Ayarlar ekranında entegrasyon durumu, son hata, manuel retry ve bağlantı loglarını takip edin.": "На экране настроек отслеживайте статус интеграций, последние ошибки, ручной повтор и журналы соединений.",
  "AI Rapor Merkezi'nde önerileri kaynak, güven ve insan onayıyla inceleyin.": "В центре отчётов ИИ рассматривайте рекомендации с указанием источника, уровня достоверности и согласования человеком.",
  "Raporlar ve dokümantasyon üzerinden test, kabul, eğitim ve canlıya geçiş checklist durumunu yönetin.": "Управляйте статусом чек-листа тестирования, приёмки, обучения и запуска через отчёты и документацию.",
  "İhtiyaç haritası": "Карта потребностей",
  "ERP modül planı": "План модулей ERP",
  "Pazar kıyası": "Анализ рынка",
  "Karar kaydı": "Журнал решений",
  "Güvenli oturum temeli": "Основа безопасной сессии",
  "Rol bazlı navigasyon": "Навигация на основе ролей",
  "Denetimli aksiyon servisi": "Сервис действий с аудитом",
  "Korumalı ekranlar": "Защищённые экраны",
  "Veri kontrol ve uygulama isteği": "Запрос проверки и применения данных",
  "Anlık yenileme": "Обновление в реальном времени",
  "Kişi dizini servisi": "Сервис справочника контактов",
  "Kullanıcı yönetim paneli": "Панель управления пользователями",
  "Rol matrisi": "Матрица ролей",
  "Finans defteri modeli": "Модель финансового леджера",
  "Finans defteri servisi": "Сервис финансового леджера",
  "Finans operasyon paneli": "Панель финансовых операций",
  "Denetimli finans aksiyonları": "Финансовые операции с аудитом",
  "Saha işleri atama, öncelik, SLA, foto/video kanıt, iptal ve yönetici onayıyla görünür olur.": "Полевые работы отображаются с назначением, приоритетом, SLA, фото/видео подтверждением, отменой и согласованием управляющего.",
  "Kişi, daire, finans, servis, belge ve AI özetleri, her ekibi tek bir doğrusal akışa zorlamadan birbirine bağlı kalır.": "Контакты, квартиры, финансы, сервис, документы и AI-сводки остаются связанными без принуждения каждой команды к единому линейному процессу.",
  "Bağlantılı çalışma alanı": "Связанное рабочее пространство",
  "Operasyonel kayıt": "Операционная запись",
  "Güncel görünüm": "Актуальное представление",
  "Ekip erişimi": "Доступ команды",
  "Yasal takipteki 15 daire için erişim kısıtlama listesi güncellendi.": "Обновлён список ограничений доступа для 15 квартир на юридическом сопровождении.",
  "Hasar ve temizlik kanıtını muhasebe onayına bağla": "Привязать подтверждение ущерба и уборки к согласованию бухгалтерии",
  "Depozito tutarını checkout takibinde izle": "Отслеживать сумму депозита в контроле выезда",
  "Rezervasyon ön kontrolünü tamamla": "Завершить предварительную проверку резервирования",
  "Yerel örnek veri": "Локальные тестовые данные",
  "Servis SLA inceleme isteği oluştur": "Создать запрос на проверку SLA по заявке",
  "SLA incelemesi aç": "Открыть проверку SLA",
  "Hazırlık": "Подготовка",
  "Servis kataloğu ve sipariş kapısı": "Каталог услуг и оформление заказа",
  "Fiyat, SLA, borç politikası, depozito ve ekip kuralı sipariş oluşmadan önce görünür.": "Цена, SLA, политика по задолженности, депозит и правила распределения по бригадам видны ещё до оформления заказа.",
  "{count} sevke hazır": "{count} готово к отправке",
  "Borç esnek": "Гибкая политика по задолженности",
  "Yönetici kontrol": "Контроль управляющего",
  "{name} siparişi hazırla": "Оформить заказ «{name}»",
  "Hazırla": "Подготовить",
  "Sipariş kontrolü": "Контроль заказа",
  "Saha görevleri, SLA ve medya kanıtı": "Полевые задачи, SLA и медиа-подтверждения",
  "Atama, rota, checklist, medya kanıtı ve yönetici onayı tek görev panosunda takip edilir.": "Назначение, маршрут, чек-лист, медиа-подтверждения и согласование управляющего ведутся на одной панели задач.",
  "{id} saha görevini hazırla": "Подготовить полевую задачу {id}",
  "Daire teslimi, kısa konaklama sonrası temizlik ve temel sarf malzeme kontrolü.": "Передача квартиры, уборка после короткого проживания и проверка базовых расходных материалов.",
  "Standart daire temizliği": "Стандартная уборка квартиры",
  "Derin temizlik ve checkout hazırlığı": "Генеральная уборка и подготовка к выезду",
  "Checkout sonrası detaylı temizlik, hasar fotoğrafları ve depozito kontrol notu.": "Детальная уборка после выезда, фотографии повреждений и заметка по контролю депозита.",
  "Klima bakımı ve drenaj kontrolü": "Обслуживание кондиционера и проверка дренажа",
  "Filtre, drenaj, soğutma performansı ve servis kanıtı ile periyodik klima bakımı.": "Периодическое обслуживание кондиционера с проверкой фильтра, дренажа, эффективности охлаждения и подтверждением сервиса.",
  "Acil tesisat müdahalesi": "Аварийный сантехнический вызов",
  "Su kaçağı, gider tıkanıklığı ve acil tesisat onarımı için hızlı saha yönlendirmesi.": "Оперативное направление бригады при утечке воды, засоре стока и аварийном сантехническом ремонте.",
  "Malik, kiracı ve misafirler için planlı havalimanı transferi ve varış bildirimi.": "Плановый трансфер из аэропорта и уведомление о прибытии для собственников, арендаторов и гостей.",
  "Ortak alan kapasitesi, aidat durumu ve kullanıcı yetkisine göre rezervasyon kontrolü.": "Контроль бронирования по вместимости общей зоны, статусу взносов и правам пользователя.",
  "Muhasebe onayı ve borç kontrolü tamamlanmadan saha işine çıkarma": "Не направлять на объект до завершения бухгалтерского согласования и проверки задолженности",
  "SLA ve ekip uygunluğuna göre görevi ata": "Назначить задачу с учётом SLA и доступности бригады",
  "Personel rota ve medya kanıtı talimatını gönder": "Отправить инструкцию исполнителю по маршруту и медиа-подтверждению",
  "Saha notu ve kapanış kanıtını kontrol et": "Проверить полевую заметку и подтверждение закрытия",
  "Sorunu yerinde doğrula": "Подтвердить проблему на месте",
  "Öncesi fotoğraf yükle": "Загрузить фото до начала работ",
  "Daire giriş kontrolü": "Контроль допуска в квартиру",
  "Fotoğraf kanıtı": "Фотоподтверждение",
  "Varış saatini doğrula": "Подтвердить время прибытия",
  "Tedarikçiyi ata": "Назначить подрядчика",
  "Misafir bildirimini gönder": "Отправить уведомление гостю",
  "Hasar alanını işaretle": "Отметить зону повреждения",
  "Yönetici onayı al": "Получить согласование руководителя",
  "Haziran kapanış sinyali": "Сигнал закрытия за июнь",
  "Son aya göre {sign}{delta} tahsilat farkı. AI raporları sadece öneri üretir; onay insan rolünde kalır.": "Разница по сбору платежей {sign}{delta} относительно прошлого месяца. Отчёты AI формируют только рекомендации; одобрение остаётся за человеком.",
  "Avsallar master plandan operasyon kaydına": "От генплана Avsallar к операционной записи",
  "Telefon kaydı bekliyor": "Номер телефона ожидается",
  "Portal": "Портал",
  "Lead": "Лид",
  "Kurumsal Grup": "Корпоративная группа",
  "Phase 7": "Фаза 7",
  "Teknik": "Техническая служба",
  "Servis": "Сервис",
  "toplam": "всего",
  "Dolu": "Занято",
  "Boş": "Свободно",
  "Bakımda": "На обслуживании",
  "AI": "ИИ",
  "Ocak": "Янв",
  "New Level Premium price-list package": "Пакет прайс-листа New Level Premium",
  "Project documents, facility map and floor plans": "Проектная документация, карта объекта и планы этажей",
  "Construction and showroom media": "Медиаматериалы стройки и демонстрационного шоурума",
  "Unknown": "Неизвестно",
  "Open basement": "Открытый цокольный этаж",
  "Ground floor": "Первый этаж",
  "Block B demo fallback": "Резервные данные Блока B (демо)",
  "Block D demo fallback": "Резервные данные Блока D (демо)",
  "Waleri-approved demo fallback: copy B Block prices and numbering/reference logic from A Block.": "Демо-заглушка, утверждённая Валери: цены, нумерация и логика привязки Блока B скопированы из Блока A.",
  "Waleri-approved demo fallback: copy D Block prices from E Block.": "Демо-заглушка, утверждённая Валери: цены Блока D скопированы из Блока E.",
  "Deal": "Сделка",
  "Denetim izi": "Журнал аудита",
  "Proceed with reservation and ROI pack": "Продолжить с оформлением бронирования и пакетом расчёта окупаемости (ROI)",
  "Check residence-zone status before promise": "Проверить статус зоны резидентства перед тем, как давать обещание клиенту",
  "Need appraisal and source-of-funds review": "Требуется оценка объекта и проверка источника происхождения средств",
  "Do not promise residence suitability": "Не давать обещаний относительно соответствия требованиям резидентства",
  "investment": "Инвестиция",
  "holiday_home": "Дом для отдыха",
  "citizenship": "Гражданство",
  "residence": "Резидентство",
  "clear": "Без ограничений",
  "quota_review": "Проверка квоты",
  "restricted": "Ограничено",
  "Legal takipteki 15 daire için erişim kısıtlama listesi güncellendi.": "Обновлён список ограничений доступа для 15 квартир на юридическом сопровождении.",
  "External data service is not configured; using local ticket seed data.": "Внешний сервис данных не настроен; используются локальные тестовые данные заявок.",
  "İmar, tapu ve yetki belgelerinin bir kısmı tarama/PDF görseli olarak geldi; OCR veya insan doğrulaması gerekir.": "Часть документов по планировке, кадастру (тапу) и разрешениям поступила в виде сканов/изображений PDF; требуется OCR или проверка человеком.",
  "Tutuldu": "Удержан",
  "ROI tablosu ve Almanca proje paketi": "Таблица ROI и пакет проекта на немецком языке",
  "Beach club ve otel hizmetleri tanıtım turu": "Ознакомительный тур: бич-клуб и услуги отеля",
  "Hukuk ortağıyla uygunluk ön kontrolü": "Предварительная проверка соответствия с юридическим партнёром",
  "Ödeme planı onaylanınca daireyi rezerve et": "Зарезервировать квартиру после подтверждения плана оплаты",
  "Gelmeme (no-show) sonrası kurtarma mesajı gönder": "Отправить сообщение для повторного вовлечения после неявки (no-show)",
  "Tem": "Июл",
  "Ön kontrol": "Предварительная проверка",
  "satış planı": "План продажи",
  "low": "низкий",
  "medium": "средний",
  "high": "высокий",
  "Reservation": "Бронирование",
  "Payment Plan": "План платежей",
  "Sales Contract": "Договор купли-продажи",
  "Ready for payment-plan signature": "Готово к подписанию плана платежей",
  "Collect buyer signature": "Получить подпись покупателя",
  "Request passport and source-of-funds pack": "Запросить паспорт и подтверждение источника средств",
  "Validate title deed pack before contract": "Проверить пакет документов TAPU перед договором",
  "Keep listing authorization attached": "Сохранить привязку авторизации листинга",
  "Correct buyer name before reservation": "Исправить имя покупателя перед бронированием",
  "Standart daire temizligi": "Стандартная уборка квартиры",
  "Daire teslimi, kisa konaklama sonrasi temizlik ve temel sarf malzeme kontrolu.": "Приём/передача квартиры, уборка после короткого проживания и проверка базовых расходных материалов.",
  "Derin temizlik ve checkout hazirligi": "Глубокая уборка и подготовка к выезду",
  "Checkout sonrasi detayli temizlik, hasar fotograflari ve depozito kontrol notu.": "Детальная уборка после выезда, фотографии повреждений и заметка по проверке депозита.",
  "Klima bakimi ve drenaj kontrolu": "Обслуживание кондиционера и проверка дренажа",
  "Filtre, drenaj, sogutma performansi ve servis kaniti ile periyodik klima bakimi.": "Периодическое обслуживание кондиционера: фильтр, дренаж, эффективность охлаждения и подтверждение выполнения работ.",
  "Acil tesisat mudahalesi": "Экстренный вызов сантехника",
  "Su kacagi, gider tikanikligi ve acil tesisat onarimi icin hizli saha yonlendirmesi.": "Быстрое направление специалиста на объект при утечке воды, засоре канализации и экстренном ремонте сантехники.",
  "Ortak alan kapasitesi, aidat durumu ve kullanici yetkisine gore rezervasyon kontrolu.": "Проверка бронирования с учётом вместимости общих зон, статуса взносов и прав пользователя.",
  "mixed": "смешанная бригада",
  "internal": "внутренняя бригада",
  "vendor": "подрядчик",
  "1Cati keeps the operational service catalogue, service orders, SLA tasks and ticket events inside Supabase.": "1Cati хранит каталог операционных услуг, заказы на обслуживание, задачи по SLA и события заявок в Supabase.",
  "Twenty CRM remains the relationship/contact system; 1Cati remains the resident-service and field-operations system.": "Twenty CRM остаётся системой учёта контактов и взаимоотношений; 1Cati остаётся системой обслуживания жителей и полевых операций.",
  "Muhasebe onayi ve borc kontrolu tamamlanmadan saha isine cikarma": "Не направлять специалиста на объект до завершения согласования бухгалтерии и проверки задолженности",
  "Saha notu ve kapanis kanitini kontrol et": "Проверить заметку с объекта и подтверждение закрытия",
  "SLA ve ekip uygunluguna gore gorevi ata": "Назначить задачу с учётом SLA и доступности бригады",
  "Personel rota ve medya kaniti talimatini gonder": "Отправить сотруднику маршрут и инструкцию по медиа-подтверждению",
  "Daire giris kontrolu": "Проверка доступа в квартиру",
  "Fotograf kaniti": "Фотоподтверждение",
  "Sorunu yerinde dogrula": "Подтвердить проблему на месте",
  "Oncesi fotograf yukle": "Загрузить фото «до»",
  "Varis saatini dogrula": "Подтвердить время прибытия",
  "Tedarikciyi ata": "Назначить подрядчика",
  "Misafir bildirimini gonder": "Отправить уведомление гостю",
  "Hasar alanini isaretle": "Отметить зону повреждения",
  "Yonetici onayi al": "Получить согласование управляющего",
  "Acil": "Срочно",
  "Atandı": "Назначено",
  "Ödeme bekliyor": "Ожидает оплаты",
  "Çözüldü": "Решено",
  "Kapandı": "Закрыто",
  "Güvenlik - Selim": "Безопасность - Селим",
  "Muhasebe - Merve": "Бухгалтерия - Мерве",
  "Operasyon - Can": "Операции - Джан",
  "Teknik - Ahmet": "Техническая служба - Ахмет",
  "Teknik - Burak": "Техническая служба - Бурак",
  "Temizlik - Esra": "Клининг - Эсра",
  "Site Yönetimi": "Управление объектом",
  "Sakin Destek": "Поддержка жильцов",
  "E-posta": "Электронная почта",
  "Aidat borcu ve erişim uyarısı": "Задолженность по взносам и уведомление о доступе",
  "Klima servis randevusu": "Запись на обслуживание кондиционера",
  "Bugünkü check-out ve depozito kontrolü": "Сегодняшний выезд (check-out) и проверка депозита",
  "Aylık finans raporu hazır": "Ежемесячный финансовый отчет готов",
  "Borç > 0": "Долг > 0",
  "SLA < 4 saat": "SLA < 4 часов",
  "Check-in bugün": "Check-in сегодня",
  "Belge eksik": "Документ отсутствует",
  "Push + Ekip": "Push + Команда",
  "Rol profili ve oturum kontrolü": "Профиль ролей и контроль сессий",
  "Yerel çalışma ortamında yetki profili kullanılabilir; üretim ortamında doğrulanmış kullanıcı profili önceliklidir.": "В локальной среде разработки доступен профиль прав; в продуктивной среде приоритет имеет проверенный профиль пользователя.",
  "Rol bazlı menü ve yetki matrisi": "Меню и матрица прав на основе ролей",
  "Her rol için görüntüleme, oluşturma, onay, dışa aktarma ve yönetim hakları açık tanımlanır.": "Для каждой роли явно определены права на просмотр, создание, одобрение, экспорт и управление.",
  "Finans, erişim ve AI karar izi": "Журнал решений по финансам, доступу и AI",
  "Hassas kararlar aktör, modül, sebep, risk ve zaman bilgisiyle izlenebilir şekilde modellenir.": "Критические решения моделируются так, чтобы их можно было отследить по инициатору, модулю, причине, риску и времени.",
  "Şirket/site izolasyon hazırlığı": "Готовность к изоляции компании/сайта",
  "Veri modeli şirket, site ve rol bağlamını güvenli erişim politikalarına hazırlayacak şekilde tasarlanmıştır.": "Модель данных спроектирована так, чтобы контекст компании, сайта и роли был готов к политикам безопасного доступа.",
  "AI aksiyonlarında insan onayı": "Одобрение человеком действий AI",
  "AI finans, erişim veya hassas verilerde doğrudan işlem yapmaz; öneri ve onay kuyruğu üretir.": "AI не выполняет прямых операций с финансами, доступом или чувствительными данными; система формирует очередь рекомендаций и одобрений.",
  "Operasyon Sorumlusu": "Ответственный за операции",
  "Rol bazlı panele giriş yaptı": "Вошёл в панель на основе роли",
  "90+ gün borçlu hesapları dışa aktardı": "Экспортировал счета с задолженностью 90+ дней",
  "Kısıtlı erişim listesi inceledi": "Проверил список ограниченного доступа",
  "AI Operasyon": "AI Операции",
  "Tahsilat önceliği önerisi oluşturdu": "Сформировал рекомендацию по приоритету взыскания",
  "Daire Import": "Импорт квартир",
  "Daire import doğrulama raporunu onayladı": "Утвердил отчёт проверки импорта квартир"
}
