// German business-copy dictionary for the 1Cati dashboard, AI assistant and
// platform marketing content. Populated by the July 2026 localization audit.
// Keys are the canonical Turkish source strings (or {token} templates); do not
// hand-edit keys without updating every sibling locale file identically.

export const deCopy: Record<string, string> = {
  "Aidat, tahsilat, depozito veya finans raporu sorun...": "Fragen Sie nach Nebenkosten, Zahlungseingängen, Kautionen oder Finanzberichten...",
  "Atanan servis, saha notu veya rezervasyon işi sorun...": "Fragen Sie nach zugewiesenen Serviceaufträgen, Einsatznotizen oder Reservierungsvorgängen...",
  "Servis, rezervasyon, belge veya mesaj hakkında sorun...": "Fragen Sie nach Service, Reservierungen, Dokumenten oder Nachrichten...",
  "Operasyon Kullanıcısı": "Betriebsbenutzer",
  "Operasyon Asistanı": "Betriebsassistent",
  "Toplam Daire": "Wohnungen gesamt",
  "{rate}% doluluk": "{rate}% Belegung",
  "{vacant} boş, {maintenance} bakımda": "{vacant} leer, {maintenance} in Wartung",
  "Toplam Borç": "Gesamtschuld",
  "{count} erişim kısıtı": "{count} Zugangssperren",
  "Açık Servis": "Offene Serviceanfragen",
  "{count} SLA dışı": "{count} SLA-Überschreitungen",
  "Teknik, finans ve depozito işleri": "Technik-, Finanz- und Kautionsvorgänge",
  "Bugünkü İşler": "Heutige Aufgaben",
  "{count} çıkış": "{count} Checkouts",
  "Giriş, çıkış, temizlik, depozito": "Check-in, Check-out, Reinigung, Kaution",
  "{count} operasyon riski AI kuyruğunda: borç, SLA ve check-out birlikte takip ediliyor.": "{count} Betriebsrisiken in der KI-Warteschlange: Schulden, SLA und Check-out werden gemeinsam verfolgt.",
  "{count} dairede erişim kısıtı var. Finans onayı olmadan servis yönlendirilmemeli.": "Bei {count} Wohnungen besteht eine Zugangssperre. Service darf ohne Finanzfreigabe nicht disponiert werden.",
  "{count} servis talebi SLA dışına çıktı. Teknik ekip için öncelik listesi hazır.": "{count} Serviceanfragen haben die SLA überschritten. Prioritätenliste für das Technikteam liegt vor.",
  "ERP Operasyon Merkezi": "ERP-Betriebszentrale",
  "Satış, proje takibi, WhatsApp/Telegram lead akışı, evrak, servis, finans ve AI önceliklendirme tek çalışma alanında toplanır. Operasyon görünümü 769 birim ölçeğinde yönetim, kontrol ve takip için çalışır.": "Vertrieb, Projektverfolgung, WhatsApp/Telegram-Lead-Fluss, Unterlagen, Service, Finanzen und KI-Priorisierung laufen in einem einzigen Arbeitsbereich zusammen. Die Betriebsansicht dient der Verwaltung, Kontrolle und Nachverfolgung im Umfang von 769 Einheiten.",
  "Aktif rol:": "Aktive Rolle:",
  "Veri yenilenemedi. Lütfen tekrar deneyin.": "Daten konnten nicht aktualisiert werden. Bitte erneut versuchen.",
  "Portföy kaynağı": "Portfolioquelle",
  "daire": "Wohnung",
  "açık servis": "offener Service",
  "aktif rol": "aktive Rolle",
  "modülüne git": "zum Modul wechseln",
  "ERP modül durumu": "ERP-Modulstatus",
  "CRM, daire matrisi, kullanıcı rolleri, finans, servis, saha, rezervasyon, iletişim, mobil PWA, entegrasyon, AI ve güvenlik kontrolleri aynı işletim planında izlenir.": "CRM, Wohnungsmatrix, Benutzerrollen, Finanzen, Service, Außendienst, Reservierung, Kommunikation, mobile PWA, Integrationen, KI und Sicherheitskontrollen werden im selben Betriebsplan überwacht.",
  "{complete} aktif · {readyForUat} kontrol hazır · {inProgress} yapımda": "{complete} aktiv · {readyForUat} testbereit · {inProgress} in Arbeit",
  "Modül": "Modul",
  "ekranını aç": "Ansicht öffnen",
  "Aktif": "Aktiv",
  "Kontrol hazır": "Testbereit",
  "Yapımda": "In Arbeit",
  "Planlandı": "Geplant",
  "Bloke": "Gesperrt",
  "Nasıl kullanılır:": "So wird es genutzt:",
  "modülünü aç": "Modul öffnen",
  "Doluluk ve tahsilat sağlığı detayını aç": "Detail zu Belegung und Inkasso öffnen",
  "Doluluk ve tahsilat sağlığı": "Belegung und Inkasso-Status",
  "Doluluk oranı, gecikmiş borç ve servis baskısı birlikte okunur.": "Belegungsquote, überfällige Schulden und Servicebelastung werden gemeinsam ausgewertet.",
  "Haziran hedefi korunuyor": "Juni-Ziel wird eingehalten",
  "Daire durum dağılımı detayını aç": "Detail zur Wohnungsstatusverteilung öffnen",
  "Daire durum dağılımı": "Wohnungsstatusverteilung",
  "Operasyon ekibi için canlı portföy kırılımı.": "Live-Portfolioaufschlüsselung für das Betriebsteam.",
  "Blok bazlı operasyon": "Betrieb nach Block",
  "{count} blok": "{count} Blöcke",
  "Blok": "Block",
  "daire matrisi detayını aç": "Wohnungsmatrix-Detail öffnen",
  "{count} daire": "{count} Wohnungen",
  "Dolu:": "Belegt:",
  "Boş:": "Leer:",
  "Bakım:": "Wartung:",
  "Borç:": "Schuld:",
  "AI operasyon asistanı raporlarını aç": "Berichte des KI-Betriebsassistenten öffnen",
  "AI operasyon asistanı": "KI-Betriebsassistent",
  "Borç, SLA, depozito ve rezervasyon verilerini birleştirerek günlük yapılacakları sıralar.": "Fasst Schulden-, SLA-, Kautions- und Reservierungsdaten zusammen und priorisiert die Tagesaufgaben.",
  "detayını aç": "Detail öffnen",
  "Son operasyon akışı": "Letzter Betriebsablauf",
  "Bugünkü kritik işler": "Heutige kritische Aufgaben",
  "{hours} saat": "{hours} Stunden",
  "servis talebini aç": "Serviceanfrage öffnen",
  "rezervasyon detayını aç": "Reservierungsdetail öffnen",
  "Depozito:": "Kaution:",
  "Finans özetini aç": "Finanzübersicht öffnen",
  "Aylık beklenen aidat": "Erwartetes Hausgeld pro Monat",
  "Haziran tahsilat": "Inkasso Juni",
  "Depozito riski": "Kautionsrisiko",
  "rol izni yok": "keine Rollenberechtigung",
  "Bu modül mevcut rol için kapalı": "Dieses Modul ist für die aktuelle Rolle gesperrt",
  "Rol kapalı": "Rolle gesperrt",
  "İncele": "Prüfen",
  "Canlı daire": "Wohnungen live",
  "Açık servis": "Offener Service",
  "finans kontrolü": "Finanzkontrolle",
  "Erişim riski": "Zugangsrisiko",
  "Operasyon merkezi": "Betriebszentrale",
  "Daire, servis, finans ve rezervasyon aynı kontrol düzleminde": "Wohnungen, Service, Finanzen und Reservierung auf derselben Kontrollebene",
  "Bu görünüm yönetim ve sorumlu rolü için portföy ölçeğinde risk, iş yükü ve tahsilat sinyallerini birleştirir.": "Diese Ansicht bündelt Risiko-, Arbeitslast- und Inkassosignale auf Portfolioebene für Geschäftsführung und verantwortliche Rolle.",
  "AI risk": "KI-Risiko",
  "öncelikli aksiyon": "vorrangige Maßnahme",
  "İş yoğunluğu": "Arbeitsauslastung",
  "Saatlik sinyal": "Stündliches Signal",
  "Gün {day}: {value}%": "Tag {day}: {value}%",
  "Saat {hour}: {value}%": "Uhrzeit {hour}: {value}%",
  "Rol bağlantıları aktif": "Rollenverknüpfungen aktiv",
  "Dashboard kartları, API ve AI yanıtları aynı RBAC matrisinden geçer.": "Dashboard-Kacheln, API und KI-Antworten laufen über dieselbe RBAC-Matrix.",
  "Çalışma alanı ritmi": "Arbeitsrhythmus",
  "Hover ve kart geçişleri gerçek modül akışlarını gösterir.": "Hover- und Kartenübergänge zeigen die realen Modulabläufe.",
  "Yetki sınırları": "Berechtigungsgrenzen",
  "Bu ekranda şirket geneli daire matrisi, finans defteri, kullanıcı yönetimi ve platform ayarları gösterilmez. Kapalı bir sayfa URL ile açılırsa sistem sizi tekrar kendi çalışma alanınıza döndürür.": "In dieser Ansicht werden die unternehmensweite Wohnungsmatrix, das Finanzbuch, die Benutzerverwaltung und die Plattformeinstellungen nicht angezeigt. Wird eine gesperrte Seite per URL aufgerufen, leitet das System Sie zurück in Ihren eigenen Arbeitsbereich.",
  "açık modül": "freigeschaltetes Modul",
  "yetkili iş": "berechtigte Aufgabe",
  "Finans, Satış & Aidat": "Finanzen, Verkauf & Hausgeld",
  "{clientName} için satış ödemeleri, aidat, borç yaşlandırma, depozito, ödeme doğrulama, kira geliri ve erişim kısıtı kararları aynı finans akışında yönetilir.": "Verkaufszahlungen, Hausgeld, Schuldenaltersanalyse, Kaution, Zahlungsabgleich, Mieteinnahmen und Entscheidungen zur Zugangssperre für {clientName} werden im selben Finanzablauf verwaltet.",
  "Toplam borç": "Gesamtschuld",
  "Aylık aidat": "Monatliches Hausgeld",
  "Kısıtlı erişim": "Zugangssperre",
  "Aylık nakit akışı": "Monatlicher Cashflow",
  "Tahsilat, açık borç ve servis gideri birlikte takip edilir.": "Inkasso, offene Schulden und Servicekosten werden gemeinsam verfolgt.",
  "Tahsilat {amount}": "Inkasso {amount}",
  "Borç yaşlandırma": "Schuldenaltersanalyse",
  "Önceliklendirme 90+ gün ve erişim kısıtından başlar.": "Die Priorisierung beginnt bei 90+ Tagen und Zugangssperre.",
  "{days} gün": "{days} Tage",
  "Yasal takip": "Rechtliches Mahnverfahren",
  "Gecikmiş": "Überfällig",
  "Ödeme doğrulama": "Zahlungsabgleich",
  "Banka dekontu, online ödeme, manuel tahsilat ve kasa hareketi aynı hesap kaydına bağlanır.": "Bankbeleg, Online-Zahlung, manuelles Inkasso und Kassenbewegung werden demselben Kontoeintrag zugeordnet.",
  "Borç kısıtlama kuralı": "Regel zur Schuldensperre",
  "90+ gün borçta erişim kısıtı, servis bekletme ve yasal takip önerisi otomatik görünür.": "Ab 90+ Tagen Zahlungsrückstand erscheinen Zugangssperre, Service-Zurückstellung und Empfehlung zum rechtlichen Mahnverfahren automatisch.",
  "Depozito kontrolü": "Kautionskontrolle",
  "Hasar, temizlik ve iade onayı rezervasyon çıkışıyla finans panelinde kapanır.": "Schaden, Reinigung und Rückerstattungsfreigabe werden mit dem Reservierungs-Checkout im Finanzpanel abgeschlossen.",
  "Satış ödeme planı": "Verkaufszahlungsplan",
  "0% taksit akışı; liste fiyatı, peşinat, kalan vade, kur riski ve sözleşme blokajını satıştan önce görünür yapar.": "0%-Ratenablauf; macht Listenpreis, Anzahlung, Restlaufzeit, Kursrisiko und Vertragssperre vor dem Verkauf sichtbar.",
  "Açık vade {amount}": "Offene Rate {amount}",
  "Plan sayısı": "Anzahl der Pläne",
  "Planında": "Im Plan",
  "Vade uyarısı": "Ratenwarnung",
  "Blokeli": "Gesperrt",
  "Plan": "Plan",
  "Alıcı": "Käufer",
  "Liste": "Liste",
  "Ödenen": "Bezahlt",
  "Sonraki vade": "Nächste Rate",
  "Durum": "Status",
  "Vade yaklaştı": "Rate steht bevor",
  "Gecikti": "Überfällig",
  "Blokaj": "Sperre",
  "Daire": "Wohnung",
  "Malik": "Eigentümer",
  "Borç": "Schuld",
  "Yaş": "Alter",
  "Erişim": "Zugang",
  "Önerilen aksiyon": "Empfohlene Maßnahme",
  "Ucretsiz": "Kostenlos",
  "Odeme once": "Zahlung vor",
  "Cari hesaba yaz": "Auf laufendes Konto buchen",
  "Onayli": "Freigegeben",
  "Beklet": "Zurückstellen",
  "Taslak": "Entwurf",
  "Borc kontrolu": "Schuldenkontrolle",
  "Odeme bekliyor": "Zahlung ausstehend",
  "Gorev acildi": "Aufgabe eröffnet",
  "Atandi": "Zugewiesen",
  "Tamamlandi": "Abgeschlossen",
  "Iptal": "Storniert",
  "Supabase live": "Supabase live",
  "Yetkili dairenize bağlı servis taleplerini, randevu durumunu, medya kanıtını ve yönetim yanıtlarını tek ekrandan takip edin.": "Verfolgen Sie die Servicetickets Ihrer berechtigten Einheit, den Termin­status, die Mediennachweise und die Antworten der Verwaltung auf einem einzigen Bildschirm.",
  "Saha ekibi için atanan servis işleri, SLA önceliği, medya kanıtı ve kapanış adımları aynı iş kuyruğunda yönetilir.": "Die dem Außendienst zugewiesenen Serviceaufträge, SLA-Priorität, Mediennachweise und Abschlussschritte werden in derselben Auftragswarteschlange verwaltet.",
  "ve diğer Ataberk portföyleri için teknik servis, ödeme doğrulama, fotoğraf/video kanıtı ve SLA takibi aynı iş kuyruğunda yönetilir.": "und für weitere Ataberk-Portfolios werden technischer Service, Zahlungsprüfung, Foto-/Videonachweis und SLA-Tracking in derselben Auftragswarteschlange verwaltet.",
  "Servis Talepleri": "Servicetickets",
  "Kuyrugu yenile": "Warteschlange aktualisieren",
  "SLA inceleme istegi alindi": "SLA-Prüfanfrage erhalten",
  "Servis SLA ve kanit kuyrugu incelemesi": "Prüfung der Service-SLA- und Nachweiswarteschlange",
  "Servis talebi verisi su anda alinamadi. Yerel veriyle devam ediliyor.": "Servicedaten konnten derzeit nicht abgerufen werden. Es wird mit lokalen Daten fortgefahren.",
  "Açık talep": "Offenes Ticket",
  "SLA dışı": "SLA überschritten",
  "Onay bekleyen": "Freigabe ausstehend",
  "Borç blokeli": "Wegen Zahlungsrückstand gesperrt",
  "Medya kanıtı": "Mediennachweis",
  "Katalog": "Katalog",
  "Siparis": "Auftrag",
  "Saha gorevi": "Außendiensteinsatz",
  "Borc kapali": "Wegen Zahlungsrückstand gesperrt",
  "SLA {hours} saat": "SLA {hours} Stunden",
  "Siparis hazirligi kayda alindi": "Auftragsvorbereitung erfasst",
  "{name} servis siparisi": "Serviceauftrag {name}",
  "{count} blokeli": "{count} gesperrt",
  "{count} onay": "{count} Freigaben",
  "{count} SLA riski": "{count} SLA-Risiko",
  "Yonetici": "Verwaltung",
  "{count} medya - SLA {sla} saat": "{count} Medien – SLA {sla} Stunden",
  "Gorev aksiyonu kayda alindi": "Aufgabenaktion erfasst",
  "{id} saha gorevi": "Außendiensteinsatz {id}",
  "Aksiyon": "Aktion",
  "Takipteki talepleriniz": "Ihre verfolgten Tickets",
  "Öncelikli iş kuyruğu": "Priorisierte Auftragswarteschlange",
  "{count} gecikmiş": "{count} überfällig",
  "Finans blokeli": "Wegen Zahlungsrückstand gesperrt",
  "Servis kapsamı": "Serviceumfang",
  "Servis güvenlik kuralı": "Sicherheitsregel für Service",
  "Sadece sizin dairenize veya yetkili kaydınıza bağlı talepler gösterilir.": "Es werden nur Tickets angezeigt, die Ihrer Einheit oder Ihrem berechtigten Datensatz zugeordnet sind.",
  "Borç blokeli dairelerde teknisyen sahaya çıkmadan önce muhasebe onayı ve ödeme doğrulaması gerekir.": "Bei Einheiten mit Zahlungsrückstand sind vor dem Einsatz des Technikers die Freigabe der Buchhaltung und eine Zahlungsprüfung erforderlich.",
  "Kanıt ve yanıt": "Nachweis und Antwort",
  "Saha iş akışı": "Außendienst-Workflow",
  "Fotoğraf, açıklama, randevu ve kapanış kararı yönetim ekibiyle aynı kayıt üzerinden paylaşılır.": "Foto, Beschreibung, Termin und Abschlussentscheidung werden im selben Datensatz mit dem Verwaltungsteam geteilt.",
  "Talep, fotoğraf, maliyet, onay, atama ve kapanış kanıtı tek kayıtta tutulur.": "Ticket, Foto, Kosten, Freigabe, Zuweisung und Abschlussnachweis werden in einem einzigen Datensatz gehalten.",
  "Günlük rota": "Tagesroute",
  "AI önerisi": "KI-Vorschlag",
  "SLA ve kanıt ihtiyacına göre teknik rota sadeleştirilir; finans tutarları saha görünümünde maskelenir.": "Die Technikerroute wird anhand von SLA und Nachweisbedarf vereinfacht; Finanzbeträge werden in der Außendienstansicht ausgeblendet.",
  "SLA, tahmini maliyet ve borç durumu birlikte skorlanarak günlük teknik rota oluşturulur.": "SLA, geschätzte Kosten und Zahlungsrückstandsstatus werden gemeinsam bewertet, um die tägliche Technikerroute zu erstellen.",
  "Ticketing mimarisi": "Ticketing-Architektur",
  "Talep": "Ticket",
  "Konu": "Thema",
  "Öncelik": "Priorität",
  "Sorumlu": "Zuständig",
  "Servis izni": "Serviceberechtigung",
  "Ödeme": "Zahlung",
  "Onaylı": "Freigegeben",
  "Kontrol": "Prüfung",
  "Maliyet": "Kosten",
  "Rezervasyon & Giriş-Çıkış": "Reservierung & Check-in/Check-out",
  "Yetkili rezervasyon, giriş-çıkış, erişim kodu ve depozito durumunu sadece kendi kaydınız kapsamında takip edin.": "Verfolgen Sie Reservierung, Check-in/Check-out, Zugangscode und Kautionsstatus ausschließlich im Rahmen Ihres eigenen Datensatzes.",
  "Saha ekibi için giriş-çıkış, temizlik, erişim ve operasyon görevleri sadeleştirilmiş çizelgede gösterilir.": "Check-in/Check-out, Reinigung, Zugang und Betriebsaufgaben werden dem Außendienstteam in einem vereinfachten Zeitplan angezeigt.",
  "Web uygulama içinde rezervasyon, check-in, check-out, temizlik, erişim kodu ve depozito süreçlerini yönetin.": "Verwalten Sie Reservierung, Check-in, Check-out, Reinigung, Zugangscode und Kautionsprozesse innerhalb der Web-App.",
  "Aktif kayıt": "Aktiver Datensatz",
  "Bugün giriş": "Heute Check-in",
  "Bugün çıkış": "Heute Check-out",
  "Depozito kontrol": "Kautionsprüfung",
  "Rezervasyon durumunuz": "Ihr Reservierungsstatus",
  "Bugünkü operasyon çizelgesi": "Heutiger Betriebsplan",
  "aktif iş": "aktive Aufträge",
  "Giriş": "Check-in",
  "Çıkış": "Check-out",
  "Depozito": "Kaution",
  "Erişim kodu": "Zugangscode",
  "Erişim durumu yalnızca yetkili kaydınız için gösterilir.": "Der Zugangsstatus wird nur für Ihren berechtigten Datensatz angezeigt.",
  "Borç, depozito ve kimlik kontrolü tamamlanınca erişim kodu onaya hazır hale gelir; aktivasyon insan onayıyla yapılır.": "Sobald Zahlungsstand, Kaution und Identitätsprüfung abgeschlossen sind, wird der Zugangscode zur Freigabe bereitgestellt; die Aktivierung erfolgt durch manuelle Bestätigung.",
  "bekleyen veya kısıtlı kayıt": "ausstehende oder eingeschränkte Datensätze",
  "Kapanış kontrolü": "Abschlussprüfung",
  "Hasar ve depozito": "Schäden und Kaution",
  "Check-out sonrası hasar, fotoğraf kanıtı ve iade kararı portal kaydına bağlanır.": "Schäden nach dem Check-out, Fotonachweis und Rückerstattungsentscheidung werden im Portal-Datensatz erfasst.",
  "Check-out sonrası fotoğraf, servis maliyeti ve depozito kesintisi aynı finans kaydına bağlanır.": "Fotos nach dem Check-out, Servicekosten und Kautionsabzug werden im selben Finanzdatensatz erfasst.",
  "Saha önceliği": "Außendienstpriorität",
  "AI doluluk önerisi": "KI-Belegungsvorschlag",
  "Temizlik, erişim ve çıkış işleri günlük ekip kapasitesine göre sıralanır.": "Reinigung, Zugang und Check-out-Aufgaben werden nach der täglichen Teamkapazität priorisiert.",
  "Boş daire, bakım durumu ve önceki kanal performansına göre fiyat ve kanal önerisi üretilebilir.": "Preis- und Kanalvorschläge können anhand freier Einheiten, Wartungsstatus und bisheriger Kanalperformance erstellt werden.",
  "Gezinti ve online tur akışı": "Besichtigungs- und Online-Tour-Workflow",
  "New Level Premium satış görüşmeleri dil, alıcı hedefi, kanal, sorumlu danışman ve takip tarihiyle yönetilir.": "Verkaufsgespräche für New Level Premium werden nach Sprache, Käuferzielgruppe, Kanal, zuständigem Berater und Follow-up-Termin verwaltet.",
  "aktif görüşme": "aktive Gespräche",
  "Onaylı tur": "Bestätigte Tour",
  "Takip gerekli": "Follow-up erforderlich",
  "Online tur": "Online-Tour",
  "No-show kurtarma": "No-Show-Nachfassung",
  "Tur": "Tour",
  "Hedef": "Zielgruppe",
  "İstenen tip": "Gewünschter Typ",
  "Kanal": "Kanal",
  "Takip": "Follow-up",
  "Sonraki aksiyon": "Nächste Aktion",
  "Kayıt": "Datensatz",
  "Misafir/Sakin": "Gast/Bewohner",
  "Temizlik": "Reinigung",
  "Onaylandı": "Bestätigt",
  "Tamamlandı": "Abgeschlossen",
  "Gelmedi": "Nicht erschienen",
  "Cevap gerekli": "Antwort erforderlich",
  "İşlemde": "In Bearbeitung",
  "Hazır": "Bereit",
  "Portal mesajları, bildirimler ve yönetim yanıtları yalnızca yetkili kaydınız kapsamında gösterilir.": "Portalnachrichten, Benachrichtigungen und Antworten der Verwaltung werden nur im Rahmen Ihres berechtigten Datensatzes angezeigt.",
  "Saha ekibi için görev mesajları, SLA bildirimleri ve operasyon yanıtları sadeleştirilmiş görünümde tutulur.": "Aufgabenmeldungen, SLA-Benachrichtigungen und Betriebsantworten werden dem Außendienstteam in einer vereinfachten Ansicht bereitgestellt.",
  "Yönetim sohbeti, ekip içi koordinasyon, bildirim kuralları ve müşteri cevap takibi tek sayfada yönetilir.": "Verwaltungschat, teaminterne Koordination, Benachrichtigungsregeln und Kundenantwort-Tracking werden auf einer einzigen Seite verwaltet.",
  "İletişim Merkezi": "Kommunikationszentrale",
  "Açık konuşma": "Offene Konversation",
  "Acil takip": "Dringende Nachverfolgung",
  "Hazır mesaj": "Textbaustein",
  "Rol kuralı": "Rollenregel",
  "Portal konuşmaları": "Portal-Konversationen",
  "Müşteri ve ekip konuşmaları": "Kunden- und Teamkonversationen",
  "Kanal, konu, son mesaj ve durum bilgisi yetki kapsamınıza göre filtrelenir.": "Kanal, Thema, letzte Nachricht und Statusinformation werden entsprechend Ihrem Berechtigungsumfang gefiltert.",
  "Her konuşmada kanal, sorumlu ekip, öncelik ve son aksiyon görünür.": "Bei jeder Konversation sind Kanal, zuständiges Team, Priorität und letzte Aktion sichtbar.",
  "Toplu bildirim hazırla": "Massenbenachrichtigung vorbereiten",
  "Toplu bildirim taslağı hazırlandı": "Entwurf für Massenbenachrichtigung erstellt",
  "Taslak hazır": "Entwurf bereit",
  "Toplu bildirim": "Massenbenachrichtigung",
  "Kitle": "Zielgruppe",
  "Bildirim mantığı": "Benachrichtigungslogik",
  "Bildirimler yanlış kişiye gitmeyecek şekilde daire ve rol kapsamıyla sınırlandırılır.": "Benachrichtigungen werden anhand von Einheit und Rolle eingeschränkt, damit sie nicht an die falsche Person gehen.",
  "Push, SMS, WhatsApp ve e-posta aynı olaydan tetiklenebilir; hassas finans ve erişim kararları insan onayı olmadan uygulanmaz.": "Push, SMS, WhatsApp und E-Mail können vom selben Ereignis ausgelöst werden; sensible Finanz- und Zugangsentscheidungen werden ohne menschliche Freigabe nicht umgesetzt.",
  "Yanıt takibi": "Antwortverfolgung",
  "Negatif durumlar": "Negativfälle",
  "Yönetim yanıtı, servis randevusu ve belge talebi aynı konuşma geçmişinde kalır.": "Verwaltungsantwort, Serviceterminanfrage und Dokumentenanforderung bleiben im selben Gesprächsverlauf.",
  "Yanlış alıcı, kapalı kanal, borç ihtilafı, dil uyumsuzluğu ve tekrar eden mesajlar audit kuyruğuna düşer.": "Falscher Empfänger, geschlossener Kanal, Forderungsstreit, Sprachkonflikt und wiederholte Nachrichten laufen in die Audit-Warteschlange.",
  "Kural": "Regel",
  "Tetikleyici": "Trigger",
  "Sahip": "Verantwortlicher",
  "Kritik": "Kritisch",
  "Yüksek": "Hoch",
  "Orta": "Mittel",
  "Düşük": "Niedrig",
  "Uygun": "Unbedenklich",
  "Kontrol gerekli": "Prüfung erforderlich",
  "Partner incelemesi": "Partnerprüfung",
  "Kimlik": "Identität",
  "QR, kart, plaka": "QR, Karte, Kennzeichen",
  "Finans": "Finanzen",
  "Borç ve depozito": "Forderungen und Kaution",
  "Karar": "Entscheidung",
  "Geçiş veya kısıt": "Zugang oder Sperre",
  "Kapı": "Tür",
  "Otopark": "Parkplatz",
  "Havuz": "Pool",
  "Asansör": "Aufzug",
  "Erişim karar motoru": "Zugangsentscheidungs-Engine",
  "Kapı, borç, depozito ve kimlik tek karar motorunda": "Tür, Forderungen, Kaution und Identität in einer einzigen Entscheidungs-Engine",
  "Sistem erişim kararını sadece geçiş kartı olarak değil; ödeme, rezervasyon, belge ve güvenlik sinyaliyle birlikte değerlendirir.": "Das System bewertet die Zugangsentscheidung nicht nur anhand der Zugangskarte, sondern zusammen mit Zahlungs-, Buchungs-, Dokumenten- und Sicherheitssignalen.",
  "aktif kısıt": "aktive Sperre",
  "Canlı risk filtresi": "Live-Risikofilter",
  "{pending} bekleyen, {critical} kritik karar": "{pending} ausstehend, {critical} kritische Entscheidungen",
  "Denetim ritmi": "Prüfrhythmus",
  "Her geçiş kararı kullanıcı, sebep, saat ve belge referansıyla kayıt altında tutulur.": "Jede Zugangsentscheidung wird mit Nutzer, Begründung, Uhrzeit und Dokumentenreferenz protokolliert.",
  "Erişim & Uyum": "Zugang & Compliance",
  "Mobil kod, kart, plaka, QR, borç kısıtı, depozito kontrolü ve güvenlik olaylarını tek karar motorunda izleyin.": "Mobilcode, Karte, Kennzeichen, QR, Forderungssperre, Kautionsprüfung und Sicherheitsereignisse in einer einzigen Entscheidungs-Engine überwachen.",
  "Takipteki kayıt": "Datensatz in Bearbeitung",
  "Kısıtlı": "Eingeschränkt",
  "Bekleyen": "Ausstehend",
  "Kritik risk": "Kritisches Risiko",
  "Erişim bölgesi yoğunluğu": "Auslastung der Zugangszone",
  "{count} bölge": "{count} Zonen",
  "Kapı karar motoru": "Tür-Entscheidungs-Engine",
  "Borç, rezervasyon, depozito ve kimlik kontrolü tamamlanmadan geçici erişim açılmaz.": "Ohne abgeschlossene Prüfung von Forderungen, Buchung, Kaution und Identität wird kein temporärer Zugang freigegeben.",
  "Plaka ve otopark": "Kennzeichen und Parkplatz",
  "Otopark, misafir ve sakin erişimleri aynı uyum kayıtlarına bağlanır.": "Parkplatz-, Gast- und Bewohnerzugänge werden in denselben Compliance-Datensätzen erfasst.",
  "Her erişim kararı kullanıcı, sebep, saat ve belge referansıyla denetlenebilir tutulur.": "Jede Zugangsentscheidung bleibt mit Nutzer, Begründung, Uhrzeit und Dokumentenreferenz prüfbar dokumentiert.",
  "Oturum, vatandaşlık ve alıcı uygunluk ön kontrolü": "Vorprüfung von Aufenthaltsstatus, Staatsangehörigkeit und Käufereignung",
  "Satış ekibi uygunluk ön kontrolünü görür; sistem hukuki garanti vermez ve riskli durumları partner incelemesine gönderir.": "Das Vertriebsteam sieht die Eignungsvorprüfung; das System übernimmt keine Rechtsgarantie und leitet Risikofälle an die Partnerprüfung weiter.",
  "{count} inceleme kuyruğu": "{count} in der Prüfwarteschlange",
  "Alıcı dosyası": "Käuferakte",
  "Ön uygun": "Vorläufig geeignet",
  "Ekspertiz gerekli": "Gutachten erforderlich",
  "Bütçe": "Budget",
  "Bölge": "Region",
  "Ekspertiz": "Gutachten",
  "Gerekli": "Erforderlich",
  "Gerekmez": "Nicht erforderlich",
  "Sakin": "Bewohner",
  "Risk": "Risiko",
  "Sebep": "Grund",
  "İnceleme": "Prüfung",
  "Planlı": "Geplant",
  "Var": "Vorhanden",
  "Yok": "Nicht vorhanden",
  "Bildirim kuralları": "Benachrichtigungsregeln",
  "Borç, SLA, check-in, check-out ve belge eksikliği için rol bazlı uyarılar.": "Rollenbasierte Warnmeldungen für Forderungen, SLA, Check-in, Check-out und fehlende Dokumente.",
  "Güvenlik politikası": "Sicherheitsrichtlinie",
  "Rol bazlı erişim, hassas finans işlemleri ve insan onaylı AI kararları.": "Rollenbasierter Zugriff, sensible Finanztransaktionen und AI-Entscheidungen mit menschlicher Freigabe.",
  "Dil ve yerelleştirme": "Sprache und Lokalisierung",
  "Türkçe ana kullanım, çok dilli sakin desteği ve resmi ton standardı.": "Türkisch als Hauptsprache, mehrsprachiger Bewohnersupport und verbindlicher formeller Tonstandard.",
  "Platform Yönetim Merkezi": "Plattform-Verwaltungszentrale",
  "Rol yetki kapsamı, denetim izi, güvenlik kontrolleri ve kullanıcı görünürlüğü tek yönetim alanında takip edilir.": "Rollenberechtigungsumfang, Audit-Trail, Sicherheitskontrollen und Nutzersichtbarkeit werden in einem einzigen Verwaltungsbereich erfasst.",
  "Yüksek risk denetim": "Hochrisikoprüfung",
  "Güvenlik ve platform kontrolleri": "Sicherheits- und Plattformkontrollen",
  "Her kontrolün sahibi, amacı ve canlı durumu yönetim için görünür.": "Verantwortlicher, Zweck und Live-Status jeder Kontrolle sind für die Verwaltung sichtbar.",
  "Operasyon ayarları": "Betriebseinstellungen",
  "Yönetici, finans, güvenlik ve saha ekipleri aynı kontrol merkezinden standart kuralları görür.": "Verwaltung, Finanzen, Sicherheit und Außendienstteams sehen die Standardregeln über dieselbe Kontrollzentrale.",
  "Görünüm": "Ansicht",
  "Açık/koyu tema desteği.": "Unterstützung für Hell-/Dunkelmodus.",
  "Rol": "Rolle",
  "Kullanıcı": "Benutzer",
  "Finans onayı": "Finanzfreigabe",
  "Erişim kısıtı": "Zugangssperre",
  "Dışa aktarım": "Export",
  "Denetim": "Prüfung",
  "Aktör": "Akteur",
  "Platform sürümü:": "Plattformversion:",
  "Doğrulandı": "Verifiziert",
  "Bekliyor": "Ausstehend",
  "Eksik": "Fehlt",
  "Süresi doldu": "Abgelaufen",
  "Reddedildi": "Abgelehnt",
  "Yetkili dairenize bağlı sözleşme, kimlik, depozito, servis ve uyum belgelerini güvenli portal görünümünde takip edin.": "Verfolgen Sie die zu Ihrer autorisierten Einheit gehörenden Vertrags-, Identitäts-, Kautions-, Service- und Compliance-Dokumente in einer sicheren Portalansicht.",
  "Saha operasyonu için yalnızca görev dosyaları, servis kanıtları ve gerekli onay kayıtları gösterilir.": "Für den Außendienstbetrieb werden nur Auftragsdateien, Servicenachweise und erforderliche Freigabeprotokolle angezeigt.",
  "satış ve after-sales süreci için TAPU, kimlik, sözleşme, ödeme, depozito, servis, uyum ve proje belgelerini güvenli, denetlenebilir ve işlem bağlantılı yönetin.": "Verwalten Sie TAPU, Identitäts-, Vertrags-, Zahlungs-, Kautions-, Service-, Compliance- und Projektdokumente für Vertrieb und After-Sales sicher, prüfbar und transaktionsverknüpft.",
  "TAPU & Belge Kasası": "TAPU & Dokumententresor",
  "Belge yükle": "Dokument hochladen",
  "Toplam belge": "Dokumente gesamt",
  "Eksik/Süre doldu": "Fehlend/Abgelaufen",
  "Satış dosyası, TAPU, KYC ve EIDS kontrolü": "Prüfung von Verkaufsakte, TAPU, KYC und EIDS",
  "Satış dosyası; alıcı kimliği, TAPU, EIDS, rezervasyon, satış sözleşmesi ve ödeme planı olmadan sonraki adıma geçmez.": "Ohne Käuferidentität, TAPU, EIDS, Reservierung, Kaufvertrag und Zahlungsplan kann die Verkaufsakte nicht in den nächsten Schritt übergehen.",
  "{count} yüksek risk": "{count} Hochrisiko",
  "Satış belgesi": "Verkaufsdokument",
  "Belge tipi": "Dokumenttyp",
  "Belge": "Dokument",
  "Kapsam": "Geltungsbereich",
  "Dosya": "Akte",
  "Kategori": "Kategorie",
  "İşlem": "Aktion",
  "Belgeyi görüntüle": "Dokument ansehen",
  "Belgeyi indir": "Dokument herunterladen",
  "Kiracı": "Mieter",
  "Misafir": "Gast",
  "Müşteri & Malik CRM": "Kunden- & Eigentümer-CRM",
  "için alıcı, malik, kiracı ve misafirleri; dil, WhatsApp/telefon tercihi, borç, servis, erişim ve yatırım ilgisiyle tek kayıt altında yönetin.": "Verwalten Sie Käufer, Eigentümer, Mieter und Gäste mit Sprache, WhatsApp-/Telefonpräferenz, Forderungen, Service, Zugang und Investitionsinteresse in einem einzigen Datensatz.",
  "Aktif sakin": "Aktive Bewohner",
  "Riskli kayıt": "Risikodatensatz",
  "WhatsApp tercih": "WhatsApp-Präferenz",
  "Çok dilli destek": "Mehrsprachiger Support",
  "AI iletişim önceliği": "AI-Kommunikationspriorität",
  "aksiyon": "Aktion",
  "servis": "Service",
  "İletişim merkezi": "Kommunikationszentrale",
  "WhatsApp, telefon, e-posta ve portal bildirimleri tek sakin profiline bağlanır.": "WhatsApp-, Telefon-, E-Mail- und Portalbenachrichtigungen laufen in einem einzigen Bewohnerprofil zusammen.",
  "Borç + servis bağlamı": "Forderungs- + Servicekontext",
  "Sakin temsilcisi aramadan önce açık borç, erişim kısıtı ve servis geçmişini görür.": "Der Bewohnerbetreuer sieht offene Forderungen, Zugangssperren und Servicehistorie, bevor er anruft.",
  "Ad": "Name",
  "Tip": "Typ",
  "Dil": "Sprache",
  "Telefon": "Telefon",
  "Kapalı": "Geschlossen",
  "AI Rapor Merkezi": "AI-Berichtszentrale",
  "Yönetim kurulu, muhasebe, operasyon, güvenlik ve misafir ekipleri için hazır rapor görünümleri ve karar özetleri.": "Bereitgestellte Berichtsansichten und Entscheidungszusammenfassungen für Verwaltungsbeirat, Buchhaltung, Betrieb, Sicherheit und Gästeteams.",
  "Rapor seti": "Berichtspaket",
  "AI kontrol": "AI-Kontrolle",
  "Tahsilat trendi": "Inkassotrend",
  "Daire dağılımı": "Wohnungsverteilung",
  "Yönetim kuruluna uygun tek bakışlık portföy özeti.": "Portfolioübersicht auf einen Blick, geeignet für den Verwaltungsbeirat.",
  "{bucket} gün borç": "{bucket} Tage Schuld",
  "AI aksiyon listesinde önceliklendirilir.": "Wird in der KI-Aktionsliste priorisiert.",
  "Rapor": "Bericht",
  "Başlık": "Titel",
  "Periyot": "Zeitraum",
  "Metrik": "Kennzahl",
  "AI içgörü": "KI-Erkenntnis",
  "Dışa aktar": "Exportieren",
  "Raporu dışa aktar": "Bericht exportieren",
  "Kullanıcılar & Roller": "Benutzer & Rollen",
  "Malik, kiracı, misafir ve personel kayıtları; dil, görev yükü ve yetki kapsamı tek yönetim alanında izlenir.": "Eigentümer-, Mieter-, Gast- und Personaldatensätze - Sprache, Aufgabenlast und Berechtigungsumfang werden zentral in einem Verwaltungsbereich nachverfolgt.",
  "Personel": "Personal",
  "Sakin kaydı": "Bewohnerdatensatz",
  "Aktif görev": "Aktive Aufgabe",
  "Finans onaycı": "Finanzgenehmiger",
  "Personel operasyon kapsamı": "Betrieblicher Zuständigkeitsbereich des Personals",
  "Her ekip üyesinin rolü, saha yükü, onay limiti ve erişim kapsamı yönetim için görünürdür.": "Rolle, Einsatzlast, Genehmigungslimit und Zugriffsumfang jedes Teammitglieds sind für die Verwaltung einsehbar.",
  "Görev": "Aufgabe",
  "Limit": "Limit",
  "Yetki prensibi": "Berechtigungsprinzip",
  "Kullanıcı sadece kendi görevi için gerekli modülleri görür. Finans, erişim ve kullanıcı yönetimi ayrı onay kapsamındadır.": "Ein Benutzer sieht nur die für seine Aufgabe erforderlichen Module. Finanzen, Zugriffskontrolle und Benutzerverwaltung unterliegen einem separaten Genehmigungsbereich.",
  "Riskli": "Risikobehaftet",
  "Ekip": "Team",
  "Export": "Export",
  "Yönetim": "Verwaltung",
  "Muhasebe": "Buchhaltung",
  "Eğitim": "Schulung",
  "Tüm site": "Gesamte Anlage",
  "Operasyon": "Betrieb",
  "Sadece finans": "Nur Finanzen",
  "Saha": "Vor-Ort-Einsatz",
  "Bu sayfa rolünüz için kapalı": "Diese Seite ist für Ihre Rolle gesperrt",
  "Yetki modeli güvenlik nedeniyle varsayılan olarak erişimi reddeder. Sizin rolünüz için açık olan panele yönlendiriliyorsunuz.": "Das Berechtigungsmodell verweigert den Zugriff standardmäßig aus Sicherheitsgründen. Sie werden zu dem für Ihre Rolle freigegebenen Bereich weitergeleitet.",
  "Finans defteri": "Finanzjournal",
  "Aidat, ödeme, depozito, ceza ve düzeltme kayıtları değiştirilemez defter mantığıyla takip edilir. Hassas finans aksiyonları onay ve denetim akışına alınır.": "Nebenkosten, Zahlungen, Kautionen, Vertragsstrafen und Korrekturbuchungen werden nach dem Prinzip eines unveränderlichen Journals erfasst. Sensible Finanzaktionen laufen über einen Genehmigungs- und Prüfprozess.",
  "Son güncelleme:": "Letzte Aktualisierung:",
  "Defteri yenile": "Journal aktualisieren",
  "Finans defteri dışa aktarım isteği oluştur": "Exportanfrage für Finanzjournal erstellen",
  "Dışa aktarım isteği alındı": "Exportanfrage erhalten",
  "Finans defteri dışa aktarım isteği": "Exportanfrage Finanzjournal",
  "Finans defteri şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Das Finanzjournal kann derzeit nicht geladen werden. Versuchen Sie es erneut über die Schaltfläche Aktualisieren oder prüfen Sie den API-Status.",
  "Finans defteri kalite kontrolü dikkat istiyor:": "Die Qualitätsprüfung des Finanzjournals erfordert Aufmerksamkeit:",
  "Açık bakiye": "Offener Saldo",
  "Bu ay tahsilat": "Einzug diesen Monat",
  "Açık kayıt": "Offener Posten",
  "Son finans kayıtları": "Letzte Finanzbuchungen",
  "vade": "Fälligkeit",
  "Finans kaydı bulunamadı.": "Kein Finanzdatensatz gefunden.",
  "Finans kontrol modeli": "Finanzkontrollmodell",
  "Onaylanmış finans kaydı doğrudan değiştirilmez; düzeltme için karşı kayıt açılır. Dışa aktarım, mutabakat ve ödeme aksiyonları role göre denetim akışına alınır.": "Ein genehmigter Finanzdatensatz wird nicht direkt geändert; für Korrekturen wird eine Gegenbuchung angelegt. Export-, Abstimmungs- und Zahlungsaktionen laufen rollenbasiert über einen Prüfprozess.",
  "Onaylı kayıt": "Genehmigter Datensatz",
  "Yasal risk": "Rechtliches Risiko",
  "Ödendi": "Bezahlt",
  "Açık": "Offen",
  "Kısmi": "Teilweise",
  "İptal": "Storniert",
  "Bilinmiyor": "Unbekannt",
  "Daire yok": "Keine Einheit",
  "Kişi yok": "Keine Person",
  "Blokaj yok": "Keine Sperre",
  "Rezervasyon sözleşmesi eksik": "Reservierungsvertrag fehlt",
  "İkinci taksit doğrulanmadı": "Zweite Rate nicht verifiziert",
  "Ödeme planı imzası bekliyor": "Unterschrift des Zahlungsplans ausstehend",
  "Blokede": "Gesperrt",
  "Rezerve": "Reserviert",
  "İade hazır": "Rückzahlung bereit",
  "İade edildi": "Zurückgezahlt",
  "Kesinti bekliyor": "Abzug ausstehend",
  "Kesildi": "Abgezogen",
  "Tahsil edildi": "Eingezogen",
  "Hatalı": "Fehlerhaft",
  "İade": "Rückzahlung",
  "Banka transferi": "Banküberweisung",
  "Manuel banka": "Manuelle Bankbuchung",
  "tamamlandı": "abgeschlossen",
  "Checkout": "Checkout",
  "gün": "Tage",
  "Riskli plan": "Risikobehafteter Plan",
  "Depozito kuyruğu": "Kautions-Warteschlange",
  "Kısıt kararı": "Sperrentscheidung",
  "Mutabakat": "Abstimmung",
  "Onay kuyruğu": "Genehmigungs-Warteschlange",
  "Ödeme, depozito ve kısıt kontrol merkezi": "Kontrollzentrum für Zahlungen, Kautionen und Zugriffssperren",
  "Satış ödeme planı, depozito iadesi, banka mutabakatı ve borca bağlı erişim kısıtı aynı onay kuyruğunda izlenir. Sistem karar önerir; finans ve erişim aksiyonları insan onayıyla kapanır.": "Verkaufszahlungsplan, Kautionsrückzahlung, Bankabstimmung und schuldenbedingte Zugriffssperre werden in derselben Genehmigungs-Warteschlange nachverfolgt. Das System schlägt eine Entscheidung vor; Finanz- und Zugriffsaktionen werden erst durch eine menschliche Freigabe abgeschlossen.",
  "Kontrolleri yenile": "Kontrollen aktualisieren",
  "Mutabakat inceleme isteği oluştur": "Prüfanfrage für Abstimmung erstellen",
  "İnceleme isteği alındı": "Prüfanfrage erhalten",
  "Phase 7 mutabakat inceleme isteği": "Phase-7-Prüfanfrage Abstimmung",
  "İnceleme aç": "Prüfung öffnen",
  "Ödeme kontrol verisi şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Die Zahlungskontrolldaten können derzeit nicht geladen werden. Versuchen Sie es erneut über die Schaltfläche Aktualisieren oder prüfen Sie den API-Status.",
  "Kalite kontrolü dikkat istiyor:": "Die Qualitätsprüfung erfordert Aufmerksamkeit:",
  "Ödeme planı ve depozito işi": "Zahlungsplan- und Kautionsvorgang",
  "Açık vade": "Offene Fälligkeit",
  "Açık ödeme veya depozito işi bulunamadı.": "Kein offener Zahlungs- oder Kautionsvorgang gefunden.",
  "Kısıt ve mutabakat kuyruğu": "Sperr- und Abstimmungs-Warteschlange",
  "depozito": "Kaution",
  "Kısıt veya mutabakat kuyruğu boş.": "Sperr- oder Abstimmungs-Warteschlange ist leer.",
  "Iade emrini finans onay kuyruguna al": "Rückzahlungsauftrag in die Finanzgenehmigungs-Warteschlange aufnehmen",
  "Erisim kodunu depozito ve borc kontrolu kapanana kadar acma": "Zugriffscode erst freigeben, wenn Kautions- und Schuldenprüfung abgeschlossen ist",
  "Temizlik blokajini operasyonla eslestir": "Reinigungssperre mit dem Betriebsablauf abgleichen",
  "Yasal takip ve erişim kısıtı": "Rechtliche Verfolgung und Zugriffssperre",
  "Telefon + WhatsApp tahsilat": "Inkasso per Telefon + WhatsApp",
  "Otomatik hatırlatma": "Automatische Erinnerung",
  "Aile": "Familie",
  "Yetkili": "Bevollmächtigt",
  "telefon yok": "keine Telefonnummer",
  "Daire bağlantısı yok": "Keine Einheitenzuordnung",
  "Kişi ve rol dizini": "Personen- und Rollenverzeichnis",
  "Personel, malik, kiracı, misafir ve rol kapsamı tek dizinden yönetilir. Ekip yükü, erişim kapsamı ve riskli kayıtlar aynı ekranda takip edilir.": "Personal, Eigentümer, Mieter, Gäste und Rollenzuständigkeiten werden aus einem einzigen Verzeichnis verwaltet. Teamauslastung, Zugriffsumfang und risikobehaftete Datensätze werden auf demselben Bildschirm nachverfolgt.",
  "Son güncelleme: {lastUpdated}": "Letzte Aktualisierung: {lastUpdated}",
  "Kişi verisini yenile": "Personendaten aktualisieren",
  "Kişi dizini dışa aktarım isteği oluştur": "Exportanfrage für Personenverzeichnis erstellen",
  "Kişi dizini dışa aktarım isteği": "Exportanfrage Personenverzeichnis",
  "Kişi dizini şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Das Personenverzeichnis kann derzeit nicht geladen werden. Versuchen Sie es erneut über die Schaltfläche Aktualisieren oder prüfen Sie den API-Status.",
  "Kişi dizini kalite kontrolü dikkat istiyor: {checks}": "Die Qualitätsprüfung des Personenverzeichnisses erfordert Aufmerksamkeit: {checks}",
  "Malik / Kiracı": "Eigentümer / Mieter",
  "Personel iş yükü": "Personalauslastung",
  "Sakin bağlantıları": "Bewohnerzuordnungen",
  "Risk {riskScore}": "Risiko {riskScore}",
  "Rol kapsamı": "Rollenumfang",
  "Rol matrisi kullanıcı görünürlüğü, finans onayı, erişim kısıtı ve dışa aktarım yetkisini ayrı ayrı tutar.": "Die Rollenmatrix trennt Benutzersichtbarkeit, Finanzgenehmigung, Zugriffssperre und Exportberechtigung strikt voneinander.",
  "Onaycı": "Genehmiger",
  "Site operations risk map": "Betriebsrisikokarte der Anlage",
  "Operasyon risk haritası": "Betriebsrisikokarte",
  "Blok, borç, servis ve erişim risk haritası": "Risikokarte für Blöcke, Schulden, Service und Zugriff",
  "8 blok ve 769 daire; borç, servis, erişim ve SLA riskleri tek operasyon görünümünde okunur.": "8 Blöcke und 769 Einheiten - Schulden-, Service-, Zugriffs- und SLA-Risiken sind in einer einzigen Betriebsansicht ablesbar.",
  "kısıt": "Sperre",
  "borç": "Schuld",
  "3D blok risk haritasını daire matrisinde aç": "3D-Blockrisikokarte in der Einheitenmatrix öffnen",
  "Tahsilat rotası": "Inkassoroute",
  "90+ gün, aktif rezervasyon ve erişim kısıtı birlikte skorlanır.": "90+ Tage, aktive Reservierung und Zugriffssperre werden gemeinsam bewertet.",
  "SLA alarmı": "SLA-Alarm",
  "{count} iş": "{count} Vorgänge",
  "Teknik rota ödeme onayı ve öncelik riskine göre sıralanır.": "Die technische Route wird nach Zahlungsfreigabe und Prioritätsrisiko sortiert.",
  "Erişim motoru": "Zugriffs-Engine",
  "{count} kısıt": "{count} Sperren",
  "Mobil kod, kart ve plaka kararları tek güvenlik modelinden geçer.": "Entscheidungen zu Mobilcode, Karte und Kennzeichen laufen über ein einheitliches Sicherheitsmodell.",
  "AI nabız": "KI-Pulscheck",
  "{count} risk": "{count} Risiko",
  "Her risk aksiyona çevrilir: ara, kısıtla, servis ata, belge iste.": "Jedes Risiko wird in eine Aktion überführt: anrufen, einschränken, Auftrag zuweisen, Beleg anfordern.",
  "{label} detayını aç": "{label}-Details öffnen",
  "operasyon kaydı": "Betriebsvorgang",
  "portföy akışı": "Portfolio-Verlauf",
  "tamamlanan işlem": "abgeschlossener Vorgang",
  "rol bazlı ekip": "rollenbasiertes Team",
  "Emlak satışını, site yönetimini ve servis operasyonunu tek çalışma alanında yönetin.": "Verwalten Sie Immobilienverkauf, Wohnanlagenverwaltung und Serviceabwicklung in einem einzigen Arbeitsbereich.",
  "1Çatı; CRM, portföy, finans, servis, belge, uyumluluk ve malik raporlamasını Türkiye emlak pazarı için tasarlanmış rol bazlı bir ERP deneyiminde birleştirir.": "1Çatı vereint CRM, Portfolio, Finanzen, Service, Dokumente, Compliance und Eigentümerreporting in einer rollenbasierten ERP-Lösung, die speziell für den türkischen Immobilienmarkt entwickelt wurde.",
  "Çalışma alanına gir": "Zum Arbeitsbereich",
  "Ürün akışını incele": "Produktablauf ansehen",
  "Operasyon modeli": "Betriebsmodell",
  "Tek kayıt, net yetki, hızlı aksiyon.": "Ein Datensatz, klare Berechtigungen, schnelle Aktion.",
  "Ekipler arası kopukluk yerine, her işlem daire, kişi, belge, ödeme ve görev ilişkisiyle görünür hale gelir.": "Statt Brüchen zwischen den Teams wird jeder Vorgang über die Verknüpfung von Einheit, Person, Beleg, Zahlung und Aufgabe sichtbar.",
  "Portföy ve daire kontrolü": "Portfolio- und Einheitenkontrolle",
  "Blok, kat, daire, malik, sakin, borç, servis ve erişim durumu tek kayıt üzerinden filtrelenir.": "Block, Stockwerk, Einheit, Eigentümer, Bewohner, Schuldenstand, Service und Zugangsstatus lassen sich über einen einzigen Datensatz filtern.",
  "CRM ve rol bazlı çalışma": "CRM und rollenbasiertes Arbeiten",
  "Satış, muhasebe, saha, güvenlik, malik ve kiracı ekranları aynı veriye kendi yetki kapsamıyla erişir.": "Vertrieb, Buchhaltung, Außendienst, Sicherheit, Eigentümer und Mieter greifen auf dieselben Daten zu, jeweils im Rahmen ihrer eigenen Berechtigungen.",
  "Uyumluluk ve denetim": "Compliance und Audit",
  "EİDS, TAPU, belge, ödeme, erişim ve hassas aksiyonlar izlenebilir karar kayıtlarıyla yönetilir.": "EİDS, TAPU, Belege, Zahlungen, Zugang und sensible Aktionen werden mit nachvollziehbaren Entscheidungsprotokollen verwaltet.",
  "Temel ERP modülleri": "Kern-ERP-Module",
  "CRM, lead ve iletişim merkezi": "CRM, Lead- und Kontaktzentrale",
  "Daire matrisi ve portföy yönetimi": "Einheitenmatrix und Portfolioverwaltung",
  "Servis, saha görevleri ve SLA takibi": "Service, Außendienstaufträge und SLA-Tracking",
  "Finans defteri, aidat ve tahsilat": "Finanzbuch, Nebenkosten und Inkasso",
  "Belge kasası, TAPU, KYC ve EİDS kontrolleri": "Dokumententresor, TAPU-, KYC- und EİDS-Prüfungen",
  "Malik, kiracı, personel ve rol matrisi": "Eigentümer-, Mieter-, Personal- und Rollenmatrix",
  "Entegrasyon ve otomasyon katmanı": "Integrations- und Automatisierungsebene",
  "Sağlayıcı kararı bekleyen yol haritası; üretimde henüz aktif değildir.": "Roadmap – Anbieterentscheidung ausstehend; in Produktion noch nicht aktiv.",
  "E-posta, SMS, WhatsApp/Telegram ve bildirim sağlayıcıları": "E-Mail-, SMS-, WhatsApp/Telegram- und Benachrichtigungsanbieter",
  "Ödeme, banka mutabakatı ve dijital bakiye yükleme akışları": "Zahlungs-, Bankabgleich- und digitale Guthabenaufladungsprozesse",
  "Erişim kontrolü, plaka/kart/bariyer ve sayaç entegrasyonları": "Zugangskontrolle, Kennzeichen-/Karten-/Schrankenanbindung und Zählerintegration",
  "AI brifing, risk sıralama, kaynaklı yanıtlar ve insan onaylı aksiyonlar": "KI-Briefing, Risikorangfolge, quellenbasierte Antworten und menschlich freigegebene Aktionen",
  "Kalite standardı": "Qualitätsstandard",
  "Üretim sistemi gibi tasarlanır, kontrol sistemi gibi işletilir.": "Wird wie ein Produktionssystem entworfen und wie ein Kontrollsystem betrieben.",
  "Güvenilir": "Zuverlässig",
  "TypeScript, üretim build'i, tarayıcı kontrolleri ve rol bazlı testler release öncesi çalıştırılır.": "TypeScript-Prüfung, Produktions-Build, Browser-Checks und rollenbasierte Tests laufen vor jedem Release.",
  "İzlenebilir": "Nachvollziehbar",
  "Finans, erişim, belge ve veri değişiklikleri aktör, zaman, modül ve gerekçe ile kaydedilir.": "Änderungen in Finanzen, Zugang, Dokumenten und Daten werden mit Akteur, Zeitpunkt, Modul und Begründung protokolliert.",
  "Ölçeklenebilir": "Skalierbar",
  "769 birimlik operasyon verisi, çok dilli ekipler ve büyüyen portföy için modüler yapı kullanılır.": "Für 769 Einheiten an Betriebsdaten, mehrsprachige Teams und ein wachsendes Portfolio wird eine modulare Struktur eingesetzt.",
  "Asansör kapısı arızası": "Aufzugstürstörung",
  "Daire içi su kaçağı": "Wasserleck in der Einheit",
  "Klima drenaj kontrolü": "Klimaanlagen-Kondenswasserkontrolle",
  "Aidat borcu nedeniyle hizmet bekliyor": "Leistung wegen Nebenkostenschulden ausgesetzt",
  "Ortak alan kamera kontrolü": "Kamerakontrolle Gemeinschaftsflächen",
  "Check-out sonrası hasar raporu": "Schadensbericht nach Check-out",
  "Elektrik pano bakımı": "Wartung Elektroverteilung",
  "Temizlik ekibi yönlendirme": "Einsatzsteuerung Reinigungsteam",
  "Havuz teknik ölçüm": "Technische Poolmessung",
  "Kapı giriş kartı yenileme": "Erneuerung Zugangskarte",
  "Yangın sensörü testi": "Brandmeldertest",
  "Balkon camı hasar tespiti": "Schadensaufnahme Balkonverglasung",
  "Otopark bariyer erişimi": "Zugang Parkplatzschranke",
  "Legal takip öncesi son bildirim": "Letzte Mahnung vor Rechtsverfahren",
  "Tesisat": "Sanitär/Installation",
  "İklimlendirme": "Klimatechnik",
  "Güvenlik": "Sicherheit",
  "Elektrik": "Elektrik",
  "Ortak alan": "Gemeinschaftsfläche",
  "Hasar": "Schaden",
  "Tahsilat": "Inkasso",
  "Antalya havalimani transferi": "Transfer Flughafen Antalya",
  "Spa, fitness ve ortak alan rezervasyonu": "Reservierung Spa, Fitness und Gemeinschaftsflächen",
  "Kart, QR ve plaka erisim islemi": "Zugangsvorgang Karte, QR und Kennzeichen",
  "Hasar tespiti ve depozito raporu": "Schadensaufnahme und Kautionsbericht",
  "Yeni kart/QR, plaka tanimi, kayip kart iptali ve erisim log kontrolu.": "Neue Karte/QR, Kennzeichenerfassung, Sperrung verlorener Karten und Kontrolle des Zugangsprotokolls.",
  "Checkout, bakim veya sikayet sonrasi fotograf/video kanitli hasar raporu.": "Schadensbericht mit Foto-/Videonachweis nach Checkout, Wartung oder Beschwerde.",
  "Kat hizmetleri": "Etagenservice",
  "Rezervasyon": "Reservierung",
  "Sakin destek": "Bewohner-Support",
  "Asansor": "Aufzug",
  "Iklimlendirme": "Klimatechnik",
  "Finans onayi": "Finanzfreigabe",
  "Erisim": "Zugang",
  "Odeme linki veya cari hesaba borclandirma secimini onayla": "Auswahl zwischen Zahlungslink oder Belastung des laufenden Kontos bestätigen",
  "Malik/kiraci memnuniyet ve kapanis onayini al": "Zufriedenheit von Eigentümer/Mieter und Abschlussfreigabe einholen",
  "Arsiv ve rapor kontrolu": "Archiv- und Berichtskontrolle",
  "Parca/islem notunu gir": "Ersatzteil-/Arbeitsnotiz erfassen",
  "Kapanis kaniti yukle": "Abschlussnachweis hochladen",
  "Kimlik/yetki kontrolu": "Identitäts-/Berechtigungsprüfung",
  "Kart/QR/plaka islem kaydi": "Vorgangsprotokoll Karte/QR/Kennzeichen",
  "Access log kontrolu": "Kontrolle des Zugangsprotokolls",
  "Kapanis onayi": "Abschlussfreigabe",
  "Temizlik checklist": "Reinigungs-Checkliste",
  "Teslim notu": "Übergabevermerk",
  "Depozito etkisini not et": "Auswirkung auf Kaution vermerken",
  "Kapanis raporu": "Abschlussbericht",
  "Tamamlandi onayi": "Fertigstellungsbestätigung",
  "Yetki kapsamını dogrula": "Berechtigungsumfang prüfen",
  "Randevu uygunlugunu kontrol et": "Terminverfügbarkeit prüfen",
  "Bildirim gonder": "Benachrichtigung senden",
  "Geri bildirim al": "Rückmeldung einholen",
  "Hemen": "Sofort",
  "Sabah": "Vormittag",
  "Ogle": "Mittag",
  "Aksam": "Abend",
  "Finans onayi bekleniyor; saha aksiyonu kilitli.": "Finanzfreigabe steht aus; Außendiensteinsatz gesperrt.",
  "SLA asimi var; ekip lideri eskalasyonu gerekli.": "SLA-Überschreitung liegt vor; Eskalation an den Teamleiter erforderlich.",
  "Atama ve kanit akisi hazir.": "Zuweisung und Nachweisablauf sind bereit.",
  "Ana Kapı": "Haupteingang",
  "Depo": "Lager",
  "Mobil Kod": "Mobiler Code",
  "Kart": "Karte",
  "Plaka": "Kennzeichen",
  "QR": "QR",
  "Aidat borcu veya depozito kontrolü": "Nebenkostenschulden- oder Kautionsprüfung",
  "Giriş ön kontrolü bekliyor": "Zugangsvorprüfung ausstehend",
  "Bakım veya güvenlik kapaması": "Sperrung wegen Wartung oder Sicherheit",
  "Normal kullanım": "Normalbetrieb",
  "Sözleşme": "Vertrag",
  "Aidat": "Nebenkosten",
  "Uyum": "Compliance",
  "Kaynak: {path}": "Quelle: {path}",
  "OCR / insan onayı gerekli: {path}": "OCR / menschliche Prüfung erforderlich: {path}",
  "Yönetim Kurulu Operasyon Özeti": "Betriebsbericht für den Verwaltungsbeirat",
  "Aidat Tahsilat ve Yaşlandırma": "Hausgeld-Inkasso und Forderungsaltersstruktur",
  "Servis SLA ve Maliyet Kontrolü": "Service-SLA und Kostenkontrolle",
  "Rezervasyon, Depozito ve Hasar": "Reservierung, Kaution und Schadensfälle",
  "Erişim Güvenliği ve Uyum": "Zugangssicherheit und Compliance",
  "Haftalık": "Wöchentlich",
  "Günlük": "Täglich",
  "Anlık": "Echtzeit",
  "Müdür": "Objektleiter",
  "Misafir Operasyonu": "Gästebetrieb",
  "769 daire / %70 doluluk": "769 Einheiten / 70 % Belegung",
  "1.4M ₺ açık borç": "1,4 Mio. ₺ offene Forderungen",
  "4 SLA dışı servis": "4 SLA-Verstöße bei Serviceaufträgen",
  "2 kritik check-out": "2 kritische Check-outs",
  "33 kısıtlı erişim": "33 Zugangssperren",
  "Borç ve servis SLA riski aynı raporda izlenmeli.": "Forderungsrisiko und Service-SLA-Risiko müssen im selben Bericht überwacht werden.",
  "90+ gün borçlu 19 hesap erişim kısıtıyla takip edilmeli.": "19 Konten mit über 90 Tagen Zahlungsrückstand müssen mit Zugangssperre nachverfolgt werden.",
  "Borç blokeli servisler finans onayı olmadan sahaya düşmemeli.": "Wegen Zahlungsrückstand gesperrte Serviceaufträge dürfen ohne Finanzfreigabe nicht ins Feld gehen.",
  "Depozito kesintisi fotoğraf kanıtı ile kapatılmalı.": "Kautionsabzüge müssen mit Fotonachweis abgeschlossen werden.",
  "Mobil kod, kart ve plaka erişimi aynı karar motorundan yönetilmeli.": "Mobiler Code-, Karten- und Kennzeichenzugang müssen über dieselbe Entscheidungslogik gesteuert werden.",
  "23 daire için otomatik borç hatırlatma kuyruğu hazırlandı.": "Für 23 Einheiten wurde eine automatische Mahnwarteschlange erstellt.",
  "Bugünkü 2 check-out için depozito hasar kontrolü açıldı.": "Für die 2 heutigen Check-outs wurde die Kautions-Schadensprüfung eröffnet.",
  "Acil asansör talebi teknisyene atandı ve SLA sayacı başladı.": "Der Notfall-Aufzugsauftrag wurde dem Techniker zugewiesen, die SLA-Uhr läuft.",
  "Haziran tahsilat riski yüksek 37 hesap için öncelik skoru üretildi.": "Für die 37 Konten mit hohem Inkassorisiko im Juni wurde ein Prioritätsscore erstellt.",
  "Tahsilat önceliği": "Inkassopriorität",
  "Servis darboğazı": "Service-Engpass",
  "Check-out kontrolü": "Check-out-Kontrolle",
  "37 hesapta gecikme riski yüksek. AI, önce 90+ gün ve aktif rezervasyonu olan daireleri öneriyor.": "37 Konten weisen ein hohes Verzugsrisiko auf. Die KI schlägt vor, zuerst Einheiten mit über 90 Tagen Rückstand und aktiver Reservierung zu bearbeiten.",
  "3 talep SLA dışına çıktı. Borç blokeli talepler finans onayı olmadan sahaya gönderilmemeli.": "3 Aufträge haben die SLA überschritten. Wegen Zahlungsrückstand gesperrte Aufträge dürfen ohne Finanzfreigabe nicht ins Feld geschickt werden.",
  "2 check-out bugün kapanıyor. Depozito kesintisi ve temizlik kanıtı aynı akışta tamamlanmalı.": "2 Check-outs schließen heute ab. Kautionsabzug und Reinigungsnachweis müssen im selben Ablauf abgeschlossen werden.",
  "Kas": "Nov.",
  "Oca": "Jan.",
  "Şub": "Feb.",
  "Mar": "Mär",
  "Nis": "Apr.",
  "May": "Mai",
  "Haz": "Jun.",
  "Ağu": "Aug.",
  "Eyl": "Sep.",
  "Eki": "Okt.",
  "Ara": "Dez.",
  "Yetkili kiracı kaydı": "Bevollmächtigter Mieterdatensatz",
  "Yetkili malik kaydı": "Bevollmächtigter Eigentümerdatensatz",
  "Operasyon görev dosyası": "Betriebsauftragsakte",
  "Portalda görüntülenebilir": "Im Portal sichtbar",
  "Yönetim onayı bekliyor": "Wartet auf Verwaltungsfreigabe",
  "Checkout tamamlanana kadar depozitoyu bloke tut": "Kaution bis zum Abschluss des Check-outs sperren",
  "Depozito ve erisim kararini finans onayina bagla": "Kautions- und Zugangsentscheidung an Finanzfreigabe koppeln",
  "Erisim kisitini hukuk ve finans onayiyla surdur": "Zugangssperre mit Rechts- und Finanzfreigabe aufrechterhalten",
  "Tahsilat hatirlatmasi ve onayli kisit kontrolu ac": "Mahnwesen und freigegebene Sperrkontrolle aktivieren",
  "Taksit doğrulanmadı": "Rate nicht verifiziert",
  "Keşif, kapsam kilidi ve pazar kıyası": "Anforderungsanalyse, Scope-Festlegung und Marktvergleich",
  "UX/UI tasarım sistemi ve ürün navigasyonu": "UX/UI-Designsystem und Produktnavigation",
  "Platform temeli, auth, RBAC ve audit": "Plattformgrundlage, Auth, RBAC und Audit",
  "Site, blok, kat, daire ve veri importu": "Anlage, Block, Etage, Einheit und Datenimport",
  "Kullanıcı, malik, kiracı ve personel yönetimi": "Verwaltung von Nutzern, Eigentümern, Mietern und Personal",
  "Finans ledger motoru": "Finanz-Ledger-Engine",
  "Ödeme, depozito, mutabakat ve borç kısıtı": "Zahlung, Kaution, Abgleich und Zahlungssperre",
  "Servis kataloğu ve servis siparişi akışı": "Servicekatalog und Serviceauftrags-Workflow",
  "Görev, saha ekibi, SLA ve medya raporu": "Aufgaben, Außendienstteam, SLA und Mediendokumentation",
  "Rezervasyon, kiralama, move-in ve checkout": "Reservierung, Vermietung, Einzug und Check-out",
  "İletişim, bildirim ve doküman merkezi": "Kommunikations-, Benachrichtigungs- und Dokumentenzentrum",
  "Mobil PWA ve kurulabilir kullanıcı deneyimi": "Mobile PWA und installierbare Nutzeroberfläche",
  "Dış sistem entegrasyonları": "Externe Systemintegrationen",
  "AI premium katmanı ve gelişmiş analitik": "KI-Premiumebene und erweiterte Analytik",
  "QA, güvenlik, performans, kabul testi ve canlıya geçiş": "QA, Sicherheit, Performance, Abnahmetest und Go-Live",
  "769 dairelik site, roller, finans, servis, rezervasyon, erişim ve raporlama kapsamı tek ERP hedefinde netleşir.": "Für die Anlage mit 769 Einheiten werden Rollen, Finanzen, Service, Reservierung, Zugang und Reporting in einem einzigen ERP-Ziel klar abgegrenzt.",
  "Yönetici, muhasebe, saha ekibi, sakin ve destek rolleri kendi işlerine uygun, sade ve erişilebilir arayüzden ilerler.": "Verwaltung, Buchhaltung, Außendienst, Bewohner und Support arbeiten jeweils über eine auf ihre Aufgaben abgestimmte, einfache und zugängliche Oberfläche.",
  "Oturum, rol, izin, RLS ve denetim izi bütün hassas işlemler için gerçek kontrol zemini sağlar.": "Session, Rolle, Berechtigung, RLS und Audit-Trail bilden für alle sensiblen Vorgänge die tatsächliche Kontrollgrundlage.",
  "769 daire blok, kat, durum, borç ve erişim ilişkisiyle filtrelenebilir; import kalite kapısı yönetilir.": "Die 769 Einheiten lassen sich nach Block, Etage, Status, Forderung und Zugangsbezug filtern; das Qualitätstor für den Import wird verwaltet.",
  "Her kişi doğru daire, hesap, belge, iletişim dili ve yetki kapsamıyla tek kayıtta yönetilir.": "Jede Person wird mit korrekter Einheit, Konto, Dokument, Kommunikationssprache und Berechtigungsumfang in einem einzigen Datensatz geführt.",
  "Bakiyeler ekran hesabından değil, hesap, borç/alacak, tahakkuk, düzeltme ve ekstre kayıtlarından hesaplanır.": "Salden werden nicht aus einer Bildschirmberechnung, sondern aus Konto-, Soll/Haben-, Abgrenzungs-, Korrektur- und Kontoauszugsbuchungen berechnet.",
  "Ödeme, depozito, iade, borç eşiği ve servis/erişim kısıtları muhasebe ve hukuk onayıyla yürür.": "Zahlung, Kaution, Erstattung, Forderungsschwelle sowie Service-/Zugangssperren laufen über Buchhaltungs- und Rechtsfreigabe.",
  "Temizlik, transfer, bakım ve özel hizmetler fiyat, SLA, borç kontrolü ve görev üretimiyle siparişe dönüşür.": "Reinigung, Transfer, Wartung und Sonderleistungen werden über Preis, SLA, Forderungsprüfung und Auftragserstellung zu einem Serviceauftrag.",
  "Saha işleri atama, öncelik, SLA, foto/video kanıt, iptal ve yönetici onayıyla görünür olur.": "Außendienstarbeiten werden über Zuweisung, Priorität, SLA, Foto-/Videonachweis, Stornierung und Managementfreigabe nachvollziehbar.",
  "Müsaitlik, rezervasyon, depozito, giriş hazırlığı, checkout, kesinti ve erişim kapatma tek süreç olur.": "Verfügbarkeit, Reservierung, Kaution, Einzugsvorbereitung, Check-out, Abzug und Zugangssperrung bilden einen einzigen Prozess.",
  "Sakin, malik, yönetici ve personel iletişimi daire, borç, görev, rezervasyon ve belgeyle ilişkilendirilir.": "Die Kommunikation mit Bewohnern, Eigentümern, Verwaltung und Personal wird mit Einheit, Forderung, Auftrag, Reservierung und Dokument verknüpft.",
  "Sakin, personel ve yönetici ana işleri telefondan hızlı, erişilebilir ve kurulabilir PWA olarak yapılır.": "Die Kernaufgaben von Bewohnern, Personal und Verwaltung lassen sich schnell über eine zugängliche, installierbare PWA auf dem Smartphone erledigen.",
  "Banka/ödeme, SMS/e-posta, erişim kartı/bariyer, sayaç ve kimlik sistemleri test modu ve retry kuyruğuyla bağlanır.": "Bank-/Zahlungssysteme, SMS/E-Mail, Zugangskarte/Schranke, Zähler und Identitätssysteme werden mit Testmodus und Retry-Warteschlange angebunden.",
  "AI günlük brifing, borç riski, servis triage, anomali, doğal dil arama ve rapor taslağı üretir; hassas işlem yapmaz.": "Die KI erstellt tägliches Briefing, Forderungsrisiko, Service-Triage, Anomalieerkennung, natürlichsprachliche Suche und Berichtsentwürfe; sensible Vorgänge führt sie nicht selbst aus.",
  "Üretim canlıya geçmeden önce güvenlik, performans, yedekleme, eğitim, kabul testi ve destek kanıtı tamamlanır.": "Vor dem Produktions-Go-Live werden Sicherheit, Performance, Backup, Schulung, Abnahmetest und Support-Nachweis vollständig abgeschlossen.",
  "Yönetim özeti ve dokümantasyon merkezinden kapsam, risk ve karar kayıtlarını kontrol edin.": "Prüfen Sie Umfang, Risiko und Entscheidungsprotokolle über die Managementübersicht und das Dokumentationszentrum.",
  "Sol menüden rolünüze açık modülü seçin; üst kartlarda kritik sayılar, altta detay tabloları, arama ve aksiyonlar kullanılır.": "Wählen Sie im linken Menü das für Ihre Rolle freigegebene Modul; oben stehen die Kennzahlkarten, darunter Detailtabellen, Suche und Aktionen.",
  "Ayarlar ekranında güvenlik kontrollerini, rol yetkilerini ve son audit olaylarını inceleyin.": "Prüfen Sie im Einstellungsbereich die Sicherheitskontrollen, Rollenberechtigungen und die letzten Audit-Ereignisse.",
  "Daire Matrisi ekranında blok özetini, canlı matrisi, import doğrulamasını ve detay tablosunu kullanın.": "Nutzen Sie im Bereich Einheitenmatrix die Blockübersicht, die Live-Matrix, die Importvalidierung und die Detailtabelle.",
  "Kullanıcılar ekranında sakin, malik, kiracı, personel ve rol ilişkilerini kontrol edin.": "Prüfen Sie im Nutzerbereich die Beziehungen zwischen Bewohnern, Eigentümern, Mietern, Personal und Rollen.",
  "Finans ekranında aidat, borç, tahsilat, gecikme ve ekstre hareketlerini ledger mantığıyla inceleyin.": "Prüfen Sie im Finanzbereich Hausgeld, Forderungen, Inkasso, Verzug und Kontoauszugsbuchungen nach Ledger-Logik.",
  "Finans ve Uyum ekranlarında gecikme, depozito, kısıt ve onay kuyruğunu takip edin.": "Verfolgen Sie in den Bereichen Finanzen und Compliance Verzug, Kaution, Sperren und die Freigabewarteschlange.",
  "Servis Talepleri ekranında katalog, borç kontrolü, görev üretimi ve durum takibini yönetin.": "Verwalten Sie im Bereich Serviceanfragen Katalog, Forderungsprüfung, Auftragserstellung und Statusverfolgung.",
  "Servis Talepleri ekranında görev panosu, SLA riski ve saha raporlarını yönetin.": "Verwalten Sie im Bereich Serviceanfragen das Auftragsboard, das SLA-Risiko und die Außendienstberichte.",
  "Rezervasyon ekranında takvim, giriş/çıkış işleri, depozito ve final kontrol adımlarını takip edin.": "Verfolgen Sie im Reservierungsbereich Kalender, Ein-/Auszugsvorgänge, Kaution und die abschließenden Kontrollschritte.",
  "İletişim ve Belgeler ekranlarında konuşma, duyuru, bildirim ve dosya izinlerini yönetin.": "Verwalten Sie in den Bereichen Kommunikation und Dokumente Gespräche, Ankündigungen, Benachrichtigungen und Dateiberechtigungen.",
  "Mobil görünümde bakiye, servis, görev, belge, sohbet ve bildirim akışlarını test edin.": "Testen Sie in der mobilen Ansicht die Abläufe für Saldo, Service, Aufgaben, Dokumente, Chat und Benachrichtigungen.",
  "Ayarlar ekranında entegrasyon durumu, son hata, manuel retry ve bağlantı loglarını takip edin.": "Verfolgen Sie im Einstellungsbereich Integrationsstatus, letzte Fehler, manuelle Wiederholungsversuche und Verbindungsprotokolle.",
  "AI Rapor Merkezi'nde önerileri kaynak, güven ve insan onayıyla inceleyin.": "Prüfen Sie im KI-Berichtszentrum die Vorschläge nach Quelle, Konfidenz und manueller Freigabe.",
  "Raporlar ve dokümantasyon üzerinden test, kabul, eğitim ve canlıya geçiş checklist durumunu yönetin.": "Verwalten Sie über Berichte und Dokumentation den Checklistenstatus für Test, Abnahme, Schulung und Go-Live.",
  "İhtiyaç haritası": "Anforderungsübersicht",
  "ERP modül planı": "ERP-Modulplan",
  "Pazar kıyası": "Marktvergleich",
  "Karar kaydı": "Entscheidungsprotokoll",
  "Güvenli oturum temeli": "Sichere Session-Grundlage",
  "Rol bazlı navigasyon": "Rollenbasierte Navigation",
  "Denetimli aksiyon servisi": "Auditierbarer Aktionsservice",
  "Korumalı ekranlar": "Geschützte Bereiche",
  "Veri kontrol ve uygulama isteği": "Datenprüf- und Anwendungsauftrag",
  "Anlık yenileme": "Echtzeitaktualisierung",
  "Kişi dizini servisi": "Kontaktverzeichnisdienst",
  "Kullanıcı yönetim paneli": "Nutzerverwaltungspanel",
  "Rol matrisi": "Rollenmatrix",
  "Finans defteri modeli": "Finanz-Ledger-Modell",
  "Finans defteri servisi": "Finanz-Ledger-Dienst",
  "Finans operasyon paneli": "Finanzbetriebspanel",
  "Denetimli finans aksiyonları": "Auditierbare Finanzaktionen",
  "Tutuldu": "Reserviert",
  "Ön kontrol": "Vorprüfung",
  "Atandı": "Zugewiesen",
  "Ödeme bekliyor": "Zahlung ausstehend",
  "Çözüldü": "Gelöst",
  "Kapandı": "Geschlossen",
  "Acil": "Dringend",
  "Ocak": "Jan",
  "Dolu": "Belegt",
  "Boş": "Leer",
  "Bakımda": "In Wartung",
  "Teknik": "Technik",
  "Servis": "Service",
  "AI": "KI",
  "İmar, tapu ve yetki belgelerinin bir kısmı tarama/PDF görseli olarak geldi; OCR veya insan doğrulaması gerekir.": "Ein Teil der Bebauungs-, Eigentums- (TAPU) und Vollmachtsdokumente liegt nur als Scan/PDF-Bild vor; OCR oder manuelle Prüfung ist erforderlich.",
  "Kaynak bekliyor": "Quelle ausstehend",
  "Tem": "Jul",
  "satış planı": "Verkaufsplan",
  "Guvenlik": "Sicherheit",
  "Teknik - Ahmet": "Technik - Ahmet",
  "Teknik - Burak": "Technik - Burak",
  "Güvenlik - Selim": "Sicherheit - Selim",
  "Temizlik - Esra": "Reinigung - Esra",
  "Muhasebe - Merve": "Buchhaltung - Merve",
  "Operasyon - Can": "Betrieb - Can",
  "Selin Yönetici": "Selin Manager",
  "Merve Muhasebe": "Merve Buchhaltung",
  "Ahmet Teknik": "Ahmet Technik",
  "Selim Güvenlik": "Selim Sicherheit",
  "Daria Destek": "Daria Support",
  "Can Operasyon": "Can Betrieb",
  "Site Yönetimi": "Site-Verwaltung",
  "Sakin Destek": "Bewohner-Support",
  "E-posta": "E-Mail",
  "Aidat borcu ve erişim uyarısı": "Beitragsschuld und Zugangswarnung",
  "Klima servis randevusu": "Klimaservice-Termin",
  "Bugünkü check-out ve depozito kontrolü": "Heutiger Check-out und Kautionskontrolle",
  "Aylık finans raporu hazır": "Monatlicher Finanzbericht fertig",
  "Borç > 0": "Schuld > 0",
  "SLA < 4 saat": "SLA < 4 Stunden",
  "Check-in bugün": "Check-in heute",
  "Belge eksik": "Dokument fehlt",
  "Rol profili ve oturum kontrolü": "Rollenprofil und Sitzungskontrolle",
  "Yerel çalışma ortamında yetki profili kullanılabilir; üretim ortamında doğrulanmış kullanıcı profili önceliklidir.": "In der lokalen Entwicklungsumgebung ist ein Testrollenprofil verfügbar; in der Produktionsumgebung hat das verifizierte Benutzerprofil Vorrang.",
  "Rol bazlı menü ve yetki matrisi": "Rollenbasierte Menü- und Berechtigungsmatrix",
  "Her rol için görüntüleme, oluşturma, onay, dışa aktarma ve yönetim hakları açık tanımlanır.": "Für jede Rolle sind Anzeige-, Erstellungs-, Freigabe-, Export- und Verwaltungsrechte klar definiert.",
  "Finans, erişim ve AI karar izi": "Finanz-, Zugriffs- und KI-Entscheidungsprotokoll",
  "Hassas kararlar aktör, modül, sebep, risk ve zaman bilgisiyle izlenebilir şekilde modellenir.": "Sensible Entscheidungen werden nachvollziehbar mit Angaben zu Akteur, Modul, Grund, Risiko und Zeitpunkt erfasst.",
  "Şirket/site izolasyon hazırlığı": "Mandanten-/Standort-Isolationsbereitschaft",
  "Veri modeli şirket, site ve rol bağlamını güvenli erişim politikalarına hazırlayacak şekilde tasarlanmıştır.": "Das Datenmodell ist so gestaltet, dass Unternehmens-, Standort- und Rollenkontext für sichere Zugriffsrichtlinien vorbereitet sind.",
  "AI aksiyonlarında insan onayı": "Menschliche Freigabe bei KI-Aktionen",
  "AI finans, erişim veya hassas verilerde doğrudan işlem yapmaz; öneri ve onay kuyruğu üretir.": "Die KI führt keine direkten Transaktionen in Finanz-, Zugriffs- oder sensiblen Datenbereichen aus; sie erzeugt lediglich Vorschläge und eine Freigabewarteschlange.",
  "Operasyon Sorumlusu": "Operationsverantwortlicher",
  "Rol bazlı panele giriş yaptı": "Hat sich rollenbasiert im Dashboard angemeldet",
  "90+ gün borçlu hesapları dışa aktardı": "Konten mit über 90 Tagen Zahlungsrückstand exportiert",
  "Kısıtlı erişim listesi inceledi": "Hat die Liste der eingeschränkten Zugänge überprüft",
  "AI Operasyon": "KI-Operation",
  "Tahsilat önceliği önerisi oluşturdu": "Hat einen Vorschlag zur Inkasso-Priorisierung erstellt",
  "Daire Import": "Wohnungsimport",
  "Daire import doğrulama raporunu onayladı": "Hat den Validierungsbericht für den Wohnungsimport freigegeben",
  "Kişi, daire, finans, servis, belge ve AI özetleri, her ekibi tek bir doğrusal akışa zorlamadan birbirine bağlı kalır.": "Personen, Einheiten, Finanzen, Service, Dokumente und KI-Zusammenfassungen bleiben miteinander verknüpft, ohne jedes Team in einen starren linearen Ablauf zu zwingen.",
  "Bağlantılı çalışma alanı": "Vernetzter Arbeitsbereich",
  "Operasyonel kayıt": "Betriebsvorgang",
  "Güncel görünüm": "Aktuelle Ansicht",
  "Ekip erişimi": "Teamzugriff",
  "toplam": "Gesamt",
  "Yasal takipteki 15 daire için erişim kısıtlama listesi güncellendi.": "Die Zugangssperrliste für die 15 Einheiten im Rechtsverfahren wurde aktualisiert.",
  "Açık bodrum": "Offenes Kellergeschoss",
  "Zemin kat": "Erdgeschoss",
  "Blok B demo yedek verisi": "Block B Demo-Fallback",
  "Blok D demo yedek verisi": "Block D Demo-Fallback",
  "Waleri onaylı demo yedek verisi: B Blok fiyatları ve numaralandırma/referans mantığı A Blok'tan kopyalanmıştır.": "Waleri-genehmigter Demo-Fallback: Preise sowie Nummerierungs-/Referenzlogik von Block B wurden aus Block A übernommen.",
  "Waleri onaylı demo yedek verisi: D Blok fiyatları E Blok'tan kopyalanmıştır.": "Waleri-genehmigter Demo-Fallback: Preise für Block D wurden aus Block E übernommen.",
  "Sadece taranmış hukuki belgeler": "Nur als Scan vorliegende Rechtsdokumente",
  "New Level Premium fiyat listesi paketi": "New Level Premium Preislisten-Paket",
  "Proje belgeleri, tesis haritası ve kat planları": "Projektdokumente, Lageplan und Grundrisse",
  "İnşaat ve showroom medyası": "Baustellen- und Musterwohnungs-Medien",
  "ROI tablosu ve Almanca proje paketi": "ROI-Übersicht und deutsches Projektpaket",
  "Beach club ve otel hizmetleri tanıtım turu": "Rundgang zu Beach Club und Hotel-Service",
  "Hukuk ortağıyla uygunluk ön kontrolü": "Voranspruchsprüfung mit Rechtspartner",
  "Ödeme planı onaylanınca daireyi rezerve et": "Einheit reservieren, sobald Zahlungsplan bestätigt ist",
  "Gelmeme (no-show) sonrası kurtarma mesajı gönder": "Rückgewinnungsnachricht bei Nichterscheinen senden",
  "Hasar ve temizlik kanıtını muhasebe onayına bağla": "Schadens- und Reinigungsnachweis an die Buchhaltungsfreigabe koppeln",
  "Depozito tutarını checkout takibinde izle": "Kautionsbetrag in der Checkout-Nachverfolgung überwachen",
  "Rezervasyon ön kontrolünü tamamla": "Reservierungs-Vorprüfung abschließen",
  "Ödeme Planı": "Zahlungsplan",
  "Satış Sözleşmesi": "Kaufvertrag",
  "Hukuk Ortağı": "Rechtspartner",
  "İlan Yönetimi": "Angebotsverwaltung",
  "Ödeme planı imzası için hazır": "Bereit für Unterschrift des Zahlungsplans",
  "Alıcı imzası alınacak": "Unterschrift des Käufers einholen",
  "Pasaport ve gelir kaynağı belgeleri talep edilecek": "Reisepass und Nachweis der Mittelherkunft anfordern",
  "Sözleşme öncesi TAPU belgeleri doğrulanacak": "TAPU-Unterlagen vor Vertragsabschluss prüfen",
  "İlan yetki belgesi dosyaya ekli tutulacak": "Verkaufsvollmacht weiterhin beigefügt halten",
  "Rezervasyon öncesi alıcı adı düzeltilecek": "Käufername vor Reservierung korrigieren",
  "düşük": "niedrig",
  "orta": "mittel",
  "yüksek": "hoch",
  "Rezervasyonla ilerleyin ve ROI raporu hazırlayın": "Mit Reservierung und ROI-Unterlagen fortfahren",
  "Söz vermeden önce ikamet bölgesi durumunu kontrol edin": "Status der Wohnsitzzone vor einer Zusage prüfen",
  "Ekspertiz ve kaynak tespiti incelemesi gerekli": "Gutachten und Prüfung der Mittelherkunft erforderlich",
  "İkamet uygunluğu için söz verilmemeli": "Wohnsitz-Eignung nicht zusagen",
  "Yatırım": "Investition",
  "Tatil evi": "Ferienwohnung",
  "Vatandaşlık": "Staatsbürgerschaft",
  "İkamet": "Wohnsitz",
  "Kota incelemesi": "Kontingentprüfung",
  "Yerel örnek veri": "Lokale Seed-Daten",
  "Servis SLA inceleme isteği oluştur": "SLA-Prüfanfrage für Service erstellen",
  "SLA incelemesi aç": "SLA-Prüfung öffnen",
  "Hazırlık": "Vorbereitung",
  "Servis kataloğu ve sipariş kapısı": "Servicekatalog und Auftragsfreigabe",
  "Fiyat, SLA, borç politikası, depozito ve ekip kuralı sipariş oluşmadan önce görünür.": "Preis, SLA, Zahlungsrückstandsregel, Kaution und Team-Zuweisungsregel sind vor Auftragserstellung sichtbar.",
  "{count} sevke hazır": "{count} versandbereit",
  "Borç esnek": "Zahlungsrückstand flexibel",
  "Yönetici kontrol": "Freigabe durch Verwaltung",
  "{name} siparişi hazırla": "Auftrag {name} vorbereiten",
  "Hazırla": "Vorbereiten",
  "Sipariş kontrolü": "Auftragsprüfung",
  "Saha görevleri, SLA ve medya kanıtı": "Außendiensteinsätze, SLA und Mediennachweis",
  "Atama, rota, checklist, medya kanıtı ve yönetici onayı tek görev panosunda takip edilir.": "Zuweisung, Route, Checkliste, Mediennachweis und Freigabe durch die Verwaltung werden in einem einzigen Aufgabenboard verfolgt.",
  "{id} saha görevini hazırla": "Außendiensteinsatz {id} vorbereiten",
  "Harici veri servisi yapılandırılmamış; yerel örnek talep verisi kullanılıyor.": "Externer Datendienst ist nicht konfiguriert; lokale Ticket-Testdaten werden verwendet.",
  "1Çatı, operasyonel servis kataloğunu, servis siparişlerini, SLA görevlerini ve talep olaylarını Supabase içinde tutar.": "1Cati verwaltet den operativen Servicekatalog, Serviceaufträge, SLA-Aufgaben und Ticket-Ereignisse in Supabase.",
  "Twenty CRM, ilişki/iletişim yönetim sistemi olmayı sürdürür; 1Çatı ise sakin hizmetleri ve saha operasyonları sistemi olarak kalır.": "Twenty CRM bleibt das Beziehungs-/Kontaktsystem; 1Cati bleibt das System für Bewohnerservice und Außendiensteinsätze.",
  "karışık": "gemischt",
  "dahili": "intern",
  "tedarikçi": "Dienstleister",
  "Daire teslimi, kısa konaklama sonrası temizlik ve temel sarf malzeme kontrolü.": "Übergabe der Einheit, Reinigung nach Kurzaufenthalt und Kontrolle der Grundausstattung an Verbrauchsmaterial.",
  "Standart daire temizliği": "Standardreinigung der Einheit",
  "Derin temizlik ve checkout hazırlığı": "Grundreinigung und Checkout-Vorbereitung",
  "Checkout sonrası detaylı temizlik, hasar fotoğrafları ve depozito kontrol notu.": "Detaillierte Reinigung nach Checkout, Schadensfotos und Vermerk zur Kautionsprüfung.",
  "Klima bakımı ve drenaj kontrolü": "Klimawartung und Kondenswasserkontrolle",
  "Filtre, drenaj, soğutma performansı ve servis kanıtı ile periyodik klima bakımı.": "Periodische Klimawartung mit Filter-, Kondenswasser- und Kühlleistungsprüfung sowie Servicenachweis.",
  "Acil tesisat müdahalesi": "Notfall-Sanitäreinsatz",
  "Su kaçağı, gider tıkanıklığı ve acil tesisat onarımı için hızlı saha yönlendirmesi.": "Schnelle Einsatzsteuerung bei Wasserleck, Abflussverstopfung und dringender Sanitärreparatur.",
  "Malik, kiracı ve misafirler için planlı havalimanı transferi ve varış bildirimi.": "Geplanter Flughafentransfer und Ankunftsmeldung für Eigentümer, Mieter und Gäste.",
  "Ortak alan kapasitesi, aidat durumu ve kullanıcı yetkisine göre rezervasyon kontrolü.": "Reservierungsprüfung nach Kapazität der Gemeinschaftsfläche, Nebenkostenstand und Nutzerberechtigung.",
  "Muhasebe onayı ve borç kontrolü tamamlanmadan saha işine çıkarma": "Ohne abgeschlossene Buchhaltungsfreigabe und Schuldenprüfung keinen Außendiensteinsatz auslösen",
  "SLA ve ekip uygunluğuna göre görevi ata": "Auftrag nach SLA und Teamverfügbarkeit zuweisen",
  "Personel rota ve medya kanıtı talimatını gönder": "Anweisung zu Personaleinsatz und Mediennachweis senden",
  "Saha notu ve kapanış kanıtını kontrol et": "Außendienstnotiz und Abschlussnachweis prüfen",
  "Sorunu yerinde doğrula": "Problem vor Ort verifizieren",
  "Öncesi fotoğraf yükle": "Vorher-Foto hochladen",
  "Daire giriş kontrolü": "Zugangskontrolle Einheit",
  "Fotoğraf kanıtı": "Fotonachweis",
  "Varış saatini doğrula": "Ankunftszeit bestätigen",
  "Tedarikçiyi ata": "Dienstleister zuweisen",
  "Misafir bildirimini gönder": "Gästemeldung senden",
  "Hasar alanını işaretle": "Schadensbereich markieren",
  "Yönetici onayı al": "Freigabe des Verwalters einholen",
  "Haziran kapanış sinyali": "Abschlusssignal Juni",
  "Son aya göre {sign}{delta} tahsilat farkı. AI raporları sadece öneri üretir; onay insan rolünde kalır.": "{sign}{delta} Abweichung beim Inkasso gegenüber dem Vormonat. AI-Berichte liefern nur Empfehlungen; die Freigabe bleibt Aufgabe des Menschen.",
  "Avsallar master plandan operasyon kaydına": "Vom Avsallar-Masterplan zur Betriebsakte",
  "Telefon kaydı bekliyor": "Telefonnummer ausstehend",
  "New Level Premium price-list package": "New Level Premium Preislisten-Paket",
  "Project documents, facility map and floor plans": "Projektunterlagen, Lageplan und Grundrisse",
  "Construction and showroom media": "Bau- und Showroom-Medien",
  "Unknown": "Unbekannt",
  "Open basement": "Offenes Untergeschoss",
  "Ground floor": "Erdgeschoss",
  "Block B demo fallback": "Demo-Ersatzdaten Block B",
  "Block D demo fallback": "Demo-Ersatzdaten Block D",
  "Waleri-approved demo fallback: copy B Block prices and numbering/reference logic from A Block.": "Von Waleri freigegebene Demo-Ersatzdaten: Preise, Nummerierung und Referenzlogik von Block B wurden aus Block A übernommen.",
  "Waleri-approved demo fallback: copy D Block prices from E Block.": "Von Waleri freigegebene Demo-Ersatzdaten: Preise von Block D wurden aus Block E übernommen.",
  "Deal": "Geschäft",
  "Denetim izi": "Audit-Trail",
  "Proceed with reservation and ROI pack": "Mit Reservierung und ROI-Unterlagen fortfahren",
  "Check residence-zone status before promise": "Status der Aufenthaltszone vor Zusage prüfen",
  "Need appraisal and source-of-funds review": "Wertgutachten und Prüfung der Mittelherkunft erforderlich",
  "Do not promise residence suitability": "Eignung für Aufenthaltstitel nicht zusagen",
  "investment": "Investition",
  "holiday_home": "Ferienhaus",
  "citizenship": "Staatsbürgerschaft",
  "residence": "Aufenthaltstitel",
  "clear": "Unbedenklich",
  "quota_review": "Quotenprüfung",
  "restricted": "Eingeschränkt",
  "Legal takipteki 15 daire için erişim kısıtlama listesi güncellendi.": "Die Zugangssperrliste für die 15 Einheiten im Rechtsverfahren wurde aktualisiert.",
  "External data service is not configured; using local ticket seed data.": "Der externe Datendienst ist nicht konfiguriert; es werden lokale Beispieldaten für Aufträge verwendet.",
  "low": "Niedrig",
  "medium": "Mittel",
  "high": "Hoch",
  "Reservation": "Reservierung",
  "Payment Plan": "Zahlungsplan",
  "Sales Contract": "Kaufvertrag",
  "Ready for payment-plan signature": "Bereit zur Unterschrift des Zahlungsplans",
  "Collect buyer signature": "Unterschrift des Käufers einholen",
  "Request passport and source-of-funds pack": "Reisepass und Nachweis der Mittelherkunft anfordern",
  "Validate title deed pack before contract": "TAPU-Unterlagen vor Vertragsabschluss prüfen",
  "Keep listing authorization attached": "Verkaufsvollmacht weiterhin beigefügt halten",
  "Correct buyer name before reservation": "Käufername vor Reservierung korrigieren",
  "Standart daire temizligi": "Standard-Wohnungsreinigung",
  "Daire teslimi, kisa konaklama sonrasi temizlik ve temel sarf malzeme kontrolu.": "Wohnungsübergabe, Reinigung nach Kurzaufenthalt und Kontrolle der Grundverbrauchsmaterialien.",
  "Derin temizlik ve checkout hazirligi": "Grundreinigung und Checkout-Vorbereitung",
  "Checkout sonrasi detayli temizlik, hasar fotograflari ve depozito kontrol notu.": "Detaillierte Reinigung nach Checkout, Schadensfotos und Depot-Prüfvermerk.",
  "Klima bakimi ve drenaj kontrolu": "Klimaanlagenwartung und Drainagekontrolle",
  "Filtre, drenaj, sogutma performansi ve servis kaniti ile periyodik klima bakimi.": "Periodische Klimaanlagenwartung mit Filter, Drainage, Kühlleistung und Servicenachweis.",
  "Acil tesisat mudahalesi": "Notfall-Sanitäreinsatz",
  "Su kacagi, gider tikanikligi ve acil tesisat onarimi icin hizli saha yonlendirmesi.": "Schnelle Einsatzdisposition vor Ort bei Wasserleckagen, Abflussverstopfungen und Notfall-Sanitärreparaturen.",
  "Ortak alan kapasitesi, aidat durumu ve kullanici yetkisine gore rezervasyon kontrolu.": "Reservierungsprüfung nach Kapazität der Gemeinschaftsflächen, Beitragsstatus und Nutzerberechtigung.",
  "mixed": "Gemischtes Team",
  "internal": "Internes Team",
  "vendor": "Dienstleister",
  "1Cati keeps the operational service catalogue, service orders, SLA tasks and ticket events inside Supabase.": "1Cati verwaltet den operativen Servicekatalog, Serviceaufträge, SLA-Aufgaben und Ticket-Ereignisse in Supabase.",
  "Twenty CRM remains the relationship/contact system; 1Cati remains the resident-service and field-operations system.": "Twenty CRM bleibt das Beziehungs-/Kontaktsystem; 1Cati bleibt das System für Bewohnerservice und Außendienst.",
  "Muhasebe onayi ve borc kontrolu tamamlanmadan saha isine cikarma": "Keinen Außeneinsatz starten, bevor Buchhaltungsfreigabe und Schuldenprüfung abgeschlossen sind",
  "Saha notu ve kapanis kanitini kontrol et": "Einsatznotiz und Abschlussnachweis prüfen",
  "SLA ve ekip uygunluguna gore gorevi ata": "Aufgabe nach SLA und Teamverfügbarkeit zuweisen",
  "Personel rota ve medya kaniti talimatini gonder": "Mitarbeiter Route und Medienbeleg-Anweisung senden",
  "Daire giris kontrolu": "Zugangskontrolle Wohnung",
  "Fotograf kaniti": "Fotobeleg",
  "Sorunu yerinde dogrula": "Problem vor Ort verifizieren",
  "Oncesi fotograf yukle": "Vorher-Foto hochladen",
  "Varis saatini dogrula": "Ankunftszeit bestätigen",
  "Tedarikciyi ata": "Dienstleister zuweisen",
  "Misafir bildirimini gonder": "Gästebenachrichtigung senden",
  "Hasar alanini isaretle": "Schadensbereich markieren",
  "Yonetici onayi al": "Genehmigung des Verantwortlichen einholen",
  "Push + Ekip": "Push + Team-Kanal"
}
