// English business-copy dictionary for the 1Cati dashboard, AI assistant and
// platform marketing content. Populated by the July 2026 localization audit.
// Keys are the canonical Turkish source strings (or {token} templates); do not
// hand-edit keys without updating every sibling locale file identically.

export const enCopy: Record<string, string> = {
  "Aidat, tahsilat, depozito veya finans raporu sorun...": "Ask about dues, collections, deposits or finance reports...",
  "Atanan servis, saha notu veya rezervasyon işi sorun...": "Ask about assigned service jobs, field notes or reservation tasks...",
  "Servis, rezervasyon, belge veya mesaj hakkında sorun...": "Ask about service, reservations, documents or messages...",
  "Operasyon Kullanıcısı": "Operations User",
  "Operasyon Asistanı": "Operations Assistant",
  "Toplam Daire": "Total Units",
  "{rate}% doluluk": "{rate}% occupancy",
  "{vacant} boş, {maintenance} bakımda": "{vacant} vacant, {maintenance} under maintenance",
  "Toplam Borç": "Total Debt",
  "{count} erişim kısıtı": "{count} access restrictions",
  "Açık Servis": "Open Service Tickets",
  "{count} SLA dışı": "{count} past SLA",
  "Teknik, finans ve depozito işleri": "Technical, finance and deposit matters",
  "Bugünkü İşler": "Today's Tasks",
  "{count} çıkış": "{count} check-outs",
  "Giriş, çıkış, temizlik, depozito": "Check-in, check-out, cleaning, deposit",
  "{count} operasyon riski AI kuyruğunda: borç, SLA ve check-out birlikte takip ediliyor.": "{count} operational risks in the AI queue: debt, SLA and check-out are tracked together.",
  "{count} dairede erişim kısıtı var. Finans onayı olmadan servis yönlendirilmemeli.": "{count} units have access restrictions. Service must not be dispatched without finance approval.",
  "{count} servis talebi SLA dışına çıktı. Teknik ekip için öncelik listesi hazır.": "{count} service requests are past SLA. Priority list for the technical team is ready.",
  "ERP Operasyon Merkezi": "ERP Operations Center",
  "Satış, proje takibi, WhatsApp/Telegram lead akışı, evrak, servis, finans ve AI önceliklendirme tek çalışma alanında toplanır. Operasyon görünümü 769 birim ölçeğinde yönetim, kontrol ve takip için çalışır.": "Sales, project tracking, WhatsApp/Telegram lead flow, documents, service, finance and AI prioritization are consolidated into a single workspace. The operations view runs management, control and tracking at a scale of 769 units.",
  "Aktif rol:": "Active role:",
  "Veri yenilenemedi. Lütfen tekrar deneyin.": "Data could not be refreshed. Please try again.",
  "Portföy kaynağı": "Portfolio source",
  "daire": "unit",
  "açık servis": "open service ticket",
  "aktif rol": "active role",
  "modülüne git": "go to module",
  "ERP modül durumu": "ERP module status",
  "CRM, daire matrisi, kullanıcı rolleri, finans, servis, saha, rezervasyon, iletişim, mobil PWA, entegrasyon, AI ve güvenlik kontrolleri aynı işletim planında izlenir.": "CRM, unit matrix, user roles, finance, service, field, reservations, communication, mobile PWA, integrations, AI and security controls are all tracked under the same operating plan.",
  "{complete} aktif · {readyForUat} kontrol hazır · {inProgress} yapımda": "{complete} active · {readyForUat} ready for review · {inProgress} in progress",
  "Modül": "Module",
  "ekranını aç": "open screen",
  "Aktif": "Active",
  "Kontrol hazır": "Ready for review",
  "Yapımda": "In Progress",
  "Planlandı": "Planned",
  "Bloke": "Blocked",
  "Nasıl kullanılır:": "How to use:",
  "modülünü aç": "open module",
  "Doluluk ve tahsilat sağlığı detayını aç": "Open occupancy and collections health details",
  "Doluluk ve tahsilat sağlığı": "Occupancy and collections health",
  "Doluluk oranı, gecikmiş borç ve servis baskısı birlikte okunur.": "Occupancy rate, overdue debt and service load are read together.",
  "Haziran hedefi korunuyor": "June target is on track",
  "Daire durum dağılımı detayını aç": "Open unit status breakdown details",
  "Daire durum dağılımı": "Unit status breakdown",
  "Operasyon ekibi için canlı portföy kırılımı.": "Live portfolio breakdown for the operations team.",
  "Blok bazlı operasyon": "Block-based operations",
  "{count} blok": "{count} blocks",
  "Blok": "Block",
  "daire matrisi detayını aç": "open unit matrix details",
  "{count} daire": "{count} units",
  "Dolu:": "Occupied:",
  "Boş:": "Vacant:",
  "Bakım:": "Maintenance:",
  "Borç:": "Debt:",
  "AI operasyon asistanı raporlarını aç": "Open AI operations assistant reports",
  "AI operasyon asistanı": "AI operations assistant",
  "Borç, SLA, depozito ve rezervasyon verilerini birleştirerek günlük yapılacakları sıralar.": "Combines debt, SLA, deposit and reservation data to rank the daily task list.",
  "detayını aç": "open details",
  "Son operasyon akışı": "Latest operations feed",
  "Bugünkü kritik işler": "Today's critical tasks",
  "{hours} saat": "{hours} hours",
  "servis talebini aç": "open service request",
  "rezervasyon detayını aç": "open reservation details",
  "Depozito:": "Deposit:",
  "Finans özetini aç": "Open finance summary",
  "Aylık beklenen aidat": "Monthly expected maintenance fee",
  "Haziran tahsilat": "June collections",
  "Depozito riski": "Deposit risk",
  "rol izni yok": "no role permission",
  "Bu modül mevcut rol için kapalı": "This module is disabled for the current role",
  "Rol kapalı": "Role restricted",
  "İncele": "Review",
  "Canlı daire": "Live units",
  "Açık servis": "Open service",
  "finans kontrolü": "finance control",
  "Erişim riski": "Access risk",
  "Operasyon merkezi": "Operations center",
  "Daire, servis, finans ve rezervasyon aynı kontrol düzleminde": "Units, service, finance and reservations on the same control plane",
  "Bu görünüm yönetim ve sorumlu rolü için portföy ölçeğinde risk, iş yükü ve tahsilat sinyallerini birleştirir.": "This view consolidates portfolio-scale risk, workload and collections signals for management and responsible roles.",
  "AI risk": "AI risk",
  "öncelikli aksiyon": "priority action",
  "İş yoğunluğu": "Workload",
  "Saatlik sinyal": "Hourly signal",
  "Gün {day}: {value}%": "Day {day}: {value}%",
  "Saat {hour}: {value}%": "Hour {hour}: {value}%",
  "Rol bağlantıları aktif": "Role links active",
  "Dashboard kartları, API ve AI yanıtları aynı RBAC matrisinden geçer.": "Dashboard cards, API and AI responses all pass through the same RBAC matrix.",
  "Çalışma alanı ritmi": "Workspace rhythm",
  "Hover ve kart geçişleri gerçek modül akışlarını gösterir.": "Hover and card transitions reflect the actual module flows.",
  "Yetki sınırları": "Permission boundaries",
  "Bu ekranda şirket geneli daire matrisi, finans defteri, kullanıcı yönetimi ve platform ayarları gösterilmez. Kapalı bir sayfa URL ile açılırsa sistem sizi tekrar kendi çalışma alanınıza döndürür.": "This screen does not display the company-wide unit matrix, finance ledger, user management or platform settings. If a restricted page is opened via URL, the system redirects you back to your own workspace.",
  "açık modül": "open module",
  "yetkili iş": "authorized task",
  "Finans, Satış & Aidat": "Finance, Sales & Maintenance Fees",
  "{clientName} için satış ödemeleri, aidat, borç yaşlandırma, depozito, ödeme doğrulama, kira geliri ve erişim kısıtı kararları aynı finans akışında yönetilir.": "Sales payments, maintenance fees, debt aging, deposits, payment verification, rental income and access restriction decisions for {clientName} are all managed in the same finance workflow.",
  "Toplam borç": "Total debt",
  "Aylık aidat": "Monthly maintenance fee",
  "Kısıtlı erişim": "Restricted access",
  "Aylık nakit akışı": "Monthly cash flow",
  "Tahsilat, açık borç ve servis gideri birlikte takip edilir.": "Collections, outstanding debt and service expenses are tracked together.",
  "Tahsilat {amount}": "Collections {amount}",
  "Borç yaşlandırma": "Debt aging",
  "Önceliklendirme 90+ gün ve erişim kısıtından başlar.": "Prioritization starts with 90+ day accounts and access restrictions.",
  "{days} gün": "{days} days",
  "Yasal takip": "Legal proceedings",
  "Gecikmiş": "Overdue",
  "Ödeme doğrulama": "Payment verification",
  "Banka dekontu, online ödeme, manuel tahsilat ve kasa hareketi aynı hesap kaydına bağlanır.": "Bank receipts, online payments, manual collections and cash register entries are all linked to the same account record.",
  "Borç kısıtlama kuralı": "Debt restriction rule",
  "90+ gün borçta erişim kısıtı, servis bekletme ve yasal takip önerisi otomatik görünür.": "For 90+ day debt, access restriction, service hold and legal proceedings recommendations appear automatically.",
  "Depozito kontrolü": "Deposit control",
  "Hasar, temizlik ve iade onayı rezervasyon çıkışıyla finans panelinde kapanır.": "Damage, cleaning and refund approval are closed out in the finance panel at reservation check-out.",
  "Satış ödeme planı": "Sales payment plan",
  "0% taksit akışı; liste fiyatı, peşinat, kalan vade, kur riski ve sözleşme blokajını satıştan önce görünür yapar.": "0% installment flow; makes list price, down payment, remaining installments, FX risk and contract lock visible before the sale.",
  "Açık vade {amount}": "Open installment {amount}",
  "Plan sayısı": "Number of plans",
  "Planında": "On plan",
  "Vade uyarısı": "Installment alert",
  "Blokeli": "Locked",
  "Plan": "Plan",
  "Alıcı": "Buyer",
  "Liste": "List price",
  "Ödenen": "Paid",
  "Sonraki vade": "Next installment",
  "Durum": "Status",
  "Vade yaklaştı": "Due soon",
  "Gecikti": "Overdue",
  "Blokaj": "Lock",
  "Daire": "Unit",
  "Malik": "Owner",
  "Borç": "Debt",
  "Yaş": "Age",
  "Erişim": "Access",
  "Önerilen aksiyon": "Recommended action",
  "Ucretsiz": "Free",
  "Odeme once": "Payment first",
  "Cari hesaba yaz": "Post to current account",
  "Onayli": "Approved",
  "Beklet": "Hold",
  "Taslak": "Draft",
  "Borc kontrolu": "Debt check",
  "Odeme bekliyor": "Payment pending",
  "Gorev acildi": "Task opened",
  "Atandi": "Assigned",
  "Tamamlandi": "Completed",
  "Iptal": "Cancelled",
  "Supabase live": "Supabase live",
  "Yetkili dairenize bağlı servis taleplerini, randevu durumunu, medya kanıtını ve yönetim yanıtlarını tek ekrandan takip edin.": "Track service requests, appointment status, media evidence and management responses linked to your authorized unit from a single screen.",
  "Saha ekibi için atanan servis işleri, SLA önceliği, medya kanıtı ve kapanış adımları aynı iş kuyruğunda yönetilir.": "Assigned service jobs, SLA priority, media evidence and closing steps for the field team are managed in the same work queue.",
  "ve diğer Ataberk portföyleri için teknik servis, ödeme doğrulama, fotoğraf/video kanıtı ve SLA takibi aynı iş kuyruğunda yönetilir.": "and other Ataberk portfolios, technical service, payment verification, photo/video evidence and SLA tracking are managed in the same work queue.",
  "Servis Talepleri": "Service Requests",
  "Kuyrugu yenile": "Refresh queue",
  "SLA inceleme istegi alindi": "SLA review request received",
  "Servis SLA ve kanit kuyrugu incelemesi": "Service SLA and evidence queue review",
  "Servis talebi verisi su anda alinamadi. Yerel veriyle devam ediliyor.": "Service request data could not be retrieved right now. Continuing with local data.",
  "Açık talep": "Open request",
  "SLA dışı": "SLA breached",
  "Onay bekleyen": "Pending approval",
  "Borç blokeli": "Debt-blocked",
  "Medya kanıtı": "Media evidence",
  "Katalog": "Catalog",
  "Siparis": "Order",
  "Saha gorevi": "Field task",
  "Borc kapali": "Debt-locked",
  "SLA {hours} saat": "SLA {hours} hours",
  "Siparis hazirligi kayda alindi": "Order preparation logged",
  "{name} servis siparisi": "{name} service order",
  "{count} blokeli": "{count} blocked",
  "{count} onay": "{count} approval",
  "{count} SLA riski": "{count} SLA risk",
  "Yonetici": "Manager",
  "{count} medya - SLA {sla} saat": "{count} media - SLA {sla} hours",
  "Gorev aksiyonu kayda alindi": "Task action logged",
  "{id} saha gorevi": "{id} field task",
  "Aksiyon": "Action",
  "Takipteki talepleriniz": "Your tracked requests",
  "Öncelikli iş kuyruğu": "Priority work queue",
  "{count} gecikmiş": "{count} overdue",
  "Finans blokeli": "Finance-blocked",
  "Servis kapsamı": "Service scope",
  "Servis güvenlik kuralı": "Service security rule",
  "Sadece sizin dairenize veya yetkili kaydınıza bağlı talepler gösterilir.": "Only requests linked to your unit or your authorized record are shown.",
  "Borç blokeli dairelerde teknisyen sahaya çıkmadan önce muhasebe onayı ve ödeme doğrulaması gerekir.": "For debt-blocked units, accounting approval and payment verification are required before the technician is dispatched to site.",
  "Kanıt ve yanıt": "Evidence and response",
  "Saha iş akışı": "Field workflow",
  "Fotoğraf, açıklama, randevu ve kapanış kararı yönetim ekibiyle aynı kayıt üzerinden paylaşılır.": "Photo, description, appointment and closing decision are shared with the management team on the same record.",
  "Talep, fotoğraf, maliyet, onay, atama ve kapanış kanıtı tek kayıtta tutulur.": "Request, photo, cost, approval, assignment and closing evidence are kept in a single record.",
  "Günlük rota": "Daily route",
  "AI önerisi": "AI suggestion",
  "SLA ve kanıt ihtiyacına göre teknik rota sadeleştirilir; finans tutarları saha görünümünde maskelenir.": "The technical route is simplified based on SLA and evidence needs; financial amounts are masked in the field view.",
  "SLA, tahmini maliyet ve borç durumu birlikte skorlanarak günlük teknik rota oluşturulur.": "SLA, estimated cost and debt status are scored together to build the daily technical route.",
  "Ticketing mimarisi": "Ticketing architecture",
  "Talep": "Request",
  "Konu": "Subject",
  "Öncelik": "Priority",
  "Sorumlu": "Assignee",
  "Servis izni": "Service permission",
  "Ödeme": "Payment",
  "Onaylı": "Approved",
  "Kontrol": "Check",
  "Maliyet": "Cost",
  "Rezervasyon & Giriş-Çıkış": "Reservations & Check-in/Check-out",
  "Yetkili rezervasyon, giriş-çıkış, erişim kodu ve depozito durumunu sadece kendi kaydınız kapsamında takip edin.": "Track authorized reservation, check-in/check-out, access code and deposit status only within the scope of your own record.",
  "Saha ekibi için giriş-çıkış, temizlik, erişim ve operasyon görevleri sadeleştirilmiş çizelgede gösterilir.": "Check-in/check-out, cleaning, access and operations tasks for the field team are shown in a simplified schedule.",
  "Web uygulama içinde rezervasyon, check-in, check-out, temizlik, erişim kodu ve depozito süreçlerini yönetin.": "Manage reservation, check-in, check-out, cleaning, access code and deposit processes within the web app.",
  "Aktif kayıt": "Active record",
  "Bugün giriş": "Check-in today",
  "Bugün çıkış": "Check-out today",
  "Depozito kontrol": "Deposit check",
  "Rezervasyon durumunuz": "Your reservation status",
  "Bugünkü operasyon çizelgesi": "Today's operations schedule",
  "aktif iş": "active jobs",
  "Giriş": "Check-in",
  "Çıkış": "Check-out",
  "Depozito": "Deposit",
  "Erişim kodu": "Access code",
  "Erişim durumu yalnızca yetkili kaydınız için gösterilir.": "Access status is shown only for your authorized record.",
  "Borç, depozito ve kimlik kontrolü tamamlanınca erişim kodu onaya hazır hale gelir; aktivasyon insan onayıyla yapılır.": "Once debt, deposit and identity checks are completed, the access code becomes ready for approval; activation is done with human confirmation.",
  "bekleyen veya kısıtlı kayıt": "pending or restricted records",
  "Kapanış kontrolü": "Closing check",
  "Hasar ve depozito": "Damage and deposit",
  "Check-out sonrası hasar, fotoğraf kanıtı ve iade kararı portal kaydına bağlanır.": "Post-check-out damage, photo evidence and refund decision are linked to the portal record.",
  "Check-out sonrası fotoğraf, servis maliyeti ve depozito kesintisi aynı finans kaydına bağlanır.": "Post-check-out photos, service cost and deposit deduction are linked to the same finance record.",
  "Saha önceliği": "Field priority",
  "AI doluluk önerisi": "AI occupancy suggestion",
  "Temizlik, erişim ve çıkış işleri günlük ekip kapasitesine göre sıralanır.": "Cleaning, access and check-out tasks are ranked according to daily team capacity.",
  "Boş daire, bakım durumu ve önceki kanal performansına göre fiyat ve kanal önerisi üretilebilir.": "Price and channel recommendations can be generated based on vacant units, maintenance status and prior channel performance.",
  "Gezinti ve online tur akışı": "Viewing and online tour flow",
  "New Level Premium satış görüşmeleri dil, alıcı hedefi, kanal, sorumlu danışman ve takip tarihiyle yönetilir.": "New Level Premium sales conversations are managed by language, buyer target, channel, responsible consultant and follow-up date.",
  "aktif görüşme": "active conversations",
  "Onaylı tur": "Confirmed tour",
  "Takip gerekli": "Follow-up required",
  "Online tur": "Online tour",
  "No-show kurtarma": "No-show recovery",
  "Tur": "Tour",
  "Hedef": "Target",
  "İstenen tip": "Requested type",
  "Kanal": "Channel",
  "Takip": "Follow-up",
  "Sonraki aksiyon": "Next action",
  "Kayıt": "Record",
  "Misafir/Sakin": "Guest/Resident",
  "Temizlik": "Cleaning",
  "Onaylandı": "Confirmed",
  "Tamamlandı": "Completed",
  "Gelmedi": "No-show",
  "Cevap gerekli": "Response required",
  "İşlemde": "In progress",
  "Hazır": "Ready",
  "Portal mesajları, bildirimler ve yönetim yanıtları yalnızca yetkili kaydınız kapsamında gösterilir.": "Portal messages, notifications and management responses are shown only within the scope of your authorized record.",
  "Saha ekibi için görev mesajları, SLA bildirimleri ve operasyon yanıtları sadeleştirilmiş görünümde tutulur.": "Task messages, SLA notifications and operations responses for the field team are kept in a simplified view.",
  "Yönetim sohbeti, ekip içi koordinasyon, bildirim kuralları ve müşteri cevap takibi tek sayfada yönetilir.": "Management chat, internal team coordination, notification rules and customer response tracking are managed on a single page.",
  "İletişim Merkezi": "Communication Center",
  "Açık konuşma": "Open conversation",
  "Acil takip": "Urgent follow-up",
  "Hazır mesaj": "Message template",
  "Rol kuralı": "Role rule",
  "Portal konuşmaları": "Portal conversations",
  "Müşteri ve ekip konuşmaları": "Customer and team conversations",
  "Kanal, konu, son mesaj ve durum bilgisi yetki kapsamınıza göre filtrelenir.": "Channel, subject, last message and status information are filtered according to your authorization scope.",
  "Her konuşmada kanal, sorumlu ekip, öncelik ve son aksiyon görünür.": "Channel, responsible team, priority and last action are visible for every conversation.",
  "Toplu bildirim hazırla": "Prepare bulk notification",
  "Toplu bildirim taslağı hazırlandı": "Bulk notification draft prepared",
  "Taslak hazır": "Draft ready",
  "Toplu bildirim": "Bulk notification",
  "Kitle": "Audience",
  "Bildirim mantığı": "Notification logic",
  "Bildirimler yanlış kişiye gitmeyecek şekilde daire ve rol kapsamıyla sınırlandırılır.": "Notifications are restricted by unit and role scope so they cannot reach the wrong recipient.",
  "Push, SMS, WhatsApp ve e-posta aynı olaydan tetiklenebilir; hassas finans ve erişim kararları insan onayı olmadan uygulanmaz.": "Push, SMS, WhatsApp and email can be triggered from the same event; sensitive finance and access decisions are never executed without human approval.",
  "Yanıt takibi": "Response tracking",
  "Negatif durumlar": "Negative cases",
  "Yönetim yanıtı, servis randevusu ve belge talebi aynı konuşma geçmişinde kalır.": "Management reply, service appointment and document request stay in the same conversation history.",
  "Yanlış alıcı, kapalı kanal, borç ihtilafı, dil uyumsuzluğu ve tekrar eden mesajlar audit kuyruğuna düşer.": "Wrong recipient, blocked channel, debt dispute, language mismatch and repeated messages go into the audit queue.",
  "Kural": "Rule",
  "Tetikleyici": "Trigger",
  "Sahip": "Owner",
  "Kritik": "Critical",
  "Yüksek": "High",
  "Orta": "Medium",
  "Düşük": "Low",
  "Uygun": "Clear",
  "Kontrol gerekli": "Review required",
  "Partner incelemesi": "Partner review",
  "Kimlik": "Identity",
  "QR, kart, plaka": "QR, card, license plate",
  "Finans": "Finance",
  "Borç ve depozito": "Debt and deposit",
  "Karar": "Decision",
  "Geçiş veya kısıt": "Access or restriction",
  "Kapı": "Door",
  "Otopark": "Parking",
  "Havuz": "Pool",
  "Asansör": "Elevator",
  "Erişim karar motoru": "Access decision engine",
  "Kapı, borç, depozito ve kimlik tek karar motorunda": "Door, debt, deposit and identity in one decision engine",
  "Sistem erişim kararını sadece geçiş kartı olarak değil; ödeme, rezervasyon, belge ve güvenlik sinyaliyle birlikte değerlendirir.": "The system evaluates access decisions not just as an access card, but together with payment, reservation, document and security signals.",
  "aktif kısıt": "active restrictions",
  "Canlı risk filtresi": "Live risk filter",
  "{pending} bekleyen, {critical} kritik karar": "{pending} pending, {critical} critical decisions",
  "Denetim ritmi": "Audit cadence",
  "Her geçiş kararı kullanıcı, sebep, saat ve belge referansıyla kayıt altında tutulur.": "Every access decision is logged with user, reason, time and document reference.",
  "Erişim & Uyum": "Access & Compliance",
  "Mobil kod, kart, plaka, QR, borç kısıtı, depozito kontrolü ve güvenlik olaylarını tek karar motorunda izleyin.": "Track mobile code, card, license plate, QR, debt restriction, deposit check and security events in one decision engine.",
  "Takipteki kayıt": "Records under monitoring",
  "Kısıtlı": "Restricted",
  "Bekleyen": "Pending",
  "Kritik risk": "Critical risk",
  "Erişim bölgesi yoğunluğu": "Access zone density",
  "{count} bölge": "{count} zones",
  "Kapı karar motoru": "Door decision engine",
  "Borç, rezervasyon, depozito ve kimlik kontrolü tamamlanmadan geçici erişim açılmaz.": "Temporary access is not granted until debt, reservation, deposit and identity checks are complete.",
  "Plaka ve otopark": "License plate and parking",
  "Otopark, misafir ve sakin erişimleri aynı uyum kayıtlarına bağlanır.": "Parking, guest and resident access are all linked to the same compliance records.",
  "Her erişim kararı kullanıcı, sebep, saat ve belge referansıyla denetlenebilir tutulur.": "Every access decision is kept auditable with user, reason, time and document reference.",
  "Oturum, vatandaşlık ve alıcı uygunluk ön kontrolü": "Residency, citizenship and buyer eligibility pre-check",
  "Satış ekibi uygunluk ön kontrolünü görür; sistem hukuki garanti vermez ve riskli durumları partner incelemesine gönderir.": "The sales team sees the eligibility pre-check; the system gives no legal guarantee and forwards risky cases to partner review.",
  "{count} inceleme kuyruğu": "{count} in review queue",
  "Alıcı dosyası": "Buyer file",
  "Ön uygun": "Pre-approved",
  "Ekspertiz gerekli": "Appraisal required",
  "Bütçe": "Budget",
  "Bölge": "Zone",
  "Ekspertiz": "Appraisal",
  "Gerekli": "Required",
  "Gerekmez": "Not required",
  "Sakin": "Resident",
  "Risk": "Risk",
  "Sebep": "Reason",
  "İnceleme": "Review",
  "Planlı": "Scheduled",
  "Var": "Yes",
  "Yok": "No",
  "Bildirim kuralları": "Notification rules",
  "Borç, SLA, check-in, check-out ve belge eksikliği için rol bazlı uyarılar.": "Role-based alerts for debt, SLA, check-in, check-out and missing documents.",
  "Güvenlik politikası": "Security policy",
  "Rol bazlı erişim, hassas finans işlemleri ve insan onaylı AI kararları.": "Role-based access, sensitive finance transactions and human-approved AI decisions.",
  "Dil ve yerelleştirme": "Language and localization",
  "Türkçe ana kullanım, çok dilli sakin desteği ve resmi ton standardı.": "Turkish as the primary language, multilingual resident support and a formal tone standard.",
  "Platform Yönetim Merkezi": "Platform Management Center",
  "Rol yetki kapsamı, denetim izi, güvenlik kontrolleri ve kullanıcı görünürlüğü tek yönetim alanında takip edilir.": "Role permission scope, audit trail, security checks and user visibility are all tracked in one management area.",
  "Yüksek risk denetim": "High-risk audit",
  "Güvenlik ve platform kontrolleri": "Security and platform controls",
  "Her kontrolün sahibi, amacı ve canlı durumu yönetim için görünür.": "Every control's owner, purpose and live status is visible to management.",
  "Operasyon ayarları": "Operations settings",
  "Yönetici, finans, güvenlik ve saha ekipleri aynı kontrol merkezinden standart kuralları görür.": "Management, finance, security and field teams see standard rules from the same control center.",
  "Görünüm": "Appearance",
  "Açık/koyu tema desteği.": "Light/dark theme support.",
  "Rol": "Role",
  "Kullanıcı": "User",
  "Finans onayı": "Finance approval",
  "Erişim kısıtı": "Access restriction",
  "Dışa aktarım": "Export",
  "Denetim": "Audit",
  "Aktör": "Actor",
  "Platform sürümü:": "Platform version:",
  "Doğrulandı": "Verified",
  "Bekliyor": "Pending",
  "Eksik": "Missing",
  "Süresi doldu": "Expired",
  "Reddedildi": "Rejected",
  "Yetkili dairenize bağlı sözleşme, kimlik, depozito, servis ve uyum belgelerini güvenli portal görünümünde takip edin.": "Track the contracts, identity, deposit, service and compliance documents tied to your authorized unit in a secure portal view.",
  "Saha operasyonu için yalnızca görev dosyaları, servis kanıtları ve gerekli onay kayıtları gösterilir.": "For field operations, only task files, service evidence and required approval records are shown.",
  "satış ve after-sales süreci için TAPU, kimlik, sözleşme, ödeme, depozito, servis, uyum ve proje belgelerini güvenli, denetlenebilir ve işlem bağlantılı yönetin.": "manages TAPU, identity, contract, payment, deposit, service, compliance and project documents for the sales and after-sales process in a secure, auditable and transaction-linked way.",
  "TAPU & Belge Kasası": "TAPU & Document Vault",
  "Belge yükle": "Upload document",
  "Toplam belge": "Total documents",
  "Eksik/Süre doldu": "Missing/Expired",
  "Satış dosyası, TAPU, KYC ve EIDS kontrolü": "Sales file, TAPU, KYC and EIDS check",
  "Satış dosyası; alıcı kimliği, TAPU, EIDS, rezervasyon, satış sözleşmesi ve ödeme planı olmadan sonraki adıma geçmez.": "A sales file cannot move to the next step without buyer identity, TAPU, EIDS, reservation, sales contract and payment plan.",
  "{count} yüksek risk": "{count} high risk",
  "Satış belgesi": "Sales document",
  "Belge tipi": "Document type",
  "Belge": "Document",
  "Kapsam": "Scope",
  "Dosya": "File",
  "Kategori": "Category",
  "İşlem": "Action",
  "Belgeyi görüntüle": "View document",
  "Belgeyi indir": "Download document",
  "Kiracı": "Tenant",
  "Misafir": "Guest",
  "Müşteri & Malik CRM": "Customer & Owner CRM",
  "için alıcı, malik, kiracı ve misafirleri; dil, WhatsApp/telefon tercihi, borç, servis, erişim ve yatırım ilgisiyle tek kayıt altında yönetin.": "manages buyers, owners, tenants and guests in a single record, with language, WhatsApp/phone preference, debt, service, access and investment interest.",
  "Aktif sakin": "Active residents",
  "Riskli kayıt": "At-risk records",
  "WhatsApp tercih": "WhatsApp preferred",
  "Çok dilli destek": "Multilingual support",
  "AI iletişim önceliği": "AI communication priority",
  "aksiyon": "actions",
  "servis": "service tickets",
  "İletişim merkezi": "Communication center",
  "WhatsApp, telefon, e-posta ve portal bildirimleri tek sakin profiline bağlanır.": "WhatsApp, phone, email and portal notifications are all linked to a single resident profile.",
  "Borç + servis bağlamı": "Debt + service context",
  "Sakin temsilcisi aramadan önce açık borç, erişim kısıtı ve servis geçmişini görür.": "The resident's rep sees outstanding debt, access restrictions and service history before making the call.",
  "Ad": "Name",
  "Tip": "Type",
  "Dil": "Language",
  "Telefon": "Phone",
  "Kapalı": "Closed",
  "AI Rapor Merkezi": "AI Report Center",
  "Yönetim kurulu, muhasebe, operasyon, güvenlik ve misafir ekipleri için hazır rapor görünümleri ve karar özetleri.": "Ready report views and decision summaries for the management board, accounting, operations, security and guest teams.",
  "Rapor seti": "Report set",
  "AI kontrol": "AI control",
  "Tahsilat trendi": "Collection trend",
  "Daire dağılımı": "Unit distribution",
  "Yönetim kuruluna uygun tek bakışlık portföy özeti.": "Board-ready, single-glance portfolio summary.",
  "{bucket} gün borç": "{bucket}-day debt",
  "AI aksiyon listesinde önceliklendirilir.": "Prioritized in the AI action list.",
  "Rapor": "Report",
  "Başlık": "Title",
  "Periyot": "Period",
  "Metrik": "Metric",
  "AI içgörü": "AI insight",
  "Dışa aktar": "Export",
  "Raporu dışa aktar": "Export report",
  "Kullanıcılar & Roller": "Users & Roles",
  "Malik, kiracı, misafir ve personel kayıtları; dil, görev yükü ve yetki kapsamı tek yönetim alanında izlenir.": "Owner, tenant, guest and staff records - language, workload and permission scope tracked in one management area.",
  "Personel": "Staff",
  "Sakin kaydı": "Residents",
  "Aktif görev": "Active task",
  "Finans onaycı": "Finance approver",
  "Personel operasyon kapsamı": "Staff operations scope",
  "Her ekip üyesinin rolü, saha yükü, onay limiti ve erişim kapsamı yönetim için görünürdür.": "Every team member's role, field workload, approval limit and access scope is visible to management.",
  "Görev": "Task",
  "Limit": "Limit",
  "Yetki prensibi": "Authorization principle",
  "Kullanıcı sadece kendi görevi için gerekli modülleri görür. Finans, erişim ve kullanıcı yönetimi ayrı onay kapsamındadır.": "A user only sees the modules required for their own role. Finance, access and user management remain under separate approval scopes.",
  "Riskli": "At risk",
  "Ekip": "Team",
  "Export": "Export",
  "Yönetim": "Management",
  "Muhasebe": "Accounting",
  "Eğitim": "Training",
  "Tüm site": "Entire site",
  "Operasyon": "Operations",
  "Sadece finans": "Finance only",
  "Saha": "Field",
  "Bu sayfa rolünüz için kapalı": "This page is not available for your role",
  "Yetki modeli güvenlik nedeniyle varsayılan olarak erişimi reddeder. Sizin rolünüz için açık olan panele yönlendiriliyorsunuz.": "For security reasons, the permission model denies access by default. You are being redirected to the panel available for your role.",
  "Finans defteri": "Finance ledger",
  "Aidat, ödeme, depozito, ceza ve düzeltme kayıtları değiştirilemez defter mantığıyla takip edilir. Hassas finans aksiyonları onay ve denetim akışına alınır.": "Dues, payment, deposit, penalty and correction records are tracked with immutable-ledger logic. Sensitive finance actions go through an approval and audit workflow.",
  "Son güncelleme:": "Last updated:",
  "Defteri yenile": "Refresh ledger",
  "Finans defteri dışa aktarım isteği oluştur": "Create finance ledger export request",
  "Dışa aktarım isteği alındı": "Export request received",
  "Finans defteri dışa aktarım isteği": "Finance ledger export request",
  "Finans defteri şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "The finance ledger could not be retrieved right now. Retry with the refresh button or check the API status.",
  "Finans defteri kalite kontrolü dikkat istiyor:": "Finance ledger quality check needs attention:",
  "Açık bakiye": "Open balance",
  "Bu ay tahsilat": "Collections this month",
  "Açık kayıt": "Open record",
  "Son finans kayıtları": "Latest finance records",
  "vade": "due date",
  "Finans kaydı bulunamadı.": "No finance record found.",
  "Finans kontrol modeli": "Finance control model",
  "Onaylanmış finans kaydı doğrudan değiştirilmez; düzeltme için karşı kayıt açılır. Dışa aktarım, mutabakat ve ödeme aksiyonları role göre denetim akışına alınır.": "An approved finance record is never edited directly; a counter-entry is opened for corrections. Export, reconciliation and payment actions are routed through role-based audit workflows.",
  "Onaylı kayıt": "Approved record",
  "Yasal risk": "Legal risk",
  "Ödendi": "Paid",
  "Açık": "Open",
  "Kısmi": "Partial",
  "İptal": "Cancelled",
  "Bilinmiyor": "Unknown",
  "Daire yok": "No unit",
  "Kişi yok": "No contact",
  "Blokaj yok": "No hold",
  "Rezervasyon sözleşmesi eksik": "Reservation contract missing",
  "İkinci taksit doğrulanmadı": "Second installment not verified",
  "Ödeme planı imzası bekliyor": "Payment plan signature pending",
  "Blokede": "On hold",
  "Rezerve": "Reserved",
  "İade hazır": "Refund ready",
  "İade edildi": "Refunded",
  "Kesinti bekliyor": "Deduction pending",
  "Kesildi": "Deducted",
  "Tahsil edildi": "Collected",
  "Hatalı": "Faulty",
  "İade": "Refund",
  "Banka transferi": "Bank transfer",
  "Manuel banka": "Manual bank",
  "tamamlandı": "completed",
  "Checkout": "Checkout",
  "gün": "days",
  "Riskli plan": "At-risk plan",
  "Depozito kuyruğu": "Deposit queue",
  "Kısıt kararı": "Restriction decision",
  "Mutabakat": "Reconciliation",
  "Onay kuyruğu": "Approval queue",
  "Ödeme, depozito ve kısıt kontrol merkezi": "Payment, deposit and restriction control center",
  "Satış ödeme planı, depozito iadesi, banka mutabakatı ve borca bağlı erişim kısıtı aynı onay kuyruğunda izlenir. Sistem karar önerir; finans ve erişim aksiyonları insan onayıyla kapanır.": "Sales payment plans, deposit refunds, bank reconciliation and debt-based access restrictions are tracked in the same approval queue. The system proposes a decision; finance and access actions are closed out with human approval.",
  "Kontrolleri yenile": "Refresh checks",
  "Mutabakat inceleme isteği oluştur": "Create reconciliation review request",
  "İnceleme isteği alındı": "Review request received",
  "Phase 7 mutabakat inceleme isteği": "Phase 7 reconciliation review request",
  "İnceleme aç": "Open review",
  "Ödeme kontrol verisi şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Payment control data could not be retrieved right now. Retry with the refresh button or check the API status.",
  "Kalite kontrolü dikkat istiyor:": "Quality check needs attention:",
  "Ödeme planı ve depozito işi": "Payment plan and deposit item",
  "Açık vade": "Open due date",
  "Açık ödeme veya depozito işi bulunamadı.": "No open payment or deposit item found.",
  "Kısıt ve mutabakat kuyruğu": "Restriction and reconciliation queue",
  "depozito": "deposit",
  "Kısıt veya mutabakat kuyruğu boş.": "Restriction or reconciliation queue is empty.",
  "Iade emrini finans onay kuyruguna al": "Route the refund order into the finance approval queue",
  "Erisim kodunu depozito ve borc kontrolu kapanana kadar acma": "Do not activate the access code until deposit and debt checks are cleared",
  "Temizlik blokajini operasyonla eslestir": "Match the cleaning hold with operations",
  "Yasal takip ve erişim kısıtı": "Legal follow-up and access restriction",
  "Telefon + WhatsApp tahsilat": "Phone + WhatsApp collections",
  "Otomatik hatırlatma": "Automatic reminder",
  "Aile": "Family",
  "Yetkili": "Authorized",
  "telefon yok": "no phone",
  "Daire bağlantısı yok": "No unit link",
  "Kişi ve rol dizini": "Contact and role directory",
  "Personel, malik, kiracı, misafir ve rol kapsamı tek dizinden yönetilir. Ekip yükü, erişim kapsamı ve riskli kayıtlar aynı ekranda takip edilir.": "Staff, owners, tenants, guests and role scopes are managed from a single directory. Team workload, access scope and at-risk records are tracked on the same screen.",
  "Son güncelleme: {lastUpdated}": "Last updated: {lastUpdated}",
  "Kişi verisini yenile": "Refresh contact data",
  "Kişi dizini dışa aktarım isteği oluştur": "Create contact directory export request",
  "Kişi dizini dışa aktarım isteği": "Contact directory export request",
  "Kişi dizini şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "The contact directory could not be retrieved right now. Retry with the refresh button or check the API status.",
  "Kişi dizini kalite kontrolü dikkat istiyor: {checks}": "Contact directory quality check needs attention: {checks}",
  "Malik / Kiracı": "Owner / Tenant",
  "Personel iş yükü": "Staff workload",
  "Sakin bağlantıları": "Resident links",
  "Risk {riskScore}": "Risk {riskScore}",
  "Rol kapsamı": "Role scope",
  "Rol matrisi kullanıcı görünürlüğü, finans onayı, erişim kısıtı ve dışa aktarım yetkisini ayrı ayrı tutar.": "The role matrix keeps user visibility, finance approval, access restriction and export authorization separate.",
  "Onaycı": "Approver",
  "Site operations risk map": "Site operations risk map",
  "Operasyon risk haritası": "Operations risk map",
  "Blok, borç, servis ve erişim risk haritası": "Block, debt, service and access risk map",
  "8 blok ve 769 daire; borç, servis, erişim ve SLA riskleri tek operasyon görünümünde okunur.": "8 blocks and 769 units - debt, service, access and SLA risks read from a single operations view.",
  "kısıt": "restriction",
  "borç": "debt",
  "3D blok risk haritasını daire matrisinde aç": "Open the 3D block risk map in the unit matrix",
  "Tahsilat rotası": "Collections route",
  "90+ gün, aktif rezervasyon ve erişim kısıtı birlikte skorlanır.": "90+ day debt, active reservations and access restrictions are scored together.",
  "SLA alarmı": "SLA alarm",
  "{count} iş": "{count} jobs",
  "Teknik rota ödeme onayı ve öncelik riskine göre sıralanır.": "The technical route is ordered by payment approval status and priority risk.",
  "Erişim motoru": "Access engine",
  "{count} kısıt": "{count} restrictions",
  "Mobil kod, kart ve plaka kararları tek güvenlik modelinden geçer.": "Mobile code, card and license-plate decisions all run through a single security model.",
  "AI nabız": "AI pulse",
  "{count} risk": "{count} risks",
  "Her risk aksiyona çevrilir: ara, kısıtla, servis ata, belge iste.": "Every risk is converted into an action: call, restrict, assign a service ticket, request a document.",
  "{label} detayını aç": "Open {label} details",
  "operasyon kaydı": "operations recorded",
  "portföy akışı": "portfolio units managed",
  "tamamlanan işlem": "completed transactions",
  "rol bazlı ekip": "role-based team members",
  "Emlak satışını, site yönetimini ve servis operasyonunu tek çalışma alanında yönetin.": "Manage property sales, site management, and service operations in a single workspace.",
  "1Çatı; CRM, portföy, finans, servis, belge, uyumluluk ve malik raporlamasını Türkiye emlak pazarı için tasarlanmış rol bazlı bir ERP deneyiminde birleştirir.": "1Cati brings together CRM, portfolio, finance, service, documents, compliance, and owner reporting in a role-based ERP experience built for the Turkish real estate market.",
  "Çalışma alanına gir": "Enter workspace",
  "Ürün akışını incele": "Review product flow",
  "Operasyon modeli": "Operating model",
  "Tek kayıt, net yetki, hızlı aksiyon.": "One record, clear authority, fast action.",
  "Ekipler arası kopukluk yerine, her işlem daire, kişi, belge, ödeme ve görev ilişkisiyle görünür hale gelir.": "Instead of gaps between teams, every transaction becomes visible through its links to the unit, person, document, payment, and task.",
  "Portföy ve daire kontrolü": "Portfolio and unit control",
  "Blok, kat, daire, malik, sakin, borç, servis ve erişim durumu tek kayıt üzerinden filtrelenir.": "Block, floor, unit, owner, resident, debt, service, and access status are all filtered from a single record.",
  "CRM ve rol bazlı çalışma": "CRM and role-based operation",
  "Satış, muhasebe, saha, güvenlik, malik ve kiracı ekranları aynı veriye kendi yetki kapsamıyla erişir.": "Sales, accounting, field, security, owner, and tenant screens access the same data, each within its own permission scope.",
  "Uyumluluk ve denetim": "Compliance and audit",
  "EİDS, TAPU, belge, ödeme, erişim ve hassas aksiyonlar izlenebilir karar kayıtlarıyla yönetilir.": "EIDS, TAPU, documents, payments, access, and sensitive actions are managed with traceable decision records.",
  "Temel ERP modülleri": "Core ERP modules",
  "CRM, lead ve iletişim merkezi": "CRM, lead, and communication center",
  "Daire matrisi ve portföy yönetimi": "Unit matrix and portfolio management",
  "Servis, saha görevleri ve SLA takibi": "Service, field tasks, and SLA tracking",
  "Finans defteri, aidat ve tahsilat": "Finance ledger, dues, and collections",
  "Belge kasası, TAPU, KYC ve EİDS kontrolleri": "Document vault, TAPU, KYC, and EIDS checks",
  "Malik, kiracı, personel ve rol matrisi": "Owner, tenant, staff, and role matrix",
  "Entegrasyon ve otomasyon katmanı": "Integration and automation layer",
  "Sağlayıcı kararı bekleyen yol haritası; üretimde henüz aktif değildir.": "Roadmap pending provider decisions; not yet active in production.",
  "E-posta, SMS, WhatsApp/Telegram ve bildirim sağlayıcıları": "Email, SMS, WhatsApp/Telegram, and notification providers",
  "Ödeme, banka mutabakatı ve dijital bakiye yükleme akışları": "Payment, bank reconciliation, and digital balance top-up flows",
  "Erişim kontrolü, plaka/kart/bariyer ve sayaç entegrasyonları": "Access control, plate/card/barrier, and meter integrations",
  "AI brifing, risk sıralama, kaynaklı yanıtlar ve insan onaylı aksiyonlar": "AI briefing, risk ranking, sourced answers, and human-approved actions",
  "Kalite standardı": "Quality standard",
  "Üretim sistemi gibi tasarlanır, kontrol sistemi gibi işletilir.": "Designed like a production system, operated like a control system.",
  "Güvenilir": "Reliable",
  "TypeScript, üretim build'i, tarayıcı kontrolleri ve rol bazlı testler release öncesi çalıştırılır.": "TypeScript, production build, browser checks, and role-based tests are run before every release.",
  "İzlenebilir": "Traceable",
  "Finans, erişim, belge ve veri değişiklikleri aktör, zaman, modül ve gerekçe ile kaydedilir.": "Finance, access, document, and data changes are logged with actor, timestamp, module, and reason.",
  "Ölçeklenebilir": "Scalable",
  "769 birimlik operasyon verisi, çok dilli ekipler ve büyüyen portföy için modüler yapı kullanılır.": "A modular structure supports operational data for 769 units, multilingual teams, and a growing portfolio.",
  "Asansör kapısı arızası": "Elevator door fault",
  "Daire içi su kaçağı": "In-unit water leak",
  "Klima drenaj kontrolü": "AC drainage check",
  "Aidat borcu nedeniyle hizmet bekliyor": "On hold pending service due to dues arrears",
  "Ortak alan kamera kontrolü": "Common area camera check",
  "Check-out sonrası hasar raporu": "Post-checkout damage report",
  "Elektrik pano bakımı": "Electrical panel maintenance",
  "Temizlik ekibi yönlendirme": "Cleaning crew dispatch",
  "Havuz teknik ölçüm": "Pool technical measurement",
  "Kapı giriş kartı yenileme": "Entry card renewal",
  "Yangın sensörü testi": "Fire sensor test",
  "Balkon camı hasar tespiti": "Balcony glass damage assessment",
  "Otopark bariyer erişimi": "Parking barrier access",
  "Legal takip öncesi son bildirim": "Final notice before legal collection",
  "Tesisat": "Plumbing",
  "İklimlendirme": "HVAC",
  "Güvenlik": "Security",
  "Elektrik": "Electrical",
  "Ortak alan": "Common area",
  "Hasar": "Damage",
  "Tahsilat": "Collections",
  "Antalya havalimani transferi": "Antalya airport transfer",
  "Spa, fitness ve ortak alan rezervasyonu": "Spa, fitness, and common area booking",
  "Kart, QR ve plaka erisim islemi": "Card, QR, and plate access processing",
  "Hasar tespiti ve depozito raporu": "Damage assessment and deposit report",
  "Yeni kart/QR, plaka tanimi, kayip kart iptali ve erisim log kontrolu.": "New card/QR issuance, plate registration, lost card cancellation, and access log review.",
  "Checkout, bakim veya sikayet sonrasi fotograf/video kanitli hasar raporu.": "Photo/video-documented damage report after checkout, maintenance, or complaint.",
  "Kat hizmetleri": "Housekeeping",
  "Rezervasyon": "Reservation",
  "Sakin destek": "Resident support",
  "Asansor": "Elevator",
  "Iklimlendirme": "HVAC",
  "Finans onayi": "Finance approval",
  "Erisim": "Access",
  "Odeme linki veya cari hesaba borclandirma secimini onayla": "Confirm payment link or charge-to-account option",
  "Malik/kiraci memnuniyet ve kapanis onayini al": "Obtain owner/tenant satisfaction and closure approval",
  "Arsiv ve rapor kontrolu": "Archive and report review",
  "Parca/islem notunu gir": "Enter parts/work note",
  "Kapanis kaniti yukle": "Upload closure proof",
  "Kimlik/yetki kontrolu": "Identity/authorization check",
  "Kart/QR/plaka islem kaydi": "Card/QR/plate transaction record",
  "Access log kontrolu": "Access log review",
  "Kapanis onayi": "Closure approval",
  "Temizlik checklist": "Cleaning checklist",
  "Teslim notu": "Handover note",
  "Depozito etkisini not et": "Note deposit impact",
  "Kapanis raporu": "Closure report",
  "Tamamlandi onayi": "Completion confirmation",
  "Yetki kapsamını dogrula": "Verify authorization scope",
  "Randevu uygunlugunu kontrol et": "Check appointment availability",
  "Bildirim gonder": "Send notification",
  "Geri bildirim al": "Collect feedback",
  "Hemen": "Immediately",
  "Sabah": "Morning",
  "Ogle": "Midday",
  "Aksam": "Evening",
  "Finans onayi bekleniyor; saha aksiyonu kilitli.": "Awaiting finance approval; field action is locked.",
  "SLA asimi var; ekip lideri eskalasyonu gerekli.": "SLA breached; team lead escalation required.",
  "Atama ve kanit akisi hazir.": "Assignment and proof flow ready.",
  "Ana Kapı": "Main Gate",
  "Depo": "Storage",
  "Mobil Kod": "Mobile Code",
  "Kart": "Card",
  "Plaka": "License Plate",
  "QR": "QR",
  "Aidat borcu veya depozito kontrolü": "Dues arrears or deposit check",
  "Giriş ön kontrolü bekliyor": "Awaiting entry pre-check",
  "Bakım veya güvenlik kapaması": "Maintenance or security lockout",
  "Normal kullanım": "Normal use",
  "Sözleşme": "Contract",
  "Aidat": "Dues",
  "Uyum": "Compliance",
  "Kaynak: {path}": "Source: {path}",
  "OCR / insan onayı gerekli: {path}": "OCR / human review required: {path}",
  "Yönetim Kurulu Operasyon Özeti": "Board Operations Summary",
  "Aidat Tahsilat ve Yaşlandırma": "Dues Collection and Aging",
  "Servis SLA ve Maliyet Kontrolü": "Service SLA and Cost Control",
  "Rezervasyon, Depozito ve Hasar": "Booking, Deposit and Damage",
  "Erişim Güvenliği ve Uyum": "Access Security and Compliance",
  "Haftalık": "Weekly",
  "Günlük": "Daily",
  "Anlık": "Real-time",
  "Müdür": "Manager",
  "Misafir Operasyonu": "Guest Operations",
  "769 daire / %70 doluluk": "769 units / 70% occupancy",
  "1.4M ₺ açık borç": "1.4M ₺ outstanding debt",
  "4 SLA dışı servis": "4 services out of SLA",
  "2 kritik check-out": "2 critical check-outs",
  "33 kısıtlı erişim": "33 restricted access",
  "Borç ve servis SLA riski aynı raporda izlenmeli.": "Debt and service SLA risk must be tracked in the same report.",
  "90+ gün borçlu 19 hesap erişim kısıtıyla takip edilmeli.": "19 accounts overdue 90+ days must be tracked with access restriction.",
  "Borç blokeli servisler finans onayı olmadan sahaya düşmemeli.": "Debt-blocked services must not go to the field without finance approval.",
  "Depozito kesintisi fotoğraf kanıtı ile kapatılmalı.": "Deposit deductions must be closed out with photo evidence.",
  "Mobil kod, kart ve plaka erişimi aynı karar motorundan yönetilmeli.": "Mobile code, card and plate access must be managed from the same decision engine.",
  "23 daire için otomatik borç hatırlatma kuyruğu hazırlandı.": "An automatic debt reminder queue has been prepared for 23 units.",
  "Bugünkü 2 check-out için depozito hasar kontrolü açıldı.": "Deposit damage inspections have been opened for today's 2 check-outs.",
  "Acil asansör talebi teknisyene atandı ve SLA sayacı başladı.": "The urgent elevator request has been assigned to a technician and the SLA clock has started.",
  "Haziran tahsilat riski yüksek 37 hesap için öncelik skoru üretildi.": "A priority score has been generated for the 37 high collection-risk accounts in June.",
  "Tahsilat önceliği": "Collection priority",
  "Servis darboğazı": "Service bottleneck",
  "Check-out kontrolü": "Check-out inspection",
  "37 hesapta gecikme riski yüksek. AI, önce 90+ gün ve aktif rezervasyonu olan daireleri öneriyor.": "37 accounts show high delinquency risk. AI recommends prioritizing units with 90+ days overdue and an active booking.",
  "3 talep SLA dışına çıktı. Borç blokeli talepler finans onayı olmadan sahaya gönderilmemeli.": "3 tickets have breached SLA. Debt-blocked tickets must not be dispatched to the field without finance approval.",
  "2 check-out bugün kapanıyor. Depozito kesintisi ve temizlik kanıtı aynı akışta tamamlanmalı.": "2 check-outs are closing today. Deposit deduction and cleaning evidence must be completed in the same workflow.",
  "Kas": "Nov",
  "Oca": "Jan",
  "Şub": "Feb",
  "Mar": "Mar",
  "Nis": "Apr",
  "May": "May",
  "Haz": "Jun",
  "Ağu": "Aug",
  "Eyl": "Sep",
  "Eki": "Oct",
  "Ara": "Dec",
  "Yetkili kiracı kaydı": "Authorized tenant record",
  "Yetkili malik kaydı": "Authorized owner record",
  "Operasyon görev dosyası": "Operations task file",
  "Portalda görüntülenebilir": "Visible in portal",
  "Yönetim onayı bekliyor": "Pending management approval",
  "Checkout tamamlanana kadar depozitoyu bloke tut": "Hold deposit blocked until check-out is completed",
  "Depozito ve erisim kararini finans onayina bagla": "Tie deposit and access decisions to finance approval",
  "Erisim kisitini hukuk ve finans onayiyla surdur": "Maintain access restriction with legal and finance approval",
  "Tahsilat hatirlatmasi ve onayli kisit kontrolu ac": "Enable collection reminder and approved restriction check",
  "Taksit doğrulanmadı": "Installment not verified",
  "Keşif, kapsam kilidi ve pazar kıyası": "Discovery, scope lock and market comparison",
  "UX/UI tasarım sistemi ve ürün navigasyonu": "UX/UI design system and product navigation",
  "Platform temeli, auth, RBAC ve audit": "Platform foundation, auth, RBAC and audit",
  "Site, blok, kat, daire ve veri importu": "Site, block, floor, unit and data import",
  "Kullanıcı, malik, kiracı ve personel yönetimi": "User, owner, tenant and staff management",
  "Finans ledger motoru": "Finance ledger engine",
  "Ödeme, depozito, mutabakat ve borç kısıtı": "Payment, deposit, reconciliation and debt restriction",
  "Servis kataloğu ve servis siparişi akışı": "Service catalog and service order workflow",
  "Görev, saha ekibi, SLA ve medya raporu": "Task, field team, SLA and media report",
  "Rezervasyon, kiralama, move-in ve checkout": "Booking, leasing, move-in and check-out",
  "İletişim, bildirim ve doküman merkezi": "Communication, notification and document center",
  "Mobil PWA ve kurulabilir kullanıcı deneyimi": "Mobile PWA and installable user experience",
  "Dış sistem entegrasyonları": "External system integrations",
  "AI premium katmanı ve gelişmiş analitik": "AI premium layer and advanced analytics",
  "QA, güvenlik, performans, kabul testi ve canlıya geçiş": "QA, security, performance, acceptance testing and go-live",
  "769 dairelik site, roller, finans, servis, rezervasyon, erişim ve raporlama kapsamı tek ERP hedefinde netleşir.": "The 769-unit site's scope for roles, finance, service, booking, access and reporting is defined under a single ERP target.",
  "Yönetici, muhasebe, saha ekibi, sakin ve destek rolleri kendi işlerine uygun, sade ve erişilebilir arayüzden ilerler.": "Manager, accounting, field team, resident and support roles work through a simple, accessible interface suited to their own tasks.",
  "Oturum, rol, izin, RLS ve denetim izi bütün hassas işlemler için gerçek kontrol zemini sağlar.": "Session, role, permission, RLS and audit trail provide a real control layer for all sensitive operations.",
  "769 daire blok, kat, durum, borç ve erişim ilişkisiyle filtrelenebilir; import kalite kapısı yönetilir.": "769 units can be filtered by block, floor, status, debt and access relationship; the import quality gate is managed.",
  "Her kişi doğru daire, hesap, belge, iletişim dili ve yetki kapsamıyla tek kayıtta yönetilir.": "Each person is managed in a single record with the correct unit, account, document, communication language and authorization scope.",
  "Bakiyeler ekran hesabından değil, hesap, borç/alacak, tahakkuk, düzeltme ve ekstre kayıtlarından hesaplanır.": "Balances are calculated from account, debit/credit, accrual, adjustment and statement records, not from on-screen calculations.",
  "Ödeme, depozito, iade, borç eşiği ve servis/erişim kısıtları muhasebe ve hukuk onayıyla yürür.": "Payment, deposit, refund, debt threshold and service/access restrictions operate with accounting and legal approval.",
  "Temizlik, transfer, bakım ve özel hizmetler fiyat, SLA, borç kontrolü ve görev üretimiyle siparişe dönüşür.": "Cleaning, transfer, maintenance and special services convert to orders with price, SLA, debt check and task generation.",
  "Saha işleri atama, öncelik, SLA, foto/video kanıt, iptal ve yönetici onayıyla görünür olur.": "Field work becomes visible through assignment, priority, SLA, photo/video evidence, cancellation and manager approval.",
  "Müsaitlik, rezervasyon, depozito, giriş hazırlığı, checkout, kesinti ve erişim kapatma tek süreç olur.": "Availability, booking, deposit, move-in preparation, check-out, deduction and access closure become a single process.",
  "Sakin, malik, yönetici ve personel iletişimi daire, borç, görev, rezervasyon ve belgeyle ilişkilendirilir.": "Resident, owner, manager and staff communication is linked to the unit, debt, task, booking and document.",
  "Sakin, personel ve yönetici ana işleri telefondan hızlı, erişilebilir ve kurulabilir PWA olarak yapılır.": "Core tasks for residents, staff and managers are handled from the phone via a fast, accessible, installable PWA.",
  "Banka/ödeme, SMS/e-posta, erişim kartı/bariyer, sayaç ve kimlik sistemleri test modu ve retry kuyruğuyla bağlanır.": "Bank/payment, SMS/email, access card/barrier, meter and identity systems connect via test mode and a retry queue.",
  "AI günlük brifing, borç riski, servis triage, anomali, doğal dil arama ve rapor taslağı üretir; hassas işlem yapmaz.": "AI generates the daily briefing, debt risk, service triage, anomaly detection, natural-language search and report drafts; it does not perform sensitive operations.",
  "Üretim canlıya geçmeden önce güvenlik, performans, yedekleme, eğitim, kabul testi ve destek kanıtı tamamlanır.": "Before production go-live, security, performance, backup, training, acceptance testing and support evidence are completed.",
  "Yönetim özeti ve dokümantasyon merkezinden kapsam, risk ve karar kayıtlarını kontrol edin.": "Check scope, risk and decision records from the management summary and documentation center.",
  "Sol menüden rolünüze açık modülü seçin; üst kartlarda kritik sayılar, altta detay tabloları, arama ve aksiyonlar kullanılır.": "Select the module available to your role from the left menu; top cards show critical figures, with detail tables, search and actions below.",
  "Ayarlar ekranında güvenlik kontrollerini, rol yetkilerini ve son audit olaylarını inceleyin.": "Review security controls, role permissions and recent audit events on the Settings screen.",
  "Daire Matrisi ekranında blok özetini, canlı matrisi, import doğrulamasını ve detay tablosunu kullanın.": "Use the block summary, live matrix, import validation and detail table on the Unit Matrix screen.",
  "Kullanıcılar ekranında sakin, malik, kiracı, personel ve rol ilişkilerini kontrol edin.": "Check resident, owner, tenant, staff and role relationships on the Users screen.",
  "Finans ekranında aidat, borç, tahsilat, gecikme ve ekstre hareketlerini ledger mantığıyla inceleyin.": "Review dues, debt, collection, delinquency and statement transactions with ledger logic on the Finance screen.",
  "Finans ve Uyum ekranlarında gecikme, depozito, kısıt ve onay kuyruğunu takip edin.": "Track delinquency, deposits, restrictions and the approval queue on the Finance and Compliance screens.",
  "Servis Talepleri ekranında katalog, borç kontrolü, görev üretimi ve durum takibini yönetin.": "Manage the catalog, debt check, task generation and status tracking on the Service Requests screen.",
  "Servis Talepleri ekranında görev panosu, SLA riski ve saha raporlarını yönetin.": "Manage the task board, SLA risk and field reports on the Service Requests screen.",
  "Rezervasyon ekranında takvim, giriş/çıkış işleri, depozito ve final kontrol adımlarını takip edin.": "Track the calendar, check-in/check-out tasks, deposit and final inspection steps on the Booking screen.",
  "İletişim ve Belgeler ekranlarında konuşma, duyuru, bildirim ve dosya izinlerini yönetin.": "Manage conversations, announcements, notifications and file permissions on the Communication and Documents screens.",
  "Mobil görünümde bakiye, servis, görev, belge, sohbet ve bildirim akışlarını test edin.": "Test balance, service, task, document, chat and notification flows in the mobile view.",
  "Ayarlar ekranında entegrasyon durumu, son hata, manuel retry ve bağlantı loglarını takip edin.": "Track integration status, last error, manual retry and connection logs on the Settings screen.",
  "AI Rapor Merkezi'nde önerileri kaynak, güven ve insan onayıyla inceleyin.": "Review recommendations in the AI Report Center with source, confidence and human approval.",
  "Raporlar ve dokümantasyon üzerinden test, kabul, eğitim ve canlıya geçiş checklist durumunu yönetin.": "Manage the testing, acceptance, training and go-live checklist status through reports and documentation.",
  "İhtiyaç haritası": "Requirements map",
  "ERP modül planı": "ERP module plan",
  "Pazar kıyası": "Market comparison",
  "Karar kaydı": "Decision record",
  "Güvenli oturum temeli": "Secure session foundation",
  "Rol bazlı navigasyon": "Role-based navigation",
  "Denetimli aksiyon servisi": "Audited action service",
  "Korumalı ekranlar": "Protected screens",
  "Veri kontrol ve uygulama isteği": "Data validation and apply request",
  "Anlık yenileme": "Real-time refresh",
  "Kişi dizini servisi": "Contact directory service",
  "Kullanıcı yönetim paneli": "User management panel",
  "Rol matrisi": "Role matrix",
  "Finans defteri modeli": "Finance ledger model",
  "Finans defteri servisi": "Finance ledger service",
  "Finans operasyon paneli": "Finance operations panel",
  "Denetimli finans aksiyonları": "Audited finance actions",
  "Ocak": "Jan",
  "Dolu": "Occupied",
  "Boş": "Vacant",
  "Bakımda": "Under Maintenance",
  "Teknik": "Technical",
  "Servis": "Service",
  "İmar, tapu ve yetki belgelerinin bir kısmı tarama/PDF görseli olarak geldi; OCR veya insan doğrulaması gerekir.": "Some zoning, title deed (TAPU) and authorization documents arrived as scans/PDF images; OCR or human verification is required.",
  "Tem": "Jul",
  "Site Yönetimi": "Site Management",
  "Sakin Destek": "Resident Support",
  "E-posta": "Email",
  "Tutuldu": "Held",
  "Ön kontrol": "Pre-check",
  "Atandı": "Assigned",
  "Ödeme bekliyor": "Awaiting payment",
  "Çözüldü": "Resolved",
  "Kapandı": "Closed",
  "Borç > 0": "Debt > 0",
  "SLA < 4 saat": "SLA < 4 hours",
  "Check-in bugün": "Check-in today",
  "Belge eksik": "Document missing",
  "Aidat borcu ve erişim uyarısı": "Dues arrears and access warning",
  "Klima servis randevusu": "AC service appointment",
  "Bugünkü check-out ve depozito kontrolü": "Today's check-out and deposit inspection",
  "Aylık finans raporu hazır": "Monthly finance report ready",
  "Yerel çalışma ortamında yetki profili kullanılabilir; üretim ortamında doğrulanmış kullanıcı profili önceliklidir.": "In the local development environment a test permission profile is available; in production, the verified user profile takes priority.",
  "Her rol için görüntüleme, oluşturma, onay, dışa aktarma ve yönetim hakları açık tanımlanır.": "View, create, approve, export and manage permissions are explicitly defined for every role.",
  "Hassas kararlar aktör, modül, sebep, risk ve zaman bilgisiyle izlenebilir şekilde modellenir.": "Sensitive decisions are modeled to be traceable, including actor, module, reason, risk and timestamp information.",
  "Rol bazlı panele giriş yaptı": "Logged into role-based panel",
  "90+ gün borçlu hesapları dışa aktardı": "Exported accounts with 90+ days debt",
  "Daire Import": "Unit Import",
  "212.298+": "212,298+",
  "10.000+": "10,000+",
  "6.000+": "6,000+",
  "Kaynak bekliyor": "Awaiting source",
  "Portal": "Portal",
  "satış planı": "sales plan",
  "Acil": "Urgent",
  "Rol profili ve oturum kontrolü": "Role profile and session control",
  "Rol bazlı menü ve yetki matrisi": "Role-based menu and permission matrix",
  "Finans, erişim ve AI karar izi": "Finance, access and AI decision trail",
  "Şirket/site izolasyon hazırlığı": "Company/site isolation readiness",
  "Veri modeli şirket, site ve rol bağlamını güvenli erişim politikalarına hazırlayacak şekilde tasarlanmıştır.": "The data model is designed to prepare company, site and role context for secure access policies.",
  "AI aksiyonlarında insan onayı": "Human approval on AI actions",
  "AI finans, erişim veya hassas verilerde doğrudan işlem yapmaz; öneri ve onay kuyruğu üretir.": "AI does not perform direct actions on finance, access or sensitive data; it produces a suggestion and approval queue.",
  "Operasyon Sorumlusu": "Operations Manager",
  "Kısıtlı erişim listesi inceledi": "Reviewed restricted access list",
  "AI Operasyon": "AI Operations",
  "Tahsilat önceliği önerisi oluşturdu": "Generated collection priority suggestion",
  "Daire import doğrulama raporunu onayladı": "Approved unit import validation report",
  "Kişi, daire, finans, servis, belge ve AI özetleri, her ekibi tek bir doğrusal akışa zorlamadan birbirine bağlı kalır.": "People, units, finance, service, documents, and AI summaries stay interconnected without forcing every team into a single linear flow.",
  "Bağlantılı çalışma alanı": "Connected workspace",
  "Operasyonel kayıt": "Operational record",
  "Güncel görünüm": "Live view",
  "Ekip erişimi": "Team access",
  "Yasal takipteki 15 daire için erişim kısıtlama listesi güncellendi.": "The access restriction list has been updated for the 15 units in legal proceedings.",
  "Waleri onaylı demo yedek verisi: B Blok fiyatları ve numaralandırma/referans mantığı A Blok'tan kopyalanmıştır.": "Waleri-approved demo fallback: copy Block A prices and numbering/reference logic to Block B.",
  "Waleri onaylı demo yedek verisi: D Blok fiyatları E Blok'tan kopyalanmıştır.": "Waleri-approved demo fallback: copy Block E prices to Block D.",
  "Hasar ve temizlik kanıtını muhasebe onayına bağla": "Link damage and cleaning evidence to accounting approval",
  "Depozito tutarını checkout takibinde izle": "Track the deposit amount in checkout tracking",
  "Rezervasyon ön kontrolünü tamamla": "Complete the reservation pre-check",
  "Yatırım": "Investment",
  "Tatil evi": "Holiday Home",
  "Vatandaşlık": "Citizenship",
  "İkamet": "Residence",
  "Kota incelemesi": "Quota Review",
  "Yerel örnek veri": "Local seed",
  "Servis SLA inceleme isteği oluştur": "Create service SLA review request",
  "SLA incelemesi aç": "Open SLA review",
  "Hazırlık": "Preparation",
  "Servis kataloğu ve sipariş kapısı": "Service catalog and order gateway",
  "Fiyat, SLA, borç politikası, depozito ve ekip kuralı sipariş oluşmadan önce görünür.": "Price, SLA, debt policy, deposit and team rule are visible before the order is created.",
  "{count} sevke hazır": "{count} ready to dispatch",
  "Borç esnek": "Debt flexible",
  "Yönetici kontrol": "Manager control",
  "{name} siparişi hazırla": "Prepare {name} order",
  "Hazırla": "Prepare",
  "Sipariş kontrolü": "Order check",
  "Saha görevleri, SLA ve medya kanıtı": "Field tasks, SLA and media evidence",
  "Atama, rota, checklist, medya kanıtı ve yönetici onayı tek görev panosunda takip edilir.": "Assignment, route, checklist, media evidence and manager approval are tracked on a single task board.",
  "{id} saha görevini hazırla": "Prepare field task {id}",
  "Daire teslimi, kısa konaklama sonrası temizlik ve temel sarf malzeme kontrolü.": "Unit handover, post-short-stay cleaning, and basic consumables check.",
  "Standart daire temizliği": "Standard unit cleaning",
  "Derin temizlik ve checkout hazırlığı": "Deep cleaning and checkout preparation",
  "Checkout sonrası detaylı temizlik, hasar fotoğrafları ve depozito kontrol notu.": "Detailed post-checkout cleaning, damage photos, and deposit review note.",
  "Klima bakımı ve drenaj kontrolü": "AC maintenance and drainage check",
  "Filtre, drenaj, soğutma performansı ve servis kanıtı ile periyodik klima bakımı.": "Periodic AC maintenance covering filter, drainage, cooling performance, and service proof.",
  "Acil tesisat müdahalesi": "Emergency plumbing response",
  "Su kaçağı, gider tıkanıklığı ve acil tesisat onarımı için hızlı saha yönlendirmesi.": "Rapid field dispatch for water leaks, drain blockages, and emergency plumbing repair.",
  "Malik, kiracı ve misafirler için planlı havalimanı transferi ve varış bildirimi.": "Scheduled airport transfer and arrival notification for owners, tenants, and guests.",
  "Ortak alan kapasitesi, aidat durumu ve kullanıcı yetkisine göre rezervasyon kontrolü.": "Booking control based on common area capacity, dues status, and user authorization.",
  "Muhasebe onayı ve borç kontrolü tamamlanmadan saha işine çıkarma": "Do not dispatch to the field until accounting approval and debt check are complete",
  "SLA ve ekip uygunluğuna göre görevi ata": "Assign the task based on SLA and team availability",
  "Personel rota ve medya kanıtı talimatını gönder": "Send staff routing and media-proof instructions",
  "Saha notu ve kapanış kanıtını kontrol et": "Review field notes and closure proof",
  "Sorunu yerinde doğrula": "Verify the issue on site",
  "Öncesi fotoğraf yükle": "Upload before photo",
  "Daire giriş kontrolü": "Unit entry check",
  "Fotoğraf kanıtı": "Photo proof",
  "Varış saatini doğrula": "Confirm arrival time",
  "Tedarikçiyi ata": "Assign vendor",
  "Misafir bildirimini gönder": "Send guest notification",
  "Hasar alanını işaretle": "Mark damage area",
  "Yönetici onayı al": "Obtain manager approval",
  "Haziran kapanış sinyali": "June closing signal",
  "Son aya göre {sign}{delta} tahsilat farkı. AI raporları sadece öneri üretir; onay insan rolünde kalır.": "{sign}{delta} collection difference versus last month. AI reports only generate recommendations; approval remains a human role.",
  "WhatsApp + E-posta": "WhatsApp + Email",
  "Push + Ekip": "Push + Internal Team Channel",
  "Portal + E-posta": "Portal + Email",
  "Avsallar master plandan operasyon kaydına": "Avsallar master plan to operating record",
  "Telefon kaydı bekliyor": "Phone record pending",
  "New Level Premium price-list package": "New Level Premium price-list package",
  "Project documents, facility map and floor plans": "Project documents, facility map and floor plans",
  "Construction and showroom media": "Construction and showroom media",
  "Unknown": "Unknown",
  "Open basement": "Open basement",
  "Ground floor": "Ground floor",
  "Block B demo fallback": "Block B demo fallback",
  "Block D demo fallback": "Block D demo fallback",
  "Waleri-approved demo fallback: copy B Block prices and numbering/reference logic from A Block.": "Waleri-approved demo fallback: copy B Block prices and numbering/reference logic from A Block.",
  "Waleri-approved demo fallback: copy D Block prices from E Block.": "Waleri-approved demo fallback: copy D Block prices from E Block.",
  "Deal": "Deal",
  "Denetim izi": "Audit trail",
  "Proceed with reservation and ROI pack": "Proceed with reservation and ROI pack",
  "Check residence-zone status before promise": "Check residence-zone status before promise",
  "Need appraisal and source-of-funds review": "Need appraisal and source-of-funds review",
  "Do not promise residence suitability": "Do not promise residence suitability",
  "investment": "Investment",
  "holiday_home": "Holiday home",
  "citizenship": "Citizenship",
  "residence": "Residence permit",
  "clear": "Clear",
  "quota_review": "Quota review",
  "restricted": "Restricted",
  "Legal takipteki 15 daire için erişim kısıtlama listesi güncellendi.": "The access restriction list has been updated for the 15 units in legal proceedings.",
  "ROI tablosu ve Almanca proje paketi": "ROI table and German-language project pack",
  "Beach club ve otel hizmetleri tanıtım turu": "Beach club and hotel-services showcase tour",
  "Hukuk ortağıyla uygunluk ön kontrolü": "Pre-check eligibility with legal partner",
  "Ödeme planı onaylanınca daireyi rezerve et": "Reserve the unit once the payment plan is approved",
  "Gelmeme (no-show) sonrası kurtarma mesajı gönder": "Send a recovery message after a no-show",
  "low": "Low",
  "medium": "Medium",
  "high": "High",
  "Reservation": "Reservation",
  "Payment Plan": "Payment Plan",
  "Sales Contract": "Sales Contract",
  "Ready for payment-plan signature": "Ready for payment-plan signature",
  "Collect buyer signature": "Collect buyer signature",
  "Request passport and source-of-funds pack": "Request passport and source-of-funds pack",
  "Validate title deed pack before contract": "Validate title deed pack before contract",
  "Keep listing authorization attached": "Keep listing authorization attached",
  "Correct buyer name before reservation": "Correct buyer name before reservation",
  "Standart daire temizligi": "Standard unit cleaning",
  "Daire teslimi, kisa konaklama sonrasi temizlik ve temel sarf malzeme kontrolu.": "Unit handover, post short-stay cleaning and basic consumables check.",
  "Derin temizlik ve checkout hazirligi": "Deep cleaning and checkout preparation",
  "Checkout sonrasi detayli temizlik, hasar fotograflari ve depozito kontrol notu.": "Detailed post-checkout cleaning, damage photos and deposit-check note.",
  "Klima bakimi ve drenaj kontrolu": "AC maintenance and drainage check",
  "Filtre, drenaj, sogutma performansi ve servis kaniti ile periyodik klima bakimi.": "Periodic AC maintenance covering filter, drainage, cooling performance and service proof.",
  "Acil tesisat mudahalesi": "Emergency plumbing response",
  "Su kacagi, gider tikanikligi ve acil tesisat onarimi icin hizli saha yonlendirmesi.": "Fast on-site dispatch for water leaks, drain blockages and emergency plumbing repairs.",
  "Ortak alan kapasitesi, aidat durumu ve kullanici yetkisine gore rezervasyon kontrolu.": "Reservation check based on common-area capacity, dues status and user authorization.",
  "mixed": "Mixed crew",
  "internal": "Internal crew",
  "vendor": "Vendor",
  "1Cati keeps the operational service catalogue, service orders, SLA tasks and ticket events inside Supabase.": "1Cati keeps the operational service catalogue, service orders, SLA tasks and ticket events inside Supabase.",
  "Twenty CRM remains the relationship/contact system; 1Cati remains the resident-service and field-operations system.": "Twenty CRM remains the relationship/contact system; 1Cati remains the resident-service and field-operations system.",
  "Muhasebe onayi ve borc kontrolu tamamlanmadan saha isine cikarma": "Do not dispatch to the field before accounting approval and debt check are completed",
  "Saha notu ve kapanis kanitini kontrol et": "Check field note and closure proof",
  "SLA ve ekip uygunluguna gore gorevi ata": "Assign the task based on SLA and crew availability",
  "Personel rota ve medya kaniti talimatini gonder": "Send staff the route and media-proof instructions",
  "Daire giris kontrolu": "Unit access check",
  "Fotograf kaniti": "Photo proof",
  "Sorunu yerinde dogrula": "Verify the issue on-site",
  "Oncesi fotograf yukle": "Upload before photo",
  "Varis saatini dogrula": "Confirm arrival time",
  "Tedarikciyi ata": "Assign vendor",
  "Misafir bildirimini gonder": "Send guest notification",
  "Hasar alanini isaretle": "Mark damage area",
  "Yonetici onayi al": "Get manager approval",
  "Güvenlik - Selim": "Security - Selim",
  "Muhasebe - Merve": "Accounting - Merve",
  "Operasyon - Can": "Operations - Can",
  "Teknik - Ahmet": "Technical - Ahmet",
  "Teknik - Burak": "Technical - Burak",
  "Temizlik - Esra": "Cleaning - Esra"
}
