import type { DashboardLocale } from "@/lib/unit-matrix-copy"

type TranslationTable = Record<string, string>

const en: TranslationTable = {
  "Açık ödeme veya depozito işi bulunamadı.": "No open payment or deposit work found.",
  "Kalite kontrolü dikkat istiyor": "Quality checks need attention",
  "Kısıt ve mutabakat kuyruğu": "Restriction and reconciliation queue",
  "Kısıt veya mutabakat kuyruğu boş.": "Restriction or reconciliation queue is empty.",
  "Ödeme kontrol verisi şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Payment control data is not available right now. Try refresh again or check API status.",
  "Satış ödeme planı, depozito iadesi, banka mutabakatı ve borca bağlı erişim kısıtı aynı onay kuyruğunda izlenir. Sistem karar önerir; finans ve erişim aksiyonları insan onayıyla kapanır.": "Sales payment plan, deposit refund, bank reconciliation and debt-based access restriction are tracked in one approval queue. The system recommends decisions; finance and access actions close with human approval.",
  "Aidat, ödeme, depozito, ceza ve düzeltme kayıtları değiştirilemez defter mantığıyla takip edilir. Hassas finans aksiyonları onay ve denetim akışına alınır.": "Dues, payment, deposit, penalty and correction records are tracked with immutable-ledger logic. Sensitive finance actions enter approval and audit flow.",
  "Bu ay tahsilat": "This month collection",
  "Finans defteri şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Finance ledger is not available right now. Try refresh again or check API status.",
  "Finans defteri kalite kontrolü dikkat istiyor": "Finance ledger quality checks need attention",
  "Finans kaydı bulunamadı.": "No finance record found.",
  "Finans defteri dis aktarim istegi olusturur.": "Creates a finance ledger export request.",
  "Finans defteri disa aktarim istegi olustur": "Create finance ledger export request",
  "Finans defteri disa aktarim istegi": "Finance ledger export request",
  "Kısmi": "Partial",
  "Onaylanmış finans kaydı doğrudan değiştirilmez; düzeltme için karşı kayıt açılır. Dışa aktarım, mutabakat ve ödeme aksiyonları role göre denetim akışına alınır.": "Posted finance records are not changed directly; a counter-entry is opened for correction. Export, reconciliation and payment actions enter role-based audit flow.",
  "vade": "due date",
  "tamamlandı": "complete",
  "Çıkış": "Check-out",
  "Blokaj yok": "No blocker",
  "Rezervasyon sözleşmesi eksik": "Reservation contract missing",
  "İkinci taksit doğrulanmadı": "Second installment not verified",
  "Ödeme planı imzası bekliyor": "Payment plan signature pending",
  "İade edildi": "Refund released",
  "Kesinti bekliyor": "Deduction pending",
  "Kesildi": "Deducted",
  "Tahsil edildi": "Captured",
  "Hatalı": "Failed",
  "Banka transferi": "Bank transfer",
  "Manuel banka": "Manual bank",
  "submitted": "Submitted",
  "approved": "Approved",
  "rejected": "Rejected",
  "request_only": "Request only",
  "approval_required": "Approval required",
  "log_only": "Log only",
  "ui": "UI",
  "ai": "AI",
  "admin": "Administration",
  "manager": "Manager",
  "staff": "Staff",
  "owner": "Owner",
  "AI raporları sadece öneri üretir; onay insan rolünde kalır.": "AI reports only produce recommendations; approval stays with a human role.",
  "Son aya göre": "Compared with last month",
  "tahsilat farkı": "collection difference",
  "Yönetim kurulu, muhasebe, operasyon, güvenlik ve misafir ekipleri için otomatik raporlar ve karar özetleri.": "Automated reports and decision summaries for board, accounting, operations, security and guest teams.",
  "Saha ekibi için giriş-çıkış, temizlik, erişim ve operasyon görevleri sadeleştirilmiş çizelgede gösterilir.": "For the field team, check-in/out, cleaning, access and operations tasks are shown in a simplified schedule.",
  "Web uygulama içinde rezervasyon, check-in, check-out, temizlik, erişim kodu ve depozito süreçlerini yönetin.": "Manage reservations, check-in, check-out, cleaning, access codes and deposit processes inside the web app.",
  "Yetkili rezervasyon, giriş-çıkış, erişim kodu ve depozito durumunu sadece kendi kaydınız kapsamında takip edin.": "Track authorized reservation, check-in/out, access code and deposit status only within your own record scope.",
  "Daire / referans": "Unit / reference",
  "Dosyalar gizli kalır, metadata veritabanında tutulur ve her yükleme insan incelemesini bekler.": "Files stay private, metadata is kept in the database, and every upload waits for human review.",
  "İnceleme ekibi için isteğe bağlı not": "Optional note for the review team",
  "Maks. 25 MB. Gizli depolama, inceleme zorunlu.": "Max 25 MB. Private storage, review required.",
  "Pasaport, TAPU, ödeme kanıtı...": "Passport, TAPU, payment proof...",
  "PDF, görsel, Word veya Excel dosyası seçin": "Select a PDF, image, Word or Excel file",
  "Saha operasyonu için yalnızca görev dosyaları, servis kanıtları ve gerekli onay kayıtları gösterilir.": "Only task files, service evidence and required approval records are shown for field operations.",
  "Yetkili dairenize bağlı sözleşme, kimlik, depozito, servis ve uyum belgelerini güvenli portal görünümünde takip edin.": "Track contracts, identity, deposit, service and compliance documents for your authorized unit in a secure portal view.",
  "Yükleme başarısız.": "Upload failed.",
  "0% taksit akışı; liste fiyatı, peşinat, kalan vade, kur riski ve sözleşme blokajını satıştan önce görünür yapar.": "The 0% installment flow makes list price, down payment, remaining due date, exchange-rate risk and contract blockers visible before sale.",
  "90+ gün borçta erişim kısıtı, servis bekletme ve yasal takip önerisi otomatik görünür.": "For 90+ day debt, access restriction, service hold and legal follow-up recommendations appear automatically.",
  "Aylık aidat": "Monthly dues",
  "Aylık nakit akışı": "Monthly cash flow",
  "Banka dekontu, online ödeme, manuel tahsilat ve kasa hareketi aynı hesap kaydına bağlanır.": "Bank receipts, online payments, manual collections and cash movements are linked to the same account record.",
  "Borç kısıtlama kuralı": "Debt restriction rule",
  "Borç yaşlandırma": "Debt aging",
  "Gecikti": "Overdue",
  "Hasar, temizlik ve iade onayı rezervasyon çıkışıyla finans panelinde kapanır.": "Damage, cleaning and refund approval close in the finance panel with reservation check-out.",
  "Tahsilat, açık borç ve servis gideri birlikte takip edilir.": "Collections, open debt and service cost are tracked together.",
  "Vade yaklaştı": "Due soon",
  "Önceliklendirme 90+ gün ve erişim kısıtından başlar.": "Prioritization starts with 90+ days and access restrictions.",
  "gün": "days",
  "Acil": "Urgent",
  "Aktif": "Active",
  "Atandı": "Assigned",
  "Kapalı": "Closed",
  "Kapandı": "Closed",
  "Küçük borç": "Minor debt",
  "Orta": "Medium",
  "Temiz": "Clear",
  "Düşük": "Low",
  "Çözüldü": "Resolved",
  "İşlemde": "In progress",
  "Aksiyon": "Action",
  "Aksiyonlar": "Actions",
  "AI aksiyonlari": "AI actions",
  "AI oneriyi hazirla": "Prepare AI recommendation",
  "AI önerisi": "AI recommendation",
  "AI Rapor Merkezi": "AI Report Center",
  "AI kontrol": "AI review",
  "Aç": "Open",
  "Açık": "Open",
  "Açık bakiye": "Open balance",
  "Açık kayıt": "Open records",
  "Açık mutabakat": "Open settlement",
  "Açık talep": "Open requests",
  "Açık vade": "Open exposure",
  "Aktif iş": "active work",
  "Aktif kayıt": "Active records",
  "Alıcı": "Buyer",
  "All tasks": "All tasks",
  "All tickets": "All tickets",
  "Başlık": "Title",
  "Belge": "Document",
  "Belge aksiyonlari": "Document actions",
  "Belge paketini hazirla": "Prepare document packet",
  "Belge sayfasi aksiyonlari": "Document page actions",
  "Belge tipi": "Document type",
  "Belge yukle": "Upload document",
  "Belgeyi goruntule": "View document",
  "Belgeyi indir": "Download document",
  "Bekleyen": "Pending",
  "Bekliyor": "Pending",
  "Beklet": "Hold",
  "Blokaj": "Blocker",
  "Bloke": "Blocked",
  "Blokeli": "Blocked",
  "Borç": "Debt",
  "Borç blokeli": "Debt hold",
  "Borç esnek": "Debt flexible",
  "Borç kapalı": "Debt closed",
  "Borç kontrolü": "Debt review",
  "Borç blokeli dairelerde teknisyen sahaya çıkmadan önce muhasebe onayı ve ödeme doğrulaması gerekir.": "For debt-held units, accounting approval and payment verification are required before a technician is dispatched.",
  "Bu önizlemede yalnızca acil, gecikmiş veya blokeli talepler kalır. Tam talep tablosu aşağıda aranabilir ve sayfalanabilir.": "Only urgent, overdue or blocked requests stay in this preview. The full request table is searchable and paginated below.",
  "Bu tam operasyon kuyruğudur. Günlük iş kolay taransın diye üstteki kartlar sınırlı tutulur.": "This is the full operations queue. The upper cards stay limited so daily work remains easy to scan.",
  "Burada yalnızca en ilgili servis kartları gösterilir. Tam operasyon kuyruğu için aşağıdaki talep tablosunu kullanın.": "Only the most relevant service cards are shown here. Use the request table below for the full operations queue.",
  "Cari hesaba yaz": "Post to account",
  "Dashboard ilk altı saha görevini gösterir. Rota çok kayıt içerdiğinde tam iş gücü tablosunu kullanın.": "The dashboard shows the first six field tasks. Use the full workforce table when the route has many records.",
  "Dashboard önizlemesini genişletmek yerine tüm servis taleplerini arayın, sıralayın ve sayfalayın.": "Search, sort and paginate all service requests instead of expanding the dashboard preview.",
  "Bugün çıkış": "Check-outs today",
  "Bugün giriş": "Check-ins today",
  "Daire": "Unit",
  "Depozito": "Deposit",
  "Depozito aksiyonlari": "Deposit actions",
  "Depozito kararini incele": "Review deposit decision",
  "Depozito kontrol": "Deposit review",
  "Depozito kontrolü": "Deposit control",
  "Depozito kuyruğu": "Deposit queue",
  "Depozito riski": "Deposit risk",
  "Defteri yenile": "Refresh ledger",
  "Denetim": "Audit",
  "Dışa aktar": "Export",
  "Disa aktar": "Export",
  "Doğrulandı": "Verified",
  "Durum": "Status",
  "Eksik": "Missing",
  "Eksik/Süre doldu": "Missing/expired",
  "Ekip": "Team",
  "Erişim": "Access",
  "Erişim aksiyonlari": "Access actions",
  "Erişim bekliyor": "Access pending",
  "Erişim kodu": "Access code",
  "Erişim riski": "Access risk",
  "Finans blokeli": "Finance hold",
  "Finans kontrol": "Finance review",
  "Finans defteri": "Finance ledger",
  "Finans defteri aksiyonlari": "Finance ledger actions",
  "Finans kontrol modeli": "Finance control model",
  "Finans, Satış & Aidat": "Finance, Sales & Dues",
  "Fiyat, SLA, borç politikası, depozito ve ekip kuralı sipariş oluşmadan önce görünür.": "Price, SLA, debt policy, deposit and team rules are visible before an order is created.",
  "Fotoğraf, açıklama, randevu ve kapanış kararı yönetim ekibiyle aynı kayıt üzerinden paylaşılır.": "Photos, notes, appointments and close-out decisions are shared with management on the same record.",
  "Gecikmiş": "Overdue",
  "gecikmiş": "overdue",
  "Gerekmez": "Not required",
  "Görev": "Task",
  "Görev açıldı": "Task opened",
  "Görev aksiyonlari": "Task actions",
  "Görev aksiyonu hazirla": "Prepare task action",
  "Gorev aksiyonlari": "Task actions",
  "Gorev aksiyonu hazirla": "Prepare task action",
  "Güvenli belge yükleme": "Secure document upload",
  "Hazır": "Ready",
  "Hazirlik": "Readiness",
  "Haziran kapanis sinyali": "June closing signal",
  "Haziran tahsilat": "June collection",
  "İade": "Refund",
  "İade hazır": "Refund ready",
  "İncelemeye yükle": "Upload for review",
  "İnsan onayı": "Human approval",
  "İş": "Work",
  "İşlem": "Action",
  "Kanal": "Channel",
  "Kanıt ve yanıt": "Evidence and response",
  "Kapanış kontrolü": "Close-out control",
  "Kategori": "Category",
  "Kaydı aç": "Open record",
  "Kayıt": "Record",
  "Kayıtları aç": "Open records",
  "Kişi dizini aksiyonlari": "People directory actions",
  "Kişi dizini kalite kontrolü dikkat istiyor": "People directory quality checks need attention",
  "Kişi dizini şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "People directory is not available right now. Try refresh again or check API status.",
  "Kişi verisini yenile": "Refresh people data",
  "Kişi ve rol dizini": "People and role directory",
  "Personel": "Staff",
  "Personel iş yükü": "Staff workload",
  "Personel, malik, kiracı, misafir ve rol kapsamı tek dizinden yönetilir. Ekip yükü, erişim kapsamı ve riskli kayıtlar aynı ekranda takip edilir.": "Staff, owners, tenants, guests and role coverage are managed from one directory. Team workload, access scope and risk records are tracked on the same screen.",
  "Sakin": "Resident",
  "Sakin bağlantıları": "Resident links",
  "Malik / Kiracı": "Owner / tenant",
  "Kapsam": "Scope",
  "Onaycı": "Approver",
  "Rol matrisi kullanıcı görünürlüğü, finans onayı, erişim kısıtı ve dışa aktarım yetkisini ayrı ayrı tutar.": "The role matrix separates user visibility, finance approval, access restriction and export permissions.",
  "telefon yok": "no phone",
  "Daire bağlantısı yok": "No unit link",
  "Kontrol": "Review",
  "Kontrolleri yenile": "Refresh controls",
  "Kısıt kararı": "Restriction decision",
  "Kısıtlı": "Restricted",
  "Kısıtlı erişim": "Restricted access",
  "Kuyruk": "Queue",
  "Kuyrugu yenile": "Refresh queue",
  "Malik": "Owner",
  "Maliyet": "Cost",
  "Masked": "Masked",
  "Matris": "Matrix",
  "Medya kanıtı": "Media evidence",
  "medya": "media",
  "Misafir": "Guest",
  "Misafir/Sakin": "Guest/resident",
  "Mutabakat": "Reconciliation",
  "No-show kurtarma": "No-show recovery",
  "Odeme kontrol aksiyonlari": "Payment control actions",
  "Onay kuyruğu": "Approval queue",
  "Onaylı": "Approved",
  "Online tur": "Online tour",
  "Ödeme": "Payment",
  "Ödeme bekliyor": "Payment pending",
  "Ödeme doğrulama": "Payment verification",
  "Ödeme önce": "Payment first",
  "Ödeme planı ve depozito işi": "Payment plan and deposit work",
  "Ödeme, depozito ve kısıt kontrol merkezi": "Payment, deposit and restriction control center",
  "Ödenen": "Paid",
  "Öncelik": "Priority",
  "Öncelikli iş kuyruğu": "Priority work queue",
  "Önerilen aksiyon": "Recommended action",
  "Önizleme listeleri panonun taranabilir kalması için sınırlıdır. Tüm kayıtlar için tam tabloyu kullanın.": "Preview lists are capped to keep the dashboard scannable. Use the full table for all records.",
  "Paket aksiyonlari": "Packet actions",
  "Paketi hazirla": "Prepare packet",
  "Plan sayısı": "Plans",
  "Planında": "On track",
  "Planlı": "Scheduled",
  "Rapor": "Report",
  "Rapor aksiyonlari": "Report actions",
  "Rapor register": "Report register",
  "Rapor seti": "Report set",
  "Raporu disa aktar": "Export report",
  "Raporları aç": "Open reports",
  "Rezervasyon & Giriş-Çıkış": "Reservations & Check-in/out",
  "Rezervasyon aksiyonlari": "Reservation actions",
  "Rezervasyonlar": "Reservations",
  "Risk": "Risk",
  "Riskli kayıt": "Risk records",
  "Riskli plan": "Plans at risk",
  "Rol kapsamı": "Role coverage",
  "Saha görevi": "Field task",
  "Saha gorevi": "Field task",
  "Saha görevleri, SLA ve medya kaniti": "Field tasks, SLA and media evidence",
  "Saha iş akışı": "Field workflow",
  "Saha ekibi için atanan servis işleri, SLA önceliği, medya kanıtı ve kapanış adımları aynı iş kuyruğunda yönetilir.": "Assigned field service work, SLA priority, media evidence and close-out steps are managed in one work queue.",
  "SLA dışı": "Outside SLA",
  "SLA riski": "SLA risk",
  "SLA ve kanıt ihtiyacına göre teknik rota sadeleştirilir; finans tutarları saha görünümünde maskelenir.": "The technical route is simplified by SLA and evidence needs; finance amounts are masked in the field view.",
  "Saha önceliği": "Field priority",
  "Saklama sınıfı": "Retention class",
  "Satış belgesi": "Sales documents",
  "Satış dosyası, TAPU, KYC ve EIDS kontrolü": "Sales file, TAPU, KYC and EIDS review",
  "Satış ödeme planı": "Sales payment plan",
  "Servis": "Service",
  "Servis Talepleri": "Service Requests",
  "Servis aksiyonlari": "Service actions",
  "Servis güvenlik kuralı": "Service safety rule",
  "Servis izni": "Service clearance",
  "Servis katalogu ve siparis kapisi": "Service catalog and order gate",
  "Servis kapsamı": "Service scope",
  "Servis talebi aksiyonlari": "Service request actions",
  "Servis talebi durum dağılımı": "Service request status distribution",
  "Servis talebi verisi şu anda alınamadı. Yerel veriyle devam ediliyor.": "Service request data is not available right now. Continuing with local data.",
  "Servis SLA inceleme istegi olustur": "Create service SLA review request",
  "SLA incelemesi ac": "Open SLA review",
  "Servis SLA inceleme isteği oluştur": "Create service SLA review request",
  "SLA incelemesi aç": "Open SLA review",
  "Geciken talep, kanıt ve borç bloklarını yönetime taşır.": "Escalates overdue requests, evidence and debt blockers to management.",
  "Servis SLA ve kanıt kuyruğu incelemesi": "Service SLA and evidence queue review",
  "Siparis": "Orders",
  "Siparis hazirla": "Prepare order",
  "Siparis kontrolu": "Order control",
  "Son finans kayıtları": "Recent finance records",
  "Son güncelleme": "Last update",
  "Son tarih": "Due date",
  "Sonraki aksiyon": "Next action",
  "Sonraki vade": "Next due",
  "Sorumlu": "Owner",
  "Takip": "Follow-up",
  "Takip gerekli": "Follow-up needed",
  "Takipteki talepleriniz": "Your tracked requests",
  "Tahsilat": "Collection",
  "Tahsilat trendi": "Collection trend",
  "Talep": "Request",
  "Tam devir görev kaydı": "Full turnover task register",
  "Tam rezervasyon kaydı": "Full reservation register",
  "Tam saha görev kaydı": "Full field task register",
  "Tam servis talebi kaydı": "Full service request register",
  "Talep, fotoğraf, maliyet, onay, atama ve kapanış kanıtı tek kayıtta tutulur.": "Request, photo, cost, approval, assignment and close-out evidence stay in one record.",
  "TAPU & Belge Kasası": "TAPU & Document Vault",
  "Toplam": "Total",
  "Toplam belge": "Total documents",
  "Toplam borç": "Total debt",
  "Tur": "Tour",
  "Tüm devir işleri": "All turnover work",
  "Tüm rezervasyonlar": "All reservations",
  "Üst": "Top",
  "Ücretsiz": "Free",
  "Vade uyarısı": "Due warning",
  "Yasal risk": "Legal risk",
  "Yasal takip": "Legal follow-up",
  "Yetkili": "Authorized",
  "Yönetici": "Manager",
  "Yönetici kontrol": "Manager review",
  "Yerel veri": "Local seed",
  "Yetkili dairenize bağlı servis taleplerini, randevu durumunu, medya kanıtını ve yönetim yanıtlarını tek ekrandan takip edin.": "Track service requests, appointments, media evidence and management replies for your authorized unit.",
  "onay": "approval",
  "saat": "hours",
  "sevke hazır": "ready to dispatch",
  "ekibi için": "team for",
  "için medya ve SLA kaydı": "media and SLA record for",
  "Yükleniyor...": "Uploading...",
  "Yüksek": "High",
  "acil": "urgent",
  "active": "Active",
  "assigned": "Assigned",
  "blocked": "Blocked",
  "cancelled": "Cancelled",
  "closed": "Closed",
  "complete": "Complete",
  "confirmed": "Confirmed",
  "critical": "Critical",
  "draft": "Draft",
  "due_soon": "Due soon",
  "failed": "Failed",
  "high": "High",
  "in_progress": "In progress",
  "low": "Low",
  "medium": "Medium",
  "mock_ready": "Demo ready",
  "no_show": "No show",
  "not_required": "Not required",
  "open": "Open",
  "overdue": "Overdue",
  "pending": "Pending",
  "provider_ready": "Provider ready",
  "ready": "Ready",
  "resolved": "Resolved",
  "review": "Review",
  "scheduled": "Scheduled",
  "signature_pending": "Signature pending",
  "waiting_payment": "Waiting payment",
}

const de: TranslationTable = {
  "Açık ödeme veya depozito işi bulunamadı.": "Keine offene Zahlungs- oder Kautionsarbeit gefunden.",
  "Kalite kontrolü dikkat istiyor": "Qualitätsprüfungen benötigen Aufmerksamkeit",
  "Kısıt ve mutabakat kuyruğu": "Beschränkungs- und Abstimmungswarteschlange",
  "Kısıt veya mutabakat kuyruğu boş.": "Beschränkungs- oder Abstimmungswarteschlange ist leer.",
  "Mutabakat": "Abstimmung",
  "Ödeme kontrol verisi şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Zahlungskontrolldaten sind derzeit nicht verfügbar. Aktualisieren Sie erneut oder prüfen Sie den API-Status.",
  "Riskli plan": "Risikopläne",
  "Satış ödeme planı, depozito iadesi, banka mutabakatı ve borca bağlı erişim kısıtı aynı onay kuyruğunda izlenir. Sistem karar önerir; finans ve erişim aksiyonları insan onayıyla kapanır.": "Verkaufszahlungsplan, Kautionsrückzahlung, Bankabstimmung und schuldenbasierte Zugangssperre werden in einer Freigabewarteschlange verfolgt. Das System empfiehlt Entscheidungen; Finanz- und Zugangsaktionen schließen mit menschlicher Freigabe.",
  "Aidat, ödeme, depozito, ceza ve düzeltme kayıtları değiştirilemez defter mantığıyla takip edilir. Hassas finans aksiyonları onay ve denetim akışına alınır.": "Beiträge, Zahlungen, Kautionen, Strafen und Korrekturen werden mit unveränderlicher Ledger-Logik verfolgt. Sensible Finanzaktionen gehen in Freigabe- und Audit-Flows.",
  "Bu ay tahsilat": "Zahlungseingang diesen Monat",
  "Finans defteri şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Das Finanzledger ist derzeit nicht verfügbar. Aktualisieren Sie erneut oder prüfen Sie den API-Status.",
  "Finans defteri kalite kontrolü dikkat istiyor": "Qualitätsprüfungen des Finanzledgers benötigen Aufmerksamkeit",
  "Finans kaydı bulunamadı.": "Kein Finanzdatensatz gefunden.",
  "Finans defteri dis aktarim istegi olusturur.": "Erstellt eine Exportanfrage für das Finanzledger.",
  "Finans defteri disa aktarim istegi olustur": "Exportanfrage für Finanzledger erstellen",
  "Finans defteri disa aktarim istegi": "Exportanfrage für Finanzledger",
  "Kısmi": "Teilweise",
  "Onaylanmış finans kaydı doğrudan değiştirilmez; düzeltme için karşı kayıt açılır. Dışa aktarım, mutabakat ve ödeme aksiyonları role göre denetim akışına alınır.": "Gebuchte Finanzdatensätze werden nicht direkt geändert; für Korrekturen wird eine Gegenbuchung geöffnet. Export, Abstimmung und Zahlungsaktionen gehen in rollenbasierte Audit-Flows.",
  "vade": "Fälligkeit",
  "tamamlandı": "abgeschlossen",
  "Çıkış": "Check-out",
  "Blokaj yok": "Keine Blockade",
  "Rezervasyon sözleşmesi eksik": "Reservierungsvertrag fehlt",
  "İkinci taksit doğrulanmadı": "Zweite Rate nicht verifiziert",
  "Ödeme planı imzası bekliyor": "Zahlungsplan wartet auf Unterschrift",
  "İade edildi": "Rückerstattung freigegeben",
  "Kesinti bekliyor": "Abzug ausstehend",
  "Kesildi": "Abgezogen",
  "Tahsil edildi": "Eingezogen",
  "Hatalı": "Fehlgeschlagen",
  "Banka transferi": "Banküberweisung",
  "Manuel banka": "Manuelle Bankbuchung",
  "submitted": "Eingereicht",
  "approved": "Freigegeben",
  "rejected": "Abgelehnt",
  "request_only": "Nur Anfrage",
  "approval_required": "Freigabe erforderlich",
  "log_only": "Nur Protokoll",
  "ui": "Oberfläche",
  "ai": "KI",
  "admin": "Verwaltung",
  "manager": "Manager",
  "staff": "Mitarbeiter",
  "owner": "Eigentümer",
  "AI raporları sadece öneri üretir; onay insan rolünde kalır.": "KI-Berichte erzeugen nur Empfehlungen; die Freigabe bleibt bei einer menschlichen Rolle.",
  "Son aya göre": "Im Vergleich zum Vormonat",
  "tahsilat farkı": "Zahlungsdifferenz",
  "Yönetim kurulu, muhasebe, operasyon, güvenlik ve misafir ekipleri için otomatik raporlar ve karar özetleri.": "Automatisierte Berichte und Entscheidungszusammenfassungen für Vorstand, Buchhaltung, Operations, Sicherheit und Gästeteams.",
  "Saha ekibi için giriş-çıkış, temizlik, erişim ve operasyon görevleri sadeleştirilmiş çizelgede gösterilir.": "Für das Außendienstteam werden Check-in/out, Reinigung, Zugang und Operationsaufgaben in einem vereinfachten Plan angezeigt.",
  "Web uygulama içinde rezervasyon, check-in, check-out, temizlik, erişim kodu ve depozito süreçlerini yönetin.": "Verwalten Sie Reservierung, Check-in, Check-out, Reinigung, Zugangscode und Kaution in der Web-App.",
  "Yetkili rezervasyon, giriş-çıkış, erişim kodu ve depozito durumunu sadece kendi kaydınız kapsamında takip edin.": "Verfolgen Sie autorisierte Reservierung, Check-in/out, Zugangscode und Kaution nur im Umfang Ihres eigenen Datensatzes.",
  "Daire / referans": "Einheit / Referenz",
  "Dosyalar gizli kalır, metadata veritabanında tutulur ve her yükleme insan incelemesini bekler.": "Dateien bleiben privat, Metadaten werden in der Datenbank gespeichert, und jeder Upload wartet auf menschliche Prüfung.",
  "İnceleme ekibi için isteğe bağlı not": "Optionale Notiz für das Prüfungsteam",
  "Maks. 25 MB. Gizli depolama, inceleme zorunlu.": "Max. 25 MB. Privater Speicher, Prüfung erforderlich.",
  "Pasaport, TAPU, ödeme kanıtı...": "Pass, TAPU, Zahlungsnachweis...",
  "PDF, görsel, Word veya Excel dosyası seçin": "PDF, Bild, Word- oder Excel-Datei auswählen",
  "Saha operasyonu için yalnızca görev dosyaları, servis kanıtları ve gerekli onay kayıtları gösterilir.": "Für den Außendienst werden nur Aufgabendateien, Servicenachweise und notwendige Freigaben angezeigt.",
  "Yetkili dairenize bağlı sözleşme, kimlik, depozito, servis ve uyum belgelerini güvenli portal görünümünde takip edin.": "Verfolgen Sie Verträge, Identität, Kaution, Service- und Compliance-Dokumente Ihrer autorisierten Einheit in einer sicheren Portalansicht.",
  "Yükleme başarısız.": "Upload fehlgeschlagen.",
  "0% taksit akışı; liste fiyatı, peşinat, kalan vade, kur riski ve sözleşme blokajını satıştan önce görünür yapar.": "Der 0%-Ratenfluss macht Listenpreis, Anzahlung, Restfälligkeit, Wechselkursrisiko und Vertragsblocker vor dem Verkauf sichtbar.",
  "90+ gün borçta erişim kısıtı, servis bekletme ve yasal takip önerisi otomatik görünür.": "Bei 90+ Tagen Schuld erscheinen Zugangssperre, Service-Stopp und rechtliche Nachverfolgung automatisch als Empfehlung.",
  "Aylık aidat": "Monatlicher Beitrag",
  "Aylık nakit akışı": "Monatlicher Cashflow",
  "Banka dekontu, online ödeme, manuel tahsilat ve kasa hareketi aynı hesap kaydına bağlanır.": "Bankbeleg, Online-Zahlung, manuelle Zahlung und Kassenbewegung werden demselben Konto zugeordnet.",
  "Borç kısıtlama kuralı": "Schuldenbeschränkungsregel",
  "Borç yaşlandırma": "Schuldenalterung",
  "Gecikti": "Überfällig",
  "Hasar, temizlik ve iade onayı rezervasyon çıkışıyla finans panelinde kapanır.": "Schaden, Reinigung und Rückerstattungsfreigabe schließen mit dem Check-out im Finanzpanel.",
  "Tahsilat, açık borç ve servis gideri birlikte takip edilir.": "Zahlungseingang, offene Schuld und Servicekosten werden gemeinsam verfolgt.",
  "Vade yaklaştı": "Bald fällig",
  "Önceliklendirme 90+ gün ve erişim kısıtından başlar.": "Die Priorisierung beginnt mit 90+ Tagen und Zugangsbeschränkung.",
  "gün": "Tage",
  "Acil": "Dringend",
  "Aktif": "Aktiv",
  "Atandı": "Zugewiesen",
  "Kapalı": "Geschlossen",
  "Kapandı": "Geschlossen",
  "Küçük borç": "Kleiner Rückstand",
  "Orta": "Mittel",
  "Temiz": "Ausgeglichen",
  "Düşük": "Niedrig",
  "Çözüldü": "Gelöst",
  "İşlemde": "In Arbeit",
  "Aynı gün çok sayıda teknisyen görevi olduğunda bu kaydı kullanın.": "Nutzen Sie dieses Register, wenn am selben Tag viele Technikeraufgaben anfallen.",
  "Atama, rota, checklist, medya kanıtı ve yönetici onayı tek görev panosunda takip edilir.": "Zuweisung, Route, Checkliste, Mediennachweis und Managerfreigabe werden in einem Aufgabenboard verfolgt.",
  "Beklet": "Halten",
  "Borç blokeli dairelerde teknisyen sahaya çıkmadan önce muhasebe onayı ve ödeme doğrulaması gerekir.": "Bei schuldenblockierten Einheiten sind Buchhaltungsfreigabe und Zahlungsprüfung erforderlich, bevor ein Techniker disponiert wird.",
  "Borç esnek": "Schuld flexibel",
  "Borç kapalı": "Schuld geschlossen",
  "Borç kontrolü": "Schuldenprüfung",
  "Bu önizlemede yalnızca acil, gecikmiş veya blokeli talepler kalır. Tam talep tablosu aşağıda aranabilir ve sayfalanabilir.": "In dieser Vorschau bleiben nur dringende, überfällige oder blockierte Anfragen. Die vollständige Tabelle unten ist durchsuchbar und paginiert.",
  "Bu tam operasyon kuyruğudur. Günlük iş kolay taransın diye üstteki kartlar sınırlı tutulur.": "Dies ist die vollständige Operationswarteschlange. Die oberen Karten bleiben begrenzt, damit die Tagesarbeit schnell lesbar bleibt.",
  "Burada yalnızca en ilgili servis kartları gösterilir. Tam operasyon kuyruğu için aşağıdaki talep tablosunu kullanın.": "Hier werden nur die relevantesten Servicekarten gezeigt. Nutzen Sie die Anfragetabelle unten für die vollständige Operationswarteschlange.",
  "Cari hesaba yaz": "Auf Konto buchen",
  "Dashboard ilk altı saha görevini gösterir. Rota çok kayıt içerdiğinde tam iş gücü tablosunu kullanın.": "Das Dashboard zeigt die ersten sechs Außendienstaufgaben. Nutzen Sie bei vielen Routeneinträgen die vollständige Workforce-Tabelle.",
  "Dashboard önizlemesini genişletmek yerine tüm servis taleplerini arayın, sıralayın ve sayfalayın.": "Suchen, sortieren und paginieren Sie alle Serviceanfragen, statt die Dashboard-Vorschau zu vergrößern.",
  "Fiyat, SLA, borç politikası, depozito ve ekip kuralı sipariş oluşmadan önce görünür.": "Preis, SLA, Schuldenregel, Kaution und Teamregel sind sichtbar, bevor ein Auftrag entsteht.",
  "Fotoğraf, açıklama, randevu ve kapanış kararı yönetim ekibiyle aynı kayıt üzerinden paylaşılır.": "Fotos, Notizen, Termine und Abschlussentscheidung werden mit dem Management über denselben Datensatz geteilt.",
  "Görev açıldı": "Aufgabe geöffnet",
  "Medya kanıtı": "Mediennachweis",
  "Ödeme bekliyor": "Zahlung ausstehend",
  "Ödeme önce": "Zahlung zuerst",
  "Önizleme listeleri panonun taranabilir kalması için sınırlıdır. Tüm kayıtlar için tam tabloyu kullanın.": "Vorschaulisten sind begrenzt, damit das Dashboard scannbar bleibt. Nutzen Sie die vollständige Tabelle für alle Einträge.",
  "Saha ekibi için atanan servis işleri, SLA önceliği, medya kanıtı ve kapanış adımları aynı iş kuyruğunda yönetilir.": "Zugewiesene Außendienstaufgaben, SLA-Priorität, Mediennachweis und Abschluss werden in einer Arbeitswarteschlange verwaltet.",
  "SLA dışı": "Außerhalb SLA",
  "SLA riski": "SLA-Risiko",
  "SLA ve kanıt ihtiyacına göre teknik rota sadeleştirilir; finans tutarları saha görünümünde maskelenir.": "Die technische Route wird nach SLA- und Nachweisbedarf vereinfacht; Finanzbeträge sind in der Außendienstansicht maskiert.",
  "Sadece sizin dairenize veya yetkili kaydınıza bağlı talepler gösterilir.": "Es werden nur Anfragen angezeigt, die Ihrer Einheit oder Ihrem autorisierten Datensatz zugeordnet sind.",
  "Servis talebi verisi şu anda alınamadı. Yerel veriyle devam ediliyor.": "Serviceanfragedaten sind derzeit nicht verfügbar. Es wird mit lokalen Daten fortgefahren.",
  "Talep, fotoğraf, maliyet, onay, atama ve kapanış kanıtı tek kayıtta tutulur.": "Anfrage, Foto, Kosten, Freigabe, Zuweisung und Abschlussnachweis bleiben in einem Datensatz.",
  "Talepler": "Anfragen",
  "Ticketing mimarisi": "Ticketing-Architektur",
  "Tüm görevler": "Alle Aufgaben",
  "Tüm talepler": "Alle Anfragen",
  "Ücretsiz": "Kostenlos",
  "Yerel veri": "Lokale Daten",
  "Yetkili dairenize bağlı servis taleplerini, randevu durumunu, medya kanıtını ve yönetim yanıtlarını tek ekrandan takip edin.": "Verfolgen Sie Serviceanfragen, Termine, Mediennachweise und Managementantworten für Ihre autorisierte Einheit auf einem Bildschirm.",
  "ekibi için": "für das Team",
  "gecikmiş": "überfällig",
  "için medya ve SLA kaydı": "Medien- und SLA-Datensatz für",
  "medya": "Medien",
  "onay": "Freigabe",
  "saat": "Stunden",
  "sevke hazır": "bereit zur Disposition",
  "Aksiyon": "Aktion",
  "Aksiyonlar": "Aktionen",
  "AI aksiyonlari": "KI-Aktionen",
  "AI oneriyi hazirla": "KI-Empfehlung vorbereiten",
  "AI önerisi": "KI-Empfehlung",
  "AI Rapor Merkezi": "KI-Berichtszentrum",
  "AI kontrol": "KI-Prüfung",
  "Aç": "Öffnen",
  "Açık": "Offen",
  "Açık bakiye": "Offener Saldo",
  "Açık kayıt": "Offene Einträge",
  "Açık talep": "Offene Anfragen",
  "Aktif kayıt": "Aktive Einträge",
  "Alıcı": "Käufer",
  "Başlık": "Titel",
  "Belge": "Dokument",
  "Belge aksiyonlari": "Dokumentaktionen",
  "Belge sayfasi aksiyonlari": "Dokumentseiten-Aktionen",
  "Belge tipi": "Dokumenttyp",
  "Belge yukle": "Dokument hochladen",
  "Belgeyi goruntule": "Dokument anzeigen",
  "Belgeyi indir": "Dokument herunterladen",
  "Bekleyen": "Ausstehend",
  "Bekliyor": "Ausstehend",
  "Blokaj": "Blocker",
  "Bloke": "Blockiert",
  "Blokeli": "Blockiert",
  "Borç": "Schuld",
  "Daire": "Einheit",
  "Depozito": "Kaution",
  "Depozito aksiyonlari": "Kautionsaktionen",
  "Depozito kontrol": "Kautionsprüfung",
  "Depozito kontrolü": "Kautionskontrolle",
  "Defteri yenile": "Ledger aktualisieren",
  "Denetim": "Audit",
  "Dışa aktar": "Exportieren",
  "Disa aktar": "Exportieren",
  "Doğrulandı": "Verifiziert",
  "Durum": "Status",
  "Eksik": "Fehlt",
  "Ekip": "Team",
  "Erişim": "Zugang",
  "Erişim aksiyonlari": "Zugangsaktionen",
  "Finans defteri": "Finanzledger",
  "Finans defteri aksiyonlari": "Finanzledger-Aktionen",
  "Finans kontrol": "Finanzprüfung",
  "Finans, Satış & Aidat": "Finanzen, Verkauf & Beiträge",
  "Gecikmiş": "Überfällig",
  "Görev": "Aufgabe",
  "Görev aksiyonlari": "Aufgabenaktionen",
  "Görev aksiyonu hazirla": "Aufgabe vorbereiten",
  "Gorev aksiyonlari": "Aufgabenaktionen",
  "Gorev aksiyonu hazirla": "Aufgabe vorbereiten",
  "Güvenli belge yükleme": "Sicherer Dokumentenupload",
  "Hazır": "Bereit",
  "İnsan onayı": "Menschliche Freigabe",
  "İş": "Arbeit",
  "İşlem": "Aktion",
  "Kanal": "Kanal",
  "Kategori": "Kategorie",
  "Kayıt": "Eintrag",
  "Kişi dizini aksiyonlari": "Personenverzeichnis-Aktionen",
  "Kişi dizini kalite kontrolü dikkat istiyor": "Qualitätsprüfungen des Personenverzeichnisses benötigen Aufmerksamkeit",
  "Kişi dizini şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Das Personenverzeichnis ist derzeit nicht verfügbar. Aktualisieren Sie erneut oder prüfen Sie den API-Status.",
  "Kişi verisini yenile": "Personendaten aktualisieren",
  "Kişi ve rol dizini": "Personen- und Rollenverzeichnis",
  "Personel": "Personal",
  "Personel iş yükü": "Personalauslastung",
  "Personel, malik, kiracı, misafir ve rol kapsamı tek dizinden yönetilir. Ekip yükü, erişim kapsamı ve riskli kayıtlar aynı ekranda takip edilir.": "Personal, Eigentümer, Mieter, Gäste und Rollenabdeckung werden in einem Verzeichnis verwaltet. Teamlast, Zugriffsumfang und Risikodatensätze werden auf demselben Bildschirm verfolgt.",
  "Sakin": "Bewohner",
  "Sakin bağlantıları": "Bewohnerverknüpfungen",
  "Malik / Kiracı": "Eigentümer / Mieter",
  "Kapsam": "Umfang",
  "Onaycı": "Freigeber",
  "Rol matrisi kullanıcı görünürlüğü, finans onayı, erişim kısıtı ve dışa aktarım yetkisini ayrı ayrı tutar.": "Die Rollenmatrix trennt Benutzersichtbarkeit, Finanzfreigabe, Zugriffsbeschränkung und Exportrechte.",
  "telefon yok": "keine Telefonnummer",
  "Daire bağlantısı yok": "Keine Einheit verknüpft",
  "Kontrol": "Prüfung",
  "Kısıtlı": "Eingeschränkt",
  "Kuyruk": "Warteschlange",
  "Kuyrugu yenile": "Warteschlange aktualisieren",
  "Malik": "Eigentümer",
  "Maliyet": "Kosten",
  "Masked": "Maskiert",
  "Matris": "Matrix",
  "Misafir": "Gast",
  "Odeme kontrol aksiyonlari": "Zahlungskontroll-Aktionen",
  "Onaylı": "Freigegeben",
  "Ödeme": "Zahlung",
  "Ödenen": "Bezahlt",
  "Öncelik": "Priorität",
  "Önerilen aksiyon": "Empfohlene Aktion",
  "Paket aksiyonlari": "Paketaktionen",
  "Paketi hazirla": "Paket vorbereiten",
  "Planlı": "Geplant",
  "Rapor": "Bericht",
  "Rapor aksiyonlari": "Berichtsaktionen",
  "Raporu disa aktar": "Bericht exportieren",
  "Rezervasyon & Giriş-Çıkış": "Reservierungen & Check-in/out",
  "Rezervasyon aksiyonlari": "Reservierungsaktionen",
  "Rezervasyonlar": "Reservierungen",
  "Risk": "Risiko",
  "Rol kapsamı": "Rollenabdeckung",
  "Saha gorevi": "Außendienstaufgabe",
  "Saha görevi": "Außendienstaufgabe",
  "Servis": "Service",
  "Servis Talepleri": "Serviceanfragen",
  "Servis aksiyonlari": "Serviceaktionen",
  "Servis talebi aksiyonlari": "Serviceanfrage-Aktionen",
  "Servis SLA inceleme istegi olustur": "Service-SLA-Prüfanfrage erstellen",
  "SLA incelemesi ac": "SLA-Prüfung öffnen",
  "Servis SLA inceleme isteği oluştur": "Service-SLA-Prüfanfrage erstellen",
  "SLA incelemesi aç": "SLA-Prüfung öffnen",
  "Geciken talep, kanıt ve borç bloklarını yönetime taşır.": "Eskaliert überfällige Anfragen, Nachweise und Schuldenblockaden an das Management.",
  "Servis SLA ve kanıt kuyruğu incelemesi": "Service-SLA- und Nachweiswarteschlange prüfen",
  "Siparis": "Aufträge",
  "Siparis hazirla": "Auftrag vorbereiten",
  "Son güncelleme": "Letzte Aktualisierung",
  "Son tarih": "Fällig",
  "Sonraki aksiyon": "Nächste Aktion",
  "Sorumlu": "Verantwortlich",
  "Takip": "Nachverfolgung",
  "Talep": "Anfrage",
  "TAPU & Belge Kasası": "TAPU & Dokumententresor",
  "Toplam": "Gesamt",
  "Toplam belge": "Dokumente gesamt",
  "Toplam borç": "Gesamtschuld",
  "Tur": "Tour",
  "Üst": "Oben",
  "Yasal risk": "Rechtsrisiko",
  "Yasal takip": "Rechtliche Nachverfolgung",
  "Yönetici": "Manager",
  "Yükleniyor...": "Wird hochgeladen...",
  "active": "Aktiv",
  "assigned": "Zugewiesen",
  "blocked": "Blockiert",
  "cancelled": "Storniert",
  "closed": "Geschlossen",
  "complete": "Vollständig",
  "confirmed": "Bestätigt",
  "critical": "Kritisch",
  "draft": "Entwurf",
  "due_soon": "Bald fällig",
  "failed": "Fehlgeschlagen",
  "high": "Hoch",
  "in_progress": "In Arbeit",
  "low": "Niedrig",
  "medium": "Mittel",
  "open": "Offen",
  "overdue": "Überfällig",
  "pending": "Ausstehend",
  "ready": "Bereit",
  "resolved": "Gelöst",
  "review": "Prüfung",
  "scheduled": "Geplant",
}

const ru: TranslationTable = {
  "Açık ödeme veya depozito işi bulunamadı.": "Открытых платежных или депозитных задач нет.",
  "Kalite kontrolü dikkat istiyor": "Контроль качества требует внимания",
  "Kısıt ve mutabakat kuyruğu": "Очередь ограничений и сверки",
  "Kısıt veya mutabakat kuyruğu boş.": "Очередь ограничений или сверки пуста.",
  "Ödeme kontrol verisi şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Данные контроля платежей сейчас недоступны. Обновите снова или проверьте статус API.",
  "Riskli plan": "Рисковые планы",
  "Satış ödeme planı, depozito iadesi, banka mutabakatı ve borca bağlı erişim kısıtı aynı onay kuyruğunda izlenir. Sistem karar önerir; finans ve erişim aksiyonları insan onayıyla kapanır.": "План оплаты продажи, возврат депозита, банковская сверка и ограничение доступа по долгу отслеживаются в одной очереди одобрения. Система рекомендует решения; финансы и доступ закрываются с одобрением человека.",
  "Aidat, ödeme, depozito, ceza ve düzeltme kayıtları değiştirilemez defter mantığıyla takip edilir. Hassas finans aksiyonları onay ve denetim akışına alınır.": "Взносы, оплаты, депозиты, штрафы и корректировки отслеживаются по логике неизменяемого журнала. Чувствительные финансовые действия идут через одобрение и аудит.",
  "Bu ay tahsilat": "Поступления за месяц",
  "Finans defteri şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Финансовый журнал сейчас недоступен. Обновите снова или проверьте статус API.",
  "Finans defteri kalite kontrolü dikkat istiyor": "Контроль качества финансового журнала требует внимания",
  "Finans kaydı bulunamadı.": "Финансовых записей нет.",
  "Finans defteri dis aktarim istegi olusturur.": "Создает запрос экспорта финансового журнала.",
  "Finans defteri disa aktarim istegi olustur": "Создать запрос экспорта финансового журнала",
  "Finans defteri disa aktarim istegi": "Запрос экспорта финансового журнала",
  "Kısmi": "Частично",
  "Onaylanmış finans kaydı doğrudan değiştirilmez; düzeltme için karşı kayıt açılır. Dışa aktarım, mutabakat ve ödeme aksiyonları role göre denetim akışına alınır.": "Проведенная финансовая запись не изменяется напрямую; для корректировки открывается встречная запись. Экспорт, сверка и платежные действия идут через ролевой аудит.",
  "vade": "срок",
  "tamamlandı": "завершено",
  "Çıkış": "Выезд",
  "Blokaj yok": "Нет блокировки",
  "Rezervasyon sözleşmesi eksik": "Не хватает договора бронирования",
  "İkinci taksit doğrulanmadı": "Второй платеж не подтвержден",
  "Ödeme planı imzası bekliyor": "План платежей ожидает подписи",
  "İade edildi": "Возврат выпущен",
  "Kesinti bekliyor": "Ожидается удержание",
  "Kesildi": "Удержано",
  "Tahsil edildi": "Списано",
  "Hatalı": "Ошибка",
  "Banka transferi": "Банковский перевод",
  "Manuel banka": "Ручная банковская операция",
  "submitted": "Отправлено",
  "approved": "Одобрено",
  "rejected": "Отклонено",
  "request_only": "Только заявка",
  "approval_required": "Требуется одобрение",
  "log_only": "Только журнал",
  "ui": "Интерфейс",
  "ai": "AI",
  "admin": "Администрация",
  "manager": "Менеджер",
  "staff": "Сотрудник",
  "owner": "Владелец",
  "AI raporları sadece öneri üretir; onay insan rolünde kalır.": "AI-отчеты только дают рекомендации; одобрение остается за человеком.",
  "Son aya göre": "По сравнению с прошлым месяцем",
  "tahsilat farkı": "разница поступлений",
  "Yönetim kurulu, muhasebe, operasyon, güvenlik ve misafir ekipleri için otomatik raporlar ve karar özetleri.": "Автоматические отчеты и сводки решений для совета, бухгалтерии, операций, безопасности и гостевых команд.",
  "Saha ekibi için giriş-çıkış, temizlik, erişim ve operasyon görevleri sadeleştirilmiş çizelgede gösterilir.": "Для полевой команды заезд/выезд, уборка, доступ и операционные задачи показаны в упрощенном расписании.",
  "Web uygulama içinde rezervasyon, check-in, check-out, temizlik, erişim kodu ve depozito süreçlerini yönetin.": "Управляйте бронированием, заездом, выездом, уборкой, кодом доступа и депозитом внутри веб-приложения.",
  "Yetkili rezervasyon, giriş-çıkış, erişim kodu ve depozito durumunu sadece kendi kaydınız kapsamında takip edin.": "Отслеживайте разрешенное бронирование, заезд/выезд, код доступа и депозит только в рамках своей записи.",
  "Daire / referans": "Юнит / ссылка",
  "Dosyalar gizli kalır, metadata veritabanında tutulur ve her yükleme insan incelemesini bekler.": "Файлы остаются приватными, метаданные хранятся в базе данных, каждая загрузка ждет проверки человеком.",
  "İnceleme ekibi için isteğe bağlı not": "Необязательная заметка для команды проверки",
  "Maks. 25 MB. Gizli depolama, inceleme zorunlu.": "Макс. 25 МБ. Приватное хранилище, проверка обязательна.",
  "Pasaport, TAPU, ödeme kanıtı...": "Паспорт, TAPU, подтверждение оплаты...",
  "PDF, görsel, Word veya Excel dosyası seçin": "Выберите PDF, изображение, Word или Excel файл",
  "Saha operasyonu için yalnızca görev dosyaları, servis kanıtları ve gerekli onay kayıtları gösterilir.": "Для полевых операций показаны только файлы задач, сервисные доказательства и необходимые одобрения.",
  "Yetkili dairenize bağlı sözleşme, kimlik, depozito, servis ve uyum belgelerini güvenli portal görünümünde takip edin.": "Отслеживайте договоры, личные документы, депозит, сервис и compliance по вашему авторизованному юниту в защищенном портале.",
  "Yükleme başarısız.": "Ошибка загрузки.",
  "0% taksit akışı; liste fiyatı, peşinat, kalan vade, kur riski ve sözleşme blokajını satıştan önce görünür yapar.": "Поток рассрочки 0% показывает цену, аванс, оставшийся срок, валютный риск и блокировки договора до продажи.",
  "90+ gün borçta erişim kısıtı, servis bekletme ve yasal takip önerisi otomatik görünür.": "При долге 90+ дней автоматически видны рекомендации по ограничению доступа, удержанию сервиса и юридическому контролю.",
  "Aylık aidat": "Ежемесячный взнос",
  "Aylık nakit akışı": "Месячный денежный поток",
  "Banka dekontu, online ödeme, manuel tahsilat ve kasa hareketi aynı hesap kaydına bağlanır.": "Банковская квитанция, онлайн-оплата, ручное поступление и кассовое движение привязаны к одной учетной записи.",
  "Borç kısıtlama kuralı": "Правило ограничения по долгу",
  "Borç yaşlandırma": "Старение долга",
  "Gecikti": "Просрочено",
  "Hasar, temizlik ve iade onayı rezervasyon çıkışıyla finans panelinde kapanır.": "Повреждения, уборка и одобрение возврата закрываются в финансовой панели вместе с выездом.",
  "Tahsilat, açık borç ve servis gideri birlikte takip edilir.": "Поступления, открытый долг и сервисные расходы отслеживаются вместе.",
  "Vade yaklaştı": "Скоро срок",
  "Önceliklendirme 90+ gün ve erişim kısıtından başlar.": "Приоритизация начинается с 90+ дней и ограничений доступа.",
  "gün": "дн.",
  "Acil": "Срочно",
  "Aktif": "Активно",
  "Atandı": "Назначено",
  "Kapalı": "Закрыто",
  "Kapandı": "Закрыто",
  "Küçük borç": "Небольшой долг",
  "Orta": "Средний",
  "Temiz": "Чисто",
  "Düşük": "Низкий",
  "Çözüldü": "Решено",
  "İşlemde": "В работе",
  "Aynı gün çok sayıda teknisyen görevi olduğunda bu kaydı kullanın.": "Используйте этот реестр, когда в один день много задач для техников.",
  "Atama, rota, checklist, medya kanıtı ve yönetici onayı tek görev panosunda takip edilir.": "Назначение, маршрут, чек-лист, медиа-доказательства и одобрение менеджера отслеживаются на одной доске задач.",
  "Beklet": "Удержать",
  "Borç blokeli dairelerde teknisyen sahaya çıkmadan önce muhasebe onayı ve ödeme doğrulaması gerekir.": "Для юнитов с блокировкой по долгу требуется одобрение бухгалтерии и проверка оплаты до выезда техника.",
  "Borç esnek": "Долг допускается",
  "Borç kapalı": "Долг закрыт",
  "Borç kontrolü": "Проверка долга",
  "Bu önizlemede yalnızca acil, gecikmiş veya blokeli talepler kalır. Tam talep tablosu aşağıda aranabilir ve sayfalanabilir.": "В этом превью остаются только срочные, просроченные или заблокированные заявки. Полная таблица ниже доступна для поиска и постраничного просмотра.",
  "Bu tam operasyon kuyruğudur. Günlük iş kolay taransın diye üstteki kartlar sınırlı tutulur.": "Это полная операционная очередь. Верхние карточки ограничены, чтобы ежедневная работа легко просматривалась.",
  "Burada yalnızca en ilgili servis kartları gösterilir. Tam operasyon kuyruğu için aşağıdaki talep tablosunu kullanın.": "Здесь показаны только наиболее важные сервисные карточки. Для полной очереди используйте таблицу заявок ниже.",
  "Cari hesaba yaz": "Записать на счет",
  "Dashboard ilk altı saha görevini gösterir. Rota çok kayıt içerdiğinde tam iş gücü tablosunu kullanın.": "Панель показывает первые шесть полевых задач. Если маршрут содержит много записей, используйте полную таблицу команды.",
  "Dashboard önizlemesini genişletmek yerine tüm servis taleplerini arayın, sıralayın ve sayfalayın.": "Ищите, сортируйте и просматривайте все сервисные заявки постранично вместо расширения превью панели.",
  "Fiyat, SLA, borç politikası, depozito ve ekip kuralı sipariş oluşmadan önce görünür.": "Цена, SLA, правило долга, депозит и правило команды видны до создания заказа.",
  "Fotoğraf, açıklama, randevu ve kapanış kararı yönetim ekibiyle aynı kayıt üzerinden paylaşılır.": "Фото, заметки, встречи и решение о закрытии передаются команде управления в одной записи.",
  "Görev açıldı": "Задача открыта",
  "Medya kanıtı": "Медиа-доказательства",
  "Ödeme bekliyor": "Ожидает оплаты",
  "Ödeme önce": "Сначала оплата",
  "Önizleme listeleri panonun taranabilir kalması için sınırlıdır. Tüm kayıtlar için tam tabloyu kullanın.": "Списки превью ограничены, чтобы панель оставалась удобной для просмотра. Для всех записей используйте полную таблицу.",
  "Saha ekibi için atanan servis işleri, SLA önceliği, medya kanıtı ve kapanış adımları aynı iş kuyruğunda yönetilir.": "Назначенные полевые сервисные работы, приоритет SLA, медиа-доказательства и закрытие ведутся в одной рабочей очереди.",
  "SLA dışı": "Вне SLA",
  "SLA riski": "Риск SLA",
  "SLA ve kanıt ihtiyacına göre teknik rota sadeleştirilir; finans tutarları saha görünümünde maskelenir.": "Технический маршрут упрощается по SLA и требованиям доказательств; финансовые суммы скрыты в полевом виде.",
  "Sadece sizin dairenize veya yetkili kaydınıza bağlı talepler gösterilir.": "Показаны только заявки, связанные с вашим юнитом или авторизованной записью.",
  "Servis talebi verisi şu anda alınamadı. Yerel veriyle devam ediliyor.": "Данные сервисных заявок сейчас недоступны. Продолжаем с локальными данными.",
  "Talep, fotoğraf, maliyet, onay, atama ve kapanış kanıtı tek kayıtta tutulur.": "Заявка, фото, стоимость, одобрение, назначение и доказательство закрытия хранятся в одной записи.",
  "Talepler": "Заявки",
  "Ticketing mimarisi": "Архитектура заявок",
  "Tüm görevler": "Все задачи",
  "Tüm talepler": "Все заявки",
  "Ücretsiz": "Бесплатно",
  "Yerel veri": "Локальные данные",
  "Yetkili dairenize bağlı servis taleplerini, randevu durumunu, medya kanıtını ve yönetim yanıtlarını tek ekrandan takip edin.": "Отслеживайте сервисные заявки, встречи, медиа-доказательства и ответы управления по вашему авторизованному юниту на одном экране.",
  "ekibi için": "для команды",
  "gecikmiş": "просрочено",
  "için medya ve SLA kaydı": "медиа- и SLA-запись для",
  "medya": "медиа",
  "onay": "одобрение",
  "saat": "час.",
  "sevke hazır": "готово к отправке",
  "Aksiyon": "Действие",
  "Aksiyonlar": "Действия",
  "AI aksiyonlari": "AI-действия",
  "AI oneriyi hazirla": "Подготовить AI-рекомендацию",
  "AI önerisi": "AI-рекомендация",
  "AI Rapor Merkezi": "AI-центр отчетов",
  "AI kontrol": "AI-проверка",
  "Aç": "Открыть",
  "Açık": "Открыто",
  "Açık bakiye": "Открытый баланс",
  "Açık kayıt": "Открытые записи",
  "Açık talep": "Открытые заявки",
  "Aktif kayıt": "Активные записи",
  "Alıcı": "Покупатель",
  "Başlık": "Заголовок",
  "Belge": "Документ",
  "Belge aksiyonlari": "Действия с документом",
  "Belge sayfasi aksiyonlari": "Действия страницы документов",
  "Belge tipi": "Тип документа",
  "Belge yukle": "Загрузить документ",
  "Belgeyi goruntule": "Открыть документ",
  "Belgeyi indir": "Скачать документ",
  "Bekleyen": "Ожидает",
  "Bekliyor": "Ожидает",
  "Blokaj": "Блокировка",
  "Bloke": "Заблокировано",
  "Blokeli": "Заблокировано",
  "Borç": "Долг",
  "Daire": "Юнит",
  "Depozito": "Депозит",
  "Depozito aksiyonlari": "Действия по депозиту",
  "Depozito kontrol": "Проверка депозита",
  "Depozito kontrolü": "Контроль депозита",
  "Defteri yenile": "Обновить журнал",
  "Denetim": "Аудит",
  "Dışa aktar": "Экспорт",
  "Disa aktar": "Экспорт",
  "Doğrulandı": "Проверено",
  "Durum": "Статус",
  "Eksik": "Не хватает",
  "Ekip": "Команда",
  "Erişim": "Доступ",
  "Erişim aksiyonlari": "Действия доступа",
  "Finans defteri": "Финансовый журнал",
  "Finans defteri aksiyonlari": "Действия финансового журнала",
  "Finans kontrol": "Финансовая проверка",
  "Finans, Satış & Aidat": "Финансы, продажи и взносы",
  "Gecikmiş": "Просрочено",
  "Görev": "Задача",
  "Görev aksiyonlari": "Действия задачи",
  "Görev aksiyonu hazirla": "Подготовить задачу",
  "Gorev aksiyonlari": "Действия задачи",
  "Gorev aksiyonu hazirla": "Подготовить задачу",
  "Güvenli belge yükleme": "Безопасная загрузка документов",
  "Hazır": "Готово",
  "İnsan onayı": "Подтверждение человеком",
  "İş": "Работа",
  "İşlem": "Действие",
  "Kanal": "Канал",
  "Kategori": "Категория",
  "Kayıt": "Запись",
  "Kişi dizini aksiyonlari": "Действия каталога людей",
  "Kişi dizini kalite kontrolü dikkat istiyor": "Контроль качества каталога людей требует внимания",
  "Kişi dizini şu anda alınamadı. Yenile butonu ile tekrar deneyin veya API durumunu kontrol edin.": "Каталог людей сейчас недоступен. Обновите снова или проверьте статус API.",
  "Kişi verisini yenile": "Обновить данные людей",
  "Kişi ve rol dizini": "Каталог людей и ролей",
  "Personel": "Персонал",
  "Personel iş yükü": "Загрузка персонала",
  "Personel, malik, kiracı, misafir ve rol kapsamı tek dizinden yönetilir. Ekip yükü, erişim kapsamı ve riskli kayıtlar aynı ekranda takip edilir.": "Персонал, владельцы, арендаторы, гости и охват ролей управляются из одного каталога. Загрузка команды, область доступа и рисковые записи отслеживаются на одном экране.",
  "Sakin": "Житель",
  "Sakin bağlantıları": "Связи жителей",
  "Malik / Kiracı": "Владелец / арендатор",
  "Kapsam": "Область",
  "Onaycı": "Согласующий",
  "Rol matrisi kullanıcı görünürlüğü, finans onayı, erişim kısıtı ve dışa aktarım yetkisini ayrı ayrı tutar.": "Матрица ролей разделяет видимость пользователей, финансовое одобрение, ограничения доступа и права экспорта.",
  "telefon yok": "нет телефона",
  "Daire bağlantısı yok": "Нет связи с юнитом",
  "Kontrol": "Проверка",
  "Kısıtlı": "Ограничено",
  "Kuyruk": "Очередь",
  "Kuyrugu yenile": "Обновить очередь",
  "Malik": "Владелец",
  "Maliyet": "Стоимость",
  "Masked": "Скрыто",
  "Matris": "Матрица",
  "Misafir": "Гость",
  "Mutabakat": "Сверка",
  "Odeme kontrol aksiyonlari": "Действия контроля платежей",
  "Onaylı": "Одобрено",
  "Ödeme": "Оплата",
  "Ödenen": "Оплачено",
  "Öncelik": "Приоритет",
  "Önerilen aksiyon": "Рекомендуемое действие",
  "Paket aksiyonlari": "Действия пакета",
  "Paketi hazirla": "Подготовить пакет",
  "Planlı": "Запланировано",
  "Rapor": "Отчет",
  "Rapor aksiyonlari": "Действия отчета",
  "Raporu disa aktar": "Экспортировать отчет",
  "Rezervasyon & Giriş-Çıkış": "Бронирования и заезд/выезд",
  "Rezervasyon aksiyonlari": "Действия бронирования",
  "Rezervasyonlar": "Бронирования",
  "Risk": "Риск",
  "Rol kapsamı": "Охват ролей",
  "Saha gorevi": "Полевая задача",
  "Saha görevi": "Полевая задача",
  "Servis": "Сервис",
  "Servis Talepleri": "Сервисные заявки",
  "Servis aksiyonlari": "Сервисные действия",
  "Servis talebi aksiyonlari": "Действия сервисной заявки",
  "Servis SLA inceleme istegi olustur": "Создать запрос проверки SLA сервиса",
  "SLA incelemesi ac": "Открыть проверку SLA",
  "Servis SLA inceleme isteği oluştur": "Создать запрос проверки SLA сервиса",
  "SLA incelemesi aç": "Открыть проверку SLA",
  "Geciken talep, kanıt ve borç bloklarını yönetime taşır.": "Передает просроченные заявки, доказательства и долговые блокировки руководству.",
  "Servis SLA ve kanıt kuyruğu incelemesi": "Проверка очереди SLA сервиса и доказательств",
  "Siparis": "Заказы",
  "Siparis hazirla": "Подготовить заказ",
  "Son güncelleme": "Последнее обновление",
  "Son tarih": "Срок",
  "Sonraki aksiyon": "Следующее действие",
  "Sorumlu": "Ответственный",
  "Takip": "Контроль",
  "Talep": "Заявка",
  "TAPU & Belge Kasası": "TAPU и хранилище документов",
  "Toplam": "Всего",
  "Toplam belge": "Всего документов",
  "Toplam borç": "Общий долг",
  "Tur": "Тур",
  "Üst": "Вверх",
  "Yasal risk": "Юридический риск",
  "Yasal takip": "Юридический контроль",
  "Yönetici": "Менеджер",
  "Yükleniyor...": "Загрузка...",
  "active": "Активно",
  "assigned": "Назначено",
  "blocked": "Заблокировано",
  "cancelled": "Отменено",
  "closed": "Закрыто",
  "complete": "Готово",
  "confirmed": "Подтверждено",
  "critical": "Критично",
  "draft": "Черновик",
  "due_soon": "Скоро срок",
  "failed": "Ошибка",
  "high": "Высокий",
  "in_progress": "В работе",
  "low": "Низкий",
  "medium": "Средний",
  "open": "Открыто",
  "overdue": "Просрочено",
  "pending": "Ожидает",
  "ready": "Готово",
  "resolved": "Решено",
  "review": "Проверка",
  "scheduled": "Запланировано",
}

const tr: TranslationTable = {
  "submitted": "Onaya gönderildi",
  "approved": "Onaylandı",
  "rejected": "Reddedildi",
  "request_only": "Sadece istek",
  "approval_required": "Onay gerekli",
  "log_only": "Sadece kayıt",
  "ui": "Ekran",
  "ai": "AI",
  "admin": "Yönetim",
  "manager": "Yönetici",
  "staff": "Personel",
  "owner": "Malik",
  "low": "Düşük",
  "medium": "Orta",
  "high": "Yüksek",
  "critical": "Kritik",
  "restricted": "Kısıtlı",
}

const tables: Record<DashboardLocale, TranslationTable> = {
  tr,
  en,
  de,
  ru,
}

const intlLocales: Record<DashboardLocale, string> = {
  tr: "tr-TR",
  en: "en-US",
  de: "de-DE",
  ru: "ru-RU",
}

export function toIntlLocale(locale: DashboardLocale) {
  return intlLocales[locale] ?? "en-US"
}

export function resolveDashboardLocale(locale: string): DashboardLocale {
  return locale === "tr" || locale === "de" || locale === "ru" ? locale : "en"
}

export function localizeDashboardText(
  value: string | null | undefined,
  locale: DashboardLocale
) {
  if (!value) return value ?? ""
  return tables[locale][value] ?? value
}

export function localizeDashboardTextPart(
  value: string | null | undefined,
  locale: DashboardLocale
) {
  if (!value) return value ?? ""

  const exact = localizeDashboardText(value, locale)
  if (exact !== value) return exact

  return value
    .replace(/\baksiyonlari\b/g, localizeDashboardText("Aksiyonlar", locale).toLocaleLowerCase(toIntlLocale(locale)))
    .replace(/\bhazirla\b/g, locale === "tr" ? "hazırla" : localizeDashboardText("Hazır", locale).toLocaleLowerCase(toIntlLocale(locale)))
    .replace(/\bgorev\b/g, locale === "tr" ? "görev" : localizeDashboardText("Görev", locale).toLocaleLowerCase(toIntlLocale(locale)))
    .replace(/\bkanit\b/g, locale === "tr" ? "kanıt" : "evidence")
    .replace(/\bborc\b/g, locale === "tr" ? "borç" : localizeDashboardText("Borç", locale).toLocaleLowerCase(toIntlLocale(locale)))
}
