import {
  PUBLIC_REPORT_CONSENT_TEXT,
  type PublicReportLocale,
} from "@/lib/public-report"

const en = {
  title: "Report a problem",
  intro: "This account-free form is bound to the site and zone shown below.",
  site: "Site",
  zone: "QR location",
  category: "Category",
  categories: { cleaning: "Cleaning", technical: "Technical", security: "Security", accessibility: "Accessibility", noise: "Noise", other: "Other" },
  location: "Location details (optional)",
  description: "Description",
  contactKind: "Optional contact method",
  noContact: "No contact details",
  email: "Email",
  phone: "Phone",
  contact: "Contact details",
  consent: "Privacy consent",
  consentText: PUBLIC_REPORT_CONSENT_TEXT.en,
  submit: "Submit report",
  loading: "Checking the QR location…",
  unavailable: "This QR code is invalid, retired, or reporting is unavailable.",
  emergencyTitle: "Possible emergency detected",
  emergencyBody: "If anyone is in immediate danger, call 112 yourself now. This form does not automatically call or dispatch emergency services.",
  call112: "Call 112",
  safetyAck: "I understand that I must call 112 myself if emergency help is needed.",
  receiptTitle: "Report received",
  reference: "Reference",
  trackingToken: "Private tracking token",
  saveReceipt: "Save both values. The private token is shown here and is required to track the report.",
  track: "Track a report",
  trackingIntro: "Enter the reference and private token from your receipt.",
  checkStatus: "Check status",
  status: "Status",
  statusLabels: {
    submitted: "Submitted",
    under_review: "Under review",
    awaiting_information: "Awaiting information",
    rejected: "Rejected",
    converted: "Converted to ticket",
  },
  safetyLabels: {
    life_safety: "Immediate danger to life",
    fire_smoke: "Fire or smoke",
    gas_leak: "Gas leak",
    medical_emergency: "Medical emergency",
    electrical_hazard: "Electrical hazard",
    elevator_entrapment: "Elevator entrapment",
    flooding_active: "Active flooding",
    security_threat: "Security threat",
  },
  manager: {
    kicker: "UC10 · Human triage",
    title: "Public reports",
    intro: "Account-free QR reports remain unverified until a site-scoped manager reviews them. Conversion creates one submitted ticket only; it never dispatches staff, calls 112, grants access, or approves spend.",
    activePlacements: "Active QR placements",
    loading: "Loading…",
    noPlacements: "No scoped placements are available.",
    openPoster: "Open exact QR poster",
    setupPlacements: "Set up a QR placement",
    setupIntro: "Create the first verified site/zone placement here. The generated poster carries the exact opaque token; the bare poster URL remains setup-only.",
    siteSelect: "Site",
    zoneCode: "Zone code",
    zoneLabelTr: "Zone label (Turkish)",
    zoneLabelEn: "Zone label (English)",
    zoneLabelDe: "Zone label (German)",
    zoneLabelRu: "Zone label (Russian)",
    createPlacement: "Create placement",
    rotatePlacement: "Rotate token",
    revokePlacement: "Revoke token",
    inactivePlacement: "Inactive",
    noSites: "No manageable sites are available.",
    placementActionError: "The placement command failed or its site scope changed. Refresh and try again.",
    placementSaved: "Placement updated. Use only the newly displayed exact-token poster.",
    confirmRotate: "Rotate this token now? The old QR stops accepting reports immediately.",
    confirmRevoke: "Revoke this token now? Its QR stops accepting reports immediately.",
    triageQueue: "Triage queue",
    internalReason: "Internal review reason",
    defaultReason: "Site manager verified the public report.",
    noReports: "No public reports in your site scope.",
    loadError: "Public reports could not be loaded.",
    actionError: "The review action failed or the report changed. Refresh and try again.",
    safetyFlag: "112 safety flag",
    safetyTruth: "Confirm the situation manually; no emergency call or dispatch was triggered.",
    locationDetail: "Location detail",
    optionalContact: "Optional contact",
    possibleDuplicate: "Possible duplicate of",
    startReview: "Start review",
    convert: "Convert to ticket",
    requestInformation: "Request information",
    reject: "Reject report",
  },
  genericError: "The request could not be completed. Please check the details and try again.",
  submitting: "Submitting…",
  checking: "Checking…",
  copyLabel: "Copy",
  copied: "Copied",
  print: "Print or save receipt",
  retry: "Try again",
  openTracker: "Track this report",
  staticSafetyNotice: "In a life-threatening emergency, call 112 now — this form does not dispatch help. Please do not include ID, passport, or TCKN numbers.",
  errorIdentityData: "Please remove any ID, passport, or TCKN numbers from your description, then submit again.",
  errorContactInvalid: "Please check the email address or phone number you entered.",
  errorRateLimited: "Too many attempts. Please wait a little while and try again.",
  errorUnavailable: "The reporting service is temporarily unavailable. Please try again shortly.",
  trackingNotFound: "We couldn't find a report matching that reference and token. Please check both values from your receipt.",
}

export type PublicReportCopy = typeof en

// Map the API's machine error codes to a friendly, localized sentence so a member of
// the public never sees a raw PUBLIC_REPORT_* code or an HTTP status.
export function friendlyPublicReportError(
  copy: PublicReportCopy,
  code: string | undefined,
  fallback: string,
) {
  switch (code) {
    case "PUBLIC_REPORT_IDENTITY_DATA_FORBIDDEN":
      return copy.errorIdentityData
    case "PUBLIC_REPORT_CONTACT_INVALID":
      return copy.errorContactInvalid
    case "PUBLIC_REPORT_RATE_LIMITED":
      return copy.errorRateLimited
    case "PUBLIC_REPORT_NOT_FOUND":
    case "PUBLIC_REPORT_QR_NOT_FOUND":
      return copy.trackingNotFound
    case "PUBLIC_REPORT_UNAVAILABLE":
    case "PUBLIC_REPORT_DATABASE_NOT_CONFIGURED":
    case "PUBLIC_REPORT_DATABASE_ERROR":
      return copy.errorUnavailable
    default:
      return fallback
  }
}

export const publicReportCopy: Record<PublicReportLocale, PublicReportCopy> = {
  en,
  tr: {
    ...en,
    title: "Sorun bildir",
    intro: "Bu hesapsız form aşağıda gösterilen siteye ve QR konumuna bağlıdır.",
    site: "Site",
    zone: "QR konumu",
    category: "Kategori",
    categories: { cleaning: "Temizlik", technical: "Teknik", security: "Güvenlik", accessibility: "Erişilebilirlik", noise: "Gürültü", other: "Diğer" },
    location: "Konum ayrıntısı (isteğe bağlı)",
    description: "Açıklama",
    contactKind: "İsteğe bağlı iletişim yöntemi",
    noContact: "İletişim bilgisi yok",
    email: "E-posta",
    phone: "Telefon",
    contact: "İletişim bilgisi",
    consent: "Gizlilik onayı",
    consentText: PUBLIC_REPORT_CONSENT_TEXT.tr,
    submit: "Bildirimi gönder",
    loading: "QR konumu kontrol ediliyor…",
    unavailable: "Bu QR kodu geçersiz, kullanımdan kaldırılmış veya bildirim hizmeti kullanılamıyor.",
    emergencyTitle: "Olası acil durum algılandı",
    emergencyBody: "Acil tehlike varsa şimdi 112'yi kendiniz arayın. Bu form acil hizmetleri otomatik olarak aramaz veya yönlendirmez.",
    call112: "112'yi ara",
    safetyAck: "Acil yardım gerekiyorsa 112'yi kendim aramam gerektiğini anlıyorum.",
    receiptTitle: "Bildirim alındı",
    reference: "Referans",
    trackingToken: "Özel takip anahtarı",
    saveReceipt: "Her iki değeri de kaydedin. Özel anahtar burada gösterilir ve takip için gereklidir.",
    track: "Bildirim takip et",
    trackingIntro: "Makbuzdaki referans ve özel anahtarı girin.",
    checkStatus: "Durumu kontrol et",
    status: "Durum",
    statusLabels: {
      submitted: "Gönderildi",
      under_review: "İnceleniyor",
      awaiting_information: "Ek bilgi bekleniyor",
      rejected: "Reddedildi",
      converted: "Servis talebine dönüştürüldü",
    },
    safetyLabels: {
      life_safety: "Hayati tehlike",
      fire_smoke: "Yangın veya duman",
      gas_leak: "Gaz kaçağı",
      medical_emergency: "Tıbbi acil durum",
      electrical_hazard: "Elektrik tehlikesi",
      elevator_entrapment: "Asansörde mahsur kalma",
      flooding_active: "Aktif su baskını",
      security_threat: "Güvenlik tehdidi",
    },
    manager: {
      kicker: "UC10 · İnsan incelemesi",
      title: "Kamusal bildirimler",
      intro: "Hesapsız QR bildirimleri, site kapsamındaki bir yönetici inceleyene kadar doğrulanmamış kalır. Dönüştürme yalnızca bir gönderilmiş servis talebi oluşturur; personel yönlendirmez, 112'yi aramaz, erişim vermez veya harcamayı onaylamaz.",
      activePlacements: "Aktif QR konumları",
      loading: "Yükleniyor…",
      noPlacements: "Yetki kapsamında QR konumu yok.",
      openPoster: "Tam QR posterini aç",
      setupPlacements: "QR konumu oluştur",
      setupIntro: "Doğrulanmış ilk site ve konum kaydını burada oluşturun. Üretilen poster tam opak anahtarı taşır; anahtarsız poster adresi yalnızca kurulum içindir.",
      siteSelect: "Site",
      zoneCode: "Konum kodu",
      zoneLabelTr: "Konum etiketi (Türkçe)",
      zoneLabelEn: "Konum etiketi (İngilizce)",
      zoneLabelDe: "Konum etiketi (Almanca)",
      zoneLabelRu: "Konum etiketi (Rusça)",
      createPlacement: "Konum oluştur",
      rotatePlacement: "Anahtarı yenile",
      revokePlacement: "Anahtarı iptal et",
      inactivePlacement: "Etkin değil",
      noSites: "Yönetebileceğiniz site yok.",
      placementActionError: "QR konumu işlemi başarısız oldu veya site yetkisi değişti. Yenileyip tekrar deneyin.",
      placementSaved: "QR konumu güncellendi. Yalnızca yeni gösterilen tam anahtarlı posteri kullanın.",
      confirmRotate: "Bu anahtar şimdi yenilensin mi? Eski QR kodu hemen bildirim kabul etmeyi bırakır.",
      confirmRevoke: "Bu anahtar şimdi iptal edilsin mi? QR kodu hemen bildirim kabul etmeyi bırakır.",
      triageQueue: "İnceleme kuyruğu",
      internalReason: "İç inceleme gerekçesi",
      defaultReason: "Site yöneticisi kamusal bildirimi doğruladı.",
      noReports: "Site kapsamınızda kamusal bildirim yok.",
      loadError: "Kamusal bildirimler yüklenemedi.",
      actionError: "İnceleme işlemi başarısız oldu veya bildirim değişti. Yenileyip tekrar deneyin.",
      safetyFlag: "112 güvenlik işareti",
      safetyTruth: "Durumu elle doğrulayın; acil arama veya yönlendirme yapılmadı.",
      locationDetail: "Konum ayrıntısı",
      optionalContact: "İsteğe bağlı iletişim",
      possibleDuplicate: "Olası mükerrer bildirim",
      startReview: "İncelemeyi başlat",
      convert: "Servis talebine dönüştür",
      requestInformation: "Ek bilgi iste",
      reject: "Bildirimi reddet",
    },
    genericError: "İşlem tamamlanamadı. Bilgileri kontrol edip tekrar deneyin.",
    submitting: "Gönderiliyor…",
    checking: "Kontrol ediliyor…",
    copyLabel: "Kopyala",
    copied: "Kopyalandı",
    print: "Makbuzu yazdır veya kaydet",
    retry: "Tekrar dene",
    openTracker: "Bu bildirimi takip et",
    staticSafetyNotice: "Hayati tehlike durumunda hemen 112'yi arayın — bu form yardım yönlendirmez. Lütfen kimlik, pasaport veya TC kimlik numarası yazmayın.",
    errorIdentityData: "Lütfen açıklamadan kimlik, pasaport veya TC kimlik numaralarını çıkarıp tekrar gönderin.",
    errorContactInvalid: "Lütfen girdiğiniz e-posta adresini veya telefon numarasını kontrol edin.",
    errorRateLimited: "Çok fazla deneme yapıldı. Lütfen biraz bekleyip tekrar deneyin.",
    errorUnavailable: "Bildirim hizmeti geçici olarak kullanılamıyor. Lütfen kısa süre sonra tekrar deneyin.",
    trackingNotFound: "Bu referans ve anahtarla eşleşen bir bildirim bulunamadı. Lütfen makbuzunuzdaki her iki değeri de kontrol edin.",
  },
  de: {
    ...en,
    title: "Problem melden",
    intro: "Dieses Formular ohne Konto ist an den unten angezeigten Standort und QR-Bereich gebunden.",
    site: "Standort",
    zone: "QR-Bereich",
    category: "Kategorie",
    categories: { cleaning: "Reinigung", technical: "Technik", security: "Sicherheit", accessibility: "Barrierefreiheit", noise: "Lärm", other: "Sonstiges" },
    location: "Ortsangabe (optional)", description: "Beschreibung",
    contactKind: "Optionale Kontaktart", noContact: "Keine Kontaktdaten", email: "E-Mail", phone: "Telefon", contact: "Kontaktdaten",
    consent: "Datenschutzeinwilligung",
    consentText: PUBLIC_REPORT_CONSENT_TEXT.de,
    submit: "Meldung senden", loading: "QR-Bereich wird geprüft…",
    unavailable: "Dieser QR-Code ist ungültig, deaktiviert oder der Meldekanal ist nicht verfügbar.",
    emergencyTitle: "Möglicher Notfall erkannt",
    emergencyBody: "Bei unmittelbarer Gefahr rufen Sie jetzt selbst 112 an. Dieses Formular ruft oder alarmiert Rettungsdienste nicht automatisch.",
    call112: "112 anrufen", safetyAck: "Ich verstehe, dass ich bei einem Notfall selbst 112 anrufen muss.",
    receiptTitle: "Meldung eingegangen", reference: "Referenz", trackingToken: "Privater Tracking-Schlüssel",
    saveReceipt: "Speichern Sie beide Werte. Der private Schlüssel wird hier angezeigt und ist für die Statusabfrage erforderlich.",
    track: "Meldung verfolgen", trackingIntro: "Geben Sie Referenz und privaten Schlüssel aus dem Beleg ein.", checkStatus: "Status prüfen", status: "Status",
    statusLabels: {
      submitted: "Eingereicht",
      under_review: "In Prüfung",
      awaiting_information: "Zusätzliche Angaben ausstehend",
      rejected: "Abgelehnt",
      converted: "In Servicevorgang umgewandelt",
    },
    safetyLabels: {
      life_safety: "Unmittelbare Lebensgefahr",
      fire_smoke: "Feuer oder Rauch",
      gas_leak: "Gasleck",
      medical_emergency: "Medizinischer Notfall",
      electrical_hazard: "Elektrische Gefahr",
      elevator_entrapment: "Einschluss im Aufzug",
      flooding_active: "Aktive Überflutung",
      security_threat: "Sicherheitsbedrohung",
    },
    manager: {
      kicker: "UC10 · Menschliche Prüfung",
      title: "Öffentliche Meldungen",
      intro: "Kontolose QR-Meldungen bleiben ungeprüft, bis eine standortberechtigte Verwaltungskraft sie prüft. Die Umwandlung erzeugt genau einen eingereichten Servicevorgang; sie entsendet niemanden, ruft nicht 112 an, gewährt keinen Zutritt und genehmigt keine Ausgaben.",
      activePlacements: "Aktive QR-Bereiche",
      loading: "Wird geladen…",
      noPlacements: "Keine QR-Bereiche im Berechtigungsumfang vorhanden.",
      openPoster: "Exaktes QR-Poster öffnen",
      setupPlacements: "QR-Bereich einrichten",
      setupIntro: "Erstellen Sie hier den ersten geprüften Standort-/Bereichseintrag. Das erzeugte Poster enthält den exakten opaken Schlüssel; die Poster-URL ohne Schlüssel bleibt eine reine Einrichtungsseite.",
      siteSelect: "Standort",
      zoneCode: "Bereichscode",
      zoneLabelTr: "Bereichsbezeichnung (Türkisch)",
      zoneLabelEn: "Bereichsbezeichnung (Englisch)",
      zoneLabelDe: "Bereichsbezeichnung (Deutsch)",
      zoneLabelRu: "Bereichsbezeichnung (Russisch)",
      createPlacement: "QR-Bereich erstellen",
      rotatePlacement: "Schlüssel rotieren",
      revokePlacement: "Schlüssel sperren",
      inactivePlacement: "Inaktiv",
      noSites: "Keine verwaltbaren Standorte vorhanden.",
      placementActionError: "Der QR-Befehl ist fehlgeschlagen oder der Standortumfang hat sich geändert. Aktualisieren Sie und versuchen Sie es erneut.",
      placementSaved: "QR-Bereich aktualisiert. Verwenden Sie ausschließlich das neu angezeigte Poster mit exaktem Schlüssel.",
      confirmRotate: "Schlüssel jetzt rotieren? Der bisherige QR-Code nimmt sofort keine Meldungen mehr an.",
      confirmRevoke: "Schlüssel jetzt sperren? Der QR-Code nimmt sofort keine Meldungen mehr an.",
      triageQueue: "Prüfwarteschlange",
      internalReason: "Interne Prüfbegründung",
      defaultReason: "Die Standortverwaltung hat die öffentliche Meldung geprüft.",
      noReports: "Keine öffentlichen Meldungen in Ihrem Standortumfang.",
      loadError: "Öffentliche Meldungen konnten nicht geladen werden.",
      actionError: "Die Prüfung ist fehlgeschlagen oder die Meldung wurde geändert. Aktualisieren Sie und versuchen Sie es erneut.",
      safetyFlag: "112-Sicherheitshinweis",
      safetyTruth: "Prüfen Sie die Lage manuell; es wurde kein Notruf oder Einsatz ausgelöst.",
      locationDetail: "Ortsangabe",
      optionalContact: "Optionaler Kontakt",
      possibleDuplicate: "Mögliches Duplikat von",
      startReview: "Prüfung beginnen",
      convert: "In Servicevorgang umwandeln",
      requestInformation: "Weitere Angaben anfordern",
      reject: "Meldung ablehnen",
    },
    genericError: "Die Anfrage konnte nicht abgeschlossen werden. Prüfen Sie die Angaben und versuchen Sie es erneut.",
    submitting: "Wird gesendet…",
    checking: "Wird geprüft…",
    copyLabel: "Kopieren",
    copied: "Kopiert",
    print: "Beleg drucken oder speichern",
    retry: "Erneut versuchen",
    openTracker: "Diese Meldung verfolgen",
    staticSafetyNotice: "Rufen Sie bei Lebensgefahr sofort 112 an – dieses Formular alarmiert keine Hilfe. Bitte keine Ausweis-, Pass- oder TCKN-Nummern angeben.",
    errorIdentityData: "Bitte entfernen Sie Ausweis-, Pass- oder TCKN-Nummern aus der Beschreibung und senden Sie erneut.",
    errorContactInvalid: "Bitte prüfen Sie die eingegebene E-Mail-Adresse oder Telefonnummer.",
    errorRateLimited: "Zu viele Versuche. Bitte warten Sie einen Moment und versuchen Sie es erneut.",
    errorUnavailable: "Der Meldekanal ist vorübergehend nicht verfügbar. Bitte versuchen Sie es in Kürze erneut.",
    trackingNotFound: "Wir konnten keine Meldung zu dieser Referenz und diesem Schlüssel finden. Bitte prüfen Sie beide Werte auf Ihrem Beleg.",
  },
  ru: {
    ...en,
    title: "Сообщить о проблеме",
    intro: "Эта форма без аккаунта привязана к указанным ниже объекту и QR-зоне.",
    site: "Объект", zone: "QR-зона", category: "Категория",
    categories: { cleaning: "Уборка", technical: "Техническая", security: "Безопасность", accessibility: "Доступность", noise: "Шум", other: "Другое" },
    location: "Уточнение места (необязательно)", description: "Описание",
    contactKind: "Необязательный способ связи", noContact: "Без контактов", email: "Эл. почта", phone: "Телефон", contact: "Контактные данные",
    consent: "Согласие на обработку данных",
    consentText: PUBLIC_REPORT_CONSENT_TEXT.ru,
    submit: "Отправить", loading: "Проверяем QR-зону…",
    unavailable: "QR-код недействителен, отключён или канал сообщений недоступен.",
    emergencyTitle: "Обнаружена возможная экстренная ситуация",
    emergencyBody: "При непосредственной опасности позвоните 112 сами. Форма не вызывает и не направляет экстренные службы автоматически.",
    call112: "Позвонить 112", safetyAck: "Я понимаю, что при необходимости должен самостоятельно позвонить 112.",
    receiptTitle: "Сообщение принято", reference: "Номер", trackingToken: "Секретный ключ отслеживания",
    saveReceipt: "Сохраните оба значения. Секретный ключ показывается здесь и нужен для проверки статуса.",
    track: "Проверить сообщение", trackingIntro: "Введите номер и секретный ключ из квитанции.", checkStatus: "Проверить статус", status: "Статус",
    statusLabels: {
      submitted: "Отправлено",
      under_review: "На проверке",
      awaiting_information: "Ожидаются дополнительные сведения",
      rejected: "Отклонено",
      converted: "Преобразовано в сервисную заявку",
    },
    safetyLabels: {
      life_safety: "Непосредственная угроза жизни",
      fire_smoke: "Пожар или дым",
      gas_leak: "Утечка газа",
      medical_emergency: "Медицинская экстренная ситуация",
      electrical_hazard: "Опасность поражения током",
      elevator_entrapment: "Человек заблокирован в лифте",
      flooding_active: "Активное затопление",
      security_threat: "Угроза безопасности",
    },
    manager: {
      kicker: "UC10 · Проверка человеком",
      title: "Публичные сообщения",
      intro: "QR-сообщения без аккаунта остаются неподтверждёнными, пока их не проверит менеджер с доступом к объекту. Преобразование создаёт только одну отправленную сервисную заявку; оно не направляет персонал, не звонит 112, не предоставляет доступ и не утверждает расходы.",
      activePlacements: "Активные QR-зоны",
      loading: "Загрузка…",
      noPlacements: "В вашем контуре доступа нет QR-зон.",
      openPoster: "Открыть точный QR-плакат",
      setupPlacements: "Настроить QR-зону",
      setupIntro: "Создайте здесь первую проверенную привязку объекта и зоны. Плакат содержит точный непрозрачный ключ; адрес плаката без ключа остаётся только страницей настройки.",
      siteSelect: "Объект",
      zoneCode: "Код зоны",
      zoneLabelTr: "Название зоны (турецкий)",
      zoneLabelEn: "Название зоны (английский)",
      zoneLabelDe: "Название зоны (немецкий)",
      zoneLabelRu: "Название зоны (русский)",
      createPlacement: "Создать QR-зону",
      rotatePlacement: "Сменить ключ",
      revokePlacement: "Отозвать ключ",
      inactivePlacement: "Неактивна",
      noSites: "Нет объектов, которыми вы можете управлять.",
      placementActionError: "Команда QR-зоны не выполнена или права на объект изменились. Обновите страницу и повторите попытку.",
      placementSaved: "QR-зона обновлена. Используйте только новый плакат с точным ключом.",
      confirmRotate: "Сменить ключ сейчас? Старый QR-код сразу перестанет принимать сообщения.",
      confirmRevoke: "Отозвать ключ сейчас? QR-код сразу перестанет принимать сообщения.",
      triageQueue: "Очередь проверки",
      internalReason: "Внутренняя причина проверки",
      defaultReason: "Менеджер объекта проверил публичное сообщение.",
      noReports: "В вашем контуре объектов нет публичных сообщений.",
      loadError: "Не удалось загрузить публичные сообщения.",
      actionError: "Проверка не выполнена или сообщение изменилось. Обновите страницу и повторите попытку.",
      safetyFlag: "Предупреждение 112",
      safetyTruth: "Проверьте ситуацию вручную; экстренный звонок и выезд не выполнялись.",
      locationDetail: "Уточнение места",
      optionalContact: "Необязательный контакт",
      possibleDuplicate: "Возможный дубликат",
      startReview: "Начать проверку",
      convert: "Преобразовать в заявку",
      requestInformation: "Запросить сведения",
      reject: "Отклонить сообщение",
    },
    genericError: "Не удалось выполнить запрос. Проверьте данные и повторите попытку.",
  },
}
