-- Calendar interoperability hardening:
-- - opaque feed secrets are generated by the application and stored as SHA-256
--   digests only;
-- - stable, opaque UID plus calendar-visible SEQUENCE state;
-- - privacy-reduced, role/scope revalidated feed reads;
-- - cancellation tombstones and bounded import-preview evidence.

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.calendar_event_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  site_id UUID NOT NULL REFERENCES public.sites(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL CHECK (
    source_type IN (
      'reservation',
      'resource_booking',
      'handover_appointment',
      'loading_slot',
      'turnover_task'
    )
  ),
  source_id UUID NOT NULL,
  unit_id UUID REFERENCES public.units(id) ON DELETE SET NULL,
  audience_profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  assigned_profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  resource_label TEXT NOT NULL CHECK (
    LENGTH(BTRIM(resource_label)) BETWEEN 1 AND 160
  ),
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  lifecycle_status TEXT NOT NULL CHECK (
    lifecycle_status IN ('tentative', 'confirmed', 'cancelled', 'completed')
  ),
  stable_uid TEXT NOT NULL CHECK (LENGTH(stable_uid) BETWEEN 16 AND 255),
  sequence INTEGER NOT NULL DEFAULT 0 CHECK (sequence >= 0),
  source_version INTEGER NOT NULL DEFAULT 1 CHECK (source_version > 0),
  content_digest TEXT NOT NULL CHECK (content_digest ~ '^[0-9a-f]{64}$'),
  finance_projection BOOLEAN NOT NULL DEFAULT FALSE,
  cancelled_at TIMESTAMPTZ,
  tombstone_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (ends_at > starts_at),
  CHECK (
    (lifecycle_status <> 'cancelled' AND cancelled_at IS NULL AND tombstone_until IS NULL)
    OR
    (lifecycle_status = 'cancelled' AND cancelled_at IS NOT NULL AND tombstone_until > cancelled_at)
  ),
  UNIQUE (source_type, source_id),
  UNIQUE (company_id, stable_uid)
);

COMMENT ON TABLE public.calendar_event_records IS
  'Privacy-reduced projection for ICS. Stable UID is random/opaque; SEQUENCE changes only when calendar-visible content changes.';

CREATE TABLE IF NOT EXISTS public.calendar_feed_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  owner_profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role_snapshot TEXT NOT NULL CHECK (
    role_snapshot IN ('admin', 'manager', 'accountant', 'staff', 'owner', 'tenant')
  ),
  site_id UUID REFERENCES public.sites(id) ON DELETE CASCADE,
  scope_type TEXT NOT NULL CHECK (
    scope_type IN (
      'organization',
      'site',
      'my_bookings',
      'assigned_work',
      'finance_projection'
    )
  ),
  label TEXT NOT NULL CHECK (LENGTH(BTRIM(label)) BETWEEN 1 AND 100),
  token_digest TEXT NOT NULL CHECK (token_digest ~ '^[0-9a-f]{64}$'),
  token_hint TEXT NOT NULL CHECK (LENGTH(BTRIM(token_hint)) BETWEEN 4 AND 24),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  workflow_version INTEGER NOT NULL DEFAULT 1 CHECK (workflow_version > 0),
  expires_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  revoked_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  revocation_reason TEXT CHECK (revocation_reason IS NULL OR LENGTH(revocation_reason) <= 500),
  created_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (
    (status = 'active' AND revoked_at IS NULL)
    OR
    (status = 'revoked' AND revoked_at IS NOT NULL)
  ),
  UNIQUE (token_digest)
);

COMMENT ON COLUMN public.calendar_feed_tokens.token_digest IS
  'SHA-256 hex digest of a minimum 256-bit opaque token. Raw feed tokens must never be persisted.';

CREATE TABLE IF NOT EXISTS public.calendar_feed_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  feed_id UUID NOT NULL REFERENCES public.calendar_feed_tokens(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN ('created', 'rotated', 'revoked')),
  feed_version INTEGER NOT NULL CHECK (feed_version > 0),
  actor_profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  reason TEXT CHECK (reason IS NULL OR LENGTH(reason) <= 500),
  idempotency_key TEXT NOT NULL CHECK (LENGTH(idempotency_key) BETWEEN 8 AND 200),
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB CHECK (OCTET_LENGTH(metadata::TEXT) <= 4000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (company_id, actor_profile_id, idempotency_key),
  UNIQUE (feed_id, feed_version)
);

CREATE TABLE IF NOT EXISTS public.calendar_import_batches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  site_id UUID NOT NULL REFERENCES public.sites(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  source_digest TEXT NOT NULL CHECK (source_digest ~ '^[0-9a-f]{64}$'),
  normalized_items_digest TEXT NOT NULL CHECK (
    normalized_items_digest ~ '^[0-9a-f]{64}$'
  ),
  source_bytes INTEGER NOT NULL CHECK (source_bytes BETWEEN 1 AND 512000),
  file_name TEXT CHECK (file_name IS NULL OR LENGTH(file_name) <= 160),
  status TEXT NOT NULL DEFAULT 'preview_ready' CHECK (
    status IN ('preview_ready', 'committed', 'discarded', 'expired')
  ),
  item_count INTEGER NOT NULL DEFAULT 0 CHECK (item_count BETWEEN 0 AND 500),
  new_count INTEGER NOT NULL DEFAULT 0 CHECK (new_count BETWEEN 0 AND 500),
  duplicate_count INTEGER NOT NULL DEFAULT 0 CHECK (duplicate_count BETWEEN 0 AND 500),
  conflict_count INTEGER NOT NULL DEFAULT 0 CHECK (conflict_count BETWEEN 0 AND 500),
  invalid_count INTEGER NOT NULL DEFAULT 0 CHECK (invalid_count BETWEEN 0 AND 500),
  idempotency_key TEXT NOT NULL CHECK (LENGTH(idempotency_key) BETWEEN 8 AND 200),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (expires_at > created_at AND expires_at <= created_at + INTERVAL '7 days'),
  UNIQUE (company_id, created_by, idempotency_key)
);

CREATE TABLE IF NOT EXISTS public.calendar_import_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  batch_id UUID NOT NULL REFERENCES public.calendar_import_batches(id) ON DELETE CASCADE,
  item_ordinal INTEGER NOT NULL CHECK (item_ordinal BETWEEN 1 AND 500),
  external_identity_digest TEXT NOT NULL CHECK (
    external_identity_digest ~ '^[0-9a-f]{64}$'
  ),
  external_sequence INTEGER NOT NULL DEFAULT 0 CHECK (external_sequence >= 0),
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  event_status TEXT NOT NULL CHECK (event_status IN ('TENTATIVE', 'CONFIRMED', 'CANCELLED')),
  summary_preview TEXT CHECK (summary_preview IS NULL OR LENGTH(summary_preview) <= 160),
  content_digest TEXT NOT NULL CHECK (content_digest ~ '^[0-9a-f]{64}$'),
  classification TEXT NOT NULL CHECK (
    classification IN ('new', 'duplicate', 'update', 'stale', 'conflict', 'cancelled', 'invalid')
  ),
  matched_event_id UUID REFERENCES public.calendar_event_records(id) ON DELETE SET NULL,
  validation_errors JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (
    jsonb_typeof(validation_errors) = 'array' AND OCTET_LENGTH(validation_errors::TEXT) <= 8000
  ),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at),
  UNIQUE (batch_id, item_ordinal)
);

COMMENT ON COLUMN public.calendar_import_items.external_identity_digest IS
  'SHA-256 digest of external UID plus occurrence key. Raw external identifiers and raw ICS are never persisted.';

CREATE TABLE IF NOT EXISTS public.calendar_import_registry (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  site_id UUID NOT NULL REFERENCES public.sites(id) ON DELETE CASCADE,
  external_identity_digest TEXT NOT NULL CHECK (
    external_identity_digest ~ '^[0-9a-f]{64}$'
  ),
  last_sequence INTEGER NOT NULL DEFAULT 0 CHECK (last_sequence >= 0),
  last_content_digest TEXT NOT NULL CHECK (last_content_digest ~ '^[0-9a-f]{64}$'),
  matched_event_id UUID REFERENCES public.calendar_event_records(id) ON DELETE SET NULL,
  last_batch_id UUID REFERENCES public.calendar_import_batches(id) ON DELETE SET NULL,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (company_id, site_id, external_identity_digest)
);

CREATE INDEX IF NOT EXISTS idx_calendar_events_feed_window
  ON public.calendar_event_records(company_id, site_id, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_calendar_events_unit_window
  ON public.calendar_event_records(company_id, unit_id, starts_at)
  WHERE unit_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_calendar_events_assigned
  ON public.calendar_event_records(company_id, assigned_profile_id, starts_at)
  WHERE assigned_profile_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_calendar_feed_owner_status
  ON public.calendar_feed_tokens(owner_profile_id, status, expires_at);
CREATE INDEX IF NOT EXISTS idx_calendar_import_expiry
  ON public.calendar_import_batches(status, expires_at);
CREATE INDEX IF NOT EXISTS idx_calendar_import_registry_uid
  ON public.calendar_import_registry(company_id, site_id, external_identity_digest);

CREATE OR REPLACE FUNCTION public.protect_calendar_uid_and_sequence()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  IF NEW.stable_uid IS DISTINCT FROM OLD.stable_uid THEN
    RAISE EXCEPTION 'Calendar UID is immutable.';
  END IF;

  IF NEW.content_digest IS DISTINCT FROM OLD.content_digest THEN
    IF NEW.sequence IS DISTINCT FROM OLD.sequence + 1 THEN
      RAISE EXCEPTION 'Calendar-visible changes must increment SEQUENCE exactly once.';
    END IF;
  ELSIF NEW.sequence IS DISTINCT FROM OLD.sequence THEN
    RAISE EXCEPTION 'Calendar SEQUENCE cannot change without a visible event change.';
  END IF;
  RETURN NEW;
END;
$$;

-- Profile-parameterized helpers are required because a subscription request is
-- authenticated by the opaque capability, not by an auth session.
CREATE OR REPLACE FUNCTION public.calendar_profile_can_manage_site(
  p_profile_id UUID,
  p_site_id UUID
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    JOIN public.sites s
      ON s.id = p_site_id
     AND s.company_id = p.company_id
    WHERE p.id = p_profile_id
      AND (
        p.role = 'admin'
        OR (
          p.role = 'manager'
          AND (
            s.manager_profile_id = p.id
            OR EXISTS (
              SELECT 1
              FROM public.profile_site_assignments a
              WHERE a.company_id = p.company_id
                AND a.site_id = s.id
                AND a.profile_id = p.id
                AND a.access_role = 'manager'
                AND a.status = 'active'
                AND a.valid_from <= NOW()
                AND (a.valid_until IS NULL OR a.valid_until > NOW())
            )
          )
        )
      )
  );
$$;

CREATE OR REPLACE FUNCTION public.calendar_profile_has_staff_site(
  p_profile_id UUID,
  p_site_id UUID
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    JOIN public.profile_site_assignments a
      ON a.company_id = p.company_id
     AND a.profile_id = p.id
     AND a.site_id = p_site_id
    WHERE p.id = p_profile_id
      AND p.role = 'staff'
      AND a.access_role = 'operator'
      AND a.status = 'active'
      AND a.valid_from <= NOW()
      AND (a.valid_until IS NULL OR a.valid_until > NOW())
  );
$$;

CREATE OR REPLACE FUNCTION public.calendar_feed_is_current(p_feed_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.calendar_feed_tokens f
    JOIN public.profiles p
      ON p.id = f.owner_profile_id
     AND p.company_id = f.company_id
     AND p.role = f.role_snapshot
    WHERE f.id = p_feed_id
      AND f.status = 'active'
      AND (f.expires_at IS NULL OR f.expires_at > NOW())
      AND CASE
        WHEN f.scope_type = 'organization'
          THEN p.role = 'admin' AND f.site_id IS NULL
        WHEN f.scope_type = 'site'
          THEN p.role IN ('admin', 'manager')
            AND f.site_id IS NOT NULL
            AND public.calendar_profile_can_manage_site(p.id, f.site_id)
        WHEN f.scope_type = 'my_bookings'
          THEN p.role IN ('owner', 'tenant') AND f.site_id IS NULL
        WHEN f.scope_type = 'assigned_work'
          THEN p.role = 'staff'
            AND f.site_id IS NOT NULL
            AND public.calendar_profile_has_staff_site(p.id, f.site_id)
        WHEN f.scope_type = 'finance_projection'
          THEN p.role = 'accountant' AND f.site_id IS NULL
        ELSE FALSE
      END
  );
$$;

CREATE OR REPLACE FUNCTION public.create_calendar_feed_token_command(
  p_label TEXT,
  p_token_digest TEXT,
  p_token_hint TEXT,
  p_scope_type TEXT,
  p_idempotency_key TEXT,
  p_site_id UUID DEFAULT NULL,
  p_expires_at TIMESTAMPTZ DEFAULT NULL
)
RETURNS TABLE (
  feed_id UUID,
  scope_type TEXT,
  site_id UUID,
  label TEXT,
  token_hint TEXT,
  status TEXT,
  workflow_version INTEGER,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_actor_id UUID := (SELECT auth.uid());
  v_company_id UUID;
  v_role TEXT;
  v_existing_event public.calendar_feed_events%ROWTYPE;
  v_feed public.calendar_feed_tokens%ROWTYPE;
  v_request_fingerprint TEXT;
BEGIN
  SELECT p.company_id, p.role
  INTO v_company_id, v_role
  FROM public.profiles p
  WHERE p.id = v_actor_id;

  IF v_actor_id IS NULL OR v_company_id IS NULL THEN
    RAISE EXCEPTION 'Authentication and an active company profile are required.';
  END IF;
  IF NULLIF(BTRIM(p_label), '') IS NULL OR LENGTH(BTRIM(p_label)) > 100 THEN
    RAISE EXCEPTION 'Feed label must contain 1 to 100 characters.';
  END IF;
  IF p_token_digest IS NULL
     OR p_token_digest <> LOWER(p_token_digest)
     OR p_token_digest !~ '^[0-9a-f]{64}$'
  THEN
    RAISE EXCEPTION 'Feed token digest must be lowercase SHA-256 hex.';
  END IF;
  IF NULLIF(BTRIM(p_token_hint), '') IS NULL
     OR LENGTH(BTRIM(p_token_hint)) NOT BETWEEN 4 AND 24
  THEN
    RAISE EXCEPTION 'Feed token hint must contain 4 to 24 characters.';
  END IF;
  IF NULLIF(BTRIM(p_idempotency_key), '') IS NULL
     OR LENGTH(p_idempotency_key) NOT BETWEEN 8 AND 200
  THEN
    RAISE EXCEPTION 'Idempotency key must contain 8 to 200 characters.';
  END IF;
  IF p_expires_at IS NOT NULL AND p_expires_at <= NOW() THEN
    RAISE EXCEPTION 'Feed expiry must be in the future.';
  END IF;

  IF NOT (
    (v_role = 'admin' AND p_scope_type = 'organization' AND p_site_id IS NULL)
    OR (
      v_role IN ('admin', 'manager')
      AND p_scope_type = 'site'
      AND p_site_id IS NOT NULL
      AND public.calendar_profile_can_manage_site(v_actor_id, p_site_id)
    )
    OR (
      v_role IN ('owner', 'tenant')
      AND p_scope_type = 'my_bookings'
      AND p_site_id IS NULL
    )
    OR (
      v_role = 'staff'
      AND p_scope_type = 'assigned_work'
      AND p_site_id IS NOT NULL
      AND public.calendar_profile_has_staff_site(v_actor_id, p_site_id)
    )
    OR (
      v_role = 'accountant'
      AND p_scope_type = 'finance_projection'
      AND p_site_id IS NULL
    )
  ) THEN
    RAISE EXCEPTION 'The requested calendar scope is outside the current role or site assignment.';
  END IF;

  v_request_fingerprint := ENCODE(
    extensions.digest(
      CONVERT_TO(
        jsonb_build_object(
          'label', BTRIM(p_label),
          'tokenDigest', p_token_digest,
          'tokenHint', BTRIM(p_token_hint),
          'scopeType', p_scope_type,
          'siteId', p_site_id,
          'expiresAt', p_expires_at
        )::TEXT,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      v_company_id::TEXT || ':' || v_actor_id::TEXT || ':' || p_idempotency_key,
      0
    )
  );

  SELECT e.*
  INTO v_existing_event
  FROM public.calendar_feed_events e
  WHERE e.company_id = v_company_id
    AND e.actor_profile_id = v_actor_id
    AND e.idempotency_key = p_idempotency_key;

  IF FOUND THEN
    SELECT f.* INTO v_feed
    FROM public.calendar_feed_tokens f
    WHERE f.id = v_existing_event.feed_id;
    IF v_existing_event.event_type <> 'created'
       OR v_feed.owner_profile_id IS DISTINCT FROM v_actor_id
       OR v_existing_event.metadata ->> 'requestFingerprint'
          IS DISTINCT FROM v_request_fingerprint
       OR v_feed.token_digest IS DISTINCT FROM p_token_digest
    THEN
      RAISE EXCEPTION 'Idempotency key was already used by another calendar operation.';
    END IF;
    RETURN QUERY SELECT
      v_feed.id, v_feed.scope_type, v_feed.site_id, v_feed.label,
      v_feed.token_hint, v_feed.status, v_feed.workflow_version,
      v_feed.expires_at, v_feed.created_at;
    RETURN;
  END IF;

  BEGIN
    INSERT INTO public.calendar_feed_tokens (
      company_id, owner_profile_id, role_snapshot, site_id, scope_type,
      label, token_digest, token_hint, expires_at, created_by
    ) VALUES (
      v_company_id, v_actor_id, v_role, p_site_id, p_scope_type,
      BTRIM(p_label), p_token_digest, BTRIM(p_token_hint), p_expires_at, v_actor_id
    )
    RETURNING * INTO v_feed;
  EXCEPTION
    WHEN unique_violation THEN
      RAISE EXCEPTION 'Feed token collision; generate a new opaque token.';
  END;

  INSERT INTO public.calendar_feed_events (
    company_id, feed_id, event_type, feed_version, actor_profile_id,
    idempotency_key, metadata
  ) VALUES (
    v_company_id, v_feed.id, 'created', v_feed.workflow_version, v_actor_id,
    p_idempotency_key,
    jsonb_build_object(
      'scopeType', v_feed.scope_type,
      'siteId', v_feed.site_id,
      'requestFingerprint', v_request_fingerprint
    )
  );

  INSERT INTO public.audit_events (
    company_id, actor_profile_id, action, entity_table, entity_id,
    after_data, idempotency_key
  ) VALUES (
    v_company_id, v_actor_id, 'calendar_feed.created',
    'calendar_feed_tokens', v_feed.id,
    jsonb_build_object(
      'scopeType', v_feed.scope_type,
      'siteId', v_feed.site_id,
      'roleSnapshot', v_feed.role_snapshot,
      'expiresAt', v_feed.expires_at
    ),
    'calendar-feed:create:' || ENCODE(
      extensions.digest(
        CONVERT_TO(v_actor_id::TEXT || ':' || p_idempotency_key, 'UTF8'),
        'sha256'
      ),
      'hex'
    )
  );

  RETURN QUERY SELECT
    v_feed.id, v_feed.scope_type, v_feed.site_id, v_feed.label,
    v_feed.token_hint, v_feed.status, v_feed.workflow_version,
    v_feed.expires_at, v_feed.created_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.rotate_calendar_feed_token_command(
  p_feed_id UUID,
  p_new_token_digest TEXT,
  p_new_token_hint TEXT,
  p_idempotency_key TEXT
)
RETURNS TABLE (
  feed_id UUID,
  token_hint TEXT,
  status TEXT,
  workflow_version INTEGER,
  expires_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_actor_id UUID := (SELECT auth.uid());
  v_feed public.calendar_feed_tokens%ROWTYPE;
  v_existing_event public.calendar_feed_events%ROWTYPE;
  v_request_fingerprint TEXT;
BEGIN
  IF p_new_token_digest IS NULL
     OR p_new_token_digest <> LOWER(p_new_token_digest)
     OR p_new_token_digest !~ '^[0-9a-f]{64}$'
  THEN
    RAISE EXCEPTION 'Feed token digest must be lowercase SHA-256 hex.';
  END IF;
  IF NULLIF(BTRIM(p_new_token_hint), '') IS NULL
     OR LENGTH(BTRIM(p_new_token_hint)) NOT BETWEEN 4 AND 24
  THEN
    RAISE EXCEPTION 'Feed token hint must contain 4 to 24 characters.';
  END IF;
  IF NULLIF(BTRIM(p_idempotency_key), '') IS NULL
     OR LENGTH(p_idempotency_key) NOT BETWEEN 8 AND 200
  THEN
    RAISE EXCEPTION 'Idempotency key must contain 8 to 200 characters.';
  END IF;

  SELECT f.* INTO v_feed
  FROM public.calendar_feed_tokens f
  WHERE f.id = p_feed_id
  FOR UPDATE;

  IF NOT FOUND OR v_feed.owner_profile_id IS DISTINCT FROM v_actor_id THEN
    RAISE EXCEPTION 'Calendar feed not found.';
  END IF;
  IF NOT public.calendar_feed_is_current(v_feed.id) THEN
    RAISE EXCEPTION 'Calendar feed is revoked, expired, or no longer authorized.';
  END IF;

  v_request_fingerprint := ENCODE(
    extensions.digest(
      CONVERT_TO(
        jsonb_build_object(
          'feedId', v_feed.id,
          'tokenDigest', p_new_token_digest,
          'tokenHint', BTRIM(p_new_token_hint)
        )::TEXT,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      v_feed.company_id::TEXT || ':' || v_actor_id::TEXT || ':' || p_idempotency_key,
      0
    )
  );

  SELECT e.* INTO v_existing_event
  FROM public.calendar_feed_events e
  WHERE e.company_id = v_feed.company_id
    AND e.actor_profile_id = v_actor_id
    AND e.idempotency_key = p_idempotency_key;
  IF FOUND THEN
    IF v_existing_event.event_type <> 'rotated'
       OR v_existing_event.feed_id <> v_feed.id
       OR v_existing_event.metadata ->> 'requestFingerprint'
          IS DISTINCT FROM v_request_fingerprint
       OR v_feed.token_digest IS DISTINCT FROM p_new_token_digest
    THEN
      RAISE EXCEPTION 'Idempotency key was already used by another calendar operation.';
    END IF;
    RETURN QUERY SELECT
      f.id, f.token_hint, f.status, f.workflow_version, f.expires_at, f.updated_at
    FROM public.calendar_feed_tokens f
    WHERE f.id = v_feed.id;
    RETURN;
  END IF;

  BEGIN
    UPDATE public.calendar_feed_tokens f
    SET
      token_digest = p_new_token_digest,
      token_hint = BTRIM(p_new_token_hint),
      workflow_version = f.workflow_version + 1,
      updated_at = NOW()
    WHERE f.id = v_feed.id
    RETURNING * INTO v_feed;
  EXCEPTION
    WHEN unique_violation THEN
      RAISE EXCEPTION 'Feed token collision; generate a new opaque token.';
  END;

  INSERT INTO public.calendar_feed_events (
    company_id, feed_id, event_type, feed_version, actor_profile_id,
    idempotency_key, metadata
  ) VALUES (
    v_feed.company_id, v_feed.id, 'rotated', v_feed.workflow_version,
    v_actor_id, p_idempotency_key,
    jsonb_build_object('requestFingerprint', v_request_fingerprint)
  );

  INSERT INTO public.audit_events (
    company_id, actor_profile_id, action, entity_table, entity_id,
    after_data, idempotency_key
  ) VALUES (
    v_feed.company_id, v_actor_id, 'calendar_feed.rotated',
    'calendar_feed_tokens', v_feed.id,
    jsonb_build_object('workflowVersion', v_feed.workflow_version),
    'calendar-feed:rotate:' || ENCODE(
      extensions.digest(
        CONVERT_TO(v_actor_id::TEXT || ':' || p_idempotency_key, 'UTF8'),
        'sha256'
      ),
      'hex'
    )
  );

  RETURN QUERY SELECT
    v_feed.id, v_feed.token_hint, v_feed.status, v_feed.workflow_version,
    v_feed.expires_at, v_feed.updated_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.revoke_calendar_feed_token_command(
  p_feed_id UUID,
  p_reason TEXT,
  p_idempotency_key TEXT
)
RETURNS TABLE (
  feed_id UUID,
  status TEXT,
  workflow_version INTEGER,
  revoked_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_actor_id UUID := (SELECT auth.uid());
  v_actor_company UUID;
  v_actor_role TEXT;
  v_feed public.calendar_feed_tokens%ROWTYPE;
  v_existing_event public.calendar_feed_events%ROWTYPE;
BEGIN
  SELECT p.company_id, p.role
  INTO v_actor_company, v_actor_role
  FROM public.profiles p
  WHERE p.id = v_actor_id;

  IF NULLIF(BTRIM(p_reason), '') IS NULL OR LENGTH(BTRIM(p_reason)) > 500 THEN
    RAISE EXCEPTION 'Revocation reason must contain 1 to 500 characters.';
  END IF;
  IF NULLIF(BTRIM(p_idempotency_key), '') IS NULL
     OR LENGTH(p_idempotency_key) NOT BETWEEN 8 AND 200
  THEN
    RAISE EXCEPTION 'Idempotency key must contain 8 to 200 characters.';
  END IF;

  SELECT f.* INTO v_feed
  FROM public.calendar_feed_tokens f
  WHERE f.id = p_feed_id
  FOR UPDATE;

  IF NOT FOUND
     OR NOT (
       v_feed.owner_profile_id = v_actor_id
       OR (
         v_actor_role = 'admin'
         AND v_actor_company = v_feed.company_id
       )
     )
  THEN
    RAISE EXCEPTION 'Calendar feed not found.';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      v_feed.company_id::TEXT || ':' || v_actor_id::TEXT || ':' || p_idempotency_key,
      0
    )
  );

  SELECT e.* INTO v_existing_event
  FROM public.calendar_feed_events e
  WHERE e.company_id = v_feed.company_id
    AND e.actor_profile_id = v_actor_id
    AND e.idempotency_key = p_idempotency_key;
  IF FOUND THEN
    IF v_existing_event.event_type <> 'revoked'
       OR v_existing_event.feed_id <> v_feed.id
       OR v_existing_event.reason IS DISTINCT FROM BTRIM(p_reason)
    THEN
      RAISE EXCEPTION 'Idempotency key was already used by another calendar operation.';
    END IF;
    RETURN QUERY SELECT
      f.id, f.status, f.workflow_version, f.revoked_at
    FROM public.calendar_feed_tokens f
    WHERE f.id = v_feed.id;
    RETURN;
  END IF;

  IF v_feed.status = 'revoked' THEN
    RETURN QUERY SELECT
      v_feed.id, v_feed.status, v_feed.workflow_version, v_feed.revoked_at;
    RETURN;
  END IF;

  UPDATE public.calendar_feed_tokens f
  SET
    status = 'revoked',
    revoked_at = NOW(),
    revoked_by = v_actor_id,
    revocation_reason = BTRIM(p_reason),
    workflow_version = f.workflow_version + 1,
    updated_at = NOW()
  WHERE f.id = v_feed.id
  RETURNING * INTO v_feed;

  INSERT INTO public.calendar_feed_events (
    company_id, feed_id, event_type, feed_version, actor_profile_id,
    reason, idempotency_key, metadata
  ) VALUES (
    v_feed.company_id, v_feed.id, 'revoked', v_feed.workflow_version,
    v_actor_id, BTRIM(p_reason), p_idempotency_key, '{}'::JSONB
  );

  INSERT INTO public.audit_events (
    company_id, actor_profile_id, action, entity_table, entity_id,
    after_data, idempotency_key
  ) VALUES (
    v_feed.company_id, v_actor_id, 'calendar_feed.revoked',
    'calendar_feed_tokens', v_feed.id,
    jsonb_build_object(
      'workflowVersion', v_feed.workflow_version,
      'reason', v_feed.revocation_reason
    ),
    'calendar-feed:revoke:' || ENCODE(
      extensions.digest(
        CONVERT_TO(v_actor_id::TEXT || ':' || p_idempotency_key, 'UTF8'),
        'sha256'
      ),
      'hex'
    )
  );

  RETURN QUERY SELECT
    v_feed.id, v_feed.status, v_feed.workflow_version, v_feed.revoked_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.list_my_calendar_feeds()
RETURNS TABLE (
  feed_id UUID,
  scope_type TEXT,
  site_id UUID,
  label TEXT,
  token_hint TEXT,
  status TEXT,
  workflow_version INTEGER,
  expires_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT
    f.id, f.scope_type, f.site_id, f.label, f.token_hint, f.status,
    f.workflow_version, f.expires_at, f.revoked_at, f.created_at, f.updated_at
  FROM public.calendar_feed_tokens f
  WHERE f.owner_profile_id = (SELECT auth.uid())
  ORDER BY f.created_at DESC;
$$;

DROP TRIGGER IF EXISTS protect_calendar_uid_and_sequence
  ON public.calendar_event_records;
CREATE TRIGGER protect_calendar_uid_and_sequence
  BEFORE UPDATE ON public.calendar_event_records
  FOR EACH ROW EXECUTE FUNCTION public.protect_calendar_uid_and_sequence();

CREATE OR REPLACE FUNCTION public.register_calendar_event_source(
  p_company_id UUID,
  p_site_id UUID,
  p_source_type TEXT,
  p_source_id UUID,
  p_unit_id UUID,
  p_audience_profile_id UUID,
  p_assigned_profile_id UUID,
  p_resource_label TEXT,
  p_starts_at TIMESTAMPTZ,
  p_ends_at TIMESTAMPTZ,
  p_lifecycle_status TEXT,
  p_source_version INTEGER,
  p_finance_projection BOOLEAN DEFAULT FALSE
)
RETURNS public.calendar_event_records
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_digest TEXT;
  v_event public.calendar_event_records%ROWTYPE;
BEGIN
  IF p_source_type NOT IN (
    'reservation', 'resource_booking', 'handover_appointment',
    'loading_slot', 'turnover_task'
  ) THEN
    RAISE EXCEPTION 'Unsupported calendar source type.';
  END IF;
  IF p_lifecycle_status NOT IN ('tentative', 'confirmed', 'cancelled', 'completed') THEN
    RAISE EXCEPTION 'Unsupported calendar lifecycle status.';
  END IF;
  IF p_source_version IS NULL OR p_source_version < 1 THEN
    RAISE EXCEPTION 'Calendar source version must be positive.';
  END IF;
  IF p_ends_at <= p_starts_at THEN
    RAISE EXCEPTION 'Calendar event end must be after start.';
  END IF;
  IF NULLIF(BTRIM(p_resource_label), '') IS NULL
     OR LENGTH(BTRIM(p_resource_label)) > 160
  THEN
    RAISE EXCEPTION 'Calendar resource label must contain 1 to 160 characters.';
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM public.sites s
    WHERE s.id = p_site_id AND s.company_id = p_company_id
  ) THEN
    RAISE EXCEPTION 'Calendar site is outside the company.';
  END IF;
  IF p_unit_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.units u
    WHERE u.id = p_unit_id
      AND u.company_id = p_company_id
      AND u.site_id = p_site_id
  ) THEN
    RAISE EXCEPTION 'Calendar unit is outside the company/site.';
  END IF;
  IF p_audience_profile_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = p_audience_profile_id
      AND p.company_id = p_company_id
  ) THEN
    RAISE EXCEPTION 'Calendar audience is outside the company.';
  END IF;
  IF p_assigned_profile_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = p_assigned_profile_id
      AND p.company_id = p_company_id
  ) THEN
    RAISE EXCEPTION 'Calendar assignee is outside the company.';
  END IF;

  v_digest := ENCODE(
    extensions.digest(
      CONVERT_TO(
        CONCAT_WS(
          '|',
          BTRIM(p_resource_label),
          TO_CHAR(p_starts_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US'),
          TO_CHAR(p_ends_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US'),
          p_lifecycle_status,
          COALESCE(p_audience_profile_id::TEXT, ''),
          COALESCE(p_assigned_profile_id::TEXT, ''),
          COALESCE(p_finance_projection, FALSE)::TEXT
        ),
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  INSERT INTO public.calendar_event_records (
    company_id, site_id, source_type, source_id, unit_id,
    audience_profile_id, assigned_profile_id, resource_label,
    starts_at, ends_at, lifecycle_status, stable_uid, sequence,
    source_version, content_digest, finance_projection,
    cancelled_at, tombstone_until
  ) VALUES (
    p_company_id, p_site_id, p_source_type, p_source_id, p_unit_id,
    p_audience_profile_id, p_assigned_profile_id, BTRIM(p_resource_label),
    p_starts_at, p_ends_at, p_lifecycle_status,
    gen_random_uuid()::TEXT || '@calendar.1cati.local', 0,
    p_source_version, v_digest, COALESCE(p_finance_projection, FALSE),
    CASE WHEN p_lifecycle_status = 'cancelled' THEN NOW() ELSE NULL END,
    CASE WHEN p_lifecycle_status = 'cancelled' THEN NOW() + INTERVAL '180 days' ELSE NULL END
  )
  ON CONFLICT (source_type, source_id)
  DO UPDATE SET
    company_id = EXCLUDED.company_id,
    site_id = EXCLUDED.site_id,
    unit_id = EXCLUDED.unit_id,
    audience_profile_id = EXCLUDED.audience_profile_id,
    assigned_profile_id = EXCLUDED.assigned_profile_id,
    resource_label = EXCLUDED.resource_label,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at,
    lifecycle_status = EXCLUDED.lifecycle_status,
    sequence = CASE
      WHEN public.calendar_event_records.content_digest IS DISTINCT FROM EXCLUDED.content_digest
        THEN public.calendar_event_records.sequence + 1
      ELSE public.calendar_event_records.sequence
    END,
    source_version = GREATEST(
      public.calendar_event_records.source_version,
      EXCLUDED.source_version
    ),
    content_digest = EXCLUDED.content_digest,
    finance_projection = EXCLUDED.finance_projection,
    cancelled_at = CASE
      WHEN EXCLUDED.lifecycle_status = 'cancelled'
        THEN COALESCE(public.calendar_event_records.cancelled_at, NOW())
      ELSE NULL
    END,
    tombstone_until = CASE
      WHEN EXCLUDED.lifecycle_status = 'cancelled'
        THEN COALESCE(
          public.calendar_event_records.tombstone_until,
          NOW() + INTERVAL '180 days'
        )
      ELSE NULL
    END,
    updated_at = CASE
      WHEN public.calendar_event_records.content_digest IS DISTINCT FROM EXCLUDED.content_digest
        THEN NOW()
      ELSE public.calendar_event_records.updated_at
    END
  RETURNING * INTO v_event;

  RETURN v_event;
END;
$$;

CREATE OR REPLACE FUNCTION public.calendar_reservation_audience_profile(
  p_company_id UUID,
  p_resident_id UUID,
  p_created_by UUID
)
RETURNS UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT COALESCE(
    (
      SELECT l.profile_id
      FROM public.resident_profile_links l
      WHERE l.company_id = p_company_id
        AND l.resident_id = p_resident_id
        AND l.status = 'active'
        AND l.verified_at IS NOT NULL
        AND l.valid_from <= NOW()
        AND (l.valid_until IS NULL OR l.valid_until > NOW())
      LIMIT 1
    ),
    (
      SELECT p.id
      FROM public.profiles p
      WHERE p.id = p_created_by
        AND p.company_id = p_company_id
        AND p.role IN ('owner', 'tenant')
      LIMIT 1
    )
  );
$$;

-- Projection for the canonical reservation authority introduced by migration
-- 32. Migration 33 can call register_calendar_event_source from its own
-- transactional commands without granting this internal function to clients.
CREATE OR REPLACE FUNCTION public.sync_legacy_reservation_calendar_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_lifecycle TEXT;
  v_source_type TEXT;
  v_resource_label TEXT;
  v_assigned_profile_id UUID;
  v_finance_projection BOOLEAN;
BEGIN
  v_lifecycle := CASE NEW.lifecycle_status
    WHEN 'requested' THEN 'tentative'
    WHEN 'confirmed' THEN 'confirmed'
    WHEN 'checked_in' THEN 'confirmed'
    WHEN 'completed' THEN 'completed'
    WHEN 'cancelled' THEN 'cancelled'
    WHEN 'no_show' THEN 'cancelled'
    WHEN 'rejected' THEN 'cancelled'
    WHEN 'revoked' THEN 'cancelled'
    ELSE 'confirmed'
  END;
  v_source_type := CASE
    WHEN NEW.bookable_resource_id IS NOT NULL THEN 'resource_booking'
    ELSE 'reservation'
  END;
  SELECT
    COALESCE(NULLIF(BTRIM(br.name), ''), NULLIF(BTRIM(NEW.resource_name), ''), 'Shared facility')
  INTO v_resource_label
  FROM public.bookable_resources br
  WHERE br.id = NEW.bookable_resource_id;
  v_resource_label := COALESCE(
    v_resource_label,
    NULLIF(BTRIM(NEW.resource_name), ''),
    'Shared facility'
  );
  SELECT t.assigned_profile_id
  INTO v_assigned_profile_id
  FROM public.resource_booking_tasks t
  WHERE t.reservation_id = NEW.id
    AND t.assigned_profile_id IS NOT NULL
    AND t.status <> 'cancelled'
  ORDER BY
    CASE WHEN t.task_type = 'turnover' THEN 0 ELSE 1 END,
    t.due_at NULLS LAST,
    t.id
  LIMIT 1;
  v_finance_projection :=
    NEW.price_truth <> 'free'
    OR NEW.payment_state <> 'not_required'
    OR NEW.deposit_truth_state <> 'not_required';

  PERFORM public.register_calendar_event_source(
    NEW.company_id,
    NEW.site_id,
    v_source_type,
    NEW.id,
    NEW.unit_id,
    public.calendar_reservation_audience_profile(
      NEW.company_id,
      NEW.resident_id,
      NEW.created_by
    ),
    v_assigned_profile_id,
    v_resource_label,
    NEW.check_in_at,
    NEW.check_out_at,
    v_lifecycle,
    NEW.workflow_version,
    v_finance_projection
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_resource_booking_task_calendar_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_reservation public.reservations%ROWTYPE;
  v_resource_label TEXT;
  v_assigned_profile_id UUID;
  v_lifecycle TEXT;
BEGIN
  SELECT r.* INTO v_reservation
  FROM public.reservations r
  WHERE r.id = CASE
    WHEN TG_OP = 'DELETE' THEN OLD.reservation_id
    ELSE NEW.reservation_id
  END;
  IF NOT FOUND THEN
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
  END IF;

  SELECT COALESCE(
    NULLIF(BTRIM(br.name), ''),
    NULLIF(BTRIM(v_reservation.resource_name), ''),
    'Shared facility'
  )
  INTO v_resource_label
  FROM public.bookable_resources br
  WHERE br.id = v_reservation.bookable_resource_id;
  v_resource_label := COALESCE(
    v_resource_label,
    NULLIF(BTRIM(v_reservation.resource_name), ''),
    'Shared facility'
  );
  SELECT t.assigned_profile_id
  INTO v_assigned_profile_id
  FROM public.resource_booking_tasks t
  WHERE t.reservation_id = v_reservation.id
    AND t.assigned_profile_id IS NOT NULL
    AND t.status <> 'cancelled'
  ORDER BY
    CASE WHEN t.task_type = 'turnover' THEN 0 ELSE 1 END,
    t.due_at NULLS LAST,
    t.id
  LIMIT 1;
  v_lifecycle := CASE v_reservation.lifecycle_status
    WHEN 'requested' THEN 'tentative'
    WHEN 'confirmed' THEN 'confirmed'
    WHEN 'checked_in' THEN 'confirmed'
    WHEN 'completed' THEN 'completed'
    ELSE 'cancelled'
  END;

  PERFORM public.register_calendar_event_source(
    v_reservation.company_id,
    v_reservation.site_id,
    CASE
      WHEN v_reservation.bookable_resource_id IS NOT NULL THEN 'resource_booking'
      ELSE 'reservation'
    END,
    v_reservation.id,
    v_reservation.unit_id,
    public.calendar_reservation_audience_profile(
      v_reservation.company_id,
      v_reservation.resident_id,
      v_reservation.created_by
    ),
    v_assigned_profile_id,
    v_resource_label,
    v_reservation.check_in_at,
    v_reservation.check_out_at,
    v_lifecycle,
    v_reservation.workflow_version,
    (
      v_reservation.price_truth <> 'free'
      OR v_reservation.payment_state <> 'not_required'
      OR v_reservation.deposit_truth_state <> 'not_required'
    )
  );

  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

DO $$
DECLARE
  v_reservation public.reservations%ROWTYPE;
BEGIN
  IF TO_REGCLASS('public.reservations') IS NULL THEN
    RETURN;
  END IF;

  EXECUTE 'DROP TRIGGER IF EXISTS sync_legacy_reservation_calendar_event '
    || 'ON public.reservations';
  EXECUTE 'CREATE TRIGGER sync_legacy_reservation_calendar_event '
    || 'AFTER INSERT OR UPDATE OF '
    || 'site_id, unit_id, created_by, resource_name, bookable_resource_id, '
    || 'check_in_at, check_out_at, lifecycle_status, workflow_version, '
    || 'price_truth, payment_state, deposit_truth_state ON public.reservations '
    || 'FOR EACH ROW EXECUTE FUNCTION public.sync_legacy_reservation_calendar_event()';

  FOR v_reservation IN SELECT * FROM public.reservations LOOP
    PERFORM public.register_calendar_event_source(
      v_reservation.company_id,
      v_reservation.site_id,
      CASE
        WHEN v_reservation.bookable_resource_id IS NOT NULL THEN 'resource_booking'
        ELSE 'reservation'
      END,
      v_reservation.id,
      v_reservation.unit_id,
      public.calendar_reservation_audience_profile(
        v_reservation.company_id,
        v_reservation.resident_id,
        v_reservation.created_by
      ),
      (
        SELECT t.assigned_profile_id
        FROM public.resource_booking_tasks t
        WHERE t.reservation_id = v_reservation.id
          AND t.assigned_profile_id IS NOT NULL
          AND t.status <> 'cancelled'
        ORDER BY
          CASE WHEN t.task_type = 'turnover' THEN 0 ELSE 1 END,
          t.due_at NULLS LAST,
          t.id
        LIMIT 1
      ),
      COALESCE(
        (
          SELECT NULLIF(BTRIM(br.name), '')
          FROM public.bookable_resources br
          WHERE br.id = v_reservation.bookable_resource_id
        ),
        NULLIF(BTRIM(v_reservation.resource_name), ''),
        'Shared facility'
      ),
      v_reservation.check_in_at,
      v_reservation.check_out_at,
      CASE v_reservation.lifecycle_status
        WHEN 'requested' THEN 'tentative'
        WHEN 'confirmed' THEN 'confirmed'
        WHEN 'checked_in' THEN 'confirmed'
        WHEN 'completed' THEN 'completed'
        WHEN 'cancelled' THEN 'cancelled'
        WHEN 'no_show' THEN 'cancelled'
        WHEN 'rejected' THEN 'cancelled'
        WHEN 'revoked' THEN 'cancelled'
        ELSE 'confirmed'
      END,
      v_reservation.workflow_version,
      (
        v_reservation.price_truth <> 'free'
        OR v_reservation.payment_state <> 'not_required'
        OR v_reservation.deposit_truth_state <> 'not_required'
      )
    );
  END LOOP;

  EXECUTE 'DROP TRIGGER IF EXISTS sync_resource_booking_task_calendar_event '
    || 'ON public.resource_booking_tasks';
  EXECUTE 'CREATE TRIGGER sync_resource_booking_task_calendar_event '
    || 'AFTER INSERT OR UPDATE OF assigned_profile_id, status, due_at, task_type '
    || 'OR DELETE ON public.resource_booking_tasks '
    || 'FOR EACH ROW EXECUTE FUNCTION public.sync_resource_booking_task_calendar_event()';
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_move_handover_calendar_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_reservation public.reservations%ROWTYPE;
  v_lifecycle TEXT;
  v_resource_label TEXT;
BEGIN
  SELECT r.* INTO v_reservation
  FROM public.reservations r
  WHERE r.id = NEW.reservation_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Move/handover calendar source reservation is missing.';
  END IF;

  v_lifecycle := CASE NEW.status
    WHEN 'completed' THEN 'completed'
    WHEN 'cancelled' THEN 'cancelled'
    ELSE 'confirmed'
  END;
  v_resource_label := CASE NEW.appointment_kind
    WHEN 'move_in' THEN 'Move-in loading slot'
    WHEN 'move_out' THEN 'Move-out loading slot'
    ELSE 'Residential handover'
  END;

  -- Use the canonical reservation source key so appointment creation upgrades
  -- the existing slot event instead of creating a duplicate calendar entry.
  PERFORM public.register_calendar_event_source(
    NEW.company_id,
    NEW.site_id,
    'resource_booking',
    NEW.reservation_id,
    NEW.unit_id,
    public.calendar_reservation_audience_profile(
      NEW.company_id,
      NEW.resident_id,
      NEW.created_by
    ),
    NEW.coordinator_profile_id,
    v_resource_label,
    NEW.starts_at,
    NEW.ends_at,
    v_lifecycle,
    GREATEST(NEW.version, v_reservation.workflow_version),
    (
      v_reservation.price_truth <> 'free'
      OR v_reservation.payment_state <> 'not_required'
      OR v_reservation.deposit_truth_state <> 'not_required'
    )
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sync_move_handover_calendar_event
  ON public.move_handover_appointments;
CREATE TRIGGER sync_move_handover_calendar_event
  AFTER INSERT OR UPDATE OF
    site_id, unit_id, resident_id, appointment_kind, starts_at, ends_at,
    status, coordinator_profile_id, version
  ON public.move_handover_appointments
  FOR EACH ROW EXECUTE FUNCTION public.sync_move_handover_calendar_event();

DO $$
DECLARE
  v_appointment public.move_handover_appointments%ROWTYPE;
BEGIN
  FOR v_appointment IN
    SELECT * FROM public.move_handover_appointments
  LOOP
    PERFORM public.register_calendar_event_source(
      v_appointment.company_id,
      v_appointment.site_id,
      'resource_booking',
      v_appointment.reservation_id,
      v_appointment.unit_id,
      public.calendar_reservation_audience_profile(
        v_appointment.company_id,
        v_appointment.resident_id,
        v_appointment.created_by
      ),
      v_appointment.coordinator_profile_id,
      CASE v_appointment.appointment_kind
        WHEN 'move_in' THEN 'Move-in loading slot'
        WHEN 'move_out' THEN 'Move-out loading slot'
        ELSE 'Residential handover'
      END,
      v_appointment.starts_at,
      v_appointment.ends_at,
      CASE v_appointment.status
        WHEN 'completed' THEN 'completed'
        WHEN 'cancelled' THEN 'cancelled'
        ELSE 'confirmed'
      END,
      GREATEST(
        v_appointment.version,
        (
          SELECT r.workflow_version
          FROM public.reservations r
          WHERE r.id = v_appointment.reservation_id
        )
      ),
      COALESCE(
        (
          SELECT
            r.price_truth <> 'free'
            OR r.payment_state <> 'not_required'
            OR r.deposit_truth_state <> 'not_required'
          FROM public.reservations r
          WHERE r.id = v_appointment.reservation_id
        ),
        FALSE
      )
    );
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION public.resolve_calendar_feed_metadata(
  p_token_digest TEXT
)
RETURNS TABLE (
  feed_id UUID,
  calendar_name TEXT,
  scope_type TEXT,
  timezone_name TEXT,
  workflow_version INTEGER,
  expires_at TIMESTAMPTZ,
  refreshed_at TIMESTAMPTZ
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_feed public.calendar_feed_tokens%ROWTYPE;
BEGIN
  IF p_token_digest IS NULL
     OR p_token_digest <> LOWER(p_token_digest)
     OR p_token_digest !~ '^[0-9a-f]{64}$'
  THEN
    RETURN;
  END IF;

  SELECT f.* INTO v_feed
  FROM public.calendar_feed_tokens f
  WHERE f.token_digest = p_token_digest;

  IF NOT FOUND OR NOT public.calendar_feed_is_current(v_feed.id) THEN
    RETURN;
  END IF;

  RETURN QUERY SELECT
    v_feed.id,
    v_feed.label,
    v_feed.scope_type,
    'Europe/Istanbul'::TEXT,
    v_feed.workflow_version,
    v_feed.expires_at,
    NOW();
END;
$$;

CREATE OR REPLACE FUNCTION public.get_privacy_reduced_calendar_feed(
  p_token_digest TEXT,
  p_window_start TIMESTAMPTZ,
  p_window_end TIMESTAMPTZ
)
RETURNS TABLE (
  event_uid TEXT,
  event_sequence INTEGER,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  lifecycle_status TEXT,
  resource_label TEXT,
  event_updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_feed public.calendar_feed_tokens%ROWTYPE;
BEGIN
  IF p_token_digest IS NULL
     OR p_token_digest <> LOWER(p_token_digest)
     OR p_token_digest !~ '^[0-9a-f]{64}$'
     OR p_window_start IS NULL
     OR p_window_end IS NULL
     OR p_window_end <= p_window_start
     OR p_window_end - p_window_start > INTERVAL '730 days'
  THEN
    RETURN;
  END IF;

  SELECT f.* INTO v_feed
  FROM public.calendar_feed_tokens f
  WHERE f.token_digest = p_token_digest;

  IF NOT FOUND OR NOT public.calendar_feed_is_current(v_feed.id) THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT
    e.stable_uid,
    e.sequence,
    e.starts_at,
    e.ends_at,
    e.lifecycle_status,
    e.resource_label,
    e.updated_at
  FROM public.calendar_event_records e
  WHERE e.company_id = v_feed.company_id
    AND (
      (
        e.starts_at < p_window_end
        AND e.ends_at > p_window_start
      )
      OR (
        e.lifecycle_status = 'cancelled'
        AND e.tombstone_until > NOW()
        AND e.updated_at >= GREATEST(
          p_window_start,
          NOW() - INTERVAL '180 days'
        )
        AND e.updated_at < p_window_end
      )
    )
    AND (
      e.lifecycle_status <> 'cancelled'
      OR e.tombstone_until > NOW()
    )
    AND CASE
      WHEN v_feed.scope_type = 'organization'
        THEN TRUE
      WHEN v_feed.scope_type = 'site'
        THEN e.site_id = v_feed.site_id
      WHEN v_feed.scope_type = 'my_bookings'
        THEN e.audience_profile_id = v_feed.owner_profile_id
          AND e.unit_id IS NOT NULL
          AND (
            (
              v_feed.role_snapshot = 'owner'
              AND public.profile_has_unit_relationship(
                v_feed.owner_profile_id,
                e.unit_id,
                ARRAY['owner']::TEXT[]
              )
            )
            OR (
              v_feed.role_snapshot = 'tenant'
              AND public.profile_has_unit_relationship(
                v_feed.owner_profile_id,
                e.unit_id,
                ARRAY['tenant']::TEXT[]
              )
            )
          )
      WHEN v_feed.scope_type = 'assigned_work'
        THEN e.site_id = v_feed.site_id
          AND e.assigned_profile_id = v_feed.owner_profile_id
      WHEN v_feed.scope_type = 'finance_projection'
        THEN e.finance_projection
      ELSE FALSE
    END
  ORDER BY
    CASE
      WHEN e.starts_at < p_window_end AND e.ends_at > p_window_start THEN 0
      ELSE 1
    END,
    e.starts_at,
    e.id
  LIMIT 2000;
END;
$$;

CREATE OR REPLACE FUNCTION public.preview_calendar_import_command(
  p_site_id UUID,
  p_source_digest TEXT,
  p_file_name TEXT,
  p_total_bytes INTEGER,
  p_items JSONB,
  p_idempotency_key TEXT
)
RETURNS TABLE (
  batch_id UUID,
  item_count INTEGER,
  new_count INTEGER,
  duplicate_count INTEGER,
  conflict_count INTEGER,
  invalid_count INTEGER,
  expires_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_actor_id UUID := (SELECT auth.uid());
  v_company_id UUID;
  v_role TEXT;
  v_batch public.calendar_import_batches%ROWTYPE;
  v_item JSONB;
  v_ordinal INTEGER := 0;
  v_external_uid TEXT;
  v_occurrence_key TEXT;
  v_identity_digest TEXT;
  v_content_digest TEXT;
  v_sequence INTEGER;
  v_starts_at TIMESTAMPTZ;
  v_ends_at TIMESTAMPTZ;
  v_status TEXT;
  v_classification TEXT;
  v_errors JSONB;
  v_match public.calendar_event_records%ROWTYPE;
  v_prior public.calendar_import_items%ROWTYPE;
  v_registry public.calendar_import_registry%ROWTYPE;
  v_item_count INTEGER := 0;
  v_new_count INTEGER := 0;
  v_duplicate_count INTEGER := 0;
  v_conflict_count INTEGER := 0;
  v_invalid_count INTEGER := 0;
  v_items_digest TEXT;
BEGIN
  SELECT p.company_id, p.role
  INTO v_company_id, v_role
  FROM public.profiles p
  WHERE p.id = v_actor_id;

  IF v_actor_id IS NULL
     OR v_company_id IS NULL
     OR v_role NOT IN ('admin', 'manager')
     OR NOT public.calendar_profile_can_manage_site(v_actor_id, p_site_id)
  THEN
    RAISE EXCEPTION 'Calendar import preview requires the assigned site manager or organization administrator.';
  END IF;
  IF p_source_digest IS NULL
     OR p_source_digest <> LOWER(p_source_digest)
     OR p_source_digest !~ '^[0-9a-f]{64}$'
  THEN
    RAISE EXCEPTION 'Import source digest must be lowercase SHA-256 hex.';
  END IF;
  IF p_total_bytes IS NULL OR p_total_bytes < 1 OR p_total_bytes > 512000 THEN
    RAISE EXCEPTION 'ICS import must contain 1 to 512000 bytes.';
  END IF;
  IF p_items IS NULL
     OR jsonb_typeof(p_items) <> 'array'
     OR jsonb_array_length(p_items) > 500
     OR OCTET_LENGTH(p_items::TEXT) > 1500000
  THEN
    RAISE EXCEPTION 'ICS import preview accepts at most 500 bounded events.';
  END IF;
  IF p_file_name IS NOT NULL AND LENGTH(p_file_name) > 160 THEN
    RAISE EXCEPTION 'Import file name is too long.';
  END IF;
  IF NULLIF(BTRIM(p_idempotency_key), '') IS NULL
     OR LENGTH(p_idempotency_key) NOT BETWEEN 8 AND 200
  THEN
    RAISE EXCEPTION 'Idempotency key must contain 8 to 200 characters.';
  END IF;
  v_items_digest := ENCODE(
    extensions.digest(CONVERT_TO(p_items::TEXT, 'UTF8'), 'sha256'),
    'hex'
  );

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      v_company_id::TEXT || ':' || v_actor_id::TEXT || ':' || p_idempotency_key,
      0
    )
  );

  SELECT b.* INTO v_batch
  FROM public.calendar_import_batches b
  WHERE b.company_id = v_company_id
    AND b.created_by = v_actor_id
    AND b.idempotency_key = p_idempotency_key;
  IF FOUND THEN
    IF v_batch.site_id IS DISTINCT FROM p_site_id
       OR v_batch.source_digest IS DISTINCT FROM p_source_digest
       OR v_batch.normalized_items_digest IS DISTINCT FROM v_items_digest
       OR v_batch.source_bytes IS DISTINCT FROM p_total_bytes
    THEN
      RAISE EXCEPTION 'Import idempotency key was already used for different calendar input.';
    END IF;
    RETURN QUERY SELECT
      v_batch.id, v_batch.item_count, v_batch.new_count,
      v_batch.duplicate_count, v_batch.conflict_count,
      v_batch.invalid_count, v_batch.expires_at;
    RETURN;
  END IF;

  INSERT INTO public.calendar_import_batches (
    company_id, site_id, created_by, source_digest, normalized_items_digest,
    source_bytes, file_name, idempotency_key
  ) VALUES (
    v_company_id,
    p_site_id,
    v_actor_id,
    p_source_digest,
    v_items_digest,
    p_total_bytes,
    NULLIF(BTRIM(REGEXP_REPLACE(COALESCE(p_file_name, ''), '[\r\n]', '', 'g')), ''),
    p_idempotency_key
  )
  RETURNING * INTO v_batch;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items) LOOP
    v_ordinal := v_ordinal + 1;
    v_item_count := v_item_count + 1;
    v_errors := '[]'::JSONB;
    v_classification := NULL;
    v_starts_at := NULL;
    v_ends_at := NULL;
    v_match := NULL;
    v_prior := NULL;
    v_registry := NULL;

    IF jsonb_typeof(v_item) <> 'object' OR OCTET_LENGTH(v_item::TEXT) > 12000 THEN
      v_errors := v_errors || jsonb_build_array('invalid_or_oversized_event');
    END IF;

    v_external_uid := NULLIF(BTRIM(v_item ->> 'externalUid'), '');
    v_occurrence_key := COALESCE(v_item ->> 'occurrenceKey', '');
    IF v_external_uid IS NULL OR LENGTH(v_external_uid) > 1000
       OR LENGTH(v_occurrence_key) > 200
    THEN
      v_errors := v_errors || jsonb_build_array('invalid_external_identity');
      v_identity_digest := ENCODE(
        extensions.digest(
          CONVERT_TO(
            'invalid:' || v_batch.id::TEXT || ':' || v_ordinal::TEXT,
            'UTF8'
          ),
          'sha256'
        ),
        'hex'
      );
    ELSE
      v_identity_digest := ENCODE(
        extensions.digest(
          CONVERT_TO(v_external_uid || '|' || v_occurrence_key, 'UTF8'),
          'sha256'
        ),
        'hex'
      );
    END IF;

    IF COALESCE(v_item ->> 'sequence', '') !~ '^\d{1,9}$' THEN
      v_sequence := 0;
      v_errors := v_errors || jsonb_build_array('invalid_sequence');
    ELSE
      v_sequence := (v_item ->> 'sequence')::INTEGER;
    END IF;

    v_status := UPPER(COALESCE(v_item ->> 'status', ''));
    IF v_status NOT IN ('TENTATIVE', 'CONFIRMED', 'CANCELLED') THEN
      v_status := 'TENTATIVE';
      v_errors := v_errors || jsonb_build_array('invalid_status');
    END IF;

    v_content_digest := LOWER(COALESCE(v_item ->> 'contentDigest', ''));
    IF v_content_digest !~ '^[0-9a-f]{64}$' THEN
      v_content_digest := ENCODE(
        extensions.digest(CONVERT_TO(v_item::TEXT, 'UTF8'), 'sha256'),
        'hex'
      );
      v_errors := v_errors || jsonb_build_array('invalid_content_digest');
    END IF;

    BEGIN
      IF COALESCE(v_item ->> 'startsAt', '') !~ '(Z|[+-]\d{2}:\d{2})$'
         OR COALESCE(v_item ->> 'endsAt', '') !~ '(Z|[+-]\d{2}:\d{2})$'
      THEN
        RAISE EXCEPTION 'timezone_required';
      END IF;
      v_starts_at := (v_item ->> 'startsAt')::TIMESTAMPTZ;
      v_ends_at := (v_item ->> 'endsAt')::TIMESTAMPTZ;
      IF v_ends_at <= v_starts_at THEN
        RAISE EXCEPTION 'invalid_window';
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        v_starts_at := NULL;
        v_ends_at := NULL;
        v_errors := v_errors || jsonb_build_array('invalid_time_window');
    END;

    IF jsonb_array_length(v_errors) > 0 THEN
      v_classification := 'invalid';
    ELSE
      SELECT i.* INTO v_prior
      FROM public.calendar_import_items i
      WHERE i.batch_id = v_batch.id
        AND i.external_identity_digest = v_identity_digest
      ORDER BY i.item_ordinal
      LIMIT 1;

      IF FOUND THEN
        v_classification := CASE
          WHEN v_prior.external_sequence = v_sequence
               AND v_prior.content_digest = v_content_digest
            THEN 'duplicate'
          ELSE 'conflict'
        END;
      ELSE
        SELECT e.* INTO v_match
        FROM public.calendar_event_records e
        WHERE e.company_id = v_company_id
          AND e.site_id = p_site_id
          AND ENCODE(
            extensions.digest(
              CONVERT_TO(e.stable_uid || '|' || v_occurrence_key, 'UTF8'),
              'sha256'
            ),
            'hex'
          ) = v_identity_digest
        LIMIT 1;

        IF FOUND THEN
          v_classification := CASE
            WHEN v_status = 'CANCELLED' THEN 'cancelled'
            WHEN v_content_digest = v_match.content_digest THEN 'duplicate'
            WHEN v_sequence < v_match.sequence THEN 'stale'
            WHEN v_sequence = v_match.sequence THEN 'conflict'
            ELSE 'update'
          END;
        ELSE
          SELECT r.* INTO v_registry
          FROM public.calendar_import_registry r
          WHERE r.company_id = v_company_id
            AND r.site_id = p_site_id
            AND r.external_identity_digest = v_identity_digest;

          IF FOUND THEN
            v_classification := CASE
              WHEN v_status = 'CANCELLED' THEN 'cancelled'
              WHEN v_content_digest = v_registry.last_content_digest THEN 'duplicate'
              WHEN v_sequence < v_registry.last_sequence THEN 'stale'
              WHEN v_sequence = v_registry.last_sequence THEN 'conflict'
              ELSE 'update'
            END;
          ELSE
            v_classification := CASE
              WHEN v_status = 'CANCELLED' THEN 'cancelled'
              ELSE 'new'
            END;
          END IF;
        END IF;
      END IF;
    END IF;

    INSERT INTO public.calendar_import_items (
      company_id, batch_id, item_ordinal, external_identity_digest,
      external_sequence, starts_at, ends_at, event_status, summary_preview,
      content_digest, classification, matched_event_id, validation_errors
    ) VALUES (
      v_company_id, v_batch.id, v_ordinal, v_identity_digest,
      v_sequence, v_starts_at, v_ends_at, v_status, NULL,
      v_content_digest, v_classification, v_match.id, v_errors
    );

    v_new_count := v_new_count + CASE WHEN v_classification IN ('new', 'update', 'cancelled') THEN 1 ELSE 0 END;
    v_duplicate_count := v_duplicate_count + CASE WHEN v_classification IN ('duplicate', 'stale') THEN 1 ELSE 0 END;
    v_conflict_count := v_conflict_count + CASE WHEN v_classification = 'conflict' THEN 1 ELSE 0 END;
    v_invalid_count := v_invalid_count + CASE WHEN v_classification = 'invalid' THEN 1 ELSE 0 END;
  END LOOP;

  UPDATE public.calendar_import_batches b
  SET
    item_count = v_item_count,
    new_count = v_new_count,
    duplicate_count = v_duplicate_count,
    conflict_count = v_conflict_count,
    invalid_count = v_invalid_count,
    updated_at = NOW()
  WHERE b.id = v_batch.id
  RETURNING * INTO v_batch;

  INSERT INTO public.audit_events (
    company_id, actor_profile_id, action, entity_table, entity_id,
    after_data, idempotency_key
  ) VALUES (
    v_company_id, v_actor_id, 'calendar_import.previewed',
    'calendar_import_batches', v_batch.id,
    jsonb_build_object(
      'siteId', p_site_id,
      'itemCount', v_batch.item_count,
      'newCount', v_batch.new_count,
      'duplicateCount', v_batch.duplicate_count,
      'conflictCount', v_batch.conflict_count,
      'invalidCount', v_batch.invalid_count
    ),
    'calendar-import:preview:' || ENCODE(
      extensions.digest(
        CONVERT_TO(v_actor_id::TEXT || ':' || p_idempotency_key, 'UTF8'),
        'sha256'
      ),
      'hex'
    )
  );

  RETURN QUERY SELECT
    v_batch.id, v_batch.item_count, v_batch.new_count,
    v_batch.duplicate_count, v_batch.conflict_count,
    v_batch.invalid_count, v_batch.expires_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.purge_expired_calendar_import_previews()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_deleted INTEGER;
BEGIN
  DELETE FROM public.calendar_import_batches b
  WHERE b.expires_at <= NOW();
  GET DIAGNOSTICS v_deleted = ROW_COUNT;
  RETURN v_deleted;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_calendar_import_preview(p_batch_id UUID)
RETURNS TABLE (
  item_ordinal INTEGER,
  external_sequence INTEGER,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  event_status TEXT,
  classification TEXT,
  matched_event_id UUID,
  validation_errors JSONB
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_batch public.calendar_import_batches%ROWTYPE;
  v_actor_id UUID := (SELECT auth.uid());
BEGIN
  SELECT b.* INTO v_batch
  FROM public.calendar_import_batches b
  WHERE b.id = p_batch_id
    AND b.expires_at > NOW();

  IF NOT FOUND
     OR NOT public.calendar_profile_can_manage_site(v_actor_id, v_batch.site_id)
  THEN
    RAISE EXCEPTION 'Calendar import preview not found.';
  END IF;

  RETURN QUERY
  SELECT
    i.item_ordinal, i.external_sequence, i.starts_at, i.ends_at,
    i.event_status, i.classification, i.matched_event_id, i.validation_errors
  FROM public.calendar_import_items i
  WHERE i.batch_id = v_batch.id
  ORDER BY i.item_ordinal;
END;
$$;

DROP TRIGGER IF EXISTS protect_calendar_feed_events
  ON public.calendar_feed_events;
CREATE TRIGGER protect_calendar_feed_events
  BEFORE UPDATE OR DELETE ON public.calendar_feed_events
  FOR EACH ROW EXECUTE FUNCTION public.reject_append_only_mutation();

ALTER TABLE public.calendar_event_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_feed_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_feed_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_import_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_import_registry ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE
  public.calendar_event_records,
  public.calendar_feed_tokens,
  public.calendar_feed_events,
  public.calendar_import_batches,
  public.calendar_import_items,
  public.calendar_import_registry
FROM PUBLIC, anon, authenticated;

REVOKE ALL ON FUNCTION public.calendar_profile_can_manage_site(UUID, UUID)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.calendar_profile_has_staff_site(UUID, UUID)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.calendar_feed_is_current(UUID)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.calendar_reservation_audience_profile(
  UUID, UUID, UUID
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.register_calendar_event_source(
  UUID, UUID, TEXT, UUID, UUID, UUID, UUID, TEXT,
  TIMESTAMPTZ, TIMESTAMPTZ, TEXT, INTEGER, BOOLEAN
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.sync_legacy_reservation_calendar_event()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.sync_resource_booking_task_calendar_event()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.sync_move_handover_calendar_event()
  FROM PUBLIC, anon, authenticated;

REVOKE ALL ON FUNCTION public.create_calendar_feed_token_command(
  TEXT, TEXT, TEXT, TEXT, TEXT, UUID, TIMESTAMPTZ
) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.rotate_calendar_feed_token_command(
  UUID, TEXT, TEXT, TEXT
) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.revoke_calendar_feed_token_command(
  UUID, TEXT, TEXT
) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.list_my_calendar_feeds()
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.preview_calendar_import_command(
  UUID, TEXT, TEXT, INTEGER, JSONB, TEXT
) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_calendar_import_preview(UUID)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.purge_expired_calendar_import_previews()
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.create_calendar_feed_token_command(
  TEXT, TEXT, TEXT, TEXT, TEXT, UUID, TIMESTAMPTZ
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rotate_calendar_feed_token_command(
  UUID, TEXT, TEXT, TEXT
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_calendar_feed_token_command(
  UUID, TEXT, TEXT
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_my_calendar_feeds()
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.preview_calendar_import_command(
  UUID, TEXT, TEXT, INTEGER, JSONB, TEXT
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_calendar_import_preview(UUID)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.purge_expired_calendar_import_previews()
  TO service_role;

REVOKE ALL ON FUNCTION public.resolve_calendar_feed_metadata(TEXT)
  FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_privacy_reduced_calendar_feed(
  TEXT, TIMESTAMPTZ, TIMESTAMPTZ
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.resolve_calendar_feed_metadata(TEXT)
  TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_privacy_reduced_calendar_feed(
  TEXT, TIMESTAMPTZ, TIMESTAMPTZ
) TO anon, authenticated;

COMMENT ON FUNCTION public.resolve_calendar_feed_metadata(TEXT) IS
  'Capability lookup by token digest. Returns no row for unknown, revoked, expired or role/scope-stale feeds.';
COMMENT ON FUNCTION public.get_privacy_reduced_calendar_feed(
  TEXT, TIMESTAMPTZ, TIMESTAMPTZ
) IS
  'Privacy-reduced ICS projection only: opaque UID, SEQUENCE, time, lifecycle and generic resource label. OAuth sync remains provider-ready.';
COMMENT ON FUNCTION public.preview_calendar_import_command(
  UUID, TEXT, TEXT, INTEGER, JSONB, TEXT
) IS
  'Bounded import preview. Persists neither raw ICS nor raw external UID and never mutates a booking.';
